### ISSUE TITLE
Improve Mutations class

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1019]
Multiple TODOs in it: https://github.com/Revolutionary-Games/Thrive/blob/bf37ff573abcdafe05017db82999c9669449d83c/src/general/Mutations.cs

**Comment by DTanxxx** [comment]
Hi hhyyrylainen,
I have submitted a PR with changes to the Mutations class following the TODO comments. Please let me know if that was what the comments wanted. Thanks.
