### ISSUE TITLE
Fix editor button being enabled at start

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1036]
Probably some really minor thing that causes the editor button to became enabled right away.

**Comment by Kasterisk** [comment]
The freebuild check is missing on this line, is this the issue?
https://github.com/Revolutionary-Games/Thrive/blob/679d156621f7e7708115340b9932ad9a7dfa033c/src/microbe_stage/Microbe.cs#L851

**Comment by hhyyrylainen** [comment]
That might be it. At least the check is missing there.

**Comment by Kasterisk** [comment]
Yeah seems like it, I'll open a pull request.
