### ISSUE TITLE
Split the pause menu into a separate scene

### ISSUE THREAD

**Issue by skyace65** [Revolutionary-Games/Thrive#1038]
Right now the pause menu is under the player HUD in the microbe stage scene tree. By splitting it into a separate scene it could be reused in future stage scenes, additionally the UI code would be more organized and the scene tree would be less cluttered.

**Comment by hhyyrylainen** [comment]
The editor also has a pause menu. So there might be a good way to make a generalized base scene that works for both, I would guess.

**Comment by skyace65** [comment]
That's another reason to do this. If you agree that it's a good idea I can start working on it now.

**Comment by hhyyrylainen** [comment]
I think this is a fine enough thing to change, but not a high priority. If you want to work on this, go ahead.
