### ISSUE TITLE
Editor button is pressable when starting the game

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1044]
Even though the editor button is not in the enabled state, it can be pressed when starting a new game.
Once going to the editor once and coming back, the button is correctly unpressable before it gets enabled.

**Comment by Kasterisk** [comment]
Oh, I forgot to enable the disabled mode on the editor button, should be a tiny change to fix, should I just commit it directly?

**Comment by hhyyrylainen** [comment]
If it is really small it can be committed directly, though you might not have permissions to do that.

**Comment by Kasterisk** [comment]
Ok, I'll create another branch
