### ISSUE TITLE
Organelle models flicker sometimes (render order)

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1077]
editor placed models seem to flicker sometimes when the hover hex changes from valid to invalid, not visible until a lot of organelles are added.

**Comment by hhyyrylainen** [comment]
So it is now fixed the flickering with the hexes. But the organelle models themselves seem to do depth fighting and change which one is rendered first, the same thing is visible in the stage. Probably only good fix is depth bias (if that works here) or if the blend mode of the organelles are changed to not matter which is rendered first, or if the depth buffer could be used with the transparent objects.

**Comment by hhyyrylainen** [comment]
Here's how it looks like when moving the mouse a bit:
![Kuvakaappaus - 2020-05-04 14-45-43](https://user-images.githubusercontent.com/3796411/80964463-98605c80-8e19-11ea-9744-d7a78dd846bd.png)

![Kuvakaappaus - 2020-05-04 14-45-45](https://user-images.githubusercontent.com/3796411/80964474-9bf3e380-8e19-11ea-989f-0d50530b474b.png)

**Comment by hhyyrylainen** [comment]
Might be fixed by: https://github.com/Revolutionary-Games/Thrive/issues/1070

**Comment by hhyyrylainen** [comment]
I tried to find some depth bias or distance bias options, but it seems that only render priority is a possible thing to modify here. Which if we have microbes along with other transparent objects, won't look good or at least we need to carefully select the allowed priority values for cells and what the environment uses.

**Comment by Zireael07** [comment]
Godot is bad at sorting multiple transparent objects, your best bet is render priority indeed.
