### ISSUE TITLE
Add the glucose reduced text back to the report screen

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1079]

**Comment by Kasterisk** [comment]
The text is always static right? Like, it doesn't change the value of how much the glucose is reduced, it just stays the same.

**Comment by hhyyrylainen** [comment]
Yeah, it's hardcoded in GameWorld.cs, though it might be nice to make it a constant in Constants so that the text stays up to date if the value is changed.

**Comment by Kasterisk** [comment]
Got it.
