### ISSUE TITLE
Find out why godot physics debug draw doesn't work

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1095]
there is a godot editor option to enable physics debug drawing, but it doesn't work for me when starting the game from the editor.

I tried this but it didn't work:
https://godotengine.org/qa/44597/how-to-debugdraw-a-collisionshape2d

**Comment by Kasterisk** [comment]
Works for me, though only on the chunks and marine snows, the cells did not.
![collisionshapes](https://user-images.githubusercontent.com/54026083/79838979-123a2400-83de-11ea-81a7-012b69fa4d61.png)

**Comment by hhyyrylainen** [comment]
So it half works? I didn't check the chunks. Why I'd mainly want to see this is to debug the size of the pilus and cell to cell collisions.

**Comment by crodnu** [comment]
this kinda works for me but it's very inaccurate (it seems to only do one sphere, and grows it as the cell gets larger, without any care in the world as how good that actually represents the cell collision or how many shapes it actually has)
![Captura](https://user-images.githubusercontent.com/15220161/82133282-c30ac780-97c0-11ea-9bf0-aaa1917c70d4.PNG)

**Comment by hhyyrylainen** [comment]
I've noticed that the physics doesn't really keep up when you modify your cell.
There's a separate issue for it: https://github.com/Revolutionary-Games/Thrive/issues/1251
If the physics debug draw works for you, it will be much easier for you to fix that issue, than for me to try to do that blind.

**Comment by hhyyrylainen** [comment]
So this works for me now. Might have been the update to Godot 3.2.1 that did it?

**Comment by hhyyrylainen** [comment]
Actually that might be the extra engulf detector area I added, and the separate collisions are still not working. But as we are probably doing physics incorrectly for those, it would make sense they don't render: https://github.com/Revolutionary-Games/Thrive/issues/1126

**Comment by Kasterisk** [comment]
Turns out this is just a limitation that the debug drawing of custom collision shapes created through CollisionObject APIs is currently not supported. Here's a PR that addresses this: https://github.com/godotengine/godot/pull/45783
