### ISSUE TITLE
Reimplement returning to menu

### ISSUE THREAD

**Issue by Kasterisk** [Revolutionary-Games/Thrive#1111]
Currently returning to main menu from the microbe stage or editor is not possible yet.

**Comment by hhyyrylainen** [comment]
:+1: 
Though, I'd say that this is not super difficult. As only a single change scene call should work, right?

**Comment by Kasterisk** [comment]
Possibly, but there has to be a check to not play the thrive intro again when returning, which to me I think might be difficult, but I'm not sure though.

**Comment by hhyyrylainen** [comment]
Yeah, that probably requires a bit of thought. Putting a non-saved property (with json ignore) in `src/engine/Settings.cs` will nicely allow marking that the intro video was already played once.

**Comment by Kasterisk** [comment]
Ah, that'll do
