### ISSUE TITLE
Reimplement fluidity slider

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1125]
currently only has graphics but doesn't do anything (AFAIK).

**Comment by hhyyrylainen** [comment]
This in addition to just the bar values being applied needs to have undo / redo functionality in the editor.
And in the past the amount of MP it took to modify the rigidity depended on how much the rigidity was changed from the previous value.

**Comment by Kasterisk** [comment]
Alright, I might've fixed this #1155
