### ISSUE TITLE
Fix errors trying to lookup non-existant shape owners

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1126]
Reported to Godot and we are waiting for a fix: https://github.com/godotengine/godot/issues/39767

Might only happen after the Jukebox changes (I fixed the random choices, there were the last item was never selected).
Example error:
```
E 0:00:27.286   shape_find_owner: Index p_shape_index = -1149990763 is out of bounds (total_subshapes = 1).
  <C++ lähdekoodi>scene/3d/collision_object.cpp:328 @ shape_find_owner()
  <Pinojäljitys>:0 @ UInt32 Godot.NativeCalls.godot_icall_1_153(IntPtr , IntPtr , Int32 )()
                CollisionObject.cs:296 @ UInt32 Godot.CollisionObject.ShapeFindOwner(Int32 )()
                Microbe.cs:1705 @ void Microbe.OnContactBegin(Int32 , Godot.Node , Int32 , Int32 )()
```

**Comment by hhyyrylainen** [comment]
I looked into this a bit and it looks like godot just flat out gives invalid values sometimes:
![Kuvakaappaus - 2020-04-28 13-49-00](https://user-images.githubusercontent.com/3796411/80479396-a1ec4f00-8957-11ea-9d3b-04066c137810.png)
Might need to ask the godot people / report this as a bug to find out what's up.

As a workaround we could resolve the pilus shape owners to indexes, and then just compare the indexes, assuming that we never, or rarely enough, get valid pilus index randomly when actually not hitting a pilus.

**Comment by hhyyrylainen** [comment]
Relevant documentation:
https://docs.godotengine.org/en/3.2/classes/class_rigidbody2d.html#signals
https://docs.godotengine.org/en/3.2/classes/class_collisionobject2d.html#class-collisionobject2d
and our code: https://github.com/Revolutionary-Games/Thrive/blob/5e3b28d67ada992673ed6ae25715d637e81b9958/src/microbe_stage/Microbe.cs#L1696

**Comment by hhyyrylainen** [comment]
I think this is an error that is caused by the same thing:
```
E 0:00:40.804   _body_enter_tree: Condition "!E" is true.
  <C++ lähdekoodi>scene/3d/area.cpp:123 @ _body_enter_tree()
  <Pinojäljitys>:0 @ void Godot.NativeCalls.godot_icall_2_414(IntPtr , IntPtr , IntPtr , Boolean )()
                Node.cs:516 @ void Godot.Node.AddChild(Godot.Node , Boolean )()
                MicrobeEditor.cs:357 @ void MicrobeEditor.OnFinishEditing()()
                :0 @ void Godot.NativeCalls.godot_icall_2_585(IntPtr , IntPtr , System.String , System.Object[] )()
                Object.cs:354 @ void Godot.Object.EmitSignal(System.String , System.Object[] )()
                TransitionManager.cs:160 @ void TransitionManager.StartNextQueuedTransition()()
                :0 @ void Godot.NativeCalls.godot_icall_2_585(IntPtr , IntPtr , System.String , System.Object[] )()
                Object.cs:354 @ void Godot.Object.EmitSignal(System.String , System.Object[] )()
                Fade.cs:74 @ void Fade.OnFinished()()

```

**Comment by crodnu** [comment]
A few things i noticed are that i think we are using CreateShapeOwner wrong, as from what can tell the object we pass to that method should be the object that should own the owners (aka the microbe) and not the shape. However, changing this does not fix the error and due to a godot bug it might not even matter yet (https://github.com/godotengine/godot/issues/36528).
Shape owners apparently can have more than 1 shape in them (according to this at least https://github.com/godotengine/godot-docs/issues/3204), which is unrelated to the bug but would improve performance in organelles and pilus components by only storing 1 owner and not a list.
As for the actual bug, i suggest we ignore the case where 2 pilus hit eachother until the bug is fixed, and just make the 2 microbes suffer damage (it's not a gamebreaking bug anyway)

**Comment by hhyyrylainen** [comment]
I think this hasn't been linked yet: https://godotengine.org/qa/6756/dynamic-creation-of-collision-node-solved?show=54710#c54710
Which shows a code sample where the current object is used as the object passed to the shape owner (which is not what we do).
Might be worth trying to make this small change to see if this fixes the issues.

**Comment by hhyyrylainen** [comment]
I tried the simple fix, but that didn't work: https://github.com/Revolutionary-Games/Thrive/commit/591e4c7096f325a22be16d57a02c6df23ab9a556
My next idea is to just have a predefined shape owner in the Microbe.tscn that gets edited, so no longer using shape owners, hopefully that'll also work for the index getting with piluses.

**Comment by CoreyHendrey** [comment]
I think this is relevant
https://github.com/godotengine/godot/issues/37985

**Comment by hhyyrylainen** [comment]
This was reported to Godot: https://github.com/godotengine/godot/issues/39767

**Comment by hhyyrylainen** [comment]
Looks like the Godot issue is now fixed. At least once the next Godot version is released, we'll need to check if everything is fine on our side.

**Comment by hhyyrylainen** [comment]
Got a report that the game crashed (or rather just locks up) when exiting the editor with a really big cell, with this error:
```
At: scene/3d/collision_object.cpp:328
ERROR: shape_find_owner: Index p_shape_index = 52019136 is out of bounds (total_subshapes = 46).
```

To me this seems to link this problem quite closely to the physics related lockup.
