### ISSUE TITLE
Fix organelles making more ATP than their cost

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1137]
It seems that there is a slight problem with the atp balance calculation as organelles that shouldn't generate any ATP also increase the ATP value.

**Comment by hhyyrylainen** [comment]
I had a look and it seemed mostly accurate. I think the problem is that a lot of the organelles have the glycolysis process making way more ATP than their cost. So this might actually be part of: https://github.com/Revolutionary-Games/Thrive/issues/687

**Comment by Holomanga** [comment]
Does #1253 solve this?

**Comment by hhyyrylainen** [comment]
Maybe, I'll just leave one balancing issue open for now: https://github.com/Revolutionary-Games/Thrive/issues/687
