### ISSUE TITLE
Improve lighting in the editor

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1143]
It seems that the organelles don't really react to light. This should be fixed somehow.

**Comment by hhyyrylainen** [comment]
I did some testing and it seems that organelles do actually react to light. So I'll change this issue to be about improving the light in the editor as we already have: https://github.com/Revolutionary-Games/Thrive/issues/1080

**Comment by Kasterisk** [comment]
Apparently the editor light node is placed inside the World node, and its contents is cleared every editor enter. Could that be the problem because the light also got removed with it?
![scenetree](https://user-images.githubusercontent.com/54026083/94240521-9a989400-ff3d-11ea-8b2e-06235a465588.png)

**Comment by hhyyrylainen** [comment]
That's a good point, and a plausible reason why it doesn't seem to affect things.

**Comment by Kasterisk** [comment]
Well it's simply a matter of reparenting it to the root node. I might do it on my branch

**Comment by ender-titan1** [comment]
I will probably pick this up quite soon (tomorrow), can i get assigned?
