### ISSUE TITLE
Mouse Hover Panel flies away

### ISSUE THREAD

**Issue by icedjuro** [Revolutionary-Games/Thrive#1165]
For Buckly and me, when playing Thrive sometimes the Mouse Panel just starts moving quickly to the left of the screen

**Comment by hhyyrylainen** [comment]
This sounds very strange, I've adjusted the labels.

**Comment by hhyyrylainen** [comment]
Image of it happening: https://cdn.discordapp.com/attachments/464847028539752471/705877245666918420/unknown.png
