### ISSUE TITLE
Set different light properties for the biomes

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1184]
Basically just edit biomes.json to have different sunlight properties for each biome.

**Comment by ender-titan1** [comment]
I can do this assuming you mean that the light level in the patches should be different than the values already present in the game and should be set to a value between 0% and 100%.

**Comment by hhyyrylainen** [comment]
This is not about the light level (which already is different). This issue is about this part of the biomes.json:
```json
        "sunlight": {
            "colour": {
                "r": 1,
                "g": 1,
                "b": 1,
                "a": 1
            },
            "energy": 1,
            "specular": 0.5,
            "shadows": true,
            "direction": {
                "x": 0.25,
                "y": -0.3,
                "z": 0.75
            }
        },
```

**Comment by ender-titan1** [comment]
so just change the values for each biome (the r, g. b, a)?

**Comment by hhyyrylainen** [comment]
The other properties should also optimally be changed, and they should be sensible ie. surface patches have higher values, and maybe the vents have a bit of a red hue to the light.

**Comment by ender-titan1** [comment]
Two questions before I start:
Can the values be set to a number between 0 and 255 or between 0 and 1?
What do the energy and spectacular do?

**Comment by hhyyrylainen** [comment]
Godot colour values are floats (in range 0 to 1). Direction should be normalized vector.
I think we just feed those specular and energy values to Godot, so their documentation should answer that.

**Comment by Nunez2196** [comment]
> What do the energy and spectacular do?

Energy is the strength of a light actor/node.

Specular is in regards to the reflection blob on the model itself. So it manipulates the highlights of models.
