### ISSUE TITLE
Make the seams between compound clouds less visible

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1194]
![Kuvakaappaus - 2020-05-04 08-59-13](https://user-images.githubusercontent.com/3796411/81094142-c45c0a80-8f0b-11ea-8011-9ad467aca331.png)

**Comment by crodnu** [comment]
The seams are caused in the intersection between two planes because the colors cant be interpolated between the two textures.
One solution could be having only one plane (per compound group) rendering and following the camera, grabbing the pixel values from the current planes

**Comment by hhyyrylainen** [comment]
I'll share one more screenshot showing this:
![Kuvakaappaus - 2020-05-04 08-57-32](https://user-images.githubusercontent.com/3796411/81476030-44d68000-9218-11ea-96ca-a9edcf78479d.png)
