### ISSUE TITLE
Update all code to use Compound directly and no names

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1206]
I think this will make things nicer if no string to Compound conversion is needed when running the clouds and other stuff like that.
This will make json serialization a bit harder.

**Comment by crodnu** [comment]
The previous versions of the game relied on ids for the stuff serialized by jsons (compounds included), so we could take that as an inspiration

**Comment by hhyyrylainen** [comment]
I plan on adding custom serializers that just use the string names. And then a custom json loader converts all the strings back to Compound objects. I plan on using a compression library on the save games so it shouldn't affect the save game size much at all.

**Comment by hhyyrylainen** [comment]
I'll probably do this as part of: https://github.com/Revolutionary-Games/Thrive/issues/1013 as a preqreuisite for saving.
