### ISSUE TITLE
Investigate if the engulf detector area gets properly resized

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1207]
The cells use an additional area without collisions to detect when they are engulfing something. The size of that should get changed when the cell size changes but that might not actually work.
https://community.revolutionarygamesstudio.com/t/0-5-0-public-beta-godot-version/2617/4?u=hhyyrylainen

**Comment by CoreyHendrey** [comment]
Seems fine to me, using the Debug menu to draw the collision:

Before resizing:
![image](https://user-images.githubusercontent.com/18731181/82782885-b2351280-9ea0-11ea-8a1b-fbef920d942f.png)

After resizing:
![image](https://user-images.githubusercontent.com/18731181/82782925-c6790f80-9ea0-11ea-837c-567e5dde6ed1.png)

**Comment by hhyyrylainen** [comment]
Does it also work after adding a nucleus?

**Comment by CoreyHendrey** [comment]
Hmm, seems to.
![image](https://user-images.githubusercontent.com/18731181/82785911-d8f64780-9ea6-11ea-87bd-ee03df962a00.png)

![image](https://user-images.githubusercontent.com/18731181/82785950-ead7ea80-9ea6-11ea-8780-efdb72974e4f.png)

**Comment by CoreyHendrey** [comment]
Actually, looking at it now - it's going to be super weird for long cells. Because the collision detection will be far wider than the cell.

**Comment by hhyyrylainen** [comment]
Okay, then the problems related to engulfing are probably entirely caused by https://github.com/Revolutionary-Games/Thrive/issues/1251 so I'll close this one.

**Comment by hhyyrylainen** [comment]
Long cells cause problems also for collecting compounds as that also uses the radius, in addition to the engulfing cells next to you, but this was also an issue in the old engine. And only way to fix this is to rework all the code using the cell radius to use a more accurate model. Absorbing compounds also suffers from the same problem.
