### ISSUE TITLE
Make sure that cloud spawns are properly changed on patch change

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1210]
https://community.revolutionarygamesstudio.com/t/0-5-0-public-beta-godot-version/2617/13?u=hhyyrylainen

**Comment by CoreyHendrey** [comment]
Just info to confirm this is a glitch:

Moving to second patch:

![image](https://user-images.githubusercontent.com/18731181/83110384-54a1ff80-a106-11ea-9287-58802c8db056.png)

![image](https://user-images.githubusercontent.com/18731181/83110433-697e9300-a106-11ea-9065-8815b6dfc63e.png)

**Comment by hhyyrylainen** [comment]
I think I see the issue now. In this method: https://github.com/Revolutionary-Games/Thrive/blob/3062d956ef7afb507a065e528e92e005d7b6f035/src/microbe_stage/PatchManager.cs#L216 (this is not up to date with master as I didn't bother changing branches), the removed spawners should have their DestroyQueued property set to true so that the spawn system then removes them https://github.com/Revolutionary-Games/Thrive/blob/825e352045f14ccd9f73999502ab5d6b7ef500b1/src/microbe_stage/ISpawner.cs#L30
But it seems that additionally DestroyQueued is not checked by the SpawnSystem so fixes are needed there as well. 
Seems I forgot to implement a part of the SpawnSystem when porting it over.

**Comment by CoreyHendrey** [comment]
This appears to have fixed the issue. Let me know if you'd like it implemented a different way.

Compounds feel exceedingly rare in the second patch though. At first, I thought only iron was spawning, but upon respawning, I seen other compounds. It could just be me - or a balancing issue.

Just to show that other compounds to actually spawn.
![image](https://user-images.githubusercontent.com/18731181/83210596-a302dd00-a19e-11ea-894e-268008d8fdb7.png)
