### ISSUE TITLE
Make photosynthesis great again

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1211]
https://community.revolutionarygamesstudio.com/t/0-5-0-public-beta-godot-version/2617/13?u=hhyyrylainen

**Comment by TheRexYo** [comment]
So, is this a playtesting issue? If so, why not just ask people to find out on the forums?

**Comment by crodnu** [comment]
it works but very slowly (i needed about 4 organelles in the estuary patch to increase my levels of glucose at a rate of like 0.1 units a second).

**Comment by hhyyrylainen** [comment]
Ok so this is now confirmed to be broken. Changed title to reflect.

**Comment by hhyyrylainen** [comment]
I'll close this in favour of the generic balancing issue: #687
