### ISSUE TITLE
Fix trying to deal negative engulf damage

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1212]
![a](https://cdn.discordapp.com/attachments/464846955873304587/708712742487457882/unknown.png)

**Comment by GatoCreador887** [comment]
These are the lines the error mentioned:
https://github.com/Revolutionary-Games/Thrive/blob/fa465191c2718000c9ba268577fcac69e8c75411/src/microbe_stage/Microbe.cs#L463
https://github.com/Revolutionary-Games/Thrive/blob/fa465191c2718000c9ba268577fcac69e8c75411/src/microbe_stage/Microbe.cs#L1345
https://github.com/Revolutionary-Games/Thrive/blob/fa465191c2718000c9ba268577fcac69e8c75411/src/microbe_stage/Microbe.cs#L912
So, to me, it looks like `delta` was negative.
