### ISSUE TITLE
Reimplement the AI getting population from kills

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1218]
Currently just commented out in the code.

**Comment by TheRexYo** [comment]
So, the issue is that it needs to be reimplemented, or uncommented?

**Comment by TheRexYo** [comment]
Also, I'd be willing to both implement the AI's auto-evo and also give the player one, since the AI's gargantuan populations have always bothered me.

**Comment by icedjuro** [comment]
The feature needs to be reimplemented, the comment is just a point of reference from what the function looked like when the game was in C++.

**Comment by hhyyrylainen** [comment]
Yes, uncommenting it will definitely not compile. The AI also needs a bit more changes in order for it to receive the GameWorld so that it can actually add the population change effect.
