### ISSUE TITLE
Make membrane regenerate when organelle is added or removed

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1219]
I think there's a big oops in the game, it seems that the membrane is not regenerated when an organelle is added or removed from a microbe.
At least I couldn't find anything else sending organelle positions to the membrane other than the reset layout.

**Comment by crodnu** [comment]
The membrane does grow when you exit the editor with more organelles (tho i think it doesn't grow when you're about to reproduce)

**Comment by hhyyrylainen** [comment]
Looking at the code, I *think* that the membrane did actually regenerate. Though, I'll make a small PR making some changes that guarantee that the membrane gets regenerated on the next update, after any organelle is added or removed.
