### ISSUE TITLE
Ingame screencapture

### ISSUE THREAD

**Issue by Kasterisk** [Revolutionary-Games/Thrive#1223]
Apparently screenshot is broken for godot while in fullscreen, at least on windows, not sure if that's the case on linux or else. We could use the Godot Viewport's `GetTexture` method to get screen texture data and save it as png: https://godotengine.org/qa/37846/how-to-save-screenshots

**Comment by hhyyrylainen** [comment]
It actually works perfectly on the superior Linux platform, but it's good to have this for the Windows folks.

**Comment by hhyyrylainen** [comment]
I basically did this on my saving branch in order to use the same functionality for storing a screenshot in the save file. Just needs adding the print scr key to do it (currently it is just F12, as godot doesn't detect when I press print scr as my OS handles taking a screenshot with it).

**Comment by hhyyrylainen** [comment]
I'll mark this as impeded until the saving branch is merged.

**Comment by hhyyrylainen** [comment]
Now that saving is merged this should be just a matter of adding printscrn as as shortcut to the screenshot action.
