### ISSUE TITLE
Anti-intuition brightness in cloud rendering

### ISSUE THREAD

**Issue by fgdfgfthgr-fox** [Revolutionary-Games/Thrive#1229]
![TIM截图20200510214409](https://user-images.githubusercontent.com/60460773/81495995-7595e280-9308-11ea-9b35-3b8b5e3fd447.png)
From the image above, we can see that the circled part (where I put my mouse) has total compounds of 3675.3.
![TIM图片20200510214418](https://user-images.githubusercontent.com/60460773/81496286-b3940600-930a-11ea-837c-3a5099789fde.png)

And from this one, the total compounds is only 817.2, but appears several times brighter than the first image.
Seems like the brightness of the layers simply added up in the rendering algorithm and which shouldn't be happening. 
OS: Win10
Graphic Card: Intel HD 6000
Thrive Version: 0.5.0.0 beta

I did not find any log file under the folder, this may because I did not use a launcher.

**Comment by hhyyrylainen** [comment]
No logs are relevant for this issue.
Relevant code:
https://github.com/Revolutionary-Games/Thrive/blob/4b4a46bf26d13632ba2aecef3f8a94740c906e3b/src/microbe_stage/CompoundCloudPlane.cs#L173
And shader:
https://github.com/Revolutionary-Games/Thrive/blob/4b4a46bf26d13632ba2aecef3f8a94740c906e3b/shaders/CompoundCloudPlane.shader

**Comment by fgdfgfthgr-fox** [comment]
> No logs are relevant for this issue.
> Relevant code:
> https://github.com/Revolutionary-Games/Thrive/blob/4b4a46bf26d13632ba2aecef3f8a94740c906e3b/src/microbe_stage/CompoundCloudPlane.cs#L173
> 
> 
> And shader:
> https://github.com/Revolutionary-Games/Thrive/blob/4b4a46bf26d13632ba2aecef3f8a94740c906e3b/shaders/CompoundCloudPlane.shader

I am new to GitHub and I'm not sure how should I see this... Cause I don't understand those codes and probably won't help much dealing with the shader here.

**Comment by hhyyrylainen** [comment]
My comment is relevant for a programmer who wants to tackle this issue.

**Comment by fgdfgfthgr-fox** [comment]
Well...maybe I told a lie, but after a careful look in the CompoundCloudPlane.shader, I think the problematic line is 
`ALPHA = min(cloud1 + cloud2 + cloud3 + cloud4, 0.9f);`
Where the 4 clouds shouldn't be adding(or at least not in this way). But I am not a programmer anyway so don't expect me to fix this issue (I mean I can't, not I don't want), sorry.

**Comment by Nunez2196** [comment]
likely because the rendering blend mode is set to be additive where it is usually set to mix by default. However, setting the blend mode to mix causes this weird flicker effect. I'm kinda too backlogged to go deep into this one at the moment but, whoever wants to tackle this may find the following useful (it would involve writing the blending behavior yourself in the fragment shader):
https://godotshaders.com/snippet/blending-modes/

**Comment by Nunez2196** [comment]
> Well...maybe I told a lie, but after a careful look in the CompoundCloudPlane.shader, I think the problematic line is
> `ALPHA = min(cloud1 + cloud2 + cloud3 + cloud4, 0.9f);`
> Where the 4 clouds shouldn't be adding(or at least not in this way). But I am not a programmer anyway so don't expect me to fix this issue (I mean I can't, not I don't want), sorry.

For calculating Alpha (transparency) that is precisely the correct way. Albedo is the color of the clouds.

**Comment by MiniAlfa** [comment]
> ould involve writing the blending behavior yourself in the fra

The flicker effect is due to render priority.
