### ISSUE TITLE
Cap the maximum number of alive cells

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1261]
To reduce lag like this:
![Kuvakaappaus - 2020-05-15 18-06-24](https://user-images.githubusercontent.com/3796411/82066393-050c0e80-96d8-11ea-9b4b-b2c3b690ed72.png)

**Comment by icedjuro** [comment]
Isn't there already a cap for things that should be spawned?

**Comment by hhyyrylainen** [comment]
There's a total cap of 1000 for both cells and chunks. There should be a per-species spawned cell cap.

**Comment by hhyyrylainen** [comment]
I'll not try to keep this in the latest milestone anymore as seems like that doesn't help this getting done.

**Comment by hhyyrylainen** [comment]
We have probably got this covered well enough now.
