### ISSUE TITLE
Fix the random high pitched blip sound

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1268]
Sometimes when going to the cell stage I hear a high pitched sound. I think it might be the pilus sound not working correctly.

**Comment by hhyyrylainen** [comment]
I think this wasn't put on github yet, on discord we talked that this problem is probably due to the sound components being interrupted and repeatedly playing the same sound effect, resulting in the glitched sound.
So to fix this the pilus and chunk collision sounds should only play if the player is free (not currently playing). That should probably fix this, as such I've adjusted the difficulty for this issue.

**Comment by Satharis** [comment]
So I tested fixing this by making a list of players and instantiating a new one whenever all the old players were already playing something. Didn't fix it, still was getting the blip. It's actually really hard to track down where it comes from because it seems to randomly trigger when a sound starts to play.

**Comment by hhyyrylainen** [comment]
That's unfortunate. I'll adjust the issue difficulty.

**Comment by Kasterisk** [comment]
This seems to be a known bug in the Godot engine, with audio pops often happening randomly https://github.com/godotengine/godot/issues/22016

**Comment by hhyyrylainen** [comment]
It seems 3.2.4 (the next godot version) should fix some problems, though it seems that we should make sure *not* to do a few things:
- QueueFree an audio player that is playing (maybe also Free will cause this?)
- Change the stream of a playing audio player

This was also mentioned but I don't see us doing this: changing audio buses of a sound while it is playing.

**Comment by hhyyrylainen** [comment]
Seems like the problem can happen even without the pilus: https://youtu.be/m4ttnxHB7hM?t=1897

Unless we are doing something wrong with the audio players, I'm pretty sure that this is a Godot problem.
That video is from May so I think that's after Godot 3.2.4...

**Comment by FuJa0815** [comment]
seems like this bug comes from the `GUI Volume` category. I had everything else to 0 and heared it.

**Comment by hhyyrylainen** [comment]
I kinda doubt that but then again the GUI plays many short sounds, and the Godot developers have said that interrupting existing sounds or playing short sounds might be what causes it. So as a test we could make the GUI general sound player ignore play requests if it is playing something directly.
Also worth considering that bringing the volumes down *doesn't* stop the sound playing they just play at -infinity volume level, so if there is a bug in Godot with starting sounds or restarting already playing sounds that wouldn't prevent a blip from being caused.

**Comment by hhyyrylainen** [comment]
So that audio issue I linked to from Godot, is slated to be in the 4.0 release. So that's one more reason to look forward to that.

**Comment by hhyyrylainen** [comment]
This seems to be basically gone now, at least it hasn't shown up recently. If I remember right Godot backported various audio fixes to 3.x so that is a plausible reason why this is now gone. I'll close this based on that but if anyone still hears the audio glitching this needs to be reopened.
