### ISSUE TITLE
Damaging ice chunks and the particles look the same

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1270]
which might be a bit confusing

**Comment by HexapodPhilosopher** [comment]
I've made a model which could be an alternative to the exiting ice shard:
![Ice_Shard-2](https://github.com/Revolutionary-Games/Thrive/assets/136889460/834b6669-23b3-4a2c-b48f-9825e2fe1dad)

**Comment by hhyyrylainen** [comment]
That would make the model look different from the particles. Btw it is better to ask for graphics opinions on the thrive dev discord graphics channel as basically only me (and maybe few other programmers) watch all the github issues, so there's not much chance for iterating visuals here.
