### ISSUE TITLE
Include more decimal places in editor tooltips

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1281]
So that processes that almost produce the same amounts, don't get displayed as the same.

**Comment by Savalige** [comment]
Would one more decimal be enough since then you would just need to round down to three decimals instead of two?

**Comment by hhyyrylainen** [comment]
I can't find it right now but @buckly90 commented on discord which values were the same and more precision than that is needed.

**Comment by Savalige** [comment]
Tried with smaller numbers but I just ended up getting this
![what](https://user-images.githubusercontent.com/44610444/82143175-225cec00-9842-11ea-8115-84aef31b6bcf.PNG)

**Comment by Savalige** [comment]
wait I am stupid now i understand what he means

**Comment by Savalige** [comment]
![what](https://user-images.githubusercontent.com/44610444/82143242-b8911200-9842-11ea-9825-bd61f20ef1e9.PNG)
This should be enogh to show that they produce slightly more glucose

**Comment by hhyyrylainen** [comment]
I think this should be fixed now.
