### ISSUE TITLE
Fix the formatting checks for Windows

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1286]
Seems like the formatting has some problems on Windows: https://github.com/Revolutionary-Games/Thrive/pull/1262#issue-418704426
Someone who develops on Windows should have a look and fix them.

**Comment by hhyyrylainen** [comment]
Perhaps with pre-commit now used, this works? I still need help from someone of Windows to test things out and maybe improve our setup instructions on how to get this working.

**Comment by Kasterisk** [comment]
Forgot this issue exist. Yeah, at least for me the precommit checks work in Windows, I've used it a bunch of times with no errors. I think I remember following the current instructions in the setup documentation to get it working.

**Comment by 84634E1A607A** [comment]
https://github.com/Revolutionary-Games/Thrive/pull/2572
