### ISSUE TITLE
Delete the cloud positioning tests

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1290]
As those are probably outdated with the cloud refactoring. Also remove the outdated comments from cloud system as I assume those are probably outdated as well. @crodnu ?

**Comment by CoreyHendrey** [comment]
Hi, can I give this as a go as a first delve into the codebase? @hhyyrylainen

**Comment by icedjuro** [comment]
I may not be hhyyrylainen, but to my knowledge, no one's working on it. Feel free to give it a go!

**Comment by CoreyHendrey** [comment]
Should I just remove the whole test_clouds.cpp, as all the tests seem to contain position information?

**Comment by crodnu** [comment]
Im working on this one, im just  s l o w.
The tests/comments are about the cloud code before i changed it a few commits back.

**Comment by CoreyHendrey** [comment]
Ok, no problem I will find another issue to tackle. :)

**Comment by crodnu** [comment]
The issues tagged as "good first issue" are... good first issues :P

**Comment by hhyyrylainen** [comment]
@crodnu I'll assign you this issue, then.
