### ISSUE TITLE
In the nvidia programs list the game shows up as Godot Engine

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1293]
Would be nice to show up as Thrive, but it might not be possible to change.

**Comment by hhyyrylainen** [comment]
Also seems to show up in task manager as godot engine as found by @icedjuro

**Comment by hhyyrylainen** [comment]
This might be fixed in 0.5.1. Could someone test this?

**Comment by skyace65** [comment]
I just checked. It shows up as Thrive Game in the Nvidia program list and task manager.

**Comment by hhyyrylainen** [comment]
So the same fix for the icon (specifying resedit), has also fixed the program name elsewhere.
