### ISSUE TITLE
On Windows the release exe icon is the godot icon

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1294]
Check if it is possible to change. If not possible would be nice if Godot added the option.

**Comment by crodnu** [comment]
https://docs.godotengine.org/en/3.2/getting_started/workflow/export/changing_application_icon_for_windows.html

**Comment by hhyyrylainen** [comment]
So it seems that *I* need to install rcedit and configure godot, and then the releases should have the right icon.
Might be worth including this in some documentation (which doesn't exist yet) about making releases.
