### ISSUE TITLE
Add option to turn off the environmental particles

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1296]

**Comment by hhyyrylainen** [comment]
@Kasterisk are you still working on this, or should you be unassigned?

**Comment by Kasterisk** [comment]
Oh yeah, I never got started on this, I think someone could take over this issue.

**Comment by hhyyrylainen** [comment]
I'll not try to keep this in the latest milestone anymore as seems like that doesn't help this getting done.

**Comment by MiniAlfa** [comment]
> I'll not try to keep this in the latest milestone anymore as seems like that doesn't help this getting done.

Did you mean turn off, as in hide it ? (graphical)
or turn it off, as in destroy/disable it ? (performance)

**Comment by Kasterisk** [comment]
Turning off as in hiding it as you should be able to turn it back on again, this option should be in the graphics setting.
