### ISSUE TITLE
Concave cells turn convex outside of the editor

### ISSUE THREAD

**Issue by Burgeon** [Revolutionary-Games/Thrive#1298]
When cells are made concave in the editor, they appear as convex when the game is played

This is a concave cell in the editor:
<img width="960" alt="Animalculum" src="https://user-images.githubusercontent.com/65567509/82256166-c3849900-994d-11ea-9cbb-8c89ac3afae9.png">

This is the same cell not in the editor:
<img width="960" alt="Animalculum Reality" src="https://user-images.githubusercontent.com/65567509/82256183-cb443d80-994d-11ea-9faf-6cfc08f2e6e6.png">

(I don't know how to get a better picture)

**Comment by hhyyrylainen** [comment]
Ever since the membrane generation math was written, it has been a limitation that it doesn't work with concave shapes.

**Comment by Nunez2196** [comment]
Working on this

**Comment by hhyyrylainen** [comment]
I'm going to close this now as the collision shape generation is now based on the visual membrane, so any change to supporting concave cells need to begin with the membrane shape algorithm.
