### ISSUE TITLE
Symmetry sometimes fails to place valid organelles

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1299]
Especially noticeable on the 6 way symmetry trying to place an organelle on all sides of the initial cytoplasm.
https://youtu.be/eVcSVhDx3bU

**Comment by CoreyHendrey** [comment]
Just to expand on this, with some testing it isn't random. The symmetry fails when attempting to place along the center vertical hexes. (IE, directly ontop or underneath the starting hex)

**Comment by hhyyrylainen** [comment]
Yeah, that's pretty much right. I just didn't bother writing out "fails in certain conditions that are repeatable".
BTW I invited you to the rev games organization so you should now be able to assign yourself to issues.
