### ISSUE TITLE
can't move from mesopelagic to epipelagic

### ISSUE THREAD

**Issue by l29ah** [Revolutionary-Games/Thrive#1309]
**To Reproduce**
1. Reach mesopelagic patch
2. At the next division, try moving to the epipelagic patch
3. The button is greyed out. Can only return to bathypelagic

**Desktop (please complete the following information):**
 - OS: Gentoo GNU/Linux
 - Thrive version 0.5.0

**Comment by icedjuro** [comment]
Let me check it

**Comment by l29ah** [comment]
Screenshots:
![screenshot-shot1](https://user-images.githubusercontent.com/31852/82594344-9b46a580-9bac-11ea-89a0-e5c07730aa27.png)
![screenshot-shot2](https://user-images.githubusercontent.com/31852/82594381-aa2d5800-9bac-11ea-86af-e3d80e69d985.png)

**Comment by icedjuro** [comment]
You're only moving one patch at a time correct? it seems to work fine for me

**Comment by l29ah** [comment]
Yes, as you can see on the screenshots.

**Comment by icedjuro** [comment]
I would suggest going to options, turning on cheats. Then, play through again, pressing `P` will unlock the editor. Try to reproduce the bug again. If it still persists, please send a video.

**Comment by l29ah** [comment]
I couldn't reproduce it after enabling cheats.

**Comment by icedjuro** [comment]
Press `p`, the editor should be unlocked

**Comment by hhyyrylainen** [comment]
I'm really confused as to how this could happen without anyone else reporting this. Also I just tested with the release 0.5.0 version with cheats and I did not get this issue. Could you post the game logs from `~/.local/share/Thrive/logs` 
I'm pretty sure that if the code for resetting the patch move limit fails it would crash the game, so I really don't have a clue what might be wrong here.

**Comment by l29ah** [comment]
Here's the log.txt contents: 
http://dpaste.com/0NT96EQ

**Comment by hhyyrylainen** [comment]
So the log says that you moved to the tidepool somehow skipping a couple of patches.
Could you perhaps make a video or something? Other than that we need to add more logging to try to catch this issue.

**Comment by l29ah** [comment]
Tidepool was from the next game where the bug haven't manifested itself. I didn't skip any patches. No i couldn't since it's over an hour of repetitive work at the boring game.

**Comment by hhyyrylainen** [comment]
No one else has reported this for 0.5.0 or 0.5.1 so I'll close this.
