### ISSUE TITLE
Make cell chunks emit more compounds (if needed for balance)

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1339]
Right now if the default cell dies, the chunks barely emit 10 of each compound (checked with the mouse hover panel), and that's very low. I think that either the amount transferred to the chunks needs to be increased, or the multiplier on chunk emitted compounds needs to be raised.

**Comment by hhyyrylainen** [comment]
seems like also buffing the amount that iron chunks emit would be good

**Comment by adQuid** [comment]
Now that this is coming to the top of the backlog, how much do we think chunks should be emitting?

**Comment by CI09** [comment]
Oh I didn't mark my PR as progressing this issue: https://github.com/Revolutionary-Games/Thrive/pull/5095
On roadmap this item is "maybe kind of done" probably because of that, but if you or anyone has better ideas about doing it, go ahead.

**Comment by adQuid** [comment]
I don't have any big ideas on what to do with this, and I haven't tested out playing as a dedicated heterotroph recently, so I have no opinions on if this needs balancing. I'll put this in front of the testing team for their opinions.

**Comment by hhyyrylainen** [comment]
Good luck, I've been trying to get other people to test the chunk balance but haven't had much success recently.

**Comment by hhyyrylainen** [comment]
This can be closed after 0.7.0 release if no one notices balance problems.

**Comment by hhyyrylainen** [comment]
No one has said anything so I'll close this.
