### ISSUE TITLE
Make BioProcess.Check that all input compounds amounts are > 0

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1368]
and also that output amounts are > 0, to guard against 0 or negative values.

**Comment by rhythms06** [comment]
Hello! I think I've fixed this and want to submit a PR for it, but am getting the error
```
remote: Permission to Revolutionary-Games/Thrive.git denied to rhythms06.
fatal: unable to access 'https://github.com/Revolutionary-Games/Thrive.git/': The requested URL returned error: 403
```
when I try to publish my new branch.

**Comment by hhyyrylainen** [comment]
You need to make a fork. https://github.com/Revolutionary-Games/Thrive/blob/master/CONTRIBUTING.md

**Comment by hhyyrylainen** [comment]
https://github.com/Revolutionary-Games/Thrive/pull/1372#pullrequestreview-424451591
