### ISSUE TITLE
Improvements to the setup scripts for windows.

### ISSUE THREAD

**Issue by patowen** [Revolutionary-Games/Thrive#138]
The temp folder in MinGW is 5.54 GB on disk with 75,245 files. Based on its name, it seems like it should be deleted. However, certain folders such as cegui only exist in that directory. If the items in the temp folder are necessary, it should not be named temp.

**Comment by hhyyrylainen** [comment]
The new setup script is completely rewritten so if there are issues with it a new issue should be created.
