### ISSUE TITLE
Make MP bar show how much the current organelle costs

### ISSUE THREAD

**Issue by ATP-Kraken** [Revolutionary-Games/Thrive#1395]
- [ ] segmented MP bar to visually show how much your organelle would cost.

(https://community.revolutionarygamesstudio.com/upload://lnXDuVkQAlMZ9tyd0R1cUhrS5kX.jpeg)
![image](https://user-images.githubusercontent.com/18731181/84336818-6e9a1280-abdb-11ea-96f2-d0c31c8754ac.png)
 
- [ ] Allow us to de-select organelles

On the Community Forums:
https://community.revolutionarygamesstudio.com/t/editor-suggestions/2742

**Comment by hhyyrylainen** [comment]
I'm going to split this into separate issues to make this manageable.

**Comment by hhyyrylainen** [comment]
I edited this to be an issue for just the first thing.
