### ISSUE TITLE
Make the text on organelle selection buttons more readable

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1398]

**Comment by hhyyrylainen** [comment]
This might have been already done, needs review.
I think the original problem was that smoothing or mipmaps or something on the font used on the buttons wasn't enabled.

**Comment by skyace65** [comment]
I'm looking at it in 5.1.1. It's readable, but I think there should be a different font for text that small, the letters are just too thin.
