### ISSUE TITLE
Reimplement the arrow in editor showing forward direction

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1400]
Basically we used to have a pretty big arrow in the editor showing that "up" is forward in the cell stage.

The old model file for it is probably lost.

- [ ] basic implementation
- [ ] make it get out of the way of the player adding more organelles.

**Comment by FuJa0815** [comment]
Is @Kasterisk working on this? If not, I'd try to implement this

**Comment by Kasterisk** [comment]
I'm currently not, feel free to work on this 👍
