### ISSUE TITLE
Make initial compounds proportional to player's compound usage

### ISSUE THREAD

**Issue by icedjuro** [Revolutionary-Games/Thrive#1401]
We should be able to calculate what compounds the player cell consumes in a given amount of time, and then when the player respawns, the resource given should be taken into account. Ex: The cell uses 2 glucose, 3 iron, and 1 hydrogen in _x_ amount of time. When the player respawns, they should have 1/2 of the compounds they were given be iron, 1/3 glucose, and 1/6 hydrogen.

**Comment by hhyyrylainen** [comment]
Wouldn't an easier version be acceptable? Just count the number of chemosynthesis organelles, rusticyanins etc. and just give the starting compounds with those fractions. Would be much easier to code by adapting the existing code a bit.
Doing it by comparing the process inputs will be a bit more code and probably quite a bit more difficult to implement for little extra benefit.

**Comment by icedjuro** [comment]
My only concern is if, let's say rusticyanin uses 1 iron/s and chemosynth uses 2 sulfide/s, then the player's sulfide would run out twice as fast. Seems like not a big issue since the player will just use the remaining iron anyways. However, this will make the speed at which ATP is used unbalanced and can be detrimental to species that need a constant supply of ATP. Perhaps it could provide a challenge for the player, I'm just citing my concerns with your plan.

**Comment by williamsokol** [comment]
So right now we only are adding: atp, glucose, iron, and hydrogensulfide. Is there any other materials that organelles will burn over time? 

I plan on just doing those for now

**Comment by hhyyrylainen** [comment]
Well the issue description does call for automatic detection, so I'd say it is better to write automatic detection code rather than hardcoding the possible list of compounds. If there are some that we don't want to give as initial compounds in the future, then a prevented list of initial compounds should be added.

**Comment by williamsokol** [comment]
if the player has a positive compound balance then they would start with 0 in that compound's initial value. Sounds a little weird but I don't think it will break anything
