### ISSUE TITLE
Merge SaveManager into SaveHelper

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1408]
as that class didn't really end up being used, the unused methods should just be deleted.

**Comment by DTanxxx** [comment]
Hi hhyyrylainen,
This is my first time contributing to a repository so I might have some questions during the process (however I do have a basic overview of the contribution workflow with git). As for this particular issue, (if you are ok with me making a pull request for this) would you like to have the SaveManager class completely removed and all previous reference to that changed to SaveHelper (referenced methods in SaveManager also moved to SaveHelper)? Or would you rather want the SaveManager class to be filtered of any unused methods? Thanks.

**Comment by hhyyrylainen** [comment]
SaveManager class should be completely removed, and any methods that are used from it should be moved to SaveHelper.
