### ISSUE TITLE
Make auto-save happen after fade

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1410]
to prevent the screenshot to be just all black, and the saving message not being visible.

**Comment by DTanxxx** [comment]
Hi hhyyrylainen,
Does the fade here refer to the one when I return from the microbe editor?

**Comment by hhyyrylainen** [comment]
Yes, and also the fade when entering the editor.
The auto save happens when the scene changes, but the fade is still in progress resulting in all the auto save screenshots being black.

**Comment by DTanxxx** [comment]
Here is a suggestion for this issue. Please let me know if this is fine:
For entering editor:
1. In MicrobeEditorGUI when StartTransitions is called in _Ready(), provide arguments (editor, a new method in MicrobeEditor called OnFinishTransition)
2. In MicrobeEditor, a new field called transitionFinished is initialised to false in _Ready()
3. The new method OnTransitionFinished() sets transitionFinished to true
4. In _Process(), if transitionFinished is false then return (so OnEditorReady() is not called unless both auto evo and transition are finished).
For exiting editor, MicrobeEditor.OnFinishEditing is already being called after transitions are finished, so the auto save for exiting editor should be working fine.

**Comment by hhyyrylainen** [comment]
Other than this that sounds fine, @Kasterisk made the fade system:

> For exiting editor, MicrobeEditor.OnFinishEditing is already being called after transitions are finished, so the auto save for exiting editor should be working fine.

That is actually not what happens. The save on entering back to the stage is also triggered before the fade in is complete and results in a completely black screenshot:
![2020-09-08_12 15 48 4683](https://user-images.githubusercontent.com/3796411/92457632-1d46f280-f1cd-11ea-8bb2-db83bb4925d6.png)
Top save is the return to stage save, and the one below that is the enter editor save.

**Comment by DTanxxx** [comment]
Ah sorry I didn't see the `HUD.OnEnterStageTransition()` call in OnReturnFromEditor and thought it was straight to auto saving. If that's the case, then can I make the StartTransitions call in HUD.OnEnterStageTransition take in (stage, a new method also called OnTransitionFinished but in MicrobeStage and is basically a refactor of:
`if (!CurrentGame.FreeBuild)
            SaveHelper.AutoSave(this);`
into a separate method)?

**Comment by hhyyrylainen** [comment]
That would be basically the same thing as in the editor, right? I already said that approach sounds fine to me.

**Comment by DTanxxx** [comment]
Great, thanks!
