### ISSUE TITLE
Implement clean up old saves button

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1417]
"Clean Up Old Saves" button in the load menu is currently always disabled.
It should do the following: delete all except the latest quick save and auto save. It shouldn't touch the manual save types.
It should have a confirmation popup.

- [x] the button is enabled when there is at least 1 save file
- [x] logic for it, including a confirmation dialog. should delete all quick saves and autosaves except the last one.

**Comment by DTanxxx** [comment]
Hi hhyyrylainen,
I would like to take on this issue. I have three questions though:
- Should the button be enabled when there is at least 1 quick or auto save file, or just 1 save file in general (including manual)?
- Should deletion leave one auto save and one quick save file (if there is any) or should it only leave either auto or quick save depending on whichever is the oldest?
- Does modifying the SaveHelper class such that it has a CleanUpOldSaves method that implements similar logic as DeleteExcessSaves sound good?

**Comment by hhyyrylainen** [comment]
- If it isn't too difficult to do then it would be nice for the button to only be enabled if pressing it would delete something.
Otherwise it's fine to just enable it when there is at least one save file.
- It should operate independently on quick and auto saves so that the latest of both types is left.
- I don't see a problem with putting a cleanup method in SaveHelper.
