### ISSUE TITLE
Tutorial for making Microbes

### ISSUE THREAD

**Issue by tjblazer85** [Revolutionary-Games/Thrive#142]
Hey Guys I think we're gonna need a tutorial on how to make a Microbe because some people might not know which organelle and how many of those organelles are needed for  a cell to be able to survive.

**Comment by Untrustedlife** [comment]
SO , tooltips?

**Comment by Moopli** [comment]
CEGUI supports them, and I think we already have an issue open on wrapping the functionality. When that's done, we could easily add the toolip content to handle this issue.

**Comment by TheCreator--** [comment]
There are tooltips that describe what organelles do, and there is a info panel that describes editing the microbe.
