### ISSUE TITLE
Implement quick save and auto save cleaning

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1420]
right now I think there's a skeleton method for the quick save cleaning.
Basically they should remove the oldest files matching the save type name if there are more of that type than specified in Settings.

**Comment by DTanxxx** [comment]
Hi hhyyrylainen,
For the two RemoveExcessAuto/QuickSaves methods, can I implement them in the following way:
1. Get the max saves for auto and quick in the respective methods, from Settings.
2. Call CreateListOfSaves in SaveManager ordered by SaveOrder.LastModifiedFirst -> last element of the array is the oldest file.
3. Create respective empty lists to store the names of quick and auto save files.
4. Initialise two counters for occurrences of quick and auto save files.
5. Iterate from last element to first element of save list: if file name starts with "quick_save", append that name to quickSaveNames list and increment counter; if file name starts with "auto_save", append to autoSaveNames list, and increment counter.
6. If after incrementation, either counter becomes greater than (or greater or equal to, depending on whether the remove excess method was called after or before the save file is actually made) max saves allowed then decrement and remove the first element of quick or auto save names list -- call SaveHelper.DeleteSave too on that first element.

**Comment by hhyyrylainen** [comment]
I think that sounds about right. I doubt there could be so many saves that building and sorting the entire saves list is going to be a problem. Anyway I planned to run the excess save delete in a background task so it's not that time critical.
