### ISSUE TITLE
Upgrade to godot 3.2.2

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1424]
- [x] scripts
- [x] documentation
- [x] CI images

**Comment by skyace65** [comment]
How do you update CI images? I don't think we did that during the 3.2.1 update.

**Comment by hhyyrylainen** [comment]
I did the image updates because they are under my docker hub account.

**Comment by hhyyrylainen** [comment]
I'll update the CI image while updating it for the new devbuilds.
