### ISSUE TITLE
Models for new compounds: generic amino acid, ammonia and reproductase

### ISSUE THREAD

**Issue by jjonj** [Revolutionary-Games/Thrive#143]
For cell reproduction we need a series of new compounds:
generic amino acid, ammonia and reproductase

These models are, like the previous compound models, are perhaps not permanent additions to the game but the alternative would be to use placeholders so it would be nice to have some kind of models for these, even if they aren't great looking ones.

**Comment by Moopli** [comment]
Fixed by aa3dd7e
