### ISSUE TITLE
Add alternative ATP balance mode based on what source of ATP organelles use

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1451]
alternative ATP balance mode based on what source of ATP the organelles have to make it easier to see where your energy is coming from in addition to what organelles make it

**Comment by CI09** [comment]
So basically disabling ATP production bar segments and enabling them depending on selected source?

**Comment by hhyyrylainen** [comment]
Well not exactly, I envisioned this more like a option button below the bars that based on the selected option would redo all of the bars for example if the player selects like "without iron" mode then the bars would be calculated as if there was no iron to give a better look into whether the player can survive with just some resource and not always have to have all of the resources.

**Comment by CI09** [comment]
Could you give another example? I think you can just click segments on balance bar to make them grey out or something like that so iron could be just done like that in this case.

**Comment by hhyyrylainen** [comment]
How would you turn off iron production organelles without this feature? You can individually check or remember which resources each organelle uses and click on them to turn them off, but that requires you to be an experienced player and to remember things correctly. So it is hard to do it manually, which is why I think it would be worth it to have a button in the GUI for doing it automatically.

**Comment by CI09** [comment]
Maybe it could be embeded somehow to editor [process panel](https://github.com/Revolutionary-Games/Thrive/issues/1979) then?

**Comment by hhyyrylainen** [comment]
I mean it kind of maybe could but to get an overview of what happens if your cell runs out of iron or hydrogen sulfide for example, you need an overall balance bar. It would be kind of redundant to have a second balance bar just in the editor process panel.
