### ISSUE TITLE
Implement delete selected button

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1458]
SaveManagerGUI.cs "private Button deleteSelectedButton;" is unused

- [ ] should be implemented so that it is enabled when some saves are selected.
- [ ] And the actual delete selected functionality

**Comment by DTanxxx** [comment]
Hi hhyyrylainen,
Here is my rough idea for solving this issue:
For the first part of the issue, I can add a `deleteSelectedButton.Disabled = selected.Count == 0` in UpdateLoadButtonStatus method, as well as changing the method name to UpdateButtonsStatus.
For the second part of the issue, I can hook up the delete selected button in editor with a new method DeleteSelectedButtonPressed, which then initialises and presents a deleteSelectedConfirmDialog. For this dialog node I can copy the deleteConfirmDialog from SaveList in the editor, and hook it up with another new method OnConfirmDeleteSelected, which would then call a GD.Print(), delete the selected saves, set selected to null and refresh save list. The only class that will be changed is the SaveManagerGUI class.

I have some questions regarding this approach:
- If I set the deleteSelectedConfirmDialog's size to be the same as deleteConfirmDialog's size, as I add more text does the dialog box resize itself automatically?
- For the text itself, should I write something like "Deleting these saves cannot be undone, are you sure you want to permanently delete:" then do a for loop through selected saves and for each one append to the text "\n{saveName}"?
- Inside GD.Print(), should I also do the same as above where I use a for loop and construct a string consisted of all save names to be deleted?

**Comment by hhyyrylainen** [comment]
The dialog sizes (if you don't touch anything) seem to resize automatically, though I'm not an expert using the Godot GUI system.

Listing all the save names might be a bit long and unnecessary, and might cause problems with the dialog size etc. So I'd say just include how many saves are going to be deleted.

GD.Print should list all of the saves that are deleted, just so the game logs can be checked why a save was deleted (so we can point the blame at the user if someone complains that their saves disappeared).

Otherwise sounds good, I didn't check the existing code though, so this is based on what I remember about the code.
