### ISSUE TITLE
Make membrane graphics work better around 0,0,0

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1485]
Around the world origin the membrane vertices seem to jump around a bit, would be nice to improve the shader so that it doesn't happen.

**Comment by Huitsi** [comment]
I took a look at this and it seems to me simply removing the sign(worldVertex.x/z) multipliers from Membrane.shader fixes this without any adverse effects. I don't know what they were doing in the first place though, so I might be missing something.

**Comment by hhyyrylainen** [comment]
Could record a video comparison of before and after? If all it does is fix the wiggle, it's fine by me.
I think I ported the `sign` part as is from our previous graphics engine, I didn't come up with the math for it.

**Comment by Huitsi** [comment]
[membrane.zip](https://github.com/Revolutionary-Games/Thrive/files/5277567/membrane.zip)

**Comment by hhyyrylainen** [comment]
It looks like it just fixes the problem. Could you make a PR with that change?
