### ISSUE TITLE
Add style for horizontal scroll bar

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1495]
Which seems to be missing, at least from the save error dialog:
![Kuvakaappaus - 2020-07-29 16-16-34](https://user-images.githubusercontent.com/3796411/88804998-5005d000-d1b7-11ea-8c47-fd9de4427810.png)

**Comment by CoreyHendrey** [comment]
Looks good to me.

![image](https://user-images.githubusercontent.com/18731181/89592380-d3967f80-d88f-11ea-9a00-7cba856225c7.png)
