### ISSUE TITLE
Change to using separators or other spacing instead of hard coded spaces

### ISSUE THREAD

**Issue by shibe2** [Revolutionary-Games/Thrive#1509]
Currently, some labels have whitespace in the beginning that is used for spacing between groups of elements. This gets in the way of localization: if there is the same string but without whitespace, it needs a separate translation.

Now there's a question: whether you want a separate translation for each screen or you want to reuse translation strings. If you want the latter, you should remove those spaces and use some other technique for spacing. But if you want the former, we can go with that as well.

While making Russian localization, we replace strings with identifiers (see #1359). Currently we make identifiers with reusability in mind, for example, "SPACE\_USED\_LABEL" for "Space used:". If we were to give up reusability, we could change the identifier to "SAVEMANAGERGUI\_SPACE\_USED".

Another option is something like "\_SPACE_USED\_", where underscore in the beginning is used when there is whitespace, and underscore in the end is used when there is a colon.

**Comment by hhyyrylainen** [comment]
I think it's good practice to use actual layout for whitespace. I was just lazing when doing the save manager as the hseparator isn't invisible by default.
It'd be nice to document how to add spacing that isn't rendered.

**Comment by shibe2** [comment]
Here is how spacing can be done 3 different ways: https://gist.github.com/shibe2/0f150c736205810a9f6d2eb1570d659b

**Comment by hhyyrylainen** [comment]
I changed this issue to be about removing instances where this is done. And added to the style guide update issue to write about the proper approach: https://github.com/Revolutionary-Games/Thrive/issues/1447
At least the save manager has this. Is this done somewhere else?

**Comment by shibe2** [comment]
Leading whitespace was only in save manager. There is trailing whitespace in src/general/OptionsMenu.tscn.
