### ISSUE TITLE
Move more styling to thrive_theme.tres

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1512]
I've noticed that quite a few places use per-element styles to make things look the wanted way. For easier development of new GUI stuff it'd be really nice to move as much stuff as possible into thrive_theme.tres to make the look of controls reusable.

**Comment by hhyyrylainen** [comment]
I think this is maybe complete now, @Kasterisk ?

**Comment by Kasterisk** [comment]
It still has quite a few styles not yet customized, but more or less should be good enough for common UI elements to have the default Thrive look.

**Comment by hhyyrylainen** [comment]
Let's consider this done for now. I moved some additional styling to the base thrive theme when converting to Godot 4.
