### ISSUE TITLE
Add extinct indicator to extinct species in the auto evo results

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1514]
Right now you can only notice something going extinct by seeing that all new patch populations are 0

**Comment by Straywind** [comment]
I think I can manage this.

Should it indicate only a total extinction, or should it also/seperately mention if the population of a species in a particular patch reaches 0, instead of simply stating that that species' population is now 0?

**Comment by hhyyrylainen** [comment]
I think it would be more readable if it also said that a species is extinct in a specific patch instead of the population, in order to more easily tell in which patches the species has disappeared.
