### ISSUE TITLE
Add fallback font for chinese

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1516]
For a chinese translation to be possible we need a font that has chinese characters.
https://docs.godotengine.org/en/3.2/classes/class_dynamicfont.html
Says "DynamicFont also supports defining one or more fallbacks fonts, which will be used when displaying a character not supported by the main font." so it should be relatively simple to set that up.

Some suggested fonts (note that I didn't even check the licenses on these if they can be used):
(links now broken)
https://www.flopdesign.com/freefont/smartfont.html
https://www.flopdesign.com/freefont/kanjyukugothic-freefont.html
https://www.flopdesign.com/freefont/kanjyukugothic-freefont.html

(~~Note that once the font is done, there's still some effort to make the game translateable, but that seems to be in progress for a Russian translation which once done will help all other translations.~~ this part is now done)

**Comment by BrightShadowMoon** [comment]
those 3 link I posted was work while last time I check...now they are 403 Forbidden....
here have a good choice for many different language.
https://github.com/googlefonts/noto-fonts

**Comment by hhyyrylainen** [comment]
Once this is done the localization file for Chinese can be enabled by adding it to project.godot

**Comment by hhyyrylainen** [comment]
I'm now working on this, needs a little bit more work than I anticipated as all the GUIs need to be modified to not use fonts directly, instead I need to make new Godot font definitions that contain the fallback fonts for everything.
