### ISSUE TITLE
Reduce compound spawns while the player is stationary

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1550]
to not make it too OP

I would implement it with a variable tracking how much the player has moved, if the player has not moved much for a while I'd start to reduce the chance that compound clouds are spawned.

**Comment by Straywind** [comment]
I'll try this

**Comment by hhyyrylainen** [comment]
Well we now got code that will stop *all* spawns if the player is too stationary, which I guess is at least partly addressing the problem with this, though I still would have liked to see an exponentially reducing spawn rate for compounds while stationary, while still spawning microbes up to the game entity limit.

**Comment by Maxonovien** [comment]
I think that such a change would not be much of an issue, given that I have a count of entity `e`, the cap `c`, so you'd have to apply a factor exp(c-e) (with clamping to safeguard things) to the spawner trials. So I think what you want can be pretty well expanded over my PR.
