### ISSUE TITLE
Add numbers back to the ATP balance bar

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1559]
to at least show the totals

**Comment by DTanxxx** [comment]
Hi hhyyrylainen,
For this issue, are you looking for just the final ATP balance being shown on the bar or would you also want to have labels on each of production and consumption bars showing their values?

**Comment by hhyyrylainen** [comment]
The totals would be fine, and probably what this issue means.
It would be a bit cluttered to show the sub-bar values as well.
I think that the tooltips that are to be added for them should contain the individual bar values:
https://github.com/Revolutionary-Games/Thrive/issues/1396

**Comment by DTanxxx** [comment]
Right got it.
