### ISSUE TITLE
Improve editor tooltips

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1563]
Some ideas as to what to fix in them by @NickTheNick 
- [x] Don't talk about fermentation in tooltips rename to glycolysis (whatever the actual process name is) for that organelle
- [x] Chemosynthesis is one word
- [x] Respiration -> Aerobic Respiration
- [x] Aerobic Nitrogen Fixing -> Aerobic Nitrogen Fixation

**Comment by ender-titan1** [comment]
@NickTheNick are you doing this or can I take over?

**Comment by hhyyrylainen** [comment]
Nick has once again become inactive. I'm going to assume that you are unlikely to get a retry, so I'm unassigning him from the issue. You can give this a try if you want.

**Comment by ender-titan1** [comment]
Ok. 
On it.

**Comment by hhyyrylainen** [comment]
Many of these changes are probably possible to do on https://translate.revolutionarygamesstudio.com/ as suggestions on the English text.

**Comment by ender-titan1** [comment]
In which string is 

> Aerobic Nitrogen Fixing -> Aerobic Nitrogen Fixation

needed?

**Comment by hhyyrylainen** [comment]
Search for it in the english translation. Or learn to use something like https://github.com/ggreer/the_silver_searcher

**Comment by ender-titan1** [comment]
I changed all I found.

**Comment by hhyyrylainen** [comment]
@ender-titan1 I think you missed quite a few places with fermentation usage and some of the other ones as well. I think I now got all of them on the translations site, so I'll close this issue.
