### ISSUE TITLE
Add support for unit tests

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1571]
- [ ] Godot requiring tests (opened separate issue: https://github.com/Revolutionary-Games/Thrive/issues/4963)
- [x] plain c# requiring tests

Until godot adds proper support we should maybe use nunit3 directly.
Godot proposal: https://github.com/godotengine/godot-proposals/issues/432 (go thumbs up this)

**Comment by rhumborl** [comment]
I have dropped nunit3 in to the solution and done some initial investigation.
See https://github.com/rhumborl/Thrive/blob/1571_cs_unit_test_support/Thrive.Test/DummyTest.cs

If a universally-executable runner doesn't appear as van800 was looking at in the proposal, you'll need to discuss how much test coverage vs. refactoring you might need to do.
