### ISSUE TITLE
Editor hexes invisible in GLES2 on intel graphics

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1576]
Error:

```
ERROR: mesh_surface_get_array: OpenGL ES 2.0 does not allow retrieving mesh array data
At: drivers/gles2/rasterizer_storage_gles2.cpp:2671
```
and this:
```
**ERROR**: OpenGL ES 2.0 does not allow retrieving mesh array data
   At: drivers/gles2/rasterizer_storage_gles2.cpp:2671:mesh_surface_get_array() - OpenGL ES 2.0 does not allow retrieving mesh array data
```

These don't seem to be GLES2 specific problems as I don't have these errors and don't have the issue when running in GLES2 mode. So intel HD graphics + GLES2 (probably some older CPU) is the combination with issues.

**Comment by hhyyrylainen** [comment]
Original reporter has this CPU: https://ark.intel.com/content/www/us/en/ark/products/59836/intel-pentium-processor-b960-2m-cache-2-20-ghz.html

**Comment by westtunger** [comment]
There is an issue about that on the [Godot repo](https://github.com/godotengine/godot/issues/37147)

That may have been fixed in [40235](https://github.com/godotengine/godot/pull/40235)

**Comment by hhyyrylainen** [comment]
Interesting so update to Godot 3.2.3 probably will fix this.
One interesting thing I read from that link is that this only happens in exported game, so that's why I couldn't get it to happen.

**Comment by hhyyrylainen** [comment]
Testing this with Godot 3.3 would be nice, considering there's already a PR open for updating to Godot 3.3: https://github.com/Revolutionary-Games/Thrive/pull/2215 (though it needs some actions for, which I've been too busy to do).

**Comment by hhyyrylainen** [comment]
I was able to test now that at least on Linux with GLES2, this is no longer a problem in an exported game.
