### ISSUE TITLE
Fluid dynamics

### ISSUE THREAD

**Issue by Moopli** [Revolutionary-Games/Thrive#158]
Implement a viscous-drag and turbulence system to make the water which microbes swim through more realistic. The drag would act to minimize the relative velocity of objects with respect to the water in their immediate surroundings, causing cells to get pulled along by currents. See http://thrivegame.forum-free.ca/t1257p15-microbe-stage-gdd#30130 for details.

**Comment by T0N12** [comment]
[Position Based Fluids](http://mmacklin.com/pbf_sig_preprint.pdf) are a very realistic way to simulate fluids in real-time efficiently, as [this demo shows](https://www.youtube.com/watch?v=6WZZARzpckw). Implementing position based fluids might require modifying the physics engine [Bullet](http://bulletphysics.org/wordpress/) but we could ether work together with the Bullet developers to implement it, or do it ourselves and give the changes to the bullet team to implement it into Bullet.

**Comment by jjonj** [comment]
This is done right @TheCreator--

**Comment by TheCreator--** [comment]
Not yet. We still need to have currents move the cells.
