### ISSUE TITLE
Icons for ATP Balance bars has a delay

### ISSUE THREAD

**Issue by icedjuro** [Revolutionary-Games/Thrive#1598]
When adding new organelles, some bars shrink. And if they get too small, they won't show the icon. However, on the placement that should remove the icon, it stays. It takes another placement before the changes take effect. Same thing for showing the icon when it is big enough, there is a 1 placement delay.

**Comment by Apsum** [comment]
Hi, can i get assigned to this issue ? Thanks

**Comment by hhyyrylainen** [comment]
Sure

**Comment by hhyyrylainen** [comment]
I'll assume you @Apsum aren't working on this anymore, so I'll unassign this issue.
