### ISSUE TITLE
Remove checkbox workaround for styling once godot releases a fix

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1599]
Checkboxes need to specify a custom style, in order to get the style in the thrive theme to apply to them.
https://github.com/Revolutionary-Games/Thrive/pull/1595#issuecomment-690613896
https://github.com/Revolutionary-Games/Thrive/pull/1595#issuecomment-690673746

Waiting for this Godot issue to be fixed: https://github.com/godotengine/godot/issues/34727

**Comment by Kasterisk** [comment]
We now CustomCheckbox that doesn't utilize this workaround I think, and since that Godot issue is now fixed I think this can be closed.

**Comment by hhyyrylainen** [comment]
Did we actually update our checkbox style for this? I don't remember seeing us changing our style. Wasn't it that CustomCheckbox was created *just* to workaround this. Meaning that this issue should only be closed once we no longer need CustomCheckbox...

**Comment by Kasterisk** [comment]
Uh no, we used CustomCheckbox so that our checkbox hover texture have some use. It's not a workaround, it ends up being an alternative. In fact, I propose we keep using CustomCheckbox moving forward.

**Comment by hhyyrylainen** [comment]
Still sounds like a hack around Godot's inbuilt checkbox class not being fully done...

**Comment by 84634E1A607A** [comment]
Partly fixed in Godot 3.6 https://github.com/godotengine/godot/pull/62644

**Comment by hhyyrylainen** [comment]
With the Godot 4 update the custom checkbox was removed.
