### ISSUE TITLE
Check for crashes on reproduction and fix any issues.

### ISSUE THREAD

**Issue by jjonj** [Revolutionary-Games/Thrive#160]

**Comment by Moopli** [comment]
The error:
> ../scripts/microbe_stage/microbe.lua:1004: attempt to index local 'body2' (a nil value):
>     [C]:-1 (metamethod __index)
>     ../scripts/microbe_stage/microbe.lua:1004
> 
> terminate called after throwing an instance of 'luabind::error'
>   what():  lua runtime error
> Aborted (core dumped)

**Comment by Moopli** [comment]
A new error after fixing the first:
> ../scripts/microbe_stage/microbe.lua:322: Can't create microbe from this entity, it's missing compoundEmitter:
>     [C]:-1
>     [C]:-1 (global assert)
>     ../scripts/microbe_stage/microbe.lua:322
>     [C]:-1 (global Microbe)
>     ../scripts/microbe_stage/microbe.lua:989
> 
> terminate called after throwing an instance of 'luabind::error'
>   what():  lua runtime error
> Aborted (core dumped)

**Comment by Moopli** [comment]
Another new error:
> ../scripts/microbe_stage/microbe.lua:322: Can't create microbe from this entity, it's missing compoundAbsorber:
>     [C]:-1
>     [C]:-1 (global assert)
>     ../scripts/microbe_stage/microbe.lua:322
>     [C]:-1 (global Microbe)
>     ../scripts/microbe_stage/microbe.lua:988
> 
> terminate called after throwing an instance of 'luabind::error'
>   what():  lua runtime error
> Aborted (core dumped)

**Comment by Moopli** [comment]
And more:
> ../scripts/microbe_stage/microbe.lua:322: Can't create microbe from this entity, it's missing microbe:
>    [C]:-1
>    [C]:-1 (global assert)
>    ../scripts/microbe_stage/microbe.lua:322
>    [C]:-1 (global Microbe)
>    ../scripts/microbe_stage/microbe.lua:988
>
>terminate called after throwing an instance of 'luabind::error'
>  what():  lua runtime error
>Aborted (core dumped)

**Comment by Moopli** [comment]
All these errors seem to be due to the newly-made microbe being misconfigured. It smells like a race condition between microbe creation (which does all the configuring) and the first parts of the code which need the microbe configured (which fail with errors like the above when they try running with an incompletely-initialized microbe). That explains both the nondeterministic failure and the fact that cause of abort changes every time.

**Comment by jjonj** [comment]
Fixed with 2589fce
