### ISSUE TITLE
Add editor function to move organelles around

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1606]
It will help people make their cells symmetrical and make organelle placement much more sensible.
It should probably either be free or cost very little MP.

One potential way to add this (this was in some editor GUI concepts): is to replace right click delete with a context menu where you'd have delete and move as options.

**Comment by Satharis** [comment]
Alternative might be some kinda toggle button that turns left click into move so you can drag and drop them to a new spot, or just click them once and then it gives you the ghost image to place it somewhere else.

One issue with moving and building the cell is moving multi-hex parts might be kinda annoying like trying to move the nucleus. I considered maybe the cell editor should be changed so you can place cell pieces at arbitrary points on the grid that aren't connected and simply not let you finish editing until all of them are touching. That way you could sorta move parts off to the side 
and then stick them back together how you want.

Another idea might be to let you 'store' parts once you have placed one and 'bought' it, if you store it then it adds a quantity indicator over the organelle in the selection menu, that way you could take parts off your cell and place them again for free.

**Comment by hhyyrylainen** [comment]
Certainly for moving organelles around it'd be much nicer to be able to place them temporarily in invalid locations.

**Comment by icedjuro** [comment]
A solution came to me that would make this pretty easy. If you right click, it gives you the option to delete it or move it. If you press move, you simple delete the part and select it in your cursor. You then have to place it somewhere. The only real coding would be making moving an organelle a new type of action. The nucleus would be tricky to do, but I don't think you should be allowed to move it tbh.
