### ISSUE TITLE
Add a way for the player to control organelle split (growth) order

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1622]
way to control the order of organelles splitting in order to not die. Basically some kind of thing that lets you reorder the organelles in the player species, splitting should happen in the order the organelle list in the species defines

**Comment by Fatheadgaming** [comment]
yeah you should do that it would be more fun because every time i get ammonia and phosphate my mitocondria keep splitting then i die because i consume waaaaaaay too much glucose to even stay alive. so yeah that's a good idea
