### ISSUE TITLE
Make radius to detect cells under the cursor bigger

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1633]
To make it easier to hover over small cells, and partly mitigate: https://github.com/Revolutionary-Games/Thrive/issues/1394

**Comment by Straywind** [comment]
I'll try this one on, if it's all the same

**Comment by Kasterisk** [comment]
Is it safe to close this now?

**Comment by hhyyrylainen** [comment]
Yes. For some reason the PR didn't close it even though it mentioned it with `closes`.
