### ISSUE TITLE
Make the code use the new unknown key icon

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1636]
make an actual icon for "button icon is missing"

Blank templates are here: https://dev.revolutionarygamesstudio.com/lfs/thrive/assets/textures/gui/xelu_prompts/Keyboard_Mouse/Blanks

Probably good enough to take the blanks and add a `?` on them?

**Comment by Fatheadgaming** [comment]
lol

**Comment by hhyyrylainen** [comment]
Why did you comment that? If you don't have anything to add please use Github reactions instead of commenting which sends a bunch of people email notifications.

**Comment by Kertit** [comment]
I agree just adding a question mark will do this perfectly.
Can this be done using fonts directly in the game? 
If not I'll create the icon.

**Comment by hhyyrylainen** [comment]
It's not possible to display text on top of the key icon images without adding an entirely new system to handle that, which I don't think is really worth it just to support for *one* icon.

**Comment by Kertit** [comment]
Done 
https://dev.revolutionarygamesstudio.com/files/Asset%20development/Icons/NoKeybutton.png

**Comment by hhyyrylainen** [comment]
Nice. 
The DevCenter actually doesn't support file deletion yet: https://github.com/Revolutionary-Games/ThriveDevCenter/issues/40 well maybe someday I'll have time or someone will help me with that...

**Comment by Kertit** [comment]
I guess you can now mark this as done? or at least for the graphic part

**Comment by hhyyrylainen** [comment]
Updated this issue to now just be the code side of things.
