### ISSUE TITLE
More verbose lua error reporting

### ISSUE THREAD

**Issue by Moopli** [Revolutionary-Games/Thrive#164]
We need something better than

    terminate called after throwing an instance of 'luabind::error'
      what():  lua runtime error
    Aborted (core dumped)

Call stack? Lua globals dump?

**Comment by Moopli** [comment]
http://stackoverflow.com/questions/10768610/lualuabind-no-error-information-at-top-of-stack-after-runtime-error

**Comment by jjonj** [comment]
This was fixed with #257
