### ISSUE TITLE
Add button in options to open screenshots folder

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1642]
to make them easier to find

**Comment by Paulpicotin** [comment]
Hi, May i please get assigned to this issue ? Thanks in advance

**Comment by hhyyrylainen** [comment]
Sure.

It seems a bunch of people have wanted issues assigned to them lately. I better see a bunch of new PRs soon...

**Comment by Paulpicotin** [comment]
Hi, can you telle where am I suppose to putt the button in the menu I was thinking in graphics options but I prefer asking

**Comment by hhyyrylainen** [comment]
It should be put in misc as it is not a graphics related option.
Really the place for it would be in the key bindings options next to taking a screenshot key, but as we don't have that yet, it should go in misc.

**Comment by Paulpicotin** [comment]
ok thank's

**Comment by Paulpicotin** [comment]
hello , I'm just working on this issue and I'm at the end of it but I've got a question , when I try to find the screenshot folder in (Constants.SCREENSHOT_FOLDER) 
I got an  InvalidParameter errror 
so I'm asking me if this folder exist

**Comment by hhyyrylainen** [comment]
Have you tried taking a screenshot in the game before (press F12)? The folder should be created the first time you take a screenshot.
A button for opening that folder should properly show the error to the user if the folder doesn't exist yet.

**Comment by Paulpicotin** [comment]
ok I try

**Comment by Paulpicotin** [comment]
Ok it works I don't catch any error but the folder doesn't open and I don't know why

**Comment by hhyyrylainen** [comment]
Compare your code with the open saves folder button to see if it is different.
