### ISSUE TITLE
Make cells rotate around their center of mass (fractional offset)

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1645]
instead of always having the hex at 0,0 be the center of the cell in the stage.
Instead could compute average position of all hexes and use that as offset all the organelles when rendering and in physics.
This will prevent weirdness if the player doesn't build their cell around the middle of the editor grid.

closes #1678

**Comment by Kasterisk** [comment]
This should be already fixed by #1695

**Comment by hhyyrylainen** [comment]
I left this open because that only moves the center based on the hexes.
This issue is for making it be possible to fractionally move the origin offset, to make it exactly perfect.

**Comment by hhyyrylainen** [comment]
I'm starting to think that the current approach is probably good enough and this can be just closed if no one cares enough to implement this slight improvement.

**Comment by hhyyrylainen** [comment]
Looks like no one cares, so I'll close this as an unnecessary complication to the offset code that isn't needed.
