### ISSUE TITLE
Add key rebinding to options menu

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1653]
add a new tab in options menu for rebinding the keys (and adding more bindings) defined in the godot project so that players can customize the control scheme.

I was pretty sure there was already an issue for this, but I can't find it right now so I'm opening a new issue.

**Comment by FuJa0815** [comment]
![ThriveKeyrebind-1](https://user-images.githubusercontent.com/30809803/97288324-fe1c2700-1845-11eb-97c1-e6dbd76ee281.png)
Does this look about right?

**Comment by FuJa0815** [comment]
The import profile drop down contains a few predefined input methods.
When selecting Custom, the user can mess with the values below.
When you click on a button, a big screen pops up prompting the user for an input.
Invalid inputs are:
Esc
Control
Shift
Alt

The reason why Ctrl/Shift/Alt are invalid on their own is because the user can input key combinations like Ctrl+Z.

**Comment by hhyyrylainen** [comment]
I don't think we need a set of presets. I think it should be a button that resets the keybindings.
Regarding the individual inputs, I think we need these operations:
- Remove a keybinding
- Add a keybinding
- Modify a keybinding
Also there should be the controller inputs as well for each of the actions.

The cheats and fps toggle should be rebindable. ESC should be the only-non-rebindable key as that is needed for canceling the 
rebind.

One final thing: I suggest that the buttons to press would use the KeyPrompt system (with some additions for shift and other modifiers) in order to display the key bindings the same way they will appear in game.

**Comment by FuJa0815** [comment]
Do you mean that you can have more than two keys bound to one action?

**Comment by hhyyrylainen** [comment]
Yes, I think we should have a system that allows at least like 10 keybindings for each action. After the first 4-5 keybindings the thing should scroll to allow enough space.
Also if something is bound already to something else there should be a warning. Optimally this would be split into "domains" so that, like some games, we wouldn't unnecessarily give warnings for example if the player binds W to move forward and drive forward, as those actions should be in like a different domain as they don't actually conflict as both can't be active at the same time.

Because for some action you have:
- "Normal" keyboard input
- Alternative keyboard input
- And maybe even a third one, for example scroll is bound to: mouse wheel, + on keyboard, and + on the numpad
- Controller key mapping

**Comment by FuJa0815** [comment]
Ok, one missing topic are input axis.
Does KeyPrompt handle axis inputs as normal keys?
Does the code support axis inputs?

**Comment by hhyyrylainen** [comment]
I think there needs to be perhaps some kind of handling especially for allowing analog sticks to be used, but usually at least for WASD games let you rebind those individually.
