### ISSUE TITLE
ATP and health bar can get stuck

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1658]
https://github.com/Revolutionary-Games/Thrive/pull/1587#issuecomment-700172281

**Comment by hhyyrylainen** [comment]
Seems especially prominent when returning from a save made in the editor, the ATP bar always gets stuck not entirely full. Seems like this might be related to a big delta value as it can get stuck not entirely full when the game lags a bit as well, I've noticed.

**Comment by hhyyrylainen** [comment]
This might be fixed as I fixed a problem where the bar update method might get called with 0 or negative time passed, probably causing the bar progress problems.
If no one can get this issue to happen again, we can close this.

**Comment by hhyyrylainen** [comment]
Seems to also happen with 0.5.3
And the health bar also can suffer from this

**Comment by hhyyrylainen** [comment]
This is now better after: https://github.com/Revolutionary-Games/Thrive/pull/2077
however it can still get stuck for like half a second after which it moves in a very jittery manner. So there's definitely still some problems with this. Especially noticeable for me when suiciding.

![2021-02-12_17 38 01 4240](https://user-images.githubusercontent.com/3796411/107788819-853fcd00-6d59-11eb-9e57-42f220630ff9.png)

![2021-02-12_17 38 21 4121](https://user-images.githubusercontent.com/3796411/107788832-883abd80-6d59-11eb-9c43-abecdf17d2a1.png)

![2021-02-12_17 38 26 1212](https://user-images.githubusercontent.com/3796411/107788849-8b35ae00-6d59-11eb-90a2-36057006a019.png)

**Comment by Kasterisk** [comment]
Some ideas from hh on discord on how to go about fixing this.
> I have just one more idea: what if the interpolation would track the total elapsed time? and if for like 0.1 seconds it doesn't progress it would force progress. Or how about the interpolate method always guaranteeing that the bar moved at least EPSILON units? That way very short delta wouldn't break it.

> One more idea: what if the bar would keep track of the old value, and time elapsed since, and interpolate based on that? Then whenever the target value changes it would reset the old value to current and the elapsed time to the current delta time. I think that might be the ultimate best solution / fix for this, as it couldn't get stuck on a single value that's not the target value

Probably could be implemented in a new helper class.
