### ISSUE TITLE
Keyboard Lagging

### ISSUE THREAD

**Issue by Anth0rx** [Revolutionary-Games/Thrive#1666]
**Describe the bug**
I am experiencing enormous keyboard lagging when playing Thrive. After some time holding WASD to move there is a massive lag when releasing the key. It keeps moving for more than a minute and I am not able to interrupt moving.

**To Reproduce**
1. Start the game
2. Hold down WASD or arrow keys to move in any direction for more than five seconds
3. Release keys

**Expected behavior**
I would expect the microbe to stop moving immediately after holding WASD to move.

**System info (please complete the following information):**
- OS: 
- CPU: Intel(R) Core(TM) i5-4300U
- Thrive version: 0.5.1.1

**Logs**
Game logs: https://pastebin.com/reUePcu4

**Comment by hhyyrylainen** [comment]
From the GPU message line, looks like you are on Linux.
Does this always happen? Does it happen when you return from the editor? What about if you play in freebuild does it happen then as well?
Also, if you hold down W for a while to get movement to stay on, does it help if you press W again?

**Comment by Anth0rx** [comment]
Yes, I am on Linux and yes it always happens. The "movement toggle" remains even after returning from the editor. In freebuild it is the same. Unfortunately pressing W does not help.

**Comment by hhyyrylainen** [comment]
My only guess is that Godot for some reason doesn't pass the key input to our code. I don't really see any other way things can fail like this. Unless of course your desktop environment starts messing with the key presses.
I'll tag this as engine related issue.

**Comment by hhyyrylainen** [comment]
I just noticed something interesting in a godot blog post (https://godotengine.org/article/x11-display-server-progress-report) one of the improved things is listed as:
"The more general X11 fixes are about:
- Delay with keyboard inputs"

So it might be that this issue gets resolved once we update to godot 4.0 (once that is released).

**Comment by hhyyrylainen** [comment]
This needs to be reviewed once the next Godot version comes out if this is still a problem.

**Comment by hhyyrylainen** [comment]
I'll assume that this is fixed with the latest Godot engine versions. Feel free to reopen or comment if this is still a problem in the latest Thrive version.
