### ISSUE TITLE
Make Player.OnDeath disable reproduction dialog

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1670]
to try to make sure that the player surely can't enter the editor while dead.
https://community.revolutionarygamesstudio.com/t/0-5-2-release-candidate-testing/3063/3?u=hhyyrylainen

**Comment by SamuelValencik** [comment]
Hello, I would like to contribute to this project by resolving this issue. Could you please assign me for this?

**Comment by hhyyrylainen** [comment]
Done
