### ISSUE TITLE
Partial failure in returning to the microbe stage

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1674]
https://community.revolutionarygamesstudio.com/t/0-5-2-release-candidate-testing/3063/16?u=hhyyrylainen
https://community.revolutionarygamesstudio.com/t/0-5-2-release-candidate-testing/3063/22?u=hhyyrylainen

**Comment by RacerBG** [comment]
I can not reproduce this issue. Any volunteers? :smile:

**Comment by hhyyrylainen** [comment]
I guess this has gotten fixed by either Godot or us at some point so I'll close this. I do still occasionally see the signal connect failure but those don't seem to impact anything at all.

**Comment by RacerBG** [comment]
> I guess this has gotten fixed by either Godot or us at some point so I'll close this. I do still occasionally see the signal connect failure but those don't seem to impact anything at all.

I will keep an eye on it once we switch to Godot 4 just in case.

**Comment by hhyyrylainen** [comment]
We need to test basically *everything* after the switch to Godot 4 to make sure nothing (surprising) breaks.
