### ISSUE TITLE
Back button in options not working

### ISSUE THREAD

**Issue by FuJa0815** [Revolutionary-Games/Thrive#1677]
The back button in the options didn't work.

Steps to reproduce the behavior (I didn't try to reproduce it to keep the session, so that I can look at the bug with the debugger):
1. Go to Options
2. Change some options
3. Save
4. Alt-Tab a bit
5. Resize
6. Back button didn't work

**Expected behavior**
The options menu should close

**Screenshots**
![backBug](https://user-images.githubusercontent.com/30809803/95623268-47fac400-0a75-11eb-9cb3-c53878b490f6.gif)

**System info (please complete the following information):**
- OS: Windows 10
- Graphics card: GeForce GTX 980 TI SLI
- Thrive version: 0.5.2.0

**Logs**
The Godot-Console shows no errors.

**Additional context**
I am currently debugging the problem.

**Comment by hhyyrylainen** [comment]
Did you build the game yourself? The options menu shouldn't look like that, leading me to believe that you have a case of godot automatically breaking things (reclone or git reset to get rid of the unintended changes).
This is what the options menu should look like:
![2020-10-09_22 27 35 9759](https://user-images.githubusercontent.com/3796411/95624007-daec2c00-0a7e-11eb-8d79-8b7e491f6287.png)

I quickly tried to reproduce issue on latest master branch code, but didn't get it to happen.

**Comment by FuJa0815** [comment]
Ok, it is some kind of godot - git issue.
As you can see from the screenshot, initially there were no changes and the branch was up to date.
Then I started godot, launched the game and there were three modified files.

- In the MainMenu.cs file, 4 spaces were replaced by 6 spaces.
- In thrive_theme, some values were set to null and removed
- In the MainMenu.tscn those lines got removed:
```
[connection signal="OnOptionsClosed" from="OptionsMenu" to="." method="OnReturnFromOptions"]
[connection signal="OnBackPressed" from="SaveManagerGUI" to="." method="OnReturnFromLoadGame"]
```
![grafik](https://user-images.githubusercontent.com/30809803/95625104-3ff05380-0a78-11eb-962a-9e953949db20.png)

Why does godot mess with my files??

Sorry for the fake issue.

**Comment by FuJa0815** [comment]
PS: I have cloned the repro three times, every time godot messed with the files.

**Comment by hhyyrylainen** [comment]
No problem, almost all programmers on the team have at some point experienced problems with godot automatically breaking stuff.

I don't know why but it's just sometimes godot decides when opening some resource that it wants to break it. That first point you mention, I haven't gotten, but I somewhat regularly experience godot setting node paths to null or breaking the theme.

So it's bad advice to reclone as godot just does it again without the import cache? Good to know, I always myself just kill the changed files while godot is closed and that has always fixed things for me.

I'll add on my todo list to add this pretty common issue to the setup guide / new issue template as this is very common.

Might be nice to try to find / report this problem to the Godot developers as this is pretty annoying and especially new contributors have problems. In Thrive this seems very wide spread problem, so I haven't reported to godot thinking that some other project must be having the same problem.

**Comment by FuJa0815** [comment]
`git reset --hard` seems to work, with the exception that godot really wants to replace the spaces with a tab in MainMenu.cs I just have to watch out to not stash all changes, which is a bit anoying...
