### ISSUE TITLE
Your only part can be out of origin

### ISSUE THREAD

**Issue by FuJa0815** [Revolutionary-Games/Thrive#1678]
You can "strech" your being by "moving" the origin

**Describe the bug**
When the only structure is **not** the origin, weird things can happen

**To Reproduce**
1. Place a line
![grafik](https://user-images.githubusercontent.com/30809803/95627787-0ec65200-0a7d-11eb-9971-7d70e9f0fc98.png)
2. Remove the line, starting with the oldest part
3. Repeat until your only part is far away from the origin

**Expected behavior**
The editor and ingame-origin should be recalculated when clicking confirm. See #1668

**Screenshots**
![grafik](https://user-images.githubusercontent.com/30809803/95627403-74fea500-0a7c-11eb-8ae7-8c5cbecdb760.png)
![grafik](https://user-images.githubusercontent.com/30809803/95627553-ae371500-0a7c-11eb-8258-6b124d8d79bc.png)
When abusing this to the extreme, your cell can get invisible

**Comment by hhyyrylainen** [comment]
Related to: https://github.com/Revolutionary-Games/Thrive/issues/1645
If that issue is fixed, this problem should also go away.
I won't close this as a duplicate now as this demonstrates some pretty serious problems not fixing https://github.com/Revolutionary-Games/Thrive/issues/1645 causes.

**Comment by FuJa0815** [comment]
Also, this problem extends #1645 by also breaking the editor
