### ISSUE TITLE
Update Setup Instructions to stop godot from replacing spaces with tabs

### ISSUE THREAD

**Issue by FuJa0815** [Revolutionary-Games/Thrive#1679]
By default the godot script editor replaces four spaces with one tab.

This should not be a problem, because developers should use external editors, but the godot script editor opens the _MainMenu.cs_ by default,therefore messing with the spaces in that file.
To stop godot from doing so you can go to **Editor > Editor Settings > Text Editor > Indent > Type** and select **Spaces**.

I think this would make a good extension to the Getting Started Guide.
![grafik](https://user-images.githubusercontent.com/30809803/95636461-800f0080-0a8f-11eb-9fbe-429559c03209.png)
![grafik](https://user-images.githubusercontent.com/30809803/95636481-8e5d1c80-0a8f-11eb-85d2-c68f0dd7ee30.png)

**Comment by hhyyrylainen** [comment]
Good idea.
I put the editor settings image to the same place as the other images: https://randomthrivefiles.b-cdn.net/setup_instructions/images/godot_editor_use_spaces.png (there is already an image showing the editor settings opening)
So all that's needed for this is writing a bit of explanation text and adding link to that image.
