### ISSUE TITLE
Make sure auto-evo run doesn't start before auto-save in stage

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1685]
The auto-evo run start should be delayed until auto save has happened (or if auto-save is not on, until the fade is complete).

**Comment by Sourciluss667** [comment]
Hi, i want to contribute by resolving this issue.

**Comment by Sourciluss667** [comment]
And to be sure I'm on the good way, I just need to invert these conditions in MicrobeStage.cs ?

        // Start auto-evo if not already and settings have auto-evo be started during gameplay
        if (Settings.Instance.RunAutoEvoDuringGamePlay)
            GameWorld.IsAutoEvoFinished(true);

        // Save if wanted
        if (TransitionFinished && wantsToSave)
        {
            if (!CurrentGame.FreeBuild)
                SaveHelper.AutoSave(this);

            wantsToSave = false;
        }

**Comment by hhyyrylainen** [comment]
I don't know about inverting but the auto-evo triggering needs `TransitionFinished == true && !wantsToSave` to be true before it should be checked.
