### ISSUE TITLE
Disconnected parts allowed

### ISSUE THREAD

**Issue by FuJa0815** [Revolutionary-Games/Thrive#1694]
You can have disconnected parts in the editor
![grafik](https://user-images.githubusercontent.com/30809803/95664114-18b38800-0b45-11eb-851e-dd3e9bc6f282.png)

**Expected behavior**
When you finish editing, the game should check if every grid is connected with every other (no islands). When there are disconnected parts, the game should not let you apply those changes.

**Comment by FuJa0815** [comment]
Is there any code anywhere for getting one hexes neighbors?
Do I have to write those methods?

**Comment by hhyyrylainen** [comment]
There's a lookup table in Hex for those. I think Mutations.cs (or something it calls) takes advantage of those for looping neighbouring hexes.

**Comment by FuJa0815** [comment]
When I detect islands, I thought of a popup, that notifies my, that those changes are invalid. How should I create that popup?

**Comment by FuJa0815** [comment]
Another possibillity would be to check for islands on any removal.
When islands are detected, I could block the Done-Button.
Maybe I could even mark those Islands as red or something

**Comment by hhyyrylainen** [comment]
You can have a look at the existing microbe editor scene to see how the popups are made. They are basically the godot popup control that is made visible when needed.
Showing the disconnected parts in red would make it more obvious to immediately see that something's wrong.

**Comment by FuJa0815** [comment]
In my PR I just disabled the finishButton

**Comment by hhyyrylainen** [comment]
I think that is too vague, the player needs to be told what they have done wrong, otherwise it'll be too not obvious and frustrating to figure out what to do to fix it.

**Comment by FuJa0815** [comment]
Ok, I'll mark the islands red.
Just wait until I read myself into godot materials. Is there an existing "error" material?

**Comment by hhyyrylainen** [comment]
There isn't. I mean there is the material for invalid place for new hex, but I'd like a really explicit red for disconnected parts. As the material is an LFS file you can't commit it directly unless you join the thrive dev team to get credentials to commit git LFS files.
