### ISSUE TITLE
Investigate why compounds that have 0% concentration in a patch spawn

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1699]
https://community.revolutionarygamesstudio.com/t/0-5-2-feedback-thread/3081?u=hhyyrylainen

**Comment by hhyyrylainen** [comment]
And sometimes stuff that should, doesn't: https://community.revolutionarygamesstudio.com/t/0-5-2-feedback-thread/3081/4?u=hhyyrylainen

**Comment by Maxonovien** [comment]
Based on seen screenshot reports, it seems to always occur within multi-compound clouds as below

![image](https://user-images.githubusercontent.com/16361817/124603198-f6e3f900-de69-11eb-8449-03ef2fe56dd8.png)

It seems very likely that it is a dissolved (HS-related?) chunk, either coming from dead cells or random chunk spawn.

**Comment by hhyyrylainen** [comment]
That might be the reason why this happens. And probably something the players might not notice before reporting this.
I'll label this as review for this now requires further confirmation about if that is the case (then this can be closed).

**Comment by hhyyrylainen** [comment]
As this hasn't been reported for years, I'll consider this "fixed".
