### ISSUE TITLE
Make clouds look like they did in 0.3.4

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1701]
the clouds looked the best in 0.3.4 we should try to make them look like that again.
If someone has screenshots of 0.3.4 that would be useful.

**Comment by Kasterisk** [comment]
Here it is:
![screenshot](https://user-images.githubusercontent.com/54026083/95674354-dc7e3700-0bd9-11eb-8c24-6de6f1561b72.png)

**Comment by hhyyrylainen** [comment]
Sadly, what might have helped with this would have been the Ogre shader files that were used for this, they aren't in git (instead I think they were stored in svn, which is no longer up for looking at historical versions).

**Comment by hhyyrylainen** [comment]
At least the previous code for calculating the densities is in git: https://github.com/Revolutionary-Games/Thrive/blob/v0.3.4/src/microbe_stage/compound_cloud_system.cpp

I think though that with the old system due to the noise, some small compound clouds may have been entirely invisible, that would explain few reports about magically appearing compounds. So we should instead do something like: https://github.com/Revolutionary-Games/Thrive/issues/2286 so that completely invisible areas of clouds would be very small.

**Comment by Kasterisk** [comment]
Not very familiar with ogre shaders but I think they're also available in the 0.3.4 release build assets. Specifically in the materials folder containing `.material` files with some accompanied by a `.ps` and `.vs` file, which I assume to be the fragment and vertex shaders.

This is one for the compound clouds: [compoundClouds.zip](https://github.com/Revolutionary-Games/Thrive/files/6576470/compoundClouds.zip). Had a look inside the files and they seem pretty simple and short.

**Comment by hhyyrylainen** [comment]
Ah yes of course, good idea getting them from the release. So the interesting part is this calculation: 
```
    color = texture2D(cloudTexture, oUV0);

    color.a = color.a * texture2D(perlinNoise, oUV1 * 1.5f).x * 0.8f;
```
Of course that can't be used as is, as our texture plane size is different (so the perlin noise scaling won't work). And the actual layering on the shader passes was done with an Ogre specific blend type: `Ogre::SBT_TRANSPARENT_ALPHA`

**Comment by AverageNerdz** [comment]
Working on it ;)

**Comment by AverageNerdz** [comment]
https://github.com/Revolutionary-Games/Thrive/pull/5276
I think that the PR i linked fixed this issue, the compounds textures now look pretty much like the screenshot sent here which should result in a much better visual experience.

**Comment by hhyyrylainen** [comment]
I guess the look has been improved a bunch. So I'll close this, but I'd still like to see a few small tweaks done to the shader to see if they improve the visuals:

> At least when those screenshots are small I think the small detail is maybe too much (or there's like too much contrast)

> So the possible solutions to that are make the noise less dark or make the noise less fine 

https://discord.com/channels/464846402732687391/1267463983036633090/1267887510600814714

**Comment by AverageNerdz** [comment]
> I guess the look has been improved a bunch. So I'll close this, but I'd still like to see a few small tweaks done to the shader to see if they improve the visuals:
> 
> > At least when those screenshots are small I think the small detail is maybe too much (or there's like too much contrast)
> 
> > So the possible solutions to that are make the noise less dark or make the noise less fine
> 
> https://discord.com/channels/464846402732687391/1267463983036633090/1267887510600814714

Yeah i'll look into these asap, i think that both things are easily doable and it's nice to experiment which stuff will get the best results.
