### ISSUE TITLE
Editor font problem with specific locales when value over 1000

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1702]
Looks like this:
![2020-10-10_23 13 12 5264](https://user-images.githubusercontent.com/3796411/95673444-33234b00-0bb1-11eb-8e75-bf7f768aa0c5.png)

Some character missing in a font, I'm guessing it is some kind of space character as in Finnish numbers are formatted like this: 1 000.

**Comment by Kasterisk** [comment]
I think this is no longer the case with the new version of Jura font.

**Comment by hhyyrylainen** [comment]
Can confirm that this is now fixed.
