### ISSUE TITLE
Multiple tooltips can be on at once

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1703]
Another issue found in the last stream, I somehow got multiple tooltips to happen at once:
![2020-10-10_23 24 53 5928](https://user-images.githubusercontent.com/3796411/95673462-5a7a1800-0bb1-11eb-8916-c4b1332f66ed.png)
![2020-10-10_23 25 26 0792](https://user-images.githubusercontent.com/3796411/95673467-64038000-0bb1-11eb-9a62-4ccf1bdd690a.png)
![2020-10-10_23 25 36 9609](https://user-images.githubusercontent.com/3796411/95673468-682f9d80-0bb1-11eb-85e3-73d2621aa420.png)

**Comment by Kasterisk** [comment]
Related to #1693 (this might also get fixed if that issue is fixed)
