### ISSUE TITLE
Win and extinction screens are shown not centered

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1705]
They should be centered instead of in the top right
![2020-10-10_23 41 43 0620](https://user-images.githubusercontent.com/3796411/95673504-aaf17580-0bb1-11eb-88e1-a4f871b13e16.png)

![2020-10-10_23 43 16 1009](https://user-images.githubusercontent.com/3796411/95673507-ad53cf80-0bb1-11eb-819c-9f9b0336c4d4.png)

**Comment by Kasterisk** [comment]
I think simply setting a correct size flag for them will fix this

**Comment by hhyyrylainen** [comment]
Should have been fixed by https://github.com/Revolutionary-Games/Thrive/pull/1879
