### ISSUE TITLE
Binding agents

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1712]
- [x] binding agents placeable (should be locked behind the nucleus)
- [x] cell can enter binding mode
- [x] binding to other cells works
- [x] binding adds some benefit
- [x] unbinding possible
- [x] bound cells dying works right
- [x] saving doesn't explode related to binding

Optional: #1711

**Comment by helloguy3953** [comment]
I'll try modding in the first step if i can.

**Comment by helloguy3953** [comment]
Nevermind, too hard.

**Comment by Fatheadgaming** [comment]
Wait binding agents so baisically working on the foundation of the multicellular stage, thx i cant wait for it to be out.
