### ISSUE TITLE
Percentage of atmospheric gasses do not add up

### ISSUE THREAD

**Issue by helloguy3953** [Revolutionary-Games/Thrive#1713]
On the patch screen, percentage of atmospheric gasses do not add up. It should be 70% nitrogen instead of 78%.
![img](https://cdn.discordapp.com/attachments/228300288023461893/764820264009465856/Screen_Shot_2020-10-11_at_10.39.02.png)

**Comment by hhyyrylainen** [comment]
Fixed the image link.
