### ISSUE TITLE
Add cilia

### ISSUE THREAD

**Issue by Moopli** [Revolutionary-Games/Thrive#174]
Another movement organelle, but fundamentally different as they apply tangential force and torque.

**Comment by tjblazer85** [comment]
Don't we already have a Cilia Model? https://github.com/Revolutionary-Games/Thrive/issues/125
If the guy never sent in the model and we need a new one, I could make a model for it or if Rabiesguineapig already started on his, I have the concept art for it

**Comment by hhyyrylainen** [comment]
This probably still needs the model and then needs to be implemented.

**Comment by Untrustedlife** [comment]
Kinda wish we could get this in 0.4.0

**Comment by Untrustedlife** [comment]
but its probabbly not going to happen
