### ISSUE TITLE
Make pre-commit hook format check script work on Windows

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1742]
right now it likely doesn't work
It might be easiest to move to using a proper pre-commit definition (as with translations people will need python anyway so that isn't much extra installing needed), as long as it can call a ruby script.

once done the instructions should be updated: https://github.com/Revolutionary-Games/Thrive/blob/master/doc/setup_instructions.md#pre-commit-hook

**Comment by Demetriex** [comment]
hello can i work on this?

**Comment by hhyyrylainen** [comment]
Yes you can, I'm not aware of anyone currently working on this.

**Comment by Demetriex** [comment]
I just tested the this on window and it would seem to works fine with just extra setup.

- the update_localization script uses `msgmerge` and `msginit`, windows users can just install [this binaries](https://mlocati.github.io/articles/gettext-iconv-windows.html) can be installed. I suggest that we use`pybabel update` and `pybabel init` instead

- the hook doesn't work if it's not something like this `system 'ruby ./check_formatting.rb'`

https://github.com/Revolutionary-Games/Thrive/blob/0fae647caf627a37357879723d05bb11e7f743a6/scripts/hooks/precommit_hook.rb#L11


> It might be easiest to move to using a proper pre-commit definition

I just made a pre commit definition using https://pre-commit.com/
https://github.com/Demetriex/Thrive/blob/1742_pre_commit_hook/.pre-commit-config.yaml

**Comment by hhyyrylainen** [comment]
That looks pretty good. If you want to make a PR you should also update setup instructions regarding how the hook is to be installed.
