### ISSUE TITLE
Change the format check hook to use output capture

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1743]
instead of relying `>` being a valid redirect to file in the user's shell in the `system` command

**Comment by Paulpicotin** [comment]
may I be assign to this issue ?

**Comment by hhyyrylainen** [comment]
There you go

**Comment by Paulpicotin** [comment]
hello I don't understand what you want to say by this sentence "instead of relying > being a valid redirect to file in the user's shell in the system command" can you explain? if you want to  explain with another way than github this is my discord:
 la surprise#1620

**Comment by hhyyrylainen** [comment]
This line:
https://github.com/Revolutionary-Games/Thrive/blob/15b9337e18f325ff41954b8e24e9d1a00cd6dc7d/scripts/hooks/precommit_hook.rb#L9

relies on the system shell interpreting `>` as being redirection to a file. It would be nice if the script worked on systems that don't have a shell that does that.
Instead the ruby system syntax with backtics, that captures the output to ruby (https://stackoverflow.com/a/1563625/4371508), should be used. That way the script can then manually write to `files_to_check.txt`

**Comment by Paulpicotin** [comment]
so if I understand well the line :

 system 'git diff --cached --name-only > files_to_check.txt' 

become a thing like that : 

output = `ls #{'files_to_check.txt'}`

printf output

**Comment by hhyyrylainen** [comment]
Not exactly that, but this is the right kind of syntax:
```ruby
output = `shell command goes here`
```

**Comment by Paulpicotin** [comment]
ok  so it most become this so no? 

output = system 'git diff --cached --name-only ' 

printf output `ls #{'files_to_check.txt'}`

**Comment by hhyyrylainen** [comment]
```
printf output ls #{'files_to_check.txt'}
```
that part is wrong. The `output` variable contents needs to be written to a file called `files_to_check.txt`

**Comment by Paulpicotin** [comment]
so instead of printf a File.write  is ok?

**Comment by hhyyrylainen** [comment]
Yes, because that is what the `>` redirect in a shell does.
If the hook just prints out the file list, it will do absolutely nothing useful, it needs to be written in that file for the list of files to check to actually do something.

**Comment by Paulpicotin** [comment]
ok  so I think it's good now

**Comment by Paulpicotin** [comment]
output = system 'git diff --cached --name-only ' 

File.write output
