### ISSUE TITLE
Make GetIslandHexes non-recursive

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1747]
To avoid any possible problems with recursion depth limits

**Comment by FuJa0815** [comment]
Just to clarify:
GetIslandHexes itself is not recursive but the called method CheckmarkNeighbors is

**Comment by hhyyrylainen** [comment]
That's still not good, then. All of the stuff that GetIslandHexes calls should be made non-recursive for this to be closed.
