### ISSUE TITLE
Environmental toxins should expire

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1758]
to prevent them building up if the player is stationary.
I think 2.5 minutes for them to dissolve would be quite good.

**Comment by zackdrake** [comment]
Hi, Can i please get assigned to this issue ? Thanks in advance

**Comment by hhyyrylainen** [comment]
Sure

**Comment by fgdfgfthgr-fox** [comment]
I am terrible at codes and I couldn't find any code responsible for the timed despawn of the toxin clouds. However, I opened the game and wait, after a few minutes a toxic cloud indeed disappeared. So I guess this issue had been fixed by somebody somehow (probably zackdrake).

**Comment by hhyyrylainen** [comment]
Can someone confirm (@Revolutionary-Games/testing ?). It shouldn't be possible. The environmental toxin clouds are controlled by FloatingChunk.cs, which only has dissolve when something runs out of compounds. So it shouldn't be possible for it to disappear after some time.
