### ISSUE TITLE
Cannot enter editor after loading

### ISSUE THREAD

**Issue by FuJa0815** [Revolutionary-Games/Thrive#1761]
When saving and loading the editor button is blue, like it should be, but it can't be clicked

**To Reproduce**
1. Fill up both bars
2. Quicksave
3. Quickload

**Expected behavior**
The button should be pressable

**Screenshots**
![grafik](https://user-images.githubusercontent.com/30809803/97113470-e41a0180-16ea-11eb-9a2b-423952d24c6b.png)

**Comment by hhyyrylainen** [comment]
duplicate of: https://github.com/Revolutionary-Games/Thrive/issues/1351 (see my follow up comment there where I noticed that you can't click the editor button)

**Comment by FuJa0815** [comment]
Didn't see the comment, sorry
