### ISSUE TITLE
Tiling Textures Needed for Cell Membranes

### ISSUE THREAD

**Issue by Nunez2196** [Revolutionary-Games/Thrive#1770]
Textures are needed for the 3D Membranes of cells.

**Requirements**

- High Resolution (2048 x 2048) and square. (They will be compressed as needed by me)

- Opaque/no transparency (I will handle the Alpha channel)

- **MUST** tile perfectly, no seams

- provide grayscale images so they may be colorized easily. 

- provide Normal Maps as well.

**Reference Material**
![cell1](https://user-images.githubusercontent.com/70069814/97217756-1fc1d380-179e-11eb-985d-f3c49a196b0b.jpg)
![cell2](https://user-images.githubusercontent.com/70069814/97217780-27817800-179e-11eb-923f-257443a81282.jpg)
![membrane](https://user-images.githubusercontent.com/70069814/97217784-294b3b80-179e-11eb-860e-313aaa95aba7.jpg)

**Comment by hhyyrylainen** [comment]
There are currently multiple different textures? Won't all of them need to have new variants for the 3D membrane?

**Comment by Nunez2196** [comment]
Textures need to be ready to tile and be edited for use in a material. Current ones are useless for a material.

**Comment by hhyyrylainen** [comment]
Yes, I know that, I just want to confirm to make it sure that any artists looking at this will be aware that there needs to be 6 (?) different textures made.

**Comment by Nunez2196** [comment]
Yes, my apologies, I should have put that down. However I would really like to just get some basic stuff to work with for now. I need something for the cells

**Comment by Nunez2196** [comment]
All necessary textures are done, closing this.
