### ISSUE TITLE
Population Discrepancy Issue: 'Patch Map' shows a Population that Does Not Match 'Report' Screen - Increments by 10 Every Reproduction

### ISSUE THREAD

**Issue by Aquasheep3000** [Revolutionary-Games/Thrive#1789]
MASSIVE EDIT: I have explained the issue in detail and consolidated to what is likely a single issue.

1) In the Patch Map Screen, the population is shown to be '650' whereas in the 'Report' Screen, the population is shown to be '50'. This occurred after the first reproduction in a new biome and after subsequent reproductions (still showing '50'). It was consistent across a couple of biomes. This is as of 0.5.2.0 rc-1. Furthermore, this '650' number appears to be 10 * n where 'n' is the number of total reproductions across all biomes.

The inaccurate population count in the 'Patch Map' screen for the Pangonian Epipelagic biome (another newly-inhabited biome had the same exact behavior; this occurred after winning the game).
![10 15 20 - Thrive 0 5 2 - Inaccurate Population on 1st Reproduction New Biome](https://user-images.githubusercontent.com/44108929/97805653-1e206180-1c1d-11eb-907c-fb64e339cc63.png)

The stuck population count in the 'Report' Screen.
![10 15 20 - Thrive 0 5 2 - Inaccurate Population on 1st Reproduction New Biome 2](https://user-images.githubusercontent.com/44108929/97805806-e960da00-1c1d-11eb-9725-fb73e67252f2.png)

**Comment by hhyyrylainen** [comment]
But isn't this exactly how it should work? When you as the player move to a new patch, your population there is 0, then when you reproduce your population increases in your current patch? And that is correctly shown: population is now something when previously it was 0.

**Comment by Aquasheep3000** [comment]
@hhyyrylainen You are right. On second thought, I have begun to edit the issue, posting shortly.

**Comment by hhyyrylainen** [comment]
Does this happen with other species as well?
I'm guessing that this might be a player species specific issue.
If you can provide a save file or exact steps that make the issue happen each time, that would greatly help whoever picks up working on this issue.

**Comment by Aquasheep3000** [comment]
Here is a save file indicating the issue in the Pangonian Coast Biome. The population says 50, but that shouldn't be accurate after evolving; there should be a higher population with the previous 50. It appears it's stuck at 50 with a previous population of 0 and then the 'Report' Screen population is only incrementing by the rule of 10 * the total number of reproductions in all biomes.
[Patch Map Report Population Discrepancy.zip](https://github.com/Revolutionary-Games/Thrive/files/5471161/Patch.Map.Report.Population.Discrepancy.zip)

**Comment by hhyyrylainen** [comment]
#2623 is now merged so looking into this again should be done.

**Comment by hhyyrylainen** [comment]
This is probably fixed now or will be in the next release (0.5.10).
