### ISSUE TITLE
Slow GetIslandHexes

### ISSUE THREAD

**Issue by FuJa0815** [Revolutionary-Games/Thrive#1794]
When creating massive Species like this:
![2020-11-02 18-10-06](https://user-images.githubusercontent.com/30809803/97897941-7ba8d100-1d37-11eb-8bdf-e334774511c1.gif)
Modifying the species is very slow
Using the debugger I pinned it down to the GetIslandHexes method.
Possible fixes:
- call the method only once after modification when using symetry mode (this would sixth the performance hug seen in the gif)
- make island detection parallel

This also affects #1754 after merge

**Comment by hhyyrylainen** [comment]
It seems like GetOrganelleAt is a hot method.
Might be worth to cache all the existing hex locations and use that instead in the island check method.

![Kuvakaappaus - 2020-11-02 20-07-15](https://user-images.githubusercontent.com/3796411/97903026-1a88f980-1d47-11eb-9cfa-eec6d13425b4.png)

**Comment by hhyyrylainen** [comment]
I'm going to see if my idea works to improve the performance.
