### ISSUE TITLE
Make the GUI keyboard navigable

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1799]
The entire GUI should be usable from the keyboard, i.e. the entire game (except the microbe editor placing) should be playable with just the keyboard. This'll make future controller support easier to make (hopefully, if Godot is made sensibly so that the same approach as keyboard Control navigation also works for controllers)

**Comment by hhyyrylainen** [comment]
Our custom GUI controls, like this: https://github.com/Revolutionary-Games/Thrive/pull/2615 will also need to be updated to be keyboard navigable.

**Comment by skyace65** [comment]
I've just added a page to the Godot documentation on how to do this: https://docs.godotengine.org/en/3.4/tutorials/gui/gui_navigation.html

**Comment by hhyyrylainen** [comment]
I'll close this as controller navigation is now mostly in the main menu. There's separate issues for everything still missing like the editors: https://github.com/Revolutionary-Games/Thrive/issues/4003
