### ISSUE TITLE
Update contributing guidelines

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1802]
Some stuff to put in the contributing guidelines:

- [ ] Update existing pull requests. Don't close one and open a new one. You can add new commits to an existing PR, you can even force push to replace all the commits in an open PR.
- [ ] requirements vague often in issues, sorry for a lot of iteration to contributing instructions
- [ ] when opening a PR use the Github closing words to mark which issues it solves

**Comment by Straywind** [comment]
Could you be more clear for point number 2?

**Comment by hhyyrylainen** [comment]
> Could you be more clear for point number 2?

hmmm.

I want to have a note in the contribution guidelines that issues are often created very quickly without much thought put in their descriptions to make sure that they are understandable later. In some issues where someone asks for extra information, I've already forgotten the context and can't really accurately answer.
So there should be a note in contribution guidelines saying "sorry, issues are often very vague on the details what needs to be done" and also encourage people to post comments to ask about the issues.
