### ISSUE TITLE
Unable to load solution with Visual Studio Community Edition for MacBook

### ISSUE THREAD

**Issue by DTanxxx** [Revolutionary-Games/Thrive#1805]
**Description**
I am currently using Visual Studio 8.7.9 on a MacBook Air, and Visual Studio seems unable to open Thrive.csproj (nor Thrive.sln). An error message is shown when I try to load the project: "Load failed: Unknown solution item type: {8F3E2DF0-C35C-4265-82FC-BEA011F4A7ED}". I have tried deleting and recloning Thrive to local but it did not work.

**To Reproduce**
1. On a Mac, go to Visual Studio
2. Open either Thrive.csproj or Thrive.sln
3. Project icon shown on left panel shows a pale grey colour, with a cross next to it

**Expected behavior**
Visual Studio should be able to open the project and load all the files, showing folder icons on the left panel. It was able to open Thrive about one month ago.

**Screenshots**
<img width="768" alt="Screen Shot 2020-11-10 at 9 32 02 AM" src="https://user-images.githubusercontent.com/55208219/98593169-a4345a80-2337-11eb-9616-7899d67bc79e.png">

**System info**
- OS: macOS Catalina, Version 10.15.7
- Graphics card: Intel UHD Graphics 617 1536 MB
- Thrive version: I am not sure where to find the exact version but I was using the Debug edition of Thrive

**Comment by hhyyrylainen** [comment]
You can use `git log -n 1` to see what commit you have checked out.

Googling that error got me two interesting links:
https://github.com/godotengine/godot/issues/41936
https://developercommunity.visualstudio.com/content/problem/1026974/unknown-solution-item-type-when-project-has-toolsv.html

Both of which seem to indicate that visual studio for mac might not support new enough project format that thrive uses.
You might be able to edit the toolset and C# version specified in Thrive.csproj to get the project to load.

**Comment by DTanxxx** [comment]
Thanks! The issue is solved and I can now open the project with Visual Studio on Mac.

**Comment by DTanxxx** [comment]
> Thanks! The issue is solved and I can now open the project with Visual Studio on Mac.

Never mind, the project once again was unable to be opened after I checked out a branch. I will try other ways to fix it.

**Comment by DTanxxx** [comment]
I restarted Visual Studio and now it works. Seemed like the Godot support extension was automatically removed for some reason. I re-downloaded it and everything works!
