### ISSUE TITLE
Change everywhere Lux to lx

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1811]
change everywhere in the game to use lx for lux as that's the unit suffix. Makes translations nicer and more consistent.

**Comment by Sourciluss667** [comment]
Hello hello ! I can do this :)

**Comment by Sourciluss667** [comment]
Oh it's already fix

**Comment by hhyyrylainen** [comment]
Can someone else verify? This can be closed once it is verified that this is not an issue.

**Comment by Kasterisk** [comment]
I can't find other places that also uses lux on the sunlight level, they only use % as far as I can tell. This is probably safe to close I think
