### ISSUE TITLE
En Dash and Hyphen combined in en.po MICROBE_STAGE_HELP_MESSAGE_8

### ISSUE THREAD

**Issue by FuJa0815** [Revolutionary-Games/Thrive#1819]
```
The various compound clouds are:

White – Glucose
Yellow – Hydrogen Sulfide
Orange - Ammonia
Purple - Phosphate
Rust Brown - Iron

Glucose makes ATP
```

As you can see, En Dashes (–) and Hyphens (-) are getting mixed up

**Comment by hhyyrylainen** [comment]
It should be now possible to fix this on the translations site: https://translate.revolutionarygamesstudio.com/
I haven't set up yet that syncing over to github, so before I get that done I'll do manual syncing if needed but I plan to get the syncing to work within a week.

**Comment by hhyyrylainen** [comment]
I'll keep this open *until* the translation is merged back in.

**Comment by FuJa0815** [comment]
I fixed this in the translation system.

**Comment by hhyyrylainen** [comment]
I did notice that, I was initially confused whether this was fixed or not. But as I said, I'll wait until we get that merged to master. I'll probably try tomorrow one approach for getting the translations from weblate to github.

**Comment by hhyyrylainen** [comment]
It's merged to master now.
