### ISSUE TITLE
Colorize the mutation points bar labels

### ISSUE THREAD

**Issue by Kasterisk** [Revolutionary-Games/Thrive#1821]
They are currently colored white and a bit hard to read against the full mutation points bar. In the concepts the texts are supposed to look like this:
![9961f0310c40b3a504e8ef8f4170ca7854aa7f5c](https://user-images.githubusercontent.com/54026083/99147698-95da9b80-26b5-11eb-8f62-00ed2b381288.jpeg)
This is a bit difficult because that color made them almost invisible against the bar background when the it's empty (the bar has black bg ingame). I think it would be nice if the labels could automatically adjust their colors according to the current background they are on if that's possible in godot (maybe with shaders?).

**Comment by FuJa0815** [comment]
![grafik](https://user-images.githubusercontent.com/30809803/99266151-c1c75f80-2822-11eb-9669-292357ab0970.png)
does this look good?

**Comment by Kasterisk** [comment]
That's quite nice! for the left side label I thikn the color is a bit off, it should be #112b36, also the label above black bar could be made a _little_ bit lighter

**Comment by FuJa0815** [comment]
Are you sure, about ![#f03c15](https://via.placeholder.com/15/112b36/000000?text=+) `#112b36`? It doen't look blue in the screenshot, unless it's some visual illusion.
The colors are just copied from the MPBar, so It draws dark pink if the background is light pink and draws light pink if the background isn't.

**Comment by Kasterisk** [comment]
It's the color used in the concept, svg file for reference: [editorsvg.zip](https://github.com/Revolutionary-Games/Thrive/files/5551540/editorsvg.zip).

**Comment by FuJa0815** [comment]
Oh wow, that was some optical illusion, because it really didn't look blue in the screenshot, I thought that was just the dark pink!
I can split up the variable, but to be honest: I like the dark pink text on light pink and light pink text on dark pink better than a seperate blue, don't you agree?

**Comment by Kasterisk** [comment]
Yes, I don't mean for there to be a separate blue and pink color to use for the texts, instead the dark pink text color could be changed with a dark blue (`#112b36`) and the light pink text with a light blue also (`#a1dbf3`), sorry if I wasn't clear. I think the texts will be more easier to see with them (especially the light one on a dark background).

**Comment by FuJa0815** [comment]
![grafik](https://user-images.githubusercontent.com/30809803/99433232-8d7c9d80-290d-11eb-9dff-2716be678aba.png)
@Kasterisk does this look good?

**Comment by Kasterisk** [comment]
Yeah, that looks better.
