### ISSUE TITLE
Make the options menu adjust to content size

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1829]
It's a bit too small for the Finnish translation:
![2020-11-15_11 47 59 6869](https://user-images.githubusercontent.com/3796411/99181648-7d5f9500-2738-11eb-999d-034348172e29.png)

Another translation / screenshot showing the problem:
![img](https://cdn.discordapp.com/attachments/228300288023461893/797446583280467979/unknown.png)

**Comment by zackdrake** [comment]
Hi,

Can i be assign to this issue ? Thanks in advance

**Comment by zackdrake** [comment]
I think it got fixed without my modifications since this bug no longer appear in master, unless i'm mistaken

**Comment by Kasterisk** [comment]
The issue most likely still exist, it's probably just hidden due to the options menu being much wider.

**Comment by zackdrake** [comment]
Okay, i'll continue working on this then, thanks

**Comment by hhyyrylainen** [comment]
To easily test this, you could add a bunch of random letters in some of the english strings in en.po to make the options menu too wide again.
