### ISSUE TITLE
Make language list show the native names for the languages

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1833]
So instead of just the language code, there would be the language name after it (this can probably be fetched from C#, with caching), so `fi` would be `fi (Suomi)` after this.
Because this list looks pretty confusing:
![2020-11-15_17 35 01 2956](https://user-images.githubusercontent.com/3796411/99189384-9d5b7c80-2769-11eb-8f4a-2c3525e5868b.png)

**Comment by zackdrake** [comment]
Hi, Can i please get assigned to this issue ? Thanks in advance

**Comment by hhyyrylainen** [comment]
Yes you can.
