### ISSUE TITLE
Organelle tooltip not translatable

### ISSUE THREAD

**Issue by FuJa0815** [Revolutionary-Games/Thrive#1834]
I have translated the organelle descriptions, but the tooltip is still english, except for the reaction name (yellow)
![grafik](https://user-images.githubusercontent.com/30809803/99190136-20c69f00-2765-11eb-9339-682ea64084e1.png)

**Comment by hhyyrylainen** [comment]
@Kasterisk you probably know how the tooltip is structured internally (and what parts maybe need adjusting to be translated)?

**Comment by FuJa0815** [comment]
Note: same thing happens with the membrane types

**Comment by hhyyrylainen** [comment]
At least some parts of the tooltips are translateable, as shown here:
![2020-11-15_18 15 34 1827](https://user-images.githubusercontent.com/3796411/99190329-9edb7380-276e-11eb-91c3-f918511080fc.png)

**Comment by Kasterisk** [comment]
Tested locally and the tooltips translation seem to work well (including the membrane types), not sure why it doesn't work in your case. Have you pulled the latest changes from master branch?
![2020-11-15_23 32 07 4135](https://user-images.githubusercontent.com/54026083/99190805-335bcb00-279b-11eb-88a4-7e8c27a7305c.png)

**Comment by hhyyrylainen** [comment]
At least that "/second" part might be hard coded in C#. Maybe?

**Comment by Kasterisk** [comment]
> At least that "/second" part might be hard coded in C#. Maybe?

The `/second` text is hard coded on the SelectionMenuTooltip.cs script, specifically `WriteOrganelleProcessList()`

**Comment by Kasterisk** [comment]
Actually this may be related to #1815. @FuJa0815 it could be that you changed the language from german to english while in the cell editor, resulting in the tooltips descriptions text and title being reset while the processes name are not.

Also I noticed that the auto evo run result texts doesn't also react to the locale change, seems like gui elements that were created runtime needs some special handlings?

**Comment by hhyyrylainen** [comment]
The auto-evo results is a bit of a pain, because the information from which it is created, is destroyed when the results are applied. So without major rewrite, it's not possible to regenerate that text when changing the language.

**Comment by FuJa0815** [comment]
Update:
When I change the language setting it works, when I save the setting and relaunch the game the tooltip is in english.
When I change the language to english and back to german, the tooltips are german

**Comment by Kasterisk** [comment]
That seem to be the case, the tooltip texts could be translated fine but the language setting is not applied to them for some reason on startup, I'm guessing it's because the tooltips are autoloaded. hhyyrylainen might know more about this.

**Comment by hhyyrylainen** [comment]
That might be it. The load order is like this:
- StartupActions
- Other autoloads
- PostStartupActions

PostStartupActions is where the Settings is loaded and the language is applied. As you can see it happens after the auto loads.


I did some stuff in the settings graphics apply as it kept crashing (even after putting it in PostStartupActions), so moving settings load to StartupActions, might just work now. In the worst case it needs a bit of tweaking.

https://github.com/Revolutionary-Games/Thrive/issues/1840
