### ISSUE TITLE
Duplicated Translation Messages

### ISSUE THREAD

**Issue by RacerBG** [Revolutionary-Games/Thrive#1838]
**Describe the bug**
So far I found that **EASTEREGG_MESSAGE_22** and **EASTEREGG_MESSAGE_26** are identical to their counterparts: **EASTEREGG_MESSAGE_3** and **EASTEREGG_MESSAGE_24**.

PS: I'm saying 'so far' because I'm still at the beginning of my Bulgarian translation adventure. :) 

**To Reproduce**
Look at the '.po' file.

**Expected behavior**
Every duplicate should be removed.

Regards,
Georgi

**Comment by RacerBG** [comment]
Sorry, I just saw that @hhyyrylainen has made 2 issues about that...

**Comment by hhyyrylainen** [comment]
Those issues for reference: https://github.com/Revolutionary-Games/Thrive/issues/1824
https://github.com/Revolutionary-Games/Thrive/issues/1830
