### ISSUE TITLE
Fix text overflowing on the tutorial popups

### ISSUE THREAD

**Issue by Kasterisk** [Revolutionary-Games/Thrive#1844]
A bit tricky because the tutorial's window dialogs doesn't automatically expand with the text, need to find some way to work around it.
![2020-11-16_23 04 56 2617](https://user-images.githubusercontent.com/54026083/99280187-a3ce1f00-2863-11eb-8ae1-b9791d86e04c.png)

**Comment by hhyyrylainen** [comment]
Yeah, I had some trouble trying to get them to be sensible sizes to begin with. Basically I had to hardcode a minimum size for them that they look to obey, but I did not get the sizing based on content to work.
I'll add some more tags on this...
