### ISSUE TITLE
Rename appearance tab to membrane tab

### ISSUE THREAD

**Issue by Kasterisk** [Revolutionary-Games/Thrive#1869]
It was originally called membrane tab before the editor UI rework (and releases prior to 0.5.2), but I somehow renamed it to appearance. Membrane was actually agreed upon as the tab's name, see https://github.com/Revolutionary-Games/Thrive/pull/927#discussion_r365542717.

**Comment by hhyyrylainen** [comment]
I accept this issue after re-reading that PR comment.
