### ISSUE TITLE
Move the custom theme from MicrobeEditor.tscn

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1873]
it should be incorporated into the main thrive_theme.tres

**Comment by hhyyrylainen** [comment]
Related to: https://github.com/Revolutionary-Games/Thrive/issues/1512 ?

**Comment by Kasterisk** [comment]
I'm not quite sure which custom theme the title is referring to, I'm assuming the one in the membrane color picker which in that case have now been solved.

**Comment by hhyyrylainen** [comment]
I guess, this is fine to close, then.
