### ISSUE TITLE
Changing language while in the editor doesn't change stage language

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1885]
It's probably caused by the microbe stage scene tree being detached and being outside the main Godot tree, so it doesn't receive whatever event changing language causes.

If at all possible a nice fix would be to manually trigger the "on language changed" (whatever it is actually named) signal on the microbe stage scene tree when exiting the editor.

**Comment by Sourciluss667** [comment]
Hello hello ! I want to try fix this :)

**Comment by hhyyrylainen** [comment]
Sure, you can give it a go.
