### ISSUE TITLE
Option text and pause screen text doesn't change on language change

### ISSUE THREAD

**Issue by Dragonmemo** [Revolutionary-Games/Thrive#1886]
Changing the game language doesn't change text in option screens or pause menu.

**Comment by hhyyrylainen** [comment]
Could you post the steps required to see this happen, along with a screenshot or two?
I'm kinda thinking this might be a duplicate, but I'll wait for the repro steps before deciding that.

**Comment by Dragonmemo** [comment]
ok, my bad, it only happened on the first launch of the game with the BOTD i guess?
