### ISSUE TITLE
Make TweakedColourPicker.tscn to contain the theming for colour picker

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1891]
Make a TweakedColourPicker scene with C# signal proxy to make it more extensible for us to place more colour pickers in the GUI. 

I think it should be possible to make a TweakedColourPicker.tscn file that just has a colour picker in it and a theme, though I suppose for passing through signals it might need a short C# script file to do that. 

https://github.com/Revolutionary-Games/Thrive/pull/1879#discussion_r536631785

**Comment by Kasterisk** [comment]
Actually now that I'm about to implement this, I don't think it's necessary to make the signals pass through a C# script as the color picker itself would be the sole root node and the theme would be embedded inside it.

**Comment by hhyyrylainen** [comment]
Yeah, that probably simplifies implementing this quite a bit.
