### ISSUE TITLE
Untranslatable strings

### ISSUE THREAD

**Issue by fgdfgfthgr-fox** [Revolutionary-Games/Thrive#1894]
![QQ截图20201207113843](https://user-images.githubusercontent.com/60460773/101296423-57856600-3888-11eb-8c7b-24d392bed13e.png)
![QQ截图20201207114011](https://user-images.githubusercontent.com/60460773/101296424-58b69300-3888-11eb-9e04-3b06512533f8.png)
![QQ截图20201207115315](https://user-images.githubusercontent.com/60460773/101296425-594f2980-3888-11eb-9387-7ef868d8e954.png)
![QQ截图20201207122120](https://user-images.githubusercontent.com/60460773/101296427-59e7c000-3888-11eb-96a2-34c889800c1c.png)
Chinese Translation on https://translate.revolutionarygamesstudio.com/ has been finished but there are still some strings remains untranslatable.

**Comment by hhyyrylainen** [comment]
First two are duplicate reports for
- https://github.com/Revolutionary-Games/Thrive/issues/1870
- and https://github.com/Revolutionary-Games/Thrive/issues/1833

Went extinct is a problem in:
- https://github.com/Revolutionary-Games/Thrive/blob/4db2aa2c119db9bde4c03c67dc6256ccdb997a9b/src/auto-evo/RunResults.cs#L225
- https://github.com/Revolutionary-Games/Thrive/blob/4db2aa2c119db9bde4c03c67dc6256ccdb997a9b/src/auto-evo/RunResults.cs#L371

external effects for reproduced and death are in:
- https://github.com/Revolutionary-Games/Thrive/blob/4db2aa2c119db9bde4c03c67dc6256ccdb997a9b/src/microbe_stage/Microbe.cs#L786
- https://github.com/Revolutionary-Games/Thrive/blob/4db2aa2c119db9bde4c03c67dc6256ccdb997a9b/src/microbe_stage/Microbe.cs#L1471

**Comment by zackdrake** [comment]
Can I be assign to this ? I already modified Microbe.cs, RunResults.cs and the pot file to make the untranslatable lines translatable so i think i just need to regenerate the po files using Weblate to add the new translatable line if i understand correctly

**Comment by Kasterisk** [comment]
You need run the `update_localization.rb` script to automatically regenerate the po/pot files  (it extract the translation keys you added in the code). After that you can just use Poedit or any text editor to edit the english string. See [working_with_translations.md](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/working_with_translations.md).

**Comment by hhyyrylainen** [comment]
@zackdrake are you still working on this?

**Comment by zackdrake** [comment]
Yes I am, I'll try to finish this before the end of next week if this is okay
