### ISSUE TITLE
Improve and extend microbe AI

### ISSUE THREAD

**Issue by jjonj** [Revolutionary-Games/Thrive#190]
Features that the new AI should be able to handle:
- Different modes (predatory, plantlike, prey-like possibly)
- Surviving, seeking out necessary compounds and feeding on them
- Killing other microbes (predator mode), this involves using agent vacuoles effectively
- Fleeing from predators (prey-like mode, and possibly predators from larger predators)

More ideas are welcomed

**Comment by Untrustedlife** [comment]
Ai has been improved and extended.
