### ISSUE TITLE
Add button in main menu to open github

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1911]
add a button in the main menu to browse the source code on github because as people still don't know (link to the main github repo)

**Comment by SudhanshuBlaze** [comment]
Hi! I'm a first-timer, I would like to work on this. But I don't know C# language. I know html, css , javascript.

**Comment by hhyyrylainen** [comment]
Sure you can work on this.
You'll want to learn enough about Godot and C# to create a new button and hook up a callback for it.
Looks like the same method as opening the saves folder can be used to open URLs (https://docs.godotengine.org/en/3.2/classes/class_os.html#class-os-method-shell-open)

In case you haven't looked at this yet, you should: https://github.com/Revolutionary-Games/Thrive/blob/master/doc/setup_instructions.md

**Comment by SudhanshuBlaze** [comment]
I'm sorry. I think this issue is Bit too difficult for me. I've no idea
what you're talking about.

**Comment by hhyyrylainen** [comment]
?? then look through the other issues tagged easy or good first issue to try to find something more suitable. 

We are using Godot engine and C# for the game, you can't really work on the main game itself if you don't know those at least on a basic level. Of course there's also the launcher: https://github.com/Revolutionary-Games/Thrive-Launcher that is an Electron app.

**Comment by SudhanshuBlaze** [comment]
Thanks, I'll check it out.

**Comment by hhyyrylainen** [comment]
There is now a PR implementing this: https://github.com/Revolutionary-Games/Thrive/pull/1914
