### ISSUE TITLE
Make organelles able to turn off and change game pause behavior.

### ISSUE THREAD

**Issue by jjonj** [Revolutionary-Games/Thrive#192]
Basically we want to follow this from the GDD: 
"Pressing the pause key (defaults to Space) will pause the game and zoom in on the player's microbe, showing all organelles in detail. Left-clicking an organelle while paused will toggle it on or off." https://docs.google.com/document/d/1_n3SrO5DDWvQuEbL4lFAamRjQEa0nCwd9Sc--MbjrMI/edit

**Comment by Alex-the-666** [comment]
along with what NicktheNick said, since the spacebar is the largest key its more common that players will accidentally click it and it will be a hindrance. perhaps 'Z' for zoom would be a good key.

**Comment by hhyyrylainen** [comment]
@NickTheNick is this still the plan?

**Comment by NickTheNick** [comment]
Yeah I think it should still apply.

**Comment by hhyyrylainen** [comment]
Another idea that's come up later is that the button to pause organelles could be in the process panel: https://github.com/Revolutionary-Games/Thrive/issues/1991

**Comment by hhyyrylainen** [comment]
I'll close this issue now in favour of having this control be in the process panel: https://github.com/Revolutionary-Games/Thrive/issues/1991
