### ISSUE TITLE
Build server

### ISSUE THREAD

**Issue by Moopli** [Revolutionary-Games/Thrive#195]
Since the Jenkins server stopped working, we don't have any continuous builds. Rather than find @Nimbal and get the server running again, I've been thinking for a while to set up [Travis-CI](https://travis-ci.org/). Free, integrates with GitHub, easy to set up, the only reason we don't have Travis set up already is 'cuz I don't have the permissions required to flip the switch and turn Travis on. The owner needs to flip the switch, so we only need someone on the owners team.

**Comment by Moopli** [comment]
I think it's worth getting this running by next release; we now have more stable linux builds (funny that I say this when recent changes broke my build, but for others it's true), and it would be very handy and would be a good stepping stone to more robust test coverage.

**Comment by pgelinas** [comment]
[AppVeyor](https://www.appveyor.com/) has support for Windows build with [MinGW](https://www.appveyor.com/docs/installed-software/#mingw-msys-cygwin) and is free for Open Source projects. We can then use Travis for Linux and AppVeyor for Windows, both are configured with yaml.

**Comment by hhyyrylainen** [comment]
https://github.com/hhyyrylainen/Leviathan is built by circleci (for linux) and appveyor (for windows) so it should be pretty easy to take those configuration files and get thrive also building with those ci platforms.

**Comment by hhyyrylainen** [comment]
I've added appveyor and circleci for building and running the basic tests for thrive. I'd still like to add building and running tests with jenkins to have a faster build cycle, but I'll definitely have the "requires approval" before building to not allow malicious people to run random code by opening a pull request.

**Comment by hhyyrylainen** [comment]
There's a few tweaks I'd like to make to the Jenkins build to make it faster but this is now basically working.
