### ISSUE TITLE
Bathypelagic background textures have non-tiling section

### ISSUE THREAD

**Issue by Dragonmemo** [Revolutionary-Games/Thrive#1971]
Build 3072
Hash 88e3eb071e5e811c660b410830e31c214d0a0271

I have no idea how to reproduce it exactly but :
I started a new game, did the tutorial and got to the editor, then I saw those weird clouds remnants (here under the hex/cursor)

![image](https://user-images.githubusercontent.com/67173828/103180869-323db380-489a-11eb-806d-b552470d5b03.png)

**Comment by hhyyrylainen** [comment]
I'm nearly 100% sure that is an actual problem with the background image (bathypelagic).
I didn't find an existing issue (there's just one for a random horizontal line in that background image), so I'll rename this.

**Comment by takko** [comment]
I looked into this and found the incorrect image. It is Thrive_seafloor2.png.

**Comment by Kertit** [comment]
should be fixed now https://dev.revolutionarygamesstudio.com/files/Asset%20development/2D%20backgrounds/Thrive_seafloor2.png

**Comment by hhyyrylainen** [comment]
Yes, thank you! Finally I don't need to notice this background problem anymore.
