### ISSUE TITLE
Closing in game options menu with escape skips confirmation and saving

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1975]
Usually when options have changed, and you try to exit, you need to either save or discard the changed options, but that doesn't work when changing options from the pause menu. When doing that the options just close. When going back to the options the option to save is not available, even though the new options have not been saved.

To fix this, the options menu should intercept the escape key press and show the save changes or discard popup, if there are changed options, instead of allowing the pause menu to close.

**Comment by Kasterisk** [comment]
I can't reproduce this anymore in the master branch, the popup always shows up when I press Escape with modified settings. Looks like this is now fixed?

**Comment by hhyyrylainen** [comment]
I think so, this seems to be fixed at least on your branch that I was just testing (it doesn't have changes related to this).
