### ISSUE TITLE
Language button popup list is slightly cutoff depending on aspect ratio

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1993]
It seems like the list is slightly cutoff if the aspect ratio isn't exactly the same as 720p:
![2021-01-02_22 02 37 9513](https://user-images.githubusercontent.com/3796411/103465652-9c48d380-4d46-11eb-8775-06f032b2fb9b.png)

I think we are using the standard Godot dropdown button thing for it, so this is quite likely an engine bug.

**Comment by Kasterisk** [comment]
Referring to my post on the community forum: https://community.revolutionarygamesstudio.com/t/0-5-3-release-candidate-testing/3252/10?u=kasterisk. As the popupmenu PR hasn't backported to the 3.2 branch, I think we'll have to wait for Godot 4 so that this could be fixed.

**Comment by hhyyrylainen** [comment]
Once we move to Godot 4, setting a reasonable max height for the buttons dropdown should resolve this issue.

**Comment by Kasterisk** [comment]
Removing this from 0.5.6 milestone as 4.0 is still far away and no available built-in fix for Godot 3.

**Comment by hhyyrylainen** [comment]
I think Godot 4 fixed this.
