### ISSUE TITLE
Organelle MP costs in the editor can't be translated

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2000]
This is probably because "55 MP" is a single text inside a label, instead it should be like this:
"55" + Control with spacing + "MP"

**Comment by RacerBG** [comment]
@hhyyrylainen Could you, please, add to this issue that the ATP string from the cost/production tooltip is not translatable too?

I can not capture it on the screen but basically when the mouse hovers over the ATP bars it shows for example "Osmoregulation: **-(amount) ATP**", where ATP is the only not translatable string currently.

![Untitled](https://user-images.githubusercontent.com/68707872/103927410-fb319280-5122-11eb-98d4-df0d461ffe92.png)

**Comment by hhyyrylainen** [comment]
That is a separate issue, opened a new issue for it: https://github.com/Revolutionary-Games/Thrive/issues/2017
