### ISSUE TITLE
"@" in processes should be translateable

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2001]
The "@" symbol in a process separating the environment part is not translateable, it should be made translateable.
Related to: https://github.com/Revolutionary-Games/Thrive/issues/1980

**Comment by RacerBG** [comment]
The same string "@" should be valid for the Editor tooltips too.

**Comment by hhyyrylainen** [comment]
I'm not sure what you mean?
If #1980 is solved, the editor tooltips will use the same code, and will be translateable without needing any extra work, as it doesn't make sense that the process display code is implemented twice in the codebase.

**Comment by RacerBG** [comment]
> 
> 
> I'm not sure what you mean?
> If #1980 is solved, the editor tooltips will use the same code, and will be translateable without needing any extra work, as it doesn't make sense that the process display code is implemented twice in the codebase.

I see, it's fine then.

**Comment by hhyyrylainen** [comment]
This is now at: https://github.com/Revolutionary-Games/Thrive/blob/dab1c9753a4480fdd217fd886d8ea898e63cbebd/src/gui_common/ChemicalEquation.cs#L263

So that should be translated with a key like "PROCESS_ENVIRONMENT_SEPARATOR", with the english text being "@"
