### ISSUE TITLE
The Colour Editor Needs Tooltips And Translation Support

### ISSUE THREAD

**Issue by RacerBG** [Revolutionary-Games/Thrive#2018]
**Describe the bug**
The cell colour editor should have tooltips over the colour picker button, the two "on/off" switches and the "+" sign.

**To Reproduce**
1. Go to the Microbe Editor under Appearance.

**Expected behavior**
The colour picker should have a tooltip like "Choose a colour" or "Pick a colour", the "+" sign should have something like "Add a new colour" tooltip and the "on/off" pair of buttons should have a tooltip which explains what they are doing.
On this topic the "RGB", "HSV" and the "on/off" indicators should be translatable.

**Screenshots**
![colour picker](https://user-images.githubusercontent.com/68707872/104091512-85ded280-5286-11eb-82df-aca6564b2e77.png)

**System info (please complete the following information):**
- Thrive version [0.5.3.0]

**Comment by hhyyrylainen** [comment]
The colour picker is a standard Godot widget.
The only thing we can (probably) do is add a translations for the new colour add tooltip.
Adding new tooltips and also translations for the OFF / ON buttons (as those are images) need to be requested from Godot developers.
