### ISSUE TITLE
Make the game print the godot and C# locale when starting up

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2019]
Also when applying the language in Settings that result should be printed.

This is so that this issue can be investigated further:
> When I first started the game it automatically set it to a language based on my location, but the option menu claimed the game was in English

**Comment by JassieK** [comment]
Hello, I'am really interested in solving this issue but I am a newbie to this . I just started learning C# and unity. If you can guide me through this problem , i would love to solve this and learn some new stuff. Thank You.

**Comment by icedjuro** [comment]
Glad you're interested in contributing! I'm going to assume you already have the game set up for development. If not, check out the setup instructions in the doc folder. If you need help with that, you can join our Discord for more immediate communication. 

For this problem, you're going to need to find a place where the initial stuff is printed when the game starts as well as where settings are applied. Then for the settings, check if the language was changed. If it was, and for the game startup, print out the C# and godot local (you can find how to get that info online), make sure to use `GD.Print`, not `Console.WriteLine`. Feel free to ask more questions if you get stuck!

**Comment by JassieK** [comment]
I'll start with the setup. Thank you so much!

**Comment by JassieK** [comment]
I've completed the game set up as per the instructions , but it is showing some weird issues. 
Can you help me out please
![1](https://user-images.githubusercontent.com/77538080/109400124-e9bf7680-796c-11eb-82c4-fa2528557f78.png)
![2](https://user-images.githubusercontent.com/77538080/109400126-eaf0a380-796c-11eb-822d-0ac9719828f4.png)
