### ISSUE TITLE
The Help Menu Needs An Upper Border

### ISSUE THREAD

**Issue by RacerBG** [Revolutionary-Games/Thrive#2021]
**Describe the bug**
The help menu currently have a border only at the bottom just above the "Close" button. While scrolling down the help messages their upper part looks cut off without a border.

**To Reproduce**
1. Open the help menu and scroll down the messages.

**Expected behavior**
The help menu should have a upper border, similar to the bottom one (above the "Close" button) to reduce the effect of cut off text during scrolling down.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/68707872/104092653-03f2a780-528e-11eb-84c5-71b2ed18285f.png)

**System info:**
- Thrive version [0.5.3.0]

**Comment by hhyyrylainen** [comment]
I have concerns whether it looks weird when the scroll bar is at the top, but I agree it looks a bit weird when scrolling down.

One suggestion regarding that from dev discord:
> Maybe just add a background panel to cover the text boxes, I think that would look fine
