### ISSUE TITLE
Health and ATP bars sometimes disappear

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2022]
I've seen two people share screenshots like this:
![missing bars](https://cdn.discordapp.com/attachments/228300288023461893/797456347079507978/unknown.png)
notice how the bars and some text is gone.
I don't have a clue what causes this.

This is (roughly) what it should look like:
![unknown](https://user-images.githubusercontent.com/54026083/94529337-ced4c300-0263-11eb-8c4f-f6875f0bb63e.png)
(taken from another issue, but that at least shows what bars and numbers there should be)

**Comment by Biologicah** [comment]
One of the screenshotters here, just going to add the idea i had towards it:
the game updating the amount of resources you currently have causes the evolution thing to refresh when you can evolve, since i noticed it was flashing when i was swimming over clouds

**Comment by punctdan** [comment]
I don't know if it will help finding the issue but ATP icon is somehow still there in the first screenshot.

**Comment by RacerBG** [comment]
By the looks of it this could happen before entering the editor (reproduce your species). I played a few generations with my cell but I wasn't able to reproduce it so far. Also I collected all the needed compounds, saved the game and reloaded it to see if that was the cause - still nothing.

Maybe a broken save file is to blame?

For reference (if this is a graphical issue) I'm using AMD Radeon R7 250 on Windows 7 SP1 x64 bit.

**Comment by Kasterisk** [comment]
Most likely a graphical issue, I think this is related to https://community.revolutionarygamesstudio.com/t/0-5-3-release-candidate-testing/3252/5?u=kasterisk, though that one also has the editor button to disappear. I'd guess the Light2D node (which does the flashing effect for when the editor button is enabled) mess up the ui rendering or something. So maybe a godot bug, not sure.

**Comment by hhyyrylainen** [comment]
It seems that quite a few additional reports have come in about this since the last comment here. And basically now it seems that any part of the bottom right GUI is prone to disappear. Likely linked to the light 2D node used there. It would be nice to add an option in the options menu to disable the light2d (or whatever it was that animated the pulsing on the button), to see if this issue goes away when disabling that option.

**Comment by hhyyrylainen** [comment]
The workaround option has now been added, so testing is now needed by the people who have experienced the GUI parts disappearing.

**Comment by Kasterisk** [comment]
There hasn't been any reports regarding this for quite a while now, safe to assume this can be closed until proven otherwise?

**Comment by hhyyrylainen** [comment]
Yeah, I think we can close this for now. May have even been some Godot engine update that fixed this quietly.
