### ISSUE TITLE
Options save confirmation popup doesn't adapt to translation size

### ISSUE THREAD

**Issue by LibreHacker** [Revolutionary-Games/Thrive#2027]
![needfix](https://user-images.githubusercontent.com/66357625/104117426-3ce45800-5332-11eb-90ed-1d458b9eacfd.png)
I found two, see screenshot(s).

**Comment by hhyyrylainen** [comment]
What I see is that the buttons for trying to exit with unsaved changes (presumably, I don't speak that language so I'm not sure) are outside their popup box. What's the other problem?

**Comment by RacerBG** [comment]
@hhyyrylainen Yes, the Cancel button is outside of the box not only in Russian (I tested it with Bulgarian). The other bugs which he seems to mention are about #1894 though.

**Comment by hhyyrylainen** [comment]
The issue about the dropdown box contents not being translatable is: https://github.com/Revolutionary-Games/Thrive/issues/1870
