### ISSUE TITLE
Design a way for the AI and other game objects to keep references to other game objects

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2029]
Do we need to have destruction callbacks or maybe just weak references (need to check that weak references are saved correctly)? Otherwise the objects might keep references to disposed objects and that's bad, and caused the saving problems issues.

Probably will also be good to have for binding agents (@FuJa0815 )

For reference see: https://github.com/Revolutionary-Games/Thrive/pull/2028

- [x] designed and implemented (I did some stuff towards this here: https://github.com/Revolutionary-Games/Thrive/pull/2332)
- [x] styleguide is updated to require people to use this approach when references are kept across frames, single frame local usage variables do not need to be updated to follow the new style

**Comment by Kasterisk** [comment]
I think `Object.IsInstanceValid` could be used as a workaround instead to check if a node/object has been disposed but there's still a reference to it.

**Comment by hhyyrylainen** [comment]
That could maybe work, but it would be easy to forger that...
You are right about weak references having the problem that another reference might be keeping the object alive.
Perhaps destruction callbacks, with maybe a wrapper class for keeping the reference, would be the easiest and most fool-proof way to make this.
