### ISSUE TITLE
Add button next to "open screenshots" to open the logs

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2051]
so that I can reduce the amount of guidance I need to provide to people to find the logs.

**Comment by Paulpicotin** [comment]
Hello  can I  do this one?

**Comment by hhyyrylainen** [comment]
Yes

**Comment by Paulpicotin** [comment]
can you just tell me were are the log please ?

**Comment by hhyyrylainen** [comment]
The logs folder is created next to the saves and screenshot folders.

**Comment by Paulpicotin** [comment]
did I've to translate like I've done for the screenshot folder one ?

**Comment by hhyyrylainen** [comment]
I'm not sure what you are asking.
If you mean whether a new button needs to use the translation system, the answer is yes.

**Comment by Paulpicotin** [comment]
yes that were my question
