### ISSUE TITLE
Add tutorial saying to press the editor button if it has been enabled for a while

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2056]
If the player hasn't pressed the editor button within 20 seconds of it becoming available, a tutorial should open that tells the player to press it to go to the editor.

**Comment by punctdan** [comment]
Maybe also add a tutorial telling you to collect enough Ammonia and Phosphate to reproduce. That could appear a few seconds after getting full of glucose.

**Comment by hhyyrylainen** [comment]
Following the philosophy that the tutorial shouldn't be in your face, there is actually a tutorial for collecting ammonia and phoshpates to reproduce, but it is shown only after 3 minutes as I considered that to be the maximum amount of time the player should be allowed to be confused in order to not frustrate the player.
That delay is controlled by this variable:
```
public const float MICROBE_REPRODUCTION_TUTORIAL_DELAY = 180;
```
Which I suppose could be maybe reduced to two minutes?

**Comment by Kasterisk** [comment]
Personally I prefer for a bit more shorter delay. I'd say one minute but two minutes is also probably good.

**Comment by hhyyrylainen** [comment]
I don't want the delay to be too short as it might take almost like a minute for the glucose tutorial to appear, so I want some safety margin there (to not have the reproduction tutorial popup before the glucose tutorial is done, I know it could be programmed to only start counting after the glucose tutorial, but the current implementation is what it is), which is the reason why I think the minimum should be 120 seconds of gameplay before the reproduction tutorial can be shown.

**Comment by Kasterisk** [comment]
Ah okay, didn't realize the timer starts before the previous tutorial, two minutes it is then. Maybe it can be tweaked later once we get around that.
