### ISSUE TITLE
Add a warning popup for open screenshots or saves folder if they don't exist

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2065]
At least if the user hasn't taken a screenshot the open screenshots button just silently fails.
Instead it should show a warning popup that the folder doesn't exist and suggest taking a screenshot and then trying again.
The same probably also applies to the browse saves folder button so that should also have a warning popup, and suggesting the player to make a save first.

I think it's fine to have this either way: after closing the warning the folder is attempted to be opened anyway, or nothing is done (trying to open a non-existing folder is not a fatal error so it doesn't matter).

**Comment by celebrityknave** [comment]
Hi, I've just quickly thrown something together for this issue for a first contribution. Just created in a pull request. Let me know if there are any issues. Cheers.
