### ISSUE TITLE
Investigate why await on ToSignal causes a warning

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2071]
`await ToSignal(tween, "tween_completed");`

triggers this warning for me (and presumably once we update the CI commandline tool version that should also complain): 
```
\src\gui_common\GUICommon.cs:2828 Type 'Godot.SignalAwaiter' is not awaitable
```

See discussion here: https://github.com/Revolutionary-Games/Thrive/pull/2046#discussion_r566923626

Possibly might be because the Godot type doesn't implement all the required interfaces so code inspections fail. `Godot.IAwaiter ` doesn't implement `ICriticalNotifyCompletion` interface.

**Comment by knightofiam** [comment]
Thank you for this information! I'm experiencing the same error and opened an issue with Godot [here](https://github.com/godotengine/godot/issues/52594).

**Comment by knightofiam** [comment]
We've determined it's probably not a bug in Godot, and that the `ICriticalNotifyCompletion` is optional and unnecessary in this case. I've taken the next step and reported this to JetBrain's [Godot Support Plugin](https://github.com/JetBrains/godot-support/issues/67) team. I'll let you know what we discover.

**Comment by hhyyrylainen** [comment]
With the switch to Godot 4, this is probably no longer in the Thrive code.

**Comment by hhyyrylainen** [comment]
There's no longer any instances of this in the Thrive code.
