### ISSUE TITLE
Key prompts is stuck after disabling tutorial in microbe editor

### ISSUE THREAD

**Issue by Kasterisk** [Revolutionary-Games/Thrive#2075]
When disabling the tutorial (in current game) setting in the options menu while in the editor, the key prompts were stuck open (doesn't rotate and won't disappear) after you return to the stage. ~~Note that this may only happen if running from the MicrobeEditor scene directly in Godot, and most likely won't happen in a normal playthrough.~~ (See comment below)

**Comment by hhyyrylainen** [comment]
So you mean this problem only happens when directly starting the editor scene from the Godot editor? Do you have exact steps for reproducing the issue?

**Comment by Kasterisk** [comment]
Wait no I think got it the wrong way around. It actually do happen in a normal playthrough (by starting New Game) and probably won't happen by starting from the editor directly. Steps to reproduce:
- New Game
- Go to the editor by pressing P
- Disable the current game tutorial setting
- Return to the stage
- And the key prompts is stuck

**Comment by hhyyrylainen** [comment]
Interesting, so it seems like when the tutorial is disabled in the editor, the stage doesn't get the memo that all the tutorials should be hidden, but it does get the message that tutorials should no longer run (so the key prompts tutorial no longer react to the player holding down the key). Could be relatively easy to debug why the tutorials don't hide themselves in this case.
