### ISSUE TITLE
Back button from load menu doesn't do anything

### ISSUE THREAD

**Issue by LogicalKip** [Revolutionary-Games/Thrive#2098]
From the main menu, click on Load Game, then on Back. It stays on the loading menu instead of returning on the main menu.

Not to be mistaken with the back button you can get from New Game > Esc > Load Game > Back, which is different and DOES work.

**Comment by hhyyrylainen** [comment]
I can't reproduce this issue on master or with 0.5.3 release. One thing that may have happened is that the game actually locked up. Did any of the buttons work? Did the screenshots for the saves load or did they stay showing the Thrive logo?

**Comment by LogicalKip** [comment]
Yes, I could select saves, delete them, try to load them, click on refresh, open save directory etc. 
I just cloned the repository this morning. 
Although, now that I try, I could only reproduce the error from my locally built version of the game (0.5.3.1-alpha). The bug is indeed not present on the released version from the launcher (0.5.3)

**Comment by hhyyrylainen** [comment]
Running on clean master branch version I don't get this issue. See: https://wiki.revolutionarygamesstudio.com/wiki/Cleaning_Local_Thrive_Version
