### ISSUE TITLE
Organelle right click popup MP costs don't take symmetry into account

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2103]
they should as otherwise the remove cost is inaccurate (but move cost is accurate as only one thing can be moved at once).

**Comment by ender-titan1** [comment]
What scripts manage the MP cost, the pop-up and symmetry?

**Comment by Kasterisk** [comment]
For the MP costs it's defined in [Constants.cs](https://github.com/Revolutionary-Games/Thrive/blob/b6a77438cc21f30780cfaab54656e8fd7bdf6ad6/simulation_parameters/Constants.cs), the organelle popup in [OrganellePopupMenu.cs](https://github.com/Revolutionary-Games/Thrive/blob/b6a77438cc21f30780cfaab54656e8fd7bdf6ad6/src/microbe_stage/editor/OrganellePopupMenu.cs) and the [MicrobeEditor](https://github.com/Revolutionary-Games/Thrive/blob/b6a77438cc21f30780cfaab54656e8fd7bdf6ad6/src/microbe_stage/editor/MicrobeEditor.cs) script handles the symmetry along with other functionalities.

**Comment by ender-titan1** [comment]
Thanks.

**Comment by ender-titan1** [comment]
Does MicrobeEditor.cs also manage MP reduction?

**Comment by Kasterisk** [comment]
Yeah, it pretty much manages everything in the editor including mutation point changes. The code that specifically handles that is inside this method: https://github.com/Revolutionary-Games/Thrive/blob/b6a77438cc21f30780cfaab54656e8fd7bdf6ad6/src/microbe_stage/editor/MicrobeEditor.cs#L977

**Comment by ender-titan1** [comment]
So, `ChangeMutationPoints` Void can only be activated by MicrobeEditorAction and i can’t find that in MicrobeEditor.cs. It’s probably in another script. Which script is it?

**Comment by Kasterisk** [comment]
`MicrobeEditorAction` is instantiated in the MicrobeEditor script whenever a new action is needed, like here for example: https://github.com/Revolutionary-Games/Thrive/blob/e71c7be3190afe1d45bfc174ad1049132ebccf5d/src/microbe_stage/editor/MicrobeEditor.cs#L1732

**Comment by Kasterisk** [comment]
Closing as this is already implemented on master.
