### ISSUE TITLE
Add translation support for colour picker + tooltip

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2106]
Need to add the text to MainMenu.CallMiscTranslations and that should be it

**Comment by bieladeka** [comment]
Hi, I'd like to work on this one.
I can see there are already translation for strings "OK" and "Cancel". Where I can find exact strings which should be translated? 
Thanks

**Comment by hhyyrylainen** [comment]
You can play the game and interact with the colour picker in the editor on the membrane tab to see what are all of the elements that have text on them in it, and what tooltips there are.

**Comment by bieladeka** [comment]
Hi, how I can add to the files  locale/bg.po, locale/ca.po ... etc,  MSGID for translation ? It's could be done automatically somehow? Thanks.

**Comment by hhyyrylainen** [comment]
Just noticed that this is a duplicate of: https://github.com/Revolutionary-Games/Thrive/issues/2018
