### ISSUE TITLE
Report Tab Statistics Formatting

### ISSUE THREAD

**Issue by RacerBG** [Revolutionary-Games/Thrive#2107]
**Describe the bug**

This is just a small formatting issue. The species population on the graph does not show "species" - only their total population and the years are not separated by a space. 

**To Reproduce**
1. Go to the Reports Tab.

**Expected behavior**
Above the species population numbers there should be an indicator ("species" for example) which should be shown in the tooltip as well (just like the other graphs which have C degrees and %). Also there should be a space between the number of the years, the population number and their type (K, M, B, etc.) on the graphs as well as on the tooltips.

**Screenshots**
![2021-02-17_22 38 35 1429](https://user-images.githubusercontent.com/68707872/108270894-b6b10200-7178-11eb-958c-303a59489c67.png)

**System info (please complete the following information):**
- Thrive version [0.5.3.1]

**Comment by hhyyrylainen** [comment]
Regarding the missing space, this seems to be translation specific as the English version looks fine:
![2021-02-18_09 15 31 4277](https://user-images.githubusercontent.com/3796411/108319369-f8b66400-71c9-11eb-91c0-442d85d05661.png)

Also to me it makes quite a bit of sense that the tooltip has the first line as the dataset name (which I suppose could be "Species: {0}", then the x axis value and finally on the third line the y axis value.

I suppose "Population" should be shown on the y axis of the population chart.
So in the end this is:
- One issue in a translation
- One missing label in the population char
- A request to add "Species" in front of the dataset name in the datapoint tooltip.

@Kasterisk opinions?

**Comment by RacerBG** [comment]
> Regarding the missing space, this seems to be translation specific as the English version looks fine:
> ![2021-02-18_09 15 31 4277](https://user-images.githubusercontent.com/3796411/108319369-f8b66400-71c9-11eb-91c0-442d85d05661.png)
> 
> Also to me it makes quite a bit of sense that the tooltip has the first line as the dataset name (which I suppose could be "Species: {0}", then the x axis value and finally on the third line the y axis value.
> 
> I suppose "Population" should be shown on the y axis of the population chart.
> So in the end this is:
> 
> * One issue in a translation
> * One missing label in the population char
> * A request to add "Species" in front of the dataset name in the datapoint tooltip.
> 
> Is my analysis correct?
> 
> @Kasterisk opinions?

The species should go above the y axis and after 187 according to your screenshot (the name of the species is fine as it is). But English lacks space too. I tried to add a space before the string but it corrects it because the original lacks a space.

**Comment by hhyyrylainen** [comment]
> The species should go above the y axis and after 187 according to your screenshot (the name of the species is fine as it is). But English lacks space too. I tried to add a space before the string but it corrects it because the original lacks a space.

So you mean between 100 and the M? After a bit of googling it does seem to be a common thing to have a space between the number and magnitude suffix. So I guess we should fix it.

**Comment by Kasterisk** [comment]
> Above the species population numbers there should be an indicator ("species" for example) which should be shown in the tooltip as well (just like the other graphs which have C degrees and %)

I think "individuals" would be more fitting, as it will be weird if the y axis on the tooltip says 100 species/populations.

> Also there should be a space between the number of the years, the population number and their type (K, M, B, etc.) on the graphs as well as on the tooltips.

The missing space between years was likely because of the panel not being wide enough, so I think the statistics panel (and maybe the log panel) just needs to be tweaked so the statistics would be able to automatically expand to the left for more space. For the numbers suffix, I guess we could add some spacings to the `FormatNumber` extension method.

**Comment by RacerBG** [comment]
> > Above the species population numbers there should be an indicator ("species" for example) which should be shown in the tooltip as well (just like the other graphs which have C degrees and %)
> 
> I think "individuals" would be more fitting, as it will be weird if the y axis on the tooltip says 100 species/population.
> 
> > Also there should be a space between the number of the years, the population number and their type (K, M, B, etc.) on the graphs as well as on the tooltips.
> 
> The missing space between years was likely because of the panel not being wide enough, so I think the statistics panel (and maybe the log panel) just needs to be tweaked so the statistics would be able to automatically expand to the left for more space. For the numbers suffix, I guess we could add some spacings to the `FormatNumber` extension method.

Individuals sounds very good to me. Actually, I'm using the exact same word in Bulgarian at some places to make a distinction between a specific population number and the species as a whole.

**Comment by Kasterisk** [comment]
> Also to me it makes quite a bit of sense that the tooltip has the first line as the dataset name (which I suppose could be "Species: {0}", then the x axis value and finally on the third line the y axis value.

I think in some cases that will make the tooltip too long, the current layout should be fine and is already concise enough. So in my opinion the final issues were:
- Give the species pop graph y axis a name
- Add spacing to the number suffix
- And tweak the statistics panel to allow it to automatically expand to the left

**Comment by hhyyrylainen** [comment]
> I think "individuals" would be more fitting, as it will be weird if the y axis on the tooltip says 100 species/population.

That's a bit confusing as it isn't literally individuals, the population numbers represent like billions or trillions of individuals, as microbes are very populous.

@Kasterisk Could you explain what that last final issue in your list is? I agree with the first two, but I didn't really get what the last point is about...

**Comment by Kasterisk** [comment]
> That's a bit confusing as it isn't literally individuals, the population numbers represent like billions or trillions of individuals, as microbes are very populous.

Well, the current design is for the name of y axis to be some kind of unit for a single y axis number (hence 76 % and not 76 Percentage), so it's the closest that makes sense in my opinion.

> @Kasterisk Could you explain what that last final issue in your list is? I agree with the first two, but I didn't really get what the last point is about...

In @RacerBG's screenshot, the year number labels are very close to each other, I suspect it's because the horizontal spacing on the HBoxContainer that contains the x axis ticks is set to zero (which is why there's no spacing once the text gets too long) and the panel should expand to accommodate for that. Now that I think about it, I just realised the statistics panel used ScrollContainer, so it should already be able to automatically expand within itself...

**Comment by hhyyrylainen** [comment]
> Well, the current design is for the name of y axis to be some kind of unit for a single y axis number (hence 76 % and not 76 Percentage), so it's the closest that makes sense in my opinion.

I guess then it might be better to leave it blank?

> In @RacerBG's screenshot, the year number labels are very close to each other, I suspect it's because the horizontal spacing on the HBoxContainer that contains the x axis ticks is set to zero (which is why there's no spacing once the text gets too long) and the panel should expand to accommodate for that. Now that I think about it, I just realised the statistics panel used ScrollContainer, so it should already be able to automatically expand within itself...

Ah, okay. Sounds good.

**Comment by Kasterisk** [comment]
> I guess then it might be better to leave it blank?

Hm, probably. It should be already clear that the numbers indicates number of individuals without the unit anyways. What do you think @RacerBG?

**Comment by RacerBG** [comment]
> > I guess then it might be better to leave it blank?
> 
> Hm, probably. It should be already clear that the numbers indicates number of individuals without the unit anyways. What do you think @RacerBG?

No problems, will the tooltip include it though (after the second number I mean)?

**Comment by Kasterisk** [comment]
Unfortunately no, the one above the y axis and in the tooltip are related, so if one is empty the other one will be too.

**Comment by RacerBG** [comment]
> Unfortunately no, the one above the y axis and in the tooltip are related, so if one is empty the other one will be too.

That's fine, go ahead. :smiley:

**Comment by hhyyrylainen** [comment]
One comment regarding the spacing with the "M" might be worth it to change the translation so that it is "{0} M" and update the code to reflect that.
