### ISSUE TITLE
[0.5.3.1] Thrive Crashed After The Editor

### ISSUE THREAD

**Issue by RacerBG** [Revolutionary-Games/Thrive#2108]
**Describe the bug**

Thrive crashed with a light gray background instead of a biome color right after exiting the Editor.

**To Reproduce**
Please, have a look at the log file, I'm not sure if this is easily reproducible.

**System info (please complete the following information):**
- OS: [Windows 7 SP1 64 bit]
- AMD Radeon R7 250 2GB
- Thrive version [0.5.3.1]

**Logs**
[log.txt](https://github.com/Revolutionary-Games/Thrive/files/5998915/log.txt)

Regards,
Georgi

**Comment by hhyyrylainen** [comment]
Does this always happen? Or just rarely?

Looking at the log this seems to be the error part:
```
**ERROR**: Condition "!E" is true.
   At: scene/3d/area.cpp:123:_body_enter_tree() - Condition "!E" is true.
**ERROR**: Condition "!E" is true.
   At: scene/3d/area.cpp:123:_body_enter_tree() - Condition "!E" is true.
**ERROR**: Condition "!E" is true.
   At: scene/3d/area.cpp:123:_body_enter_tree() - Condition "!E" is true.
**ERROR**: Condition "!E" is true.
   At: scene/3d/area.cpp:123:_body_enter_tree() - Condition "!E" is true.
**ERROR**: Condition "!E" is true.
   At: scene/3d/area.cpp:123:_body_enter_tree() - Condition "!E" is true.
Previous patch (Пангонски отвори) different to current patch (Пангонски тидален басейн) despawning all entities.
**ERROR**: Condition "!E" is true.
   At: scene/3d/area.cpp:140:_body_exit_tree() - Condition "!E" is true.
**ERROR**: Condition "!E" is true.
   At: scene/3d/area.cpp:140:_body_exit_tree() - Condition "!E" is true.
**ERROR**: Condition "!E" is true.
   At: scene/3d/area.cpp:140:_body_exit_tree() - Condition "!E" is true.
**ERROR**: Condition "!E" is true.
   At: scene/3d/area.cpp:140:_body_exit_tree() - Condition "!E" is true.
**ERROR**: Condition "!E" is true.
   At: scene/3d/area.cpp:140:_body_exit_tree() - Condition "!E" is true.
```

Which looks related to the physics problems (meaning this issue is a duplicate): https://github.com/Revolutionary-Games/Thrive/issues/1282 with the exact same error in this issue: https://github.com/Revolutionary-Games/Thrive/issues/2043

**Comment by RacerBG** [comment]
This is the first time happening on my working environment. Yesterday it was too late for me to test this extensively. I will give it another go today (I have plenty of time). :smiley:

**Comment by RacerBG** [comment]
It happened again, this time on a laptop with AMD Radeon R5 M330 GPU and Windows 7 SP1 64 bit.

This happened after generation 15 and the whole OS stalled together with Thrive.

**Comment by hhyyrylainen** [comment]
So it happens randomly? Then I'm pretty confident this is the physics related lockup / #2043 has this error message, as such I'll close this as duplicate. Btw I just heard that Godot 4.0 potentially has a fix for this problem.

**Comment by RacerBG** [comment]
@hhyyrylainen Other than this bug the game seems very stable on my PC. The only thing which I noticed and I don't know if it deserves a separate bug report is that the clouds are starting to flash a lot after generation 10+. I don't know if this is related to the game settings or it is a rendering issue.

**Comment by hhyyrylainen** [comment]
I get it also on my computer. I'm not really sure what causes it, but it might have something to do when there are a lot of clouds on screen. There's an existing issue about this: https://github.com/Revolutionary-Games/Thrive/issues/1700
