### ISSUE TITLE
Make microbe rotation use physics force

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2112]
instead of directly just changing the rotation of the physics body.

NOTE: to anyone going to take a look at this, all the axes are currently locked, so you'll want to unlock them before starting on this, otherwise you'll wonder why the angular force doesn't do anything (https://github.com/Revolutionary-Games/Thrive/pull/2266)

I tried to do this years ago but I ended up just having the cells oscillate around their wanted direction instead of the rotation stabilizing, so this is a bit difficult to do.

With this we can make piluses hitting work better. And also we can finally make rotation speed be affected by cell mass, so implementing cilia will make more sense (#174).

**Comment by hhyyrylainen** [comment]
Also now needed to make cell colonies work better.

**Comment by hhyyrylainen** [comment]
This is being worked on this branch: https://github.com/Revolutionary-Games/Thrive/compare/physics_rotation

**Comment by Nunez2196** [comment]
If anyone wants to help or learn more, just ping me. I'm working pretty actively on it on my local branch
