### ISSUE TITLE
Make patch move in freebuild allow moving to any reachable patch

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2115]
So instead of requiring the player to select each subsequent patch in a path and click the move button, in freebuild any patch (from the current patch where there is a viable path) can be moved to.

**Comment by icedjuro** [comment]
What algorithm do you recommend to check if there is a connection between two patches?

**Comment by hhyyrylainen** [comment]
A depth first search seems a fine candidate. Or maybe a non-recursive approach with a list of open and visited nodes (to easily avoid going in loops which the recursive approach might get stuck in).

**Comment by Jonathon594** [comment]
To be fair free build is essentially sandbox mode, does the patch having a path really matter?

**Comment by hhyyrylainen** [comment]
In practice, probably not, but I'd like this to be futureproofed. Basically so that the move is shorthand exactly for the player clicking move patch manually on each patch on a route to the target patch.
