### ISSUE TITLE
Update the editor's undo tutorial text

### ISSUE THREAD

**Issue by Kasterisk** [Revolutionary-Games/Thrive#2118]
Need to be slightly reworded since it still mentions that right clicking deletes organelles instead of opening up the organelle menu.
![2021-02-25_16 37 59 2248](https://user-images.githubusercontent.com/54026083/109134138-51689c80-7788-11eb-984e-0d1331954d43.png)

**Comment by hhyyrylainen** [comment]
Yeah, it's basically still correct, but could use improvements. If the rewording is done on the translations site care needs to be taken so that the text still fits the box, or the box size needs to be slightly increased.

**Comment by Kasterisk** [comment]
I think the text being too long should be ok, as the tutorial boxes has scrollbars now.

**Comment by hhyyrylainen** [comment]
That's true, though, I'd really like to keep the English tutorials so that they don't have scrollbars, it's more of a stopgap measure to make sure all languages work without a ton of testing effort.

**Comment by ender-titan1** [comment]
I could do this, all I need to know is in which file the text is located.

**Comment by hhyyrylainen** [comment]
locale/en.po contains all the English text for the game.

**Comment by ender-titan1** [comment]
Ok, the text has been reworded.
