### ISSUE TITLE
Add direct key bindings for organelle delete and move

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2119]
in the editor.

Basically needs just some extra attributes on the methods in MicrobeEditor to hook them up, and creating the actions in the godot project definition.

Should also be added to the input definitions json so that they are rebindable.

**Comment by Jdumontier** [comment]
Hello, I'd like to start working on Thrive with this issue please.

**Comment by hhyyrylainen** [comment]
Sure. I'll assign this issue to you. Let me know if you need me to link the setup instructions or anything like that.

**Comment by Jdumontier** [comment]
Thanks, you already did link it to me in Discord, I should be fine... for now.

**Comment by Varhastr** [comment]
Hello! If Jdumontier is willing to have an apprentice for this issue I'd like to help as well

**Comment by Jdumontier** [comment]
I am so sorry but I have to withdraw from the project entirely. Things changed at school and I am not longer allowed to work on this project. 
I'd like to thank you for letting me have this opportunity and I'd like to apologize for the wasted time.

Good luck

**Comment by jjuicecup** [comment]
I'm interested in working on this issue, it's my first one.

**Comment by hhyyrylainen** [comment]
@jjuicecup are you still working on this issue or should I unassign you?

**Comment by jjuicecup** [comment]
@hhyyrylainen couldn't figure it out sorry, please unassign me

**Comment by c-mirai** [comment]
Hi, I'd like to start working on this issue.

**Comment by Nunez2196** [comment]
> Hi, I'd like to start working on this issue.

I've assigned you, if you need any help you can ping hhyyrylainen or myself. There are other programmers who might help you if you just mention what you're stuck on here

**Comment by c-mirai** [comment]
@Nunez2196 I want the delete key to close the organelle popup menu, but I can't find in the code how it's currently done (i.e. how the escape key does it.) I wrote my own HideOrganelleMenu method and it works fine, but there must be a better way?
