### ISSUE TITLE
Please start working on a Mac download version even if it’s not certified 

### ISSUE THREAD

**Issue by validreview** [Revolutionary-Games/Thrive#2120]
**Important**
Please only submit technical bug reports here. This is not a place to make feature requests
or suggestions. For that please visit our community forums:
https://community.revolutionarygamesstudio.com/

**Describe the bug**

**To Reproduce**
2. Click on new game / something else '....'
3. Play and do '....'

**Expected behavior**
A clear and concise description of what you expected to happen, instead of what actually
happened.

**Screenshots**

**System info (please complete the following information):**
- OS: [e.g. Windows 10]
- Graphics card (you can find this in the game logs) [e.g. OpenGL ES 3.0 Renderer:
    GeForce GTX 1080 Ti/PCIe/SSE2]
- Thrive version [e.g. 0.4.0.2]

**Logs**

Please use a text hosting service (for example https://pastebin.com/) to submit your logs.
You can copy the launcher output or the contents of the following files: `log.txt` and mono
log file. You can find these log files by reading the game log to see their location.
For example:
```
Mono: Logfile is: /home/hhyyrylainen/.local/share/godot/mono/mono_logs/2020_07_21 23.10.26 (265121).txt
Game logs are written to: /home/hhyyrylainen/.local/share/Thrive/logs latest log is 'log.txt'
```

**Additional context**

**Comment by hhyyrylainen** [comment]
The game itself is available as a zip for mac (made with standard Godot export templates): https://github.com/Revolutionary-Games/Thrive/releases/tag/v0.5.3.1
![Kuvakaappaus - 2021-03-01 08-46-11](https://user-images.githubusercontent.com/3796411/109461310-9e8b8d80-7a6a-11eb-9846-da72ea7703c2.png)

Seeing as there wasn't an issue yet in the launcher repo about implementing it working fine for mac, I opened one just now: https://github.com/Revolutionary-Games/Thrive-Launcher/issues/114
