### ISSUE TITLE
Make a model for cytoplasm when used as a cell chunk

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2121]
and after that remove the fallback mitochondria usage if no organelle model was selected.
In the future the cytoplasm model could additionally be used in the list to pick from, so it wouldn't be just a fallback.

**Comment by nbroderick-code** [comment]
@hhyyrylainen could you give a screen shot of what part of the game this is supposed to fit into? Which bit specifically are we trying to replace? Sorry, I just don't quite understand the request

**Comment by hhyyrylainen** [comment]
Right now when a cell dies, the organelles in it become the corpse chunk models. However, as cytoplasm is invisible it doesn't have a model for it. So we need a special model used whenever cytoplasm is dropped as a cell corpse chunk.

**Comment by nbroderick-code** [comment]
Got some ideas floating around in my notebook. May I ask what a good target poly count is?

**Comment by hhyyrylainen** [comment]
Around 300 triangles should be the target for each organelle model.

**Comment by nbroderick-code** [comment]
Weighing in at exactly 300 triangles, I basically just modelled a blob. Haha.
 
![Cytoplasm_mockup](https://user-images.githubusercontent.com/61485226/114278148-3e7df480-99e3-11eb-8e1d-543801dcb255.png)

![Cytoplasm_Alone](https://user-images.githubusercontent.com/61485226/114278189-738a4700-99e3-11eb-83b0-5f258a8f071b.png)

Thoughts? Feedback welcome, obviously.

**Comment by hhyyrylainen** [comment]
You should post those on the graphics dev discord channel, as that's much more active in terms of getting feedback.
I'll give a quick bit of feedback: I think it would be greatly improved by having a slightly unevenly transparent texture to emphasise that cytoplasm contains specific strands of stuff (I can't remember the exact term right now).

**Comment by nbroderick-code** [comment]
Ah, ok. I didn't realize textures got used.

**Comment by Nunez2196** [comment]
You need some more interesting normal maps maybe. It looks extremely smooth. What does the topology look like?

**Comment by nbroderick-code** [comment]
Agreed. What size are the textures for these? This has no texturing at all since I assumed a material was just applied in the game engine.

![image](https://user-images.githubusercontent.com/61485226/114278548-37f07c80-99e5-11eb-899b-c351e525cc76.png)

**Comment by nbroderick-code** [comment]
Here is the glb and .pngs. Let me know if I did everything ok. First time for everything!
[Cytoplasm_Export.zip](https://github.com/Revolutionary-Games/Thrive/files/6290555/Cytoplasm_Export.zip)
