### ISSUE TITLE
Differentiate graph marker indicating extinct species

### ISSUE THREAD

**Issue by Kasterisk** [Revolutionary-Games/Thrive#2131]
Currently an X icon is used to mark any extinction types on the species population graph, and may create the impression that a species have gone extinct entirely even though it's only patch-specific. Would be nice if a unique icon is used to indicate that.

**Comment by hhyyrylainen** [comment]
Perhaps the entirely extinct indicator could be a skull icon, as that's a pretty common death indicator.
