### ISSUE TITLE
Hydrogen Sulfide in Bathypelagic and Mesopelagic patches

### ISSUE THREAD

**Issue by ender-titan1** [Revolutionary-Games/Thrive#2139]
I have found a bug while playing thrive on windows.

the bug:

there was a green cloud of Hydrogen Sulfide in the Bathypelagic and Mesopelagic patches where, (as far as i understand) the Hydrogen Sulfide level should be 0% (according to the statistics in the patch map)

how to recreate:

1. go to the Mesopelagic or Bathypelagic patches
2. after a while you will find a cloud of Hydrogen Sulfide.

screenshots:

![Thrive - 0 5 3 1 20 03 2021 12_26_33](https://user-images.githubusercontent.com/81180880/112037490-10269b00-8b42-11eb-9be2-9c806566f3a5.png)
![Thrive - 0 5 3 1 20 03 2021 12_26_43](https://user-images.githubusercontent.com/81180880/112037498-1157c800-8b42-11eb-9127-23ae14c8932f.png)

hope this helps!

**Comment by hhyyrylainen** [comment]
Already a known issue: https://github.com/Revolutionary-Games/Thrive/issues/1699
probably related to: https://github.com/Revolutionary-Games/Thrive/issues/1777 and https://github.com/Revolutionary-Games/Thrive/issues/1541
