### ISSUE TITLE
Played hours and i notice a couple things that i think it could improve the experience.

### ISSUE THREAD

**Issue by wirytiox** [Revolutionary-Games/Thrive#2140]
The AI has a problem that happens when they have a pilus: the problem is that they try to "eat"  iron or something that they can't eat or doesn't help them.
another problem is the damage of the pilus: when you get hit by them, you'll die, i'm not sure if the problem is the ausence of invulnerabilty frames or what, but that is something weird.
i would like a better tutorial where they give you a custom cell with a pilus, and toxins. and it would be cool if the teach you how to eat another things. (it was a bit hard to me)
the next thing is a personal problem, but if they allow you to keep half of your non spent mutacion points would help a lot if you need to quickly upgrade something.
Another minor inconvenience is the body block that you own allys do.
for what i've played that's all the things that annoys me. but the worst problem is the pilus damage/invulnerability frames issue.
Good luck with the developing of the game, i can't help with code because i'm not good at it, but i can give an oppinion and share the greate game that you guys are doing.

**Comment by hhyyrylainen** [comment]
Github issues are for tracking concrete bugs and accepted new features to be completed. If you want to provide general feedback, please head over to our community forums: https://community.revolutionarygamesstudio.com/
