### ISSUE TITLE
Update thermoplast tooltip to say it is not implemented

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2148]
as a lot of people ask about it.

Should be done by duplicating the not implemented info node and putting that in the thermoplast tooltip.

**Comment by ender-titan1** [comment]
Ok, I will do this.
Shouldn't take long.

**Comment by ender-titan1** [comment]
Just I can't find the scene in which to do that.

**Comment by hhyyrylainen** [comment]
Maybe the naming is a tiny bit confusing, but it is in TooltipManager

![Kuvakaappaus - 2021-03-26 21-56-01](https://user-images.githubusercontent.com/3796411/112686071-1be5ca80-8e7e-11eb-9a05-24d5d56eba05.png)
