### ISSUE TITLE
Add place name generator to be used by the patch map generator

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2153]
For the procedural map: https://github.com/Revolutionary-Games/Thrive/issues/682 we need procedural names.
For now just an English implementation is needed, but in the future we could have language specific generators.

See: https://github.com/Revolutionary-Games/Thrive/pull/2151#issuecomment-808895448

**Comment by Kemikal1** [comment]
Dont we have preset biomes? How would the procedural names be implemented?

**Comment by hhyyrylainen** [comment]
Biome names would still be fixed, but the patch names would be generated. Even now "Pangonia" is a fictional place name, so quite easily a fictional place name generator could replace that part of the names.
