### ISSUE TITLE
Population number starts wrapping when the population is big in Microbe HUD

### ISSUE THREAD

**Issue by icedjuro** [Revolutionary-Games/Thrive#2154]
Not sure on other screen resolutions, but for a 1920x1080, once the population reaches 10k, digits start going to a new line.

**Comment by Kasterisk** [comment]
This is actually intended, I made the label autowrapped so the box doesn't extend to the left and possibly obstructing the view if the number gets large enough. A better solution I think is formatting the population number to use letter `K` or `M` and so on to indicate thousands/millions.

**Comment by icedjuro** [comment]
That sounds fine to me
