### ISSUE TITLE
Half the UI (HP, ATP and ammonia meter) disappear after getting able to evolve

### ISSUE THREAD

**Issue by joendter** [Revolutionary-Games/Thrive#2155]
**Describe the bug**

Once I have enough ammonia and phosphate to evolve, the UI for HP, ATP and ammonia gets bugged and half of it invisible. If i hover over it everything shows up again, but if i stop hovering over it it disappears again.

**To Reproduce**
1. Create new Game
2. Gather enough ammonia and phosphate to evolve
3. See error

**Expected behavior**
UI being permanently visible even when not hovering over it.

**Screenshots**
Bugged UI:
![image](https://user-images.githubusercontent.com/71767955/112763179-ae63a680-9003-11eb-80ce-15ace5dc7c19.png)

Normal UI:
![image](https://user-images.githubusercontent.com/71767955/112763229-df43db80-9003-11eb-9b48-2175f1a9d48b.png)

**System info (please complete the following information):**
- OS: Windows 10
- Graphics card: OpenGL ES 3.0 Renderer: Intel(R) Iris(R) Graphics 540
- Thrive version 0.5.3.1

**Logs**

https://pastebin.com/eyCRbj1f

the mono log seems to be empty:
![image](https://user-images.githubusercontent.com/71767955/112763556-37c7a880-9005-11eb-99f0-65c7d20a834a.png)

**Comment by hhyyrylainen** [comment]
I'm pretty sure this is a duplicate of: https://github.com/Revolutionary-Games/Thrive/issues/2022
