### ISSUE TITLE
Make sure you want to quit

### ISSUE THREAD

**Issue by JukoiDev** [Revolutionary-Games/Thrive#2156]
"Make sure you want to quit" message box.

**Comment by hhyyrylainen** [comment]
I guess it is a good idea to require confirmation in the in game pause menu before returning to the main menu or quitting the game.
To not bother the user unnecessarily, I think that quit confirmation box should only pop up if it has been more than 10 seconds since the last save.

**Comment by RacerBG** [comment]
@hhyyrylainen I would suggest to add a "Do not show this again" checkbox in to the yes/no quit dialogue. In this way the user can choose if he/she wants to be bothered by this message again. This should also be added somewhere in the options menu as a checkbox if the first option is implemented.

**Comment by ender-titan1** [comment]
What scene is the pause menu in?

**Comment by hhyyrylainen** [comment]
The godot search functionality is really useful:
![Kuvakaappaus - 2021-04-02 20-34-04](https://user-images.githubusercontent.com/3796411/113439225-d29ff880-93f2-11eb-8391-0a3dcf49b52b.png)

**Comment by Kasterisk** [comment]
https://github.com/Revolutionary-Games/Thrive/blob/master/src/general/PauseMenu.tscn

**Comment by ender-titan1** [comment]
Nevermind just found it.

**Comment by ender-titan1** [comment]
hey, can i get assigned?
