### ISSUE TITLE
NL_BE Shooting out of its limits.

### ISSUE THREAD

**Issue by PhiMyth** [Revolutionary-Games/Thrive#2162]
**Problem with**
The problem occurs with the Dutch (Belgium) translation

**Bug Description.**

When the Dutch (Belgium) language is selected, the text seems to be going out of limits because it's way too long.

**To Reproduce?**
How to see the mishap:
1. Go to settings and set the game to Dutch (Belgium).
2. Click on 'Varia'.
3. See the mishap.

**What I originally expected.**
The text should be inside the blue-ish box instead of covering the background. Ultimately, the box should expand or/and a new text line should start.

**Screenshots.**
<img width="2560" alt="Schermafbeelding 2021-03-30 om 19 57 31" src="https://user-images.githubusercontent.com/77279534/113035392-7c814a00-9193-11eb-8de0-e9aba1b72554.png">

**System info.**
- OS: macOS Big Sur (MacOS 11.2.3)
- Graphics card: AMD Radeon Pro Vega 48 Using OpenGL 3.0
- Thrive version: 0.5.3.1 (Most Recent)

**Logs.**
Mono: TXT files were empty 🤷🏼 
Log: [Pastebin.com](https://pastebin.com/J3rN8vjZ)

**Additional context**
It's not something critical, but it is [mildly infuriating.](https://www.reddit.com/r/mildlyinfuriating/)

Thank you, Phi.

**Comment by hhyyrylainen** [comment]
If this is *just* about the options menu, then this is a duplicate of: https://github.com/Revolutionary-Games/Thrive/issues/1829

**Comment by PhiMyth** [comment]
Alright, I'll close it as a duplicate. That other issue seems to be a deep search tho XD (this is 2162 and the one you mentioned iss 1829)

Still, Thank you.
