### ISSUE TITLE
Spamming clicking through the editor causes unreliable crash

### ISSUE THREAD

**Issue by icedjuro** [Revolutionary-Games/Thrive#2179]
Spamming the continue buttons in the editor in rapid succession (did this for speedrunning), caused the game to crash and logs state it closed normally. Don't always crash when you click through, but maybe like 10% of the time.

**Comment by hhyyrylainen** [comment]
Might this be fixed by: https://github.com/Revolutionary-Games/Thrive/pull/2232 ?

**Comment by hhyyrylainen** [comment]
I got one more person to agree with me that this is teh same as #2232 so I'll close this.
