### ISSUE TITLE
Fix line breaking in texts (need proper line breaking support)

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2192]
Right now they linebreak wherever they want, and especially in translations they are often quite silly. Something needs to be done. The optimal thing would be to have them linebreak only on spaces or if a single word is too long, then per character break.

https://github.com/Revolutionary-Games/Thrive/pull/2174#issuecomment-816708684

**Comment by RacerBG** [comment]
Linebreak on a space sounds reasonable for me. But there are quite a few languages which have a habit of making very long words, including but not limited to Bulgarian, Finnish, Hungarian, Russian and Turkish.

I believe there is not a single rule for most of the languages how to transfer a word on a new line when the limit is reached. The compromise, in my opinion, is to simply add a translation comment which should explain how many characters are allowed on a single row for the specified strings before the break occurs.

If a hard limit is made and break on a space is not possible, however, the optimal solution would be a break after/before a consonant-vowel syllable (I believe this is the most common way).

Regards,
Georgi

**Comment by hhyyrylainen** [comment]
See the discussion I linked, this could be solved by explicit line breaks in translations, however that is not currently possible because the same text is used in another context. So the explicit linebreak would break something else...

**Comment by RacerBG** [comment]
> See the discussion I linked, this could be solved by explicit line breaks in translations, however that is not currently possible because the same text is used in another context. So the explicit linebreak would break something else...

This currently leads to three options - adding a translation comment for every affected string and/or waiting for Godot 4.0, or adding different strings for the same words (in the same manner as you did for the keys) which is not very practical in my opinion.

**Comment by Kasterisk** [comment]
Should we close this now that organelle names no longer shown up front?

**Comment by hhyyrylainen** [comment]
Uhh, I wouldn't because the tooltips are affected by the same problem, so this is basically kind of a placeholder for needing proper line breaking support. There'll be plenty of places in the game where we'll need this. I just added the engine tag as I think it'd be pretty great to have the engine handle line breaking in a good way.

**Comment by hhyyrylainen** [comment]
Godot 4 added word line break mode for labels, which we can use in any case where something weird happens.
