### ISSUE TITLE
Make population graphs use longs instead of ints

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2197]
as the graphs have problems when a population number goes over the max int value.

**Comment by hhyyrylainen** [comment]
Also found out that the external effects need to also be updated to use longs: https://github.com/Revolutionary-Games/Thrive/blob/33d5740bd33d9151c38553b629352e6b42eaa064/src/auto-evo/ExternalEffect.cs#L20

**Comment by hhyyrylainen** [comment]
@Kasterisk will you work on this soon? If so could you add this back to a milestone (I've just cleared this from all).

**Comment by Kasterisk** [comment]
I think I will make one single package PR for graphs improvements soon.

**Comment by Kasterisk** [comment]
Want to point out that the graphs previously used floats not ints, I've now changed them to doubles in my graph improvements branch.

**Comment by hhyyrylainen** [comment]
Hmm interesting. Maybe doubles would be the better choice? Or how are you handling showing fractional values like the compound concentrations?

**Comment by Kasterisk** [comment]
I rounded them off to 3 digits.

**Comment by hhyyrylainen** [comment]
I guess maybe that works. I'm just a bit worried as to what we might want to use the graphs system to display in the future and whether it can handle that.
