### ISSUE TITLE
Have Cmake update CEGUI's version string on compilation

### ISSUE THREAD

**Issue by jjonj** [Revolutionary-Games/Thrive#222]
the main menu layout contains Property name="Text" value="v0.2.2"  which should be updated using the thriveversion.ver file automatically. This could probably be done using cmake and have it update during compilation.

**Comment by hhyyrylainen** [comment]
I'm going to do a startup time read of the file `thriveversion.ver` and update the GUI. 


Windows release process might need to include the version file in the future (if it doesn't already)

**Comment by hhyyrylainen** [comment]
I'm pretty sure this has been fixed for quite some time. Even if it hasn't the engine switch will at least take care of this.
