### ISSUE TITLE
Microbe forward direction gone wrong after ramming chunks

### ISSUE THREAD

**Issue by Kasterisk** [Revolutionary-Games/Thrive#2220]
Noticed that my cell starts going in the wrong direction (relative to cursor) after ramming things at sufficient speed and then seems to correct itself over time albeit very slowly. Likely caused by the angular y axis being unlocked in #2123, so I think it needs to be relocked? At least until we switched over to physics based turning, as it seems that the direct turning is still affected by the y axis rotation.

**Comment by hhyyrylainen** [comment]
This actually used to happen, even before we changed the axis lock. And people have been reporting this for the past year, so this is highly unlikely to be caused by that, instead this seems rather random. I'll try to dig up the existing issue.

**Comment by hhyyrylainen** [comment]
I couldn't find an existing issue, so maybe this was not made into an issue yet?
I'll adjust the tags as I think this is a very random and hard issue to solve and this has happened even before the changed axis locks. As we set the full rotation (I think) on the microbe body, it should *not* be possible for it to go wrong, though maybe we should set it in the physics process callback (I think there's a TODO about that) as that's the right place to fudge the values the physics computations (like velocity) are set in. This might even be a Godot bug where it thinks the rotation is up to date in the physics engine and doesn't want to update it for some reason.

**Comment by 84634E1A607A** [comment]
Locking angular Y do solve the problem? 
Or I say the three angular axis should all be locked. 
After locking the Y axis, it runs well.

I think the problem is caused by when Godot is handling the collision, it changed the Y axis angle, so later processes go wrong.

**Comment by Kasterisk** [comment]
Retested this and can confirm that locking the Y axis always keep the cell orientation correct even when dragged along chunks:

https://user-images.githubusercontent.com/54026083/118386609-db672980-b642-11eb-830b-3d042deb42e1.mp4

And this is with the axis unlocked (notice that the cell orientation is easily affected):

https://user-images.githubusercontent.com/54026083/118386656-3b5dd000-b643-11eb-9abd-5a4d64e8477e.mp4

**Comment by hhyyrylainen** [comment]
I'm still pretty certain that, as the axis lock change was done only a few months ago, this issue was reported even before that.

> Locking angular Y do solve the problem?
Or I say the three angular axis should all be locked.
After locking the Y axis, it runs well.

Can't do both that and solve this: https://github.com/Revolutionary-Games/Thrive/issues/2112

I'm tempted to say that issue #2112 needs to be solved before I accept any change regarding this issue.

**Comment by Kasterisk** [comment]
> I'm still pretty certain that, as the axis lock change was done only a few months ago, this issue was reported even before that.

Not sure but the bug is somehow happens to be more prominent in recent builds than in previous releases, so this specifically must be correlated with the axis lock change imo.

I'm concerned this could be a main source of complain for players if #2112 doesn't make it into the next update (seeing it's quite a difficult issue to tackle). Personally I recommend fixing this as a temporary workaround if that issue doesn't get fixed first.

**Comment by hhyyrylainen** [comment]
And that's with Godot 3.3? If it truly is much more common, then I suppose it needs to be accepted, though a big note should be added to the physics based turning issue so that no one wastes time on it with the axis locks being wrong.

**Comment by Kasterisk** [comment]
Yeah I tested with Godot 3.3 and at least for me it happens quite often, the inevitable accidental collision with other cells and small chunks plays a big part.
