### ISSUE TITLE
Pilus Restrictions

### ISSUE THREAD

**Issue by RacerBG** [Revolutionary-Games/Thrive#2222]
**Describe the bug**
The pilus can be placed inside the cell and could be obstruct by other parts of the cell.

**Expected behavior**
The pilus placement should not be allowed inside the body of the cell. Also, when a pilus is placed, the other cell parts should have a placement restriction according to it's heading (to avoid obstructing it).

**Screenshots**
![2021-05-08_22 19 50 8567](https://user-images.githubusercontent.com/68707872/117551025-38b01900-b04c-11eb-9e38-724f34fad6ea.png)
![2021-05-08_22 20 05 2415](https://user-images.githubusercontent.com/68707872/117551026-39e14600-b04c-11eb-9b45-eccd397a7da2.png)

Regards,
Georgi

**Comment by hhyyrylainen** [comment]
It's a known bug that sometimes the pilus or flagella rotate incorrectly: https://github.com/Revolutionary-Games/Thrive/issues/1500
as for disallowing it inside the cell, that would be a design decision that requires quite a bit of extra coding checks to make that happen, so I'll close this suggestion.
