### ISSUE TITLE
Explain in flagellum tooltip that the direction it points out of the membrane affects it

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2240]
and that it determines the thrust vector it is able to generate, so flagella on the sides of the cell only work for sideways movement, flagella at the back increase your forward speed.

can be done on the translations site

**Comment by RacerBG** [comment]
@hhyyrylainen I would like to tackle this issue myself. :smiley: 

I will make a suggestion in Weblate for fixing this issue.

**Comment by hhyyrylainen** [comment]
I did my own take on it based on your suggestion, further suggestions welcome: https://translate.revolutionarygamesstudio.com/translate/thrive/thrive-game/en/?checksum=f5530e6e66f819cf

**Comment by RacerBG** [comment]
Just one small thing which I missed: "**which use ATP**" this probably should be "**which uses ATP**" but I'm not 100% sure. Your text seems very good to me.

**Comment by hhyyrylainen** [comment]
I think the current form is right, because the "which use" refers to the earlier word "fibers" and that's plural, so that's why "use" is used instead of "uses", I think. I'm not a native English speaker either. @buckly90 did you check that part of the translation?

**Comment by buckly90** [comment]
I'm honestly not so sure myself. I personally think that both forms are arguably correct.

"The cable is a collection of steel threads that are used to reinforce the structure."
Or
"The cable is a collection of steel threads that is used to reinforce the structure."

Either way they communicate the same, as the reader naturally assumes what the are/is refers to.
