### ISSUE TITLE
Make the existing placed hex colour more distinct

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2241]
Now that the editor light problem is fixed, the colour difference between the two types of hexes (already placed when entering the editor and newly placed) is too small. The already placed hex colour should be darkened further.

**Comment by hhyyrylainen** [comment]
Related to: https://github.com/Revolutionary-Games/Thrive/issues/192

**Comment by CI09** [comment]
Is just decreasing material brightness in oldhex.material ok? Or is there anything to be done in terms of programming?

**Comment by hhyyrylainen** [comment]
Yeah, I think so (unless that exposes some unexpected issue). That's why I didn't tag this as C# and only programming.

**Comment by CI09** [comment]
![image](https://github.com/Revolutionary-Games/Thrive/assets/100433934/66ceb393-ae2a-48a9-b0e4-a8ceee74a33c)
Should I make it brighter/darker or is it fine?

**Comment by hhyyrylainen** [comment]
I think that's about right for the player to realize that there's something different about those hexes.

**Comment by CI09** [comment]
Uhm. I tried pushing local repo to my remote fork and with git GUI and it asked me for credentials for Devcenter. It used to worked just fine last time. Hmm.

**Comment by hhyyrylainen** [comment]
The material files are stored with Git LFS, see the caveat about that in the [setup instructions.](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/setup_instructions.md)

**Comment by CI09** [comment]
I didn't manage to get it working so here's instructions if someone in dev team finds time and will want to implement this
- find OldHex.material in Godot editor
- lower Albedo color value (I made it 155, 155, 155)

and that's it.

**Comment by hhyyrylainen** [comment]
I made a PR of this: https://github.com/Revolutionary-Games/Thrive/pull/4649 though based on other developer feedback I didn't make the material as dark as that.
