### ISSUE TITLE
Max Health resets to 100 (in health bar) when Player Dies

### ISSUE THREAD

**Issue by adQuid** [Revolutionary-Games/Thrive#2249]
**Describe the bug**

When a player dies, the health meter shows the default max health of 100 than whatever the player microbe had.

**To Reproduce**
1. Click the suicide button
2. Observe health meter

**Expected behavior**
Health bar should show 0 out of actual max health.

**Comment by hhyyrylainen** [comment]
Well this used to be even worse, as in: the health bar kept showing your last health even if you were dead. Now it defaults to showing 0 out of 100 (default health) when the player microbe is null.
