### ISSUE TITLE
See if changing rendering mode to multi-threaded improves things

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2273]
Currently the render mode is set to single-safe, though I think because of that we might have at least one crash: https://github.com/Revolutionary-Games/Thrive/issues/2078

So I think we should try setting the render mode to multithreaded, if it improves performance that would be a plus as well. If it doesn't break anything, I think it would be worth it to change to it anyway.

**Comment by 84634E1A607A** [comment]
I think it does improve things.

https://1drv.ms/u/s!AmQa4DeAoN8FlXnMeaXfpBmB5gnm?e=jDNssA

**Comment by 84634E1A607A** [comment]
And I haven't found any issues yet.

**Comment by hhyyrylainen** [comment]
Thanks for testing.this 
I made a PR to make it easier for other people to test this as well. On my computer I didn't notice any real FPS improvement, but I also don't think I experienced the jitter that the Godot editor tooltip warns is possible in multithreaded mode.

https://github.com/Revolutionary-Games/Thrive/pull/2301
