### ISSUE TITLE
Increase perlin noise texture size or get UV scaling math right

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2286]
If the perlin noise texture had a more localized (by it being higher resolution or UV scaling multiplier being used), the clouds could look like this:
![2021-06-01_11 26 10 4449](https://user-images.githubusercontent.com/3796411/120310234-d5c64080-c2de-11eb-9d25-5ca321287947.png)

I tried for a few hours to get the math right but I just couldn't, as I don't understand the clouds system enough. This is caused by the single background plane being moved as the player moves so the UVs need to match up when the plane is repositioned.

This starts to get the game to much closer to https://github.com/Revolutionary-Games/Thrive/issues/1701

**Comment by Kertit** [comment]
I've managed to generate a new pelrin noise I don't know if it would fit or not. 
this one is 4k 
![image](https://user-images.githubusercontent.com/35419629/232992115-ad111caa-5a2b-4502-bcf0-52170ae0a78a.png)

I can upload it wherever you need

**Comment by hhyyrylainen** [comment]
Testing it in game, potentially with code changes, is probably necessary before being able to decide if a new random texture is good. If you have Thrive ready to compile on your computer you can replace `assets/textures/PerlinNoise.jpg`
