### ISSUE TITLE
Fix colony cells sometimes becoming detached for no reason

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2310]
sometimes the cell gets detached from the colony even when it shouldn't (especially when loading a save)

**Comment by hhyyrylainen** [comment]
There's a video showing this happening in this duplicate issue: https://github.com/Revolutionary-Games/Thrive/issues/2313

Regarding the "detaching" it is only in the physics sense, the other cells are still part of the colony (they enter engulf mode when you do, and you can't re-add them to your colony). So for some reason the physics becomes detached from the colony leader, without the actual remove from colony code running so the cell is stuck in limbo where it is half part of the colony.

**Comment by Kemikal1** [comment]
I have found that if you save the game after the cell becomes detached then load that save the cell is again attached to the players cell actions.
[Detached.zip](https://github.com/Revolutionary-Games/Thrive/files/6780311/Detached.zip)
