### ISSUE TITLE
Fix non-player colony members stop moving with the colony after physical collisions

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#2313]
When the non-player colony members collide with a iron block or something (even your own pilus) sometimes it stopped moving until you detach from the colony.

https://user-images.githubusercontent.com/60734649/121772646-3b50e180-cba9-11eb-850d-449128aca272.mp4

https://user-images.githubusercontent.com/60734649/121772679-7b17c900-cba9-11eb-8007-3fcc1d7247ab.mp4

**Comment by hhyyrylainen** [comment]
This looks the same as https://github.com/Revolutionary-Games/Thrive/issues/2310 which for me happens spontaneously, nothing even needs to hit the colony members for them to become detached

**Comment by 84634E1A607A** [comment]
It's not detached. You can see when I enter Engulf mode the other cell entered too. It just stopped moving.

**Comment by 84634E1A607A** [comment]
I'll close this then.

**Comment by 84634E1A607A** [comment]
Maybe I misunderstood "detach"?

**Comment by hhyyrylainen** [comment]
I guess I wasn't clear enough, I'll add a clarification on the other issue.
