### ISSUE TITLE
Allow overriding compound name in compound bbcode tag for translations

### ISSUE THREAD

**Issue by punctdan** [Revolutionary-Games/Thrive#2325]
In Turkish grammar; if last letter of a word is a strong consonant, it usually needs to be changed into a soft consonant depending on the suffix added. This is called "Final-obstruent devoicing". I am not quite familiar with bbcode but I assume it uses fixed words which may be a problem with the kind of words mentioned above. If otherwise, please ignore this.

To give an example of the situation, take the ammonia bbcode:

[thrive:compound]ammonia[/thrive:compound]

I assume this always shows up "Amonyak" in bbcode. There are situations I need to add a suffix to write it like this "Amonyağa". As "k" is a strong consonant, it should turn into "ğ" instead. However bbcode has the "k" hardcoded (?) in the word so I can only make it look like this: "Amonyaka". This makes the grammar incorrect.

**Comment by hhyyrylainen** [comment]
That's interesting... I guess we'll need some extra bbcode handling for that. At least Finnish translation will also read a bit more naturally with the change I have in mind.
If we extend the compound bbcode tag to allow specifying an override name this should be doable. Like:
`[thrive:compound text="glukoosia"]glucose[/thrive:compound]` which would use the "something" from `text="something"` part to replace the compound name but show the right icon after it.

@Kasterisk do you think that's something that could be added to the custom bbcode handler?

**Comment by Kasterisk** [comment]
I suppose so, code probably could be adapted from Godot's bbcode implementation. Regarding the override name extension, maybe we can turn it for specifying the compound's internal name instead (maybe as `type`)? The content between the tags will then be whatever is an appropriate translation for that compound's name, this will also reduce the likelihood of the compound's internal name often being mistakenly translated as of currently. So what `[thrive:compound]` tag will do is basically is just adding a bolded font to the text and a suitable icon for the specified compound.

**Comment by hhyyrylainen** [comment]
In English text, the shorter bbcode would be preferrable to me as it avoids mistakes with calling things by incorrect name.
This would really only be needed for special cases like translations where the compound name is not suitable as-is in the current place of the sentence.

**Comment by hhyyrylainen** [comment]
I guess now that the support is in, some translation should try it out. I'm too busy with higher priority stuff to jump on this myself at the moment.
