### ISSUE TITLE
Cell Process panel (and tutorial popups) is on top of menu

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#2326]
Cell Process panel is on top of menu, making menu buttons unclickable.

To reproduce, open Cell Process menu and drag it to the middle of the screen. Then press escape, you will find the buttons unclickable.

**Comment by hhyyrylainen** [comment]
![2021-06-14_08 40 19 7171](https://user-images.githubusercontent.com/3796411/121844135-2c267c80-ccec-11eb-90f8-61403c08aab7.png)

Can confirm, the process panel being open prevents mouse click events from going to the pause menu buttons.

**Comment by 84634E1A607A** [comment]
I think ProcessPanel, CheatMenu and EditorCheatMenu should be Panel instead of WindowDialog, and maybe add custom dragging handler to it.

**Comment by hhyyrylainen** [comment]
> add custom dragging handler to it.

That's the hard part as resizing is also a feature in addition to dragging the panel around.
