### ISSUE TITLE
Add the Opening Cutscene to the game

### ISSUE THREAD

**Issue by Oliveriver** [Revolutionary-Games/Thrive#233]
Somehow this short video: https://www.youtube.com/watch?v=_4WHf1cxjmo with this soundtrack: https://www.youtube.com/watch?v=8uFhKeOGf8c should be added to the start of the game at some point before the next update. I can match up the timings to begin with, but I'll need a high quality file of the video first. Then it's simply (at least, I assume it's simply - it would surprise me if there's a lot of necessary scripting) a matter of setting the video to play before the game starts, or ideally while it loads, although that might be more difficult.

**Comment by Oliveriver** [comment]
What's the likelihood of this getting into 0.2.4? I'd assume fairly low.

**Comment by jjonj** [comment]
I'd say that there's 25% chance I could get this to work in 4 hours work. 98% chance I could get it to work in a few days worth of looking into it.
Just a priority question! I don't mind changing priorities if desired. My current priorities are 
looking into issues people have had with setting up thrive on windows, 
then the scrolling selector for organelles in editor 
and then look into adding a grid structure over entities that would make making better AI easier..
