### ISSUE TITLE
MICROBE_STAGE_UNBIND_TEXT use bbcode

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#2334]
Should the "unbind all key" in MICROBE_STAGE_UNBIND_TEXT use bbcode instead?

**Comment by hhyyrylainen** [comment]
Only the organelle processes description tooltip supports bbcode at this point, so the text would just show the bbcode without handling it. There's already an issue for bbcode to be added to be supported in the help menu: https://github.com/Revolutionary-Games/Thrive/issues/2250
