### ISSUE TITLE
Crash when deleting other organelles and then moving the nucleus

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2340]
I seem to sometimes be able to get a crash when trying to move the nucleus after deleting (and moving) other organelles to be left with less than 5 MP. Callstack seems to be the same as: https://github.com/Revolutionary-Games/Thrive/issues/1961
so fixing that might also fix this

**Comment by Kemikal1** [comment]
Seems to happen only to cytoplasms-nucleus interaction in freeBuilder.Didnt get this crash when i moved nucleus then other organells.
Move nucleus,
Move all cytoplasms
Crash

Same callstack too.
