### ISSUE TITLE
Flooded "Invalid new child position" in process panel with all organelles

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#2351]
**Describe the bug**

```
E 0:01:13.464   move_child: Invalid new child position: 9.
  <C++ Error>   Index p_pos = 9 is out of bounds (data.children.size() + 1 = 8).
  <C++ Source>  scene/main/node.cpp:330 @ move_child()
  <Stack Trace> :0 @ void Godot.NativeCalls.godot_icall_2_583(IntPtr , IntPtr , IntPtr , Int32 )()
                Node.cs:811 @ void Godot.Node.MoveChild(Godot.Node , Int32 )()
                ChildObjectCache.cs:94 @ void ChildObjectCache`2[[IProcessDisplayInfo, Thrive, Version=0.5.4.0, Culture=neutral, PublicKeyToken=null],[ChemicalEquation, Thrive, Version=0.5.4.0, Culture=neutral, PublicKeyToken=null]].ApplyOrder()()
                ProcessList.cs:54 @ void ProcessList._Process(Single )()
```

**To Reproduce**
Currently if you add all organelles (nucleusless) one each and open Process List panel you'll get a flooded exception above.

**Additional Info**
![image](https://user-images.githubusercontent.com/60734649/122632939-689d1280-d108-11eb-80fc-a4784b677381.png)
![image](https://user-images.githubusercontent.com/60734649/122632942-7357a780-d108-11eb-9b7d-50694d8f1bee.png)

I'm investigating into this. Currently I can tell that this happens each frame when _Process() gets called.

**Comment by 84634E1A607A** [comment]
Okay. We can see that ```ProcessesToShow``` list have 11 children but only represents 8 processes.
![image](https://user-images.githubusercontent.com/60734649/122633115-7a32ea00-d109-11eb-8531-ffc1a4e6502c.png)

There's repeated processes.
![image](https://user-images.githubusercontent.com/60734649/122633183-bbc39500-d109-11eb-877a-5858ca788623.png)
![image](https://user-images.githubusercontent.com/60734649/122633187-c0884900-d109-11eb-9ab1-a4d1fc6a3fbf.png)
![image](https://user-images.githubusercontent.com/60734649/122633191-c7af5700-d109-11eb-8f5a-d883e1246a72.png)
![image](https://user-images.githubusercontent.com/60734649/122633196-cd0ca180-d109-11eb-9bb0-366eff0c97c0.png)

These should be merged.

**Comment by 84634E1A607A** [comment]
![image](https://user-images.githubusercontent.com/60734649/122633342-b87cd900-d10a-11eb-8b1a-2c4483256f7f.png)
![image](https://user-images.githubusercontent.com/60734649/122633346-bd418d00-d10a-11eb-9ec6-d8c57801e45f.png)
and Nitrogenase, Oxytoxisome

These four organelles all can do glycolysis so there are 4 same processes

**Comment by hhyyrylainen** [comment]
Could you provide a save file where this problem can be seen? You can zip it up and attach it to this issue.

**Comment by 84634E1A607A** [comment]
[Save_All_Organelles.thrivesave.gz](https://github.com/Revolutionary-Games/Thrive/files/6680240/Save_All_Organelles.thrivesave.gz)
Here. (I assume the .thrivesave is the same as .gz)

**Comment by hhyyrylainen** [comment]
Well internally they are .tar.gz files, but the game won't load the file unless it is renamed to .thrivesave

**Comment by 84634E1A607A** [comment]
Anyway. As github won't allow uploading of .thrivesave file I renamed it.

**Comment by hhyyrylainen** [comment]
I said "zip it up" meaning that you could put the .thrivesave file inside a .zip and upload that, then it is just a matter of extracting the .thrivesave to the right folder from the zip.

**Comment by 84634E1A607A** [comment]
Uh...

**Comment by 84634E1A607A** [comment]
[Save_All_Organelles.zip](https://github.com/Revolutionary-Games/Thrive/files/6680267/Save_All_Organelles.zip)

**Comment by hhyyrylainen** [comment]
Can confirm the bug happens if you load that save, and then open the process panel.
