### ISSUE TITLE
Make ESC go back to the main menu when options or load menu is opened from the main menu

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#2352]
Currently in options menu / load game menu you cannot even press esc to go back to the main menu. Inconvenient.

**Comment by hhyyrylainen** [comment]
Do you mean if you are in the main menu, and from there go to the options menu?
During gameplay the pause menu closes with ESC even if you are in options menu.

I don't think I've ever experienced a game where this thing worked, so this would be lowest possible priority to fix.

**Comment by 84634E1A607A** [comment]
From Main Menu click "Load Game" and you have to click "Back" to go back

**Comment by hhyyrylainen** [comment]
Do you know of a game where that *would* work?
I'll accept this as a potential feature, but working on this should be very low priority.

**Comment by 84634E1A607A** [comment]
Minecraft then...

**Comment by hhyyrylainen** [comment]
I guess it might be pretty common, then. I tested 2 games where one of them exited the options with ESC.
