### ISSUE TITLE
Pressing space or enter during the microbe intro causes it to restart

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2356]
Looks like the GUI button or whatever stays selected during the cutscene, so when you press space the button is pressed again and the cutscene restarts (for me it restarts, another person reported that the game gets stuck instead).

**Comment by punctdan** [comment]
This happened to me when pressing Enter. After pressing the button more than twice, the cutscene slowed down significantly and got frozen on the screen. I thought the game was completely frozen so I tried to use Windows key where I got a flash of gameplay scene on the screen. After pressing this key some more along with Esc, I was able to pass the cutscene screen. The game was apparently in gameplay scene even before it appeared on the screen. I was able to notice changes in cursor when I pressed Esc meaning that the scene was loaded and it opened Pause Menu where the cursor was changing to different icon around the menu borders.
