### ISSUE TITLE
Make population count use a 64 bit variable

### ISSUE THREAD

**Issue by FuJa0815** [Revolutionary-Games/Thrive#2358]
The population count should use `long` instead of `int`. 2147483648 is a realistic population count that the player can reach, as seen in this screenshot taken from the community discord: 
![grafik](https://user-images.githubusercontent.com/30809803/122655546-61e7bd00-d153-11eb-8b03-39600e0e1fb7.png)

**Comment by hhyyrylainen** [comment]
The population number is already a long, there's an existing issue about the graphs (and external effects) being wrong: https://github.com/Revolutionary-Games/Thrive/issues/2197

**Comment by FuJa0815** [comment]
whoops, should have checked the code first 😅
