### ISSUE TITLE
Shown key bindings in tooltips don't immediately update

### ISSUE THREAD

**Issue by RacerBG** [Revolutionary-Games/Thrive#2361]
**Describe the bug**
When you change a key binding in the Inputs menu, the tooltips are not immediately updated. You need to restart the game for the changes to take effect.

**To Reproduce**
1. Change a key binding which is included in a tooltip (shoot a toxin, binding mode, unbind).
2. Save the changes.
3. Go to the tooltip - it will display the old key binding.

**Expected behavior**
The key bindings in the tooltips should be updated immediately after a change is detected from the Inputs menu.

**Comment by hhyyrylainen** [comment]
This will be harder to handle than language change immediately applying to tooltips.
Probably need to have some kind of custom event handler for sending program-wide events (in this case, keybindings updated) which the bbcode supporting GUI nodes need to listen for and refresh their content.
