### ISSUE TITLE
ATP can sometimes be shown to be above the storage limit

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2367]
maybe linked to low FPS as with the same save where this shows up this doesn't happen on my computer.

![screenshot](https://cdn.discordapp.com/attachments/228300288023461893/856178679183704104/2021-06-20_17.27.21.5826.png)

Save file: [max_atp_problem.zip](https://github.com/Revolutionary-Games/Thrive/files/6682601/max_atp_problem.zip)

**Comment by Kasterisk** [comment]
This should now be fixed by #2333 as the atp amount is no longer rounded to the greatest integer.
