### ISSUE TITLE
Make language locales only need loading once the options menu is visible

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2368]
as a follow up to https://github.com/Revolutionary-Games/Thrive/pull/2354
I realized that basically it needs to be converted to use Lazy<T> and only loading the options button content when becoming visible initially. This is to make debugging easier as the language loading process throws a bunch of exceptions, so in a debugger turning on breaking on caught exceptions causes annoyance when debugging.

**Comment by Kemikal1** [comment]
So  basically revert #2354 and add the Lazy class to languages right?

**Comment by hhyyrylainen** [comment]
Not exactly because that wouldn't solve the problem. As when the OptionsMenu class is created it calls `LoadLanguages` in `_Ready` meaning that using just Lazy will be useless.
Instead LoadLanguages needs to be changed to be called when the options first becomes visible, and the variable needs to be of type `Lazy<List<string>>`.

**Comment by Kemikal1** [comment]
Isnt _ready called when options becomes visible?Because _ready is called when entering the scene tree?

**Comment by hhyyrylainen** [comment]
The options is a child node of the main menu and pause menus, meaning that _Ready for it is called way before it becomes visible (and sometimes the options never become visible even though _Ready was called).

**Comment by Kemikal1** [comment]
So its revert #2354 then call the function when option is visible.Got it.

**Comment by hhyyrylainen** [comment]
No that doesn't need to be reverted. Only the static field needs to change type, and the property needs a slight tweak.
