### ISSUE TITLE
Add a section in the options menu saying the current used GPU

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2373]
this will help users to see if they are using integrated graphics or not.

Can be queried from the VisualServer:
https://docs.godotengine.org/fi/stable/classes/class_visualserver.html#class-visualserver-method-get-video-adapter-name

Also would be nice to show the current used video memory and used renderer

https://docs.godotengine.org/fi/stable/classes/class_visualserver.html#class-visualserver-method-get-render-info

`OS.GetCurrentVideoDriver()`

**Comment by nle244** [comment]
I would like to work on this.

**Comment by nle244** [comment]
![image](https://user-images.githubusercontent.com/78895941/123528842-d9f83a80-d69f-11eb-908e-f01f9eeee897.png)

Is this what you had in mind? Also, I'm not sure I'm interpreting the video memory used correctly. By default it returns some really long number so I just divided by 1,000,000 and assumed that was MB. If everything looks good I will submit the pull request, thanks!

**Comment by hhyyrylainen** [comment]
It looks mostly correct, you can open a PR (though, you may have some Godot's automatically broken styling going on). The memory is probably in bytes so it needs to be divided by `Constants.MEBIBYTE`. And the "driver" is actually the used renderer and not any kind of info about the video driver...

**Comment by Kasterisk** [comment]
This may not actually be possible now due to https://github.com/godotengine/godot/issues/36402.

**Comment by hhyyrylainen** [comment]
Well we can turn off the multithreaded rendering, it doesn't seem to help at all, and if it causes problems we can do without it (hopefully the situation is improved for Godot 4.0's vulkan renderer).

**Comment by Kasterisk** [comment]
On my laptop at least it doesn't seem to help with the FPS and I do think the multithreaded rendering is actually the main cause of the frequent `!GDMonoUtils::is_thread_attached()` crash as I never got that before the option is enabled. This may just be me but turning off multithread also speeds up my saves loading for some reason.
