### ISSUE TITLE
Add an option to select the sound output device

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2374]
At least Godot let's us list the audio devices: https://docs.godotengine.org/fi/stable/classes/class_os.html?highlight=get_current_video_driver#class-os-method-get-audio-driver-name

would be nice to show that in the options menu and if possible allow the user to select the sound output device in the game.

**Comment by FuJa0815** [comment]
It seems like the `get_audio_driver_` methods are not the output devices but actually the audio drivers. For me this returns three drivers: PulseAudio, ALSA and Dummy. Can somebody check with a windows device?

**Comment by FuJa0815** [comment]
https://godotengine.org/asset-library/asset/525

**Comment by TomDev03** [comment]
@FuJa0815 In my case I test and appear 2 options and for I know it's my audio outputs that I have. Im on windows like you want. I change the default one and played all of the 2 options. Sorry if Im not on the right place. Only try to help
