### ISSUE TITLE
Reduce the AI spinning around while stationary

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2378]
It seems the new AI spins around while not moving, way too much, it should be reduced.

**Comment by adQuid** [comment]
Based on my previous experience working with AI, that style of spinning is the result a microbe being on top of the point it wants to move to. Making the microbe code stop moving once they reach it should stop the spinning from happening.

If we watch all the spinning from this video, however: https://www.youtube.com/watch?v=AFThdbmTG4Q&t=1291s it seems like most of the spinning microbes were attempting to engulf a chunk, which to me suggests there's an issue with the AI thinking a chunk is somewhere it's not.

**Comment by hhyyrylainen** [comment]
I didn't change the AI chunk position code to use global transform as it shouldn't be necessary. The previous AI code worked fine regarding finding real chunks...
