### ISSUE TITLE
Amend allowed list of abbreviations to styleguide

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2392]
Right now the styleguide prohibits abbreviations, but in fact we use a few in Thrive, these should be mentioned as the only allowed abbreviations:
- min
- max
- pos
- rect (when variable holds a class that has Rect in the name, also allowed in class names to make such classes)

And maybe some others if they are commonly already in use in the source code.

**Comment by Maxonovien** [comment]
When coming to spawner, there is an RadiusSqr (for squared) that occurs sometimes. It is also fully written in other parts, so I don't know if this should be added as allowed or refactored.
