### ISSUE TITLE
Freebuild editor

### ISSUE THREAD

**Issue by Moopli** [Revolutionary-Games/Thrive#240]
Background:
Editors have two uses in Thrive:
1. When accessed from a particular playthrough, an editor will edit some feature that forms part of that playthrough's state (eg, the structure of your microbe in Microbe stage, or the design of a weapon in Industrial), and thus the data pertaining to the modified feature has to be sent back and incorporated into that playthrough's state.
2. When accessed from the main menu, an editor should provide the user with the ability to make anything they want -- create fantastical creatures, epic (and very expensive) spaceships, etc. These creations, obviously, can't simply be loaded into a regular game.

To do this, we need a bunch of changes:
- Our save-game semantics change up a bit -- "creations" (eg, .*.microbe) are the things that can be looked at and fiddled with in the main-menu-accessed editors. So, if say you wanted to turn your creation into a piece of abstract art, you could load it in the main-menu-accessed editor, and twiddle to your heart's content.

In MainMenu->Editor:
- No mutation point accounting -- or, we instead track the point cost of the microbe. Understandably, the first is much easier than the second
- Every time you start it, it contains the default starter microbe, not the current microbe of the current game -- and of course, it can't change the current microbe either
- All organelles available

In Stage->Editor:
- Cannot load microbes

This issue probably wants to wait until the Microbe Editor <-> Stage data-passing has been completely redone.

**Comment by Alex-the-666** [comment]
the mutation point counter should have an infinity sign when accessed through the main menu.

**Comment by AwesomeSiebren** [comment]
This could be done using a global variable.
When in the game, this variable would be something else than when you are in the main menu, and all that is left would be an if function to change some of the editor.

**Comment by jjonj** [comment]
Yep I was thinking something simply like a global variable as well. A cleaner solution would be the player data construct that is built to maintain information across gamestates.

**Comment by AwesomeSiebren** [comment]
I'm busy setting everything up, and am by no means a pro.
But I ill at least take a look!

**Comment by jjonj** [comment]
Sure! Hit me up with any questions/obstacles! (Preferably by skype: jjonjex if you want fast replies)

**Comment by AwesomeSiebren** [comment]
Well, I do have a problem with setting CMake up, but posted it on the forums.

**Comment by AwesomeSiebren** [comment]
When I get it working, I will start.

**Comment by Alex-the-666** [comment]
I made a mock-up of the Infinity sign thing on my mock-up GUI:
[URL=http://s1290.photobucket.com/user/Alexthe666/media/ThrivePic1_zpsb25ff3de.png.html][IMG]http://i1290.photobucket.com/albums/b533/Alexthe666/ThrivePic1_zpsb25ff3de.png[/IMG][/URL]

**Comment by Moopli** [comment]
@AwesomeSiebren, is the code on your fork?

**Comment by AwesomeSiebren** [comment]
I am still figuring things out.
I can atleast view and change the code already, so the rest will come in time.

**Comment by Moopli** [comment]
I've been working on improving documentation, as I want to make Thrive a very newbie-friendly project; so whenever you have a question about the code, or about developing in general, feel free to ask.

**Comment by AwesomeSiebren** [comment]
Will do.

**Comment by AwesomeSiebren** [comment]
I will keep on trying, but I really am very slow.
I think that somebody else should pick this up if it needs to be done fast.

**Comment by Untrustedlife** [comment]
Assigned myself to it, unless AwesomeSiebren has something to say about it.

**Comment by Untrustedlife** [comment]
Looking at this issue, I will try to get all the stuff in it as stated done. SO next thing up, it needs to use the default microbe......

**Comment by Untrustedlife** [comment]
This is my next project.

**Comment by MontySpud** [comment]
I got the basic code for it done. you can currently build to your hearts content!

**Comment by TheCreator--** [comment]
Is the free editor under tools?

**Comment by MontySpud** [comment]
Editor Button currently

**Comment by hhyyrylainen** [comment]
This should really get merged at some point. 
I think this was planned to be in 0.3.3 but maybe we can get this in 0.3.4?

**Comment by hhyyrylainen** [comment]
@Untrustedlife I think this was the original issue about the freebuild editor

**Comment by Untrustedlife** [comment]
Yeah it was, the reason i asked you to delete that branch was because the way me and montyspud implemented it it was a mess, we are better off just rewriting it from scratch heh.

**Comment by Untrustedlife** [comment]
I feel bad for nuking my own and @MontySpud 's work but i think it was necessary. Like a phoenix it will rise brighter lol.

**Comment by Untrustedlife** [comment]
Will be nice to get this re-implemented

**Comment by TjWhale** [comment]
I had a couple of thoughts about this. When we have multiple patches the first part should be going to the patch screen and selecting any patch to start in. Then proceeding to the editor it might be easier from a programming perspective just to offer a very large amount of MP (like 10,000) rather than unlimited, not sure if that's easier and the result would be the same.
