### ISSUE TITLE
Fix flagella draining atp when visually inactive

### ISSUE THREAD

**Issue by Maxonovien** [Revolutionary-Games/Thrive#2406]
When having multiple flagella, with only one visually (and normally) active, for a build able to sustain it (from the editor charts), the atp still decreases.

Further tests highlighted that this could occur for flagella colinearly and (especially) diagonally opposed to the movement.
This occurs even when flagella are placed with valid editor rotation, although it seems more to be in see-saw (major drop then atp rises again).

Perhaps comes from proportional reduction of flagella? 

Perhaps related to #1500 and #1297 . 
_____
Screens from initial, replicated report

One flagella sustainability
![image](https://user-images.githubusercontent.com/16361817/125493370-fe3cf92e-cfad-4eac-bb92-aa6de4f55948.png)

Final design 
![image](https://user-images.githubusercontent.com/16361817/125493607-151f174a-19ec-40ae-85bd-9cfe997b8024.png)

Replication with one opposed flagella

![image](https://user-images.githubusercontent.com/16361817/125495423-85af86b5-8bb4-486c-a1b7-37b37547dc0c.png)

**Comment by hhyyrylainen** [comment]
Probably related to not those orientation issues as those are like visual bugs. Sound to me like for some reason for ATP draining calculation the flagella pointing in is still taking ATP even when the flagellum doesn't activate...

**Comment by Maxonovien** [comment]
I think they are probably unrelated (as I reported, this occurs even under normal circumstances; see last screenshot), but there might be some other additional unintended effect coming along.

**Comment by Kemikal1** [comment]
Not related to those issues u said. Since im working on them and i tested it on my branch where theyre fixed
