### ISSUE TITLE
Implement Tooltips

### ISSUE THREAD

**Issue by Moopli** [Revolutionary-Games/Thrive#241]
CEGUI supports tooltips, and we need them. I believe it can be done entirely through XML.

**Comment by Untrustedlife** [comment]
Note , in microbe editor, we should not only tell of the use for the organelles in game, but also some little interesting scientific tidbits

**Comment by jjonj** [comment]
Should be really simple with http://cegui.org.uk/wiki/Tooltips but it's causing some really strange bugs when changing gamestates and just aren't working anyway, hrmm..

**Comment by jjonj** [comment]
I managed to work around the strange bug, but I still need to figure out why the tooltips still aren't showing.

**Comment by jjonj** [comment]
Implemented with  5aea2a4
