### ISSUE TITLE
Game crash on moving object

### ISSUE THREAD

**Issue by TheNamesGregoryAndounuts** [Revolutionary-Games/Thrive#2430]
**Describe the bug**

I was editing my cell and selected move part when the game suddenly closed. I'm not sure what happened, but I could have something to do with having the chloroplast selected at the time

**To Reproduce**
Steps to reproduce the behavior (Requires your cell you be eukaryotic):
1. Go to cell editor
2. Place down one of those do-hykies that converts ATP to amonia
3. Select the chrolorplast on the right hand menu
4. Right click the  one of those do-hykies that converts ATP to amonia (Someone please remind me what the correct name for one of those) and click move

**Expected behavior**
I expected to be able to move the nitrogenaise(?) to the part of the cell I wanted.

**Screenshots**

**System info (please complete the following information):**
- OS: Windows 10
- Thrive version 0.5.4

**Logs**

[Thrive Crash log.txt](https://github.com/Revolutionary-Games/Thrive/files/6855714/Thrive.Crash.log.txt)

**Comment by hhyyrylainen** [comment]
I see `SceneDisplayer.LoadNewScene` in the crash callstack. So I think this is the same issue as: https://github.com/Revolutionary-Games/Thrive/issues/2340 which is already fixed on the master branch by this PR: https://github.com/Revolutionary-Games/Thrive/pull/2369
