### ISSUE TITLE
Save Error

### ISSUE THREAD

**Issue by levovix0** [Revolutionary-Games/Thrive#2431]
**To Reproduce**
Just play

**System info:**
- OS: Manjaro Linux KDE
- Graphics card: Radeon RX 5500 XT
- Thrive version: 0.5.4.0

[**log.txt**](https://pastebin.com/yrP82Tkj)
 ```
Ошибка сохранения - Сохранение неудалось! Случается в исключительных ситуациях exception:
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'PlacedOrganelle'.
  at Godot.Object.GetPtr (Godot.Object instance) [0x0001c] in <d080c72c5ee74f9f83d512ce6c36aa56>:0
  at Godot.Spatial.GetTransform () [0x00000] in <d080c72c5ee74f9f83d512ce6c36aa56>:0 
  ...
```

**Comment by hhyyrylainen** [comment]
I suspect that this is the same issue as: https://github.com/Revolutionary-Games/Thrive/issues/2128
Without save debug mode it's not possible to tell from the stacktrace even if this was a different issue: https://github.com/Revolutionary-Games/Thrive/issues/2127
