### ISSUE TITLE
Compound balances display doesn't update on language change

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2433]
Just noticed that when changing languages the numbers in compound balances display doesn't update.

Here I switched to Finnish while in the editor but the decimal separator didn't change:
![2021-07-22_18 22 24 6129](https://user-images.githubusercontent.com/3796411/126665023-3606fadc-d591-4fcf-9619-ec2a3f1f12db.png)

Here I exited the editor and immediately re-entered, which has fixed the number format:
![2021-07-22_18 22 32 1166](https://user-images.githubusercontent.com/3796411/126665041-4b4ac28e-fbab-4ec9-ad75-2ed0b3443394.png)

**Comment by Kasterisk** [comment]
Just need UpdateLabel call on translation changed notification in CompoundAmount.
