### ISSUE TITLE
Write wiki page on the compounds bbcode

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2435]
and then notify all the translators on weblate. I can do the notifiying, but I'd appreciate if someone else on the team could write that new text here: https://wiki.revolutionarygamesstudio.com/wiki/Translation_Guidelines with included examples

**Comment by Kasterisk** [comment]
I've now tweaked and added additional bits of information to the bbcode translation guidelines https://wiki.revolutionarygamesstudio.com/wiki/Translation_Guidelines#BBCode.

**Comment by hhyyrylainen** [comment]
Fixed one typo I noticed. Other than that I think it looks good enough to consider this done.
