### ISSUE TITLE
Cheats menu should be positioned slightly lower

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2436]
in order to not overlap with the new patch name location text

**Comment by rickthepat05** [comment]
Hello, is this issue still available? I'm interested in this project and want to start contributing to things on Github. Based on the labels, this seems like a good place to get started. Could I be assigned this task, if possible?

**Comment by hhyyrylainen** [comment]
Hi, yeah this is still available, no one is working on this. I've assigned you to this issue. 
Most of the time I remember to check that PRs mark which issues they close, so if someone was working on this issue there would be an event shown on this page that a PR links here.

**Comment by rickthepat05** [comment]
Cool, thanks.

**Comment by hhyyrylainen** [comment]
Actually now that I did some playtesting for the next release I realized that this is no longer required as we removed the patch name always being on screen and only having that big fade in and out name when changing patches.
