### ISSUE TITLE
Grid Behind in Microbe Editor

### ISSUE THREAD

**Issue by Alex-the-666** [Revolutionary-Games/Thrive#244]
A grid should be displayed behind the microbe editor o show a basic outline of where the player can place hexagons. Oliverriver has a video similar to what I am asking:
https://www.youtube.com/watch?v=4c-4sJRDbwk
I hope you can all see it.

**Comment by Moopli** [comment]
This idea's so good it's already been implemented!

**Comment by Alex-the-666** [comment]
sorry, I didn't see them :)

**Comment by Moopli** [comment]
I can hardly complain, I'm guilty of duplicating issues too, due to [forgetting to search](https://github.com/Revolutionary-Games/Thrive/issues?q=is%3Aissue+editor+grid).
