### ISSUE TITLE
Screen shot compatibilty

### ISSUE THREAD

**Issue by Alex-the-666** [Revolutionary-Games/Thrive#245]
when I try to take a screenshot(using PrtSc and the windows button) it is unable to capture an image of the game window, only the console behind and my desktop.

**Comment by AwesomeSiebren** [comment]
Another possibility would be to make a screenshot feature into the game itself.

**Comment by Alex-the-666** [comment]
yes, kinda like Minecraft.

**Comment by jjonj** [comment]
By running in windows mode you can take screenshots, at least I and others can, but yes we will eventually want an in-game screenshot feature :) Shouldn't be too difficult, but it is also a very low priority!

**Comment by Alex-the-666** [comment]
how do you run in windows mode, Ive looked for an option and cant find one.

**Comment by jjonj** [comment]
delete ogre.cfg inside your bin directory and then restart the game. You will then get the ogre graphic settings window where you can toggle fullscreen!
