### ISSUE TITLE
The "Add current color as preset" tooltip is black

### ISSUE THREAD

**Issue by FuJa0815** [Revolutionary-Games/Thrive#2456]
**Describe the bug**

When hovering over the + button on the colour selector the tooltip is barley visible

**Screenshots**
![tooltip](https://user-images.githubusercontent.com/30809803/127737833-af2f3ac7-a589-4a03-99e4-b795c4573172.png)

**Comment by hhyyrylainen** [comment]
That's likely because it is the inbuilt Godot tooltip, and the tweaked colour picker scene is missing the tooltip font colour theme part.
