### ISSUE TITLE
Resurrection of species in the population graph

### ISSUE THREAD

**Issue by FuJa0815** [Revolutionary-Games/Thrive#2457]
**Describe the bug**

I have experianced

**To Reproduce**
1. Start a new game
2. Periodically go to the editor and back ingame
3. be lucky. I have managed to reproduce it a few times

**Screenshots**
![extinction](https://user-images.githubusercontent.com/30809803/127738075-2a595dd3-6bb6-4183-8641-aa36400ee7fb.png)

**Logs**
The logs contains those significant lines (Ebilia Vemia is the species in the screenshot):
```
Species Ebilia Vemia has gone extinct in Pangonian Sea Floor
Species Ebilia Vemia has gone extinct in Pangonian Vents
Species Ebilia Vemia has gone extinct in Pangonian Sea Floor
```
[log.txt](https://github.com/Revolutionary-Games/Thrive/files/6911075/log.txt)

**Comment by Maxonovien** [comment]
The thing is, the population went only extinct in the patch but not overall, so it migrated back to your patch. 
This is a known issue #2131 , with an open PR  #2427 aiming at fixing it.

**Comment by Kasterisk** [comment]
Yeah, this is a long known issue. Closing as a duplicate.
