### ISSUE TITLE
Make check_formatting.rb remove trailing space in `# ` in locale files

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#2467]
> The .po starting comments include one line that is `# ` though it seems that sometimes the 
> space after `#` is automatically removed. I'm not sure what causes that, so I've just let that be.
> _Originally posted by @hhyyrylainen in https://github.com/Revolutionary-Games/Thrive/issues/2459#issuecomment-894018838_

I can't! Every time I use update_localization.rb I have to manually delete all those trailing spaces! Pls make it automatic.

(Along with starting with BOM, I really don't know how I can manually add BOM to files)

**Comment by hhyyrylainen** [comment]
I mean it doesn't do so on my computer. Even with the working formatting checks I have no issue.
If someone wants to improve the script so that it removes those trailing spaces automatically (but complains about them once so that CI will fail with them present), they are free to do so.
