### ISSUE TITLE
Create a CEGUI window that functions as an interactable scrollable series of images

### ISSUE THREAD

**Issue by jjonj** [Revolutionary-Games/Thrive#247]
This is to be used by the organelles in the editor

**Comment by Alex-the-666** [comment]
So, kinda like this?
[IMG]http://i43.tinypic.com/29w1erl.png[/IMG]

**Comment by jjonj** [comment]
Yeah kinda! I was thinking of just having a single row that scrolls horizontally but perhaps it would be good to support multiple lines! I'll see how difficult that is

**Comment by Moopli** [comment]
I don't think it would be a good idea to have the organelle-picker absorb too much screen space -- if it expands horizontally when in use, it *has* to get out of the way easily. And it has to scroll vertically, given that we've already allocated the column on the right of the screen for organelles.

**Comment by Oliveriver** [comment]
This thread page has the sort of design we're going for: http://thrivegame.forum-free.ca/t1323p90-microbe-gui-finalisation#30434

**Comment by jjonj** [comment]
Right-o! Vertical scrolling should be even easier!

**Comment by Alex-the-666** [comment]
unable to post on the tread, but heres this design, if you want it.
http://s1290.photobucket.com/user/Alexthe666/media/ThrivePic1_zpsb25ff3de.png.html?o=0

**Comment by Moopli** [comment]
It doesn't have to be a wheel, and in fact a wheel might be worse, since it bulks up the design for no reason. Stick to having the buttons scroll along a vertical line; maybe going transparent as they reach the ends or something.

**Comment by jjonj** [comment]
alright!

**Comment by jjonj** [comment]
fixed with #265
