### ISSUE TITLE
Crash on player duplication

### ISSUE THREAD

**Issue by Maxonovien** [Revolutionary-Games/Thrive#2470]
**Describe the bug**

The games crashes sometimes upon clicking player duplication cheat button.

**To Reproduce**
Steps to reproduce this bug:
1. Open the attached save in game
2. Open cheat menu
3. Click "duplicate player"

This crash is not systematic (1 in 10 trials perhaps?). I launched the game again to reproduce, but perhaps can you simply reload the save.

**System info (please complete the following information):**
- OS: Windows 10
- Graphics card (you can find this in the game logs): GeForce MX150/PCIe/SSE2
- Thrive version up-to-date master branch

**Logs**

Likely most relevant part
```
Unhandled Exception:
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Microbe'.
...
at Godot.Spatial.get_Translation () [0x00001] in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/Spatial.cs:61
  at Microbe.ForceDivide () [0x00018] in D:\Maxime\Documents\Projets\Jeux\Thrive\Thrive\src\microbe_stage\Microbe.cs:1019
  at Microbe.OnPlayerDuplicationCheat (System.Object sender, System.EventArgs e)
...
```
Full logs
https://pastebin.com/8MrzdwGF

**Game save**
[Yeah.zip](https://github.com/Revolutionary-Games/Thrive/files/6949537/Yeah.zip)

**Comment by hhyyrylainen** [comment]
If this *only* happens when using the cheat, then this is a pretty low priority issue and I've assigned this as such.
