### ISSUE TITLE
Arrow key keybindings don't work for movement

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2472]
It seems that at some point they have broken, and they are even part of the default keybindings. Perhaps with changes to the input system.

**Comment by skyace65** [comment]
Just tested this out and confirmed this. Also It looks like the game recognizes that the keys are being pressed, but for whatever reason it's not moving. If you play with the tutorial you can see the movement icons recognize that you're pressing the arrow keys.

**Comment by skyace65** [comment]
I added some prints to the MicrobeMovement.cs file

```
            {
                moveLeftTime += delta;
                GD.Print("Moving left");
                GD.Print(moveLeftTime += delta);
            }
```
it's printing when using the arrow key, and the value for moveLeftTime is changing.

**Comment by hhyyrylainen** [comment]
MicorbeMovement.cs (at least the file in src/tutorial/microbe_stage/MicrobeMovement.cs) is for the tutorial. The actual player movement happens here:
https://github.com/Revolutionary-Games/Thrive/blob/e1c699f81bb0dff2ace69d8fd4a0ca0a48c08ec5/src/microbe_stage/PlayerMicrobeInput.cs#L39

something probably has broken regarding the new input system axes handling with arrow keys.
