### ISSUE TITLE
Zero-sided texture surface

### ISSUE THREAD

**Issue by Moopli** [Revolutionary-Games/Thrive#248]
http://thrivegame.forum-free.ca/t1403p465-miscellaneous-bugs-and-questions-that-don-t-deserve-their-own-thread-thread#31528

I vaguely recall seeing this before, may be a dup.

**Comment by jjonj** [comment]
Hrrm, I don't recall seeing that one before

**Comment by ptkato** [comment]
What's the hardware requirements of the game? I suspect that might be the graphic chipset.

**Comment by jjonj** [comment]
We don't have any official requirements, but yeah it could be some unsupported feature on older hardware

**Comment by hhyyrylainen** [comment]
As the new engine needs opengl 3.3 hopefully this is fixed by the game simply refusing to run or being completely broken. (The requirements of windows 7 (or almost any modern linux) and opengl 3.3+ should be added somewhere)
