### ISSUE TITLE
Pressing Esc while loading pauses loading

### ISSUE THREAD

**Issue by FuJa0815** [Revolutionary-Games/Thrive#2501]
**Describe the bug**

When in the loading screen you can press Esc and the text won't update anymore. Pressing Esc resumes the text updating. While in this Esc state the game won't finish loading until you end this buggy state via pressing Esc again.

**Comment by hhyyrylainen** [comment]
Sounds like ESC is for some reason able to set the game to paused state, and the load operation then seems to rely on running update steps only when the game is not paused.
