### ISSUE TITLE
Write the flavour text and better brief description for the pilus

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2507]
The pilus is one of the newer organelles, as such it doesn't have a scientific background flavour text and the short description at the top of the tooltip is also very brief.
Those should be added and improved on.

**Comment by RacerBG** [comment]
If approved those suggestions will close this issue:

https://translate.revolutionarygamesstudio.com/translate/thrive/thrive-game/en/?q=pilus&sort_by=-priority%2Cposition&offset=3

https://translate.revolutionarygamesstudio.com/translate/thrive/thrive-game/en/?q=pilus&sort_by=-priority%2Cposition&offset=1

> Can be used to stab the other cells or to defend against their toxins.

**Comment by hhyyrylainen** [comment]
I totally forgot to close this issue when the pilus flavour text was written...

**Comment by RacerBG** [comment]
> I totally forgot to close this issue when the pilus flavour text was written...

No worries, I'm in the mood to close old issues today. :smile:
