### ISSUE TITLE
Duplicate player cheat doesn't work after being in the editor once

### ISSUE THREAD

**Issue by Kasterisk** [Revolutionary-Games/Thrive#2519]
Just found that it no longer spawns a player cell clone.

**Comment by hhyyrylainen** [comment]
Works for me? Starting a new game on my branch (https://github.com/Revolutionary-Games/Thrive/pull/2516) and using the duplicate cheat, spawns a player duplicate.

**Comment by Kasterisk** [comment]
Okay found out that it works at the start of the game but after the first editor session it somehow no longer works.

**Comment by hhyyrylainen** [comment]
Can confirm that, I'll update the title.
