### ISSUE TITLE
Add a system to check if the object has been registered before in InputManager.RegisterReceiver()

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#2520]
**Describe the bug**

Once I made CheatMenu a ControlWithInput, then I can't open it by F6. Later I realized that it was registered twice, one in ControlWithInput, the other in CheatMenu itself, but there was no warning, which caused a lot of confusions.

I'm thinking if some approach can be taken to warn if the object to register has been registered before.

**Comment by hhyyrylainen** [comment]
I guess this is an error condition? So maybe RegisterReceiver should throw an exception if an object is already registered?
