### ISSUE TITLE
Built-in Godot tooltips not showing over GUI elements

### ISSUE THREAD

**Issue by Kasterisk** [Revolutionary-Games/Thrive#2529]
To track possibly Godot bug where tooltips are not rendering over normal gui elements. Currently only happens in the custom color picker.

![2021-08-24_18 23 26 4667](https://user-images.githubusercontent.com/3796411/130644901-167fb46c-19d5-4731-9141-debf31f335dc.png)

**Comment by takko** [comment]
Not reproducible/fixed for me on current master: 
![image](https://user-images.githubusercontent.com/1927218/139602304-9d6cd02f-b85d-42d5-90b3-37444140011c.png)

**Comment by hhyyrylainen** [comment]
Seems fixed for me as well. I'll close this, but feel free to open if someone can still see this issue.
