### ISSUE TITLE
Fix new mysterious crash

### ISSUE THREAD

**Issue by jjonj** [Revolutionary-Games/Thrive#253]
I reproduced this twice.
First time I was trying to test the new balance changes to reproduction and after 5 minutes of play, before achieving reproduction the game crashed.
Second time I tried again, Played for ~10 minutes and managed to reproduce once and then a bit later the crash occured. 
I could not identify and particular trigger for the crash.

When crashing, the generic unhelpful lua.what() error shows up in the console. This just tells us that the crash occurs starting from a lua call somewhere. 

I added some debug prints in aiSystem and microbeSystem to see if crash occured while inside those, but playing for ~25 minutes i could not reproduce the crash.

I plan on trying to figure out why lua only sometimes gives helpful error messages which could result in getting more information about the crash. 
If that fails I'll try to run with more debug prints, which may result in me implementing a debug feature I've been considering.
I may also try to run through GDB, although that will probably just tell me the game crashes during a call to lua_eval() or some useless info like that.

**Comment by jjonj** [comment]
Moopli have suggested @ #252 that the crash occurs on the master branch, while my testing was on the 024 tuning branch.

**Comment by Untrustedlife** [comment]
Im going to get it built then ill check it out some time today

**Comment by Moopli** [comment]
Is this crash the one you fixed today? Cuz I'm trying to figure out what crashes I can repro and add straces to, and I have a feeling this one is the one you resolved today.

**Comment by jjonj** [comment]
Fixed with 5a10339
