### ISSUE TITLE
Error With upgrading save from 5.4.0 in Dictionary with Species key

### ISSUE THREAD

**Issue by TheNamesGregoryAndounuts** [Revolutionary-Games/Thrive#2532]
**Describe the bug**

Tried to upgrade my 5.4.0 save using the new save upgrade system and got an error that preveted me from playing.

**To Reproduce**
1. Create new game in 5.4.0
2. Reach the stage where it says "you have thrived"
3. Update to 5.5.0
4. Agree to upgrading save

**Expected behavior**
The game should loadstraight back up into mircobe stage.

**System info (please complete the following information):**
- OS: Windows 10
- Graphics card (you can find this in the game logs) Inno3D Geforce 3060
- Thrive 5.5.0

**Logs**
[Thrive Report.txt](https://github.com/Revolutionary-Games/Thrive/files/7047238/Thrive.Report.txt)

**Additional context**
N/A

**Comment by hhyyrylainen** [comment]
The error shows the species that is not valid data for some reason, but could you maybe provide the non-upgraded (the backup) file? That would make testing and debugging this problem easier. You can put it in a zip file and upload that to Github in a comment.

**Comment by hhyyrylainen** [comment]
With your save I was able to make a fix that makes upgrading that save work. I've opened a PR for this: https://github.com/Revolutionary-Games/Thrive/pull/2609
In all likelihood this will be included in the next release, which once released should allow you to upgrade and successfully load your backup save file.
