### ISSUE TITLE
Enemy cell bound in colony

### ISSUE THREAD

**Issue by Maxonovien** [Revolutionary-Games/Thrive#2544]
**Important**
Please only submit technical bug reports here. This is not a place to make feature requests
or suggestions. For that please visit our community forums:
https://community.revolutionarygamesstudio.com/

**Describe the bug**

It was reported that a player was able to bind with an enemy cell.

**To Reproduce**
Possibly activate binding and try to bind with a friendly and an enemy cell at the same time. The reporting player said they were effectively doing this.
(Wasn't replicated)

**Expected behavior**
Not being able to bind with the enemy cell

**Screenshots**
![image](https://user-images.githubusercontent.com/16361817/131217101-924ddbef-e27b-4d93-a541-a4526f31015a.png)

**System info (please complete the following information):**
Not reported

**Logs**
Not given

**Additional context**
A save file after this has occured is joined to the issue.
[help_i_binded_to_a_enemy_cell.zip](https://github.com/Revolutionary-Games/Thrive/files/7070666/help_i_binded_to_a_enemy_cell.zip)

**Comment by Maxonovien** [comment]
The issue is probably linked to the following code: 

If I believe the comments, we check engulfing possibility on the frame preceding binding: 

```// Cannot hijack the player, other species or other colonies (TODO: yet)
        if (other?.IsPlayerMicrobe != false || other.Colony != null || other.Species != Species)
            return;

        // Invoke this on the next frame to avoid crashing when adding a third cell
        Invoke.Instance.Perform(BeginBind);```

But if we have an additional cell touching between frames, we may select it instead of the one we checked.
```private void BeginBind()
    {
        var other = touchedMicrobes.FirstOrDefault();```

**Comment by Maxonovien** [comment]
@Revolutionary-Games/testing 
Although we probably have the reason for it (I'm working on its fixing PR), it could be good to be able to replicate the bug to confirm we indeed got rid of it afterwards.

**Comment by 84634E1A607A** [comment]
Success!
![image](https://user-images.githubusercontent.com/60734649/131245246-c70c3f11-3ebf-4a33-8075-a74ae6c5f294.png)
Maxonovien's right.

**Comment by 84634E1A607A** [comment]
[Enemy Cell Binding.zip](https://github.com/Revolutionary-Games/Thrive/files/7072219/Enemy.Cell.Binding.zip)

Three saves inside.
