### ISSUE TITLE
Make save/load buttons functional in microbe stage

### ISSUE THREAD

**Issue by jjonj** [Revolutionary-Games/Thrive#255]
F4 and F10 works without issue, just needs to be hooked up to the buttons.

**Comment by Untrustedlife** [comment]
I can handle this if someone gives me a quick rundown on how the gui works.

**Comment by Untrustedlife** [comment]
I got this all working, but at the request of moopli, im going to have to write some code to check if teh save file exists, and turn buttons on/off because of it
