### ISSUE TITLE
Common crash in Godot (free_instance_binding_data)

### ISSUE THREAD

**Issue by Maxonovien** [Revolutionary-Games/Thrive#2552]
**Important**
Please only submit technical bug reports here. This is not a place to make feature requests
or suggestions. For that please visit our community forums:
https://community.revolutionarygamesstudio.com/

**Describe the bug**

When launching Thrive on Godot, I have frequent crashes.

**To Reproduce**
The crashes happen especially at launch and when opening save loading menu. 

**System info (please complete the following information):**
- OS: Windows 10 Family Edition
- Graphics card (you can find this in the game logs) GeForce MX150/PCIe/SSE2
- Thrive version: 0.5.5

**Logs**

Common error message
```
FATAL: Condition "!GDMonoUtils::is_thread_attached()" is true.
   At: modules/mono/csharp_script.cpp:1344
```

Prior errors happen (EDIT -Not at latest crash in save menu - Maybe two unrelated issues?):
```
Doing delayed apply for some settings
Error initializing global settings: System.NullReferenceException: Object reference not set to an instance of an object
  at Settings.ApplyAll (System.Boolean delayedApply) [0x00020] in <1b95359f21d6490d882710b91037946b>:0
  at Settings.InitializeGlobalSettings () [0x0002f] in <1b95359f21d6490d882710b91037946b>:0
ERROR: _update_exports: Exception thrown from constructor of temporary MonoObject:
   At: modules/mono/csharp_script.cpp:2338
 
Unhandled Exception:
System.TypeInitializationException: The type initializer for 'Settings' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object
  at Settings.ApplyAll (System.Boolean delayedApply) [0x00020] in <1b95359f21d6490d882710b91037946b>:0
  at Settings.InitializeGlobalSettings () [0x00055] in <1b95359f21d6490d882710b91037946b>:0
  at Settings..cctor () [0x0001e] in <1b95359f21d6490d882710b91037946b>:0
i  --- End of inner exception stacTkh itrsace is  -T-h-r
e   veart Stsaiorntu:p A0c.t5i.o5ns..0.c
or () [0x000a1] in <1Stba9r5t3u5p9 fC21#d 6l4o9c0ad88l2710be9 1i0s3:79 4f6rb->F:R0  G
dot loERcRaOlRe: i sde:b furg_
end_unhandled_exception_error: System.TypeInitializationException: The type initializeurs efro:r/ / 'dSiertetcitnogrsy'  its: C:/Usershrew/Max an ime/AexcpeppDtaitoan/.R
amin g / ThrAitv:e
modulesG/ammeo nlo/omgos nao_rged /wgridt_tmeno ntoo_:u tCi:ls/.Ucspeprs:/37Max0i
e/AppData/Roaming/Thrive/logs latest log is 'log.txt'
```

Full log: (crash at launch)
https://pastebin.com/LW2XvQjG

Full log: (crash when opening load menu)
https://pastebin.com/M4Jx4ZCi

**Comment by hhyyrylainen** [comment]
I've opened an issue before about the crash when going to load menu: https://github.com/Revolutionary-Games/Thrive/issues/2078

Does that second exception actually crash the game? I see that plenty often when running Thrive from the Godot editor, but it has never crashed the game for me (and I have never seen that error when running the game standalone, ie. not through the editor).

**Comment by Maxonovien** [comment]
You mean this one?
```Unhandled Exception:
System.TypeInitializationException: The type initializer for 'Settings' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object
  at Settings.ApplyAll (System.Boolean delayedApply) [0x00020] in <1b95359f21d6490d882710b91037946b>:0
  at Settings.InitializeGlobalSettings () [0x00055] in <1b95359f21d6490d882710b91037946b>:0
  at Settings..cctor () [0x0001e] in <1b95359f21d6490d882710b91037946b>:0
i  --- End of inner exception stacTkh itrsace is  -T-h-r
e   veart Stsaiorntu:p A0c.t5i.o5ns..0.c
or () [0x000a1] in <1Stba9r5t3u5p9 fC21#d 6l4o9c0ad88l2710be9 1i0s3:79 4f6rb->F:R0  G
dot loERcRaOlRe: i sde:b furg_
end_unhandled_exception_error: System.TypeInitializationException: The type initializeurs efro:r/ / 'dSiertetcitnogrsy'  its: C:/Usershrew/Max an ime/AexcpeppDtaitoan/.R
amin g / ThrAitv:e
modulesG/ammeo nlo/omgos nao_rged /wgridt_tmeno ntoo_:u tCi:ls/.Ucspeprs:/37Max0i```

No, but I had a crash right afterwards, an given the outputit seems to mess things up badly (or Cthulhu took control of my computer), so I assumed it was probably related.

**Comment by Maxonovien** [comment]
Also, the crash when going to the load menu is a different one for me: the logs are completely different (same error message as for loading crashes), I think (not sure) I see the mini-images for the saves, and, most importantely, it is not rare *at all*.

At this point it is perhaps around 66%. I feel like I'm playing Russian roulet every time I playtest something.

**Comment by hhyyrylainen** [comment]
> You mean this one?

Yes. As far as I can tell, that has 0 indication with anything about to crash. (and also doesn't seem to be related to any settings failing to apply...)
Godot is very bad at actually giving any info about a crash. The logs often just end with innocent enough message.

> At this point it is perhaps around 66%. I feel like I'm playing Russian roulet every time I playtest something.

You are then in a much better position to debug what's wrong. As for me the crash is like a once a month thing.

**Comment by hhyyrylainen** [comment]
Looking through the logs, I'm kinda now suspicious, that *this* is indeed the crash reason:
```
ERROR: free_instance_binding_data: FATAL: Condition "!GDMonoUtils::is_thread_attached()" is true.
   At: modules/mono/csharp_script.cpp:1344
```

Perhaps the mono logs (that are separate from the normal logs) have something? They are usually blank but worth checking in this case.

btw I updated my previous message with a guess aobut something

**Comment by Maxonovien** [comment]
I'll try to give a shot at debugging this then, but I must say I'm not totally at ease working with engines. It will give me some experience though.

**Comment by Maxonovien** [comment]
Undid the changes from #2301 and I had no crash to report. 
(In other words, removed line `threads/thread_model=2` from `[rendering]` in `project.godot`)

I don't know if this is what you meant by: 
> turning rendering mode to "single-safe" away from multithreaded?

**Comment by hhyyrylainen** [comment]
Yeah, single-safe seems to be the default value. You would usually edit those options through the Godot editor.

So does the multithreaded render option work correctly when running from the launcher (ie. standalone game)?
You can run locally by running `godot thethriveprojectfile` (if you don't pass the `--editor` flag and give a path to a project, Godot will run that directly without launching the editor.

**Comment by Maxonovien** [comment]
This seems to happen when saving a game too...

**Comment by hhyyrylainen** [comment]
Could it be like a game framerate thing? The saving process causes a big lag spike, which might make the timing work out really terribly and cause a crash...

**Comment by Maxonovien** [comment]
Sounds pretty plausible, as I feel there is always a tiny bit of lag (from which I usually get to know that I'll crash beforehand). But it might be the fact that my game stops responding before the crash, so I can't confirm for sure.

**Comment by hhyyrylainen** [comment]
So was it the case that if you change to the single thread rendering mode that fixes (most of) the crashing? If so it would be a pretty simple thing to make a PR to toggle that option (and I can make a new issue to investigate the rendering mode further / again)

**Comment by Maxonovien** [comment]
It seemed to, but that seems to be random (and I have some grace periods), so it may have been a false negative. I'll try it again after I got sure that my editor button PR is fine for the checks.

**Comment by hhyyrylainen** [comment]
I got this for the first time (probably can't expect this to happen again for the next month):
```
ERROR: free_instance_binding_data: FATAL: Condition "!GDMonoUtils::is_thread_attached()" is true.
   At: modules/mono/csharp_script.cpp:1344.

=================================================================
	Native Crash Reporting
=================================================================
Got a UNKNOWN while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0xef400b - /home/hhyyrylainen/bin/godot : 
	0xef4399 - /home/hhyyrylainen/bin/godot : 
	0xee705f - /home/hhyyrylainen/bin/godot : 
	0xf010b0 - /home/hhyyrylainen/bin/godot : 
	0x7f340a733a20 - /lib64/libpthread.so.0 : 
	0x366f08a - /home/hhyyrylainen/bin/godot : _ZN14CSharpLanguage26free_instance_binding_dataEPv
	0x1544f9e - /home/hhyyrylainen/bin/godot : _ZN6ObjectD1Ev
	0x3b3897a - /home/hhyyrylainen/bin/godot : 
	0x18405f1 - /home/hhyyrylainen/bin/godot : 
	0x18874ea - /home/hhyyrylainen/bin/godot : _ZN18VisualServerWrapMT11thread_loopEv
	0x1404f6a - /home/hhyyrylainen/bin/godot : _ZN6Thread8callbackEPS_RKNS_8SettingsEPFvPvES4_
	0x3c02ea0 - /home/hhyyrylainen/bin/godot : 
	0x7f340a729299 - /lib64/libpthread.so.0 : 
	0x7f340a4fb353 - /lib64/libc.so.6 : clone

=================================================================
	Telemetry Dumper:
=================================================================
Thread 0x7f3354ff9640 may have been prematurely finalized* Assertion at mono-threads.c:650, condition `info' not met, function:mono_thread_info_current, 
Process "/home/hhyyrylainen/bin/godot --path /home/hhyyrylainen/Projects/thrive" terminated with exit code 0.
```

**Comment by hhyyrylainen** [comment]
I have not seen this in a long time so I'll assume this has just quietly gotten fixed with some engine upgrade.
