### ISSUE TITLE
Increase compound cloud brigthness in brighter biomes

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2561]
Increase the compound cloud brightness values in the brighter biomes as a stopgap until the issue to make clouds look really good is done (https://github.com/Revolutionary-Games/Thrive/issues/1701)

Can probably put a brightness multiplier in biomes.json that is then on patch change passed to the cloud system for it to multiply things when creating the texture data. One slight difficulty may be dealing with saving, but I think the cloud system already saves some info so adding the multiplier to also be saved should be doable.

Another approach could be to have per-biome compound colours as a fix for this.

**Comment by punctdan** [comment]
Looking through Steam community, this seems to be the biggest issue for many players. It would be nice to see it fixed asap.

**Comment by hhyyrylainen** [comment]
I've seen that too. I'll put this in the 0.5.7 milestone to see if that gets this more attention.
