### ISSUE TITLE
Binding agent can be placed without the nucleus

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#2574]
**To Reproduce**
1. Place a nucleus
2. Select Binding Agent
3. Undo placing the nucleus
4. Place the Binding Agent

**Screenshots**
![image](https://user-images.githubusercontent.com/60734649/132090132-03cee7d3-2319-4aec-9fb4-23db8b2ee5a7.png)
![image](https://user-images.githubusercontent.com/60734649/132090134-ecf1d266-1761-4401-bd74-a675e9281284.png)

Edit: Can't reproduce with other organelles.

**Comment by hhyyrylainen** [comment]
Just saw the edit after updating the title.
I'm going to guess that if the other parts can't be placed like this, then it's pretty weird that the binding agents can, but maybe there's some common check for those that binding agents was forgotten to be added to.
