### ISSUE TITLE
Language options is under Sounds category

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#2575]
Maybe move it under Graphics

**Comment by RacerBG** [comment]
Doesn't Misc sound like a better solution? Because translations are not really a graphic related thing.

**Comment by hhyyrylainen** [comment]
Definitely not graphics. Misc already has a ton of stuff. In most / many games the language option is under sound. Even though we don't have dialogue I think it makes much more sense there than dumping more stuff to the misc options.
