### ISSUE TITLE
Check the negative delta guards

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2577]
Just got notice that this was merged: https://github.com/godotengine/godot/pull/35617
so maybe it is time to check if we can soon remove the negative delta guards in our code.

**Comment by nathanfranke** [comment]
That PR was not cherry-picked for 3.3 or 3.x so you will only get the changes after updating to Godot 4.0 or later

**Comment by hhyyrylainen** [comment]
Now that we use 3.4 this seems like it's time to re-check this. I think I saw in the patch notes that negative frame delta is finally fixed

**Comment by RacerBG** [comment]
> Now that we use 3.4 this seems like it's time to re-check this. I think I saw in the patch notes that negative frame delta is finally fixed

That's correct, it is fixed: https://github.com/godotengine/godot/pull/35617

**Comment by hhyyrylainen** [comment]
It's probably safe to remove the negative delta guards now from everywhere, so this is pretty easy to do. Though I'd keep at least one check in the world simulation class to have some kind of detection if this ends up happening.

**Comment by hhyyrylainen** [comment]
Looks like the delta guards have been removed so I think it is finally time to close this issue.
