### ISSUE TITLE
Play the extinction theme when the extinction screen is shown

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2592]
as we apparently have that theme made but it hasn't been put in the game yet

**Comment by adQuid** [comment]
What's our process for actually getting the music file? I only know the youtube link for the extinction theme, which I assume we don't use as our repository.

**Comment by hhyyrylainen** [comment]
Ask the composer for a .ogg file and then put that in the game repo. If we more regularly put new music in the game, there could be a more controlled process.
