### ISSUE TITLE
Softlock when messing with pause on a new game

### ISSUE THREAD

**Issue by FuJa0815** [Revolutionary-Games/Thrive#2603]
**Describe the bug**

When pressing pause after the new game intro the game can softlocked. You cannot move and the Pangonian Vents-text is semi-visible and does not fade. Opening and closing the pause menu fixes this.

**To Reproduce**
1. Create a new game
2. After the cutscene press esc (before the tutorial popup shows up!)
3. Wait for the tutorial to pop up
4. Close the pause menu
5. Press the x on the tutorial popup
6. Get stuck

**Screenshots**
![image](https://user-images.githubusercontent.com/30809803/134393385-b9b77ff6-6cc6-4a62-955e-0ff8cc27efca.png)

**Comment by hhyyrylainen** [comment]
This is probably as the tutorial remembers the game is paused, it returns to the paused state when it is closed (and not to the unpaused state). I think it would make sense to block pausing the game until after the piece of code runs that pops up the tutorial (if enabled).
