### ISSUE TITLE
Add tooltips for the bottom left buttons in the microbe stage

### ISSUE THREAD

**Issue by FuJa0815** [Revolutionary-Games/Thrive#2611]
I think a confirmation when clicking on the suicide button would be nice. A friend played the game for the first time and just clicked it out of curiosity.

**Comment by hhyyrylainen** [comment]
Instead of a confirmation popup, I think it would be better to just have a tooltip for the button.

**Comment by adQuid** [comment]
I feel like the whole value of the suicide button is to skip having to wait for a hopeless microbe to starve to death, and adding a button press might work against that. I'm sure your friend didn't manage to reach extinction with that mistake.

**Comment by hhyyrylainen** [comment]
Forgot to mention that, but I also wanted to say that it's not very serious mistake to accidentally press the suicide button, as you are very unlikely to lose the game.
I'll rename this issue to be about adding tooltips for the bottom left buttons in the microbe stage, which will help in identifying what they do.

**Comment by Maxonovien** [comment]
Alternatively, perhaps it might pop a confirmation only once, if tutorials are activated?
