### ISSUE TITLE
Crash to desktop shortly after binding to another cell on Windows 10

### ISSUE THREAD

**Issue by nabm-utn** [Revolutionary-Games/Thrive#2614]
**Describe the bug**
Crash to desktop shortly after binding to another cell on windows

**To Reproduce**
Bind to another cell of your own species and move for a little while (< 2 seconds)

**Expected behavior**
Not to crash (?)

**Screenshots**

**System info (please complete the following information):**
- OS: Windows 10 Pro 64bit 20H2 (19042.1237) 
- Graphics card: Radeon RX 570 Series
- Thrive version: 0.5.5.0

**Logs**
First crash:  https://pastebin.com/Q71qUBWh
Note: several minutes before this crash i had autosave errors. It dissapeared after a few generations of evolution.

Second crash:  https://pastebin.com/ZGFd5FSp

**Additional context**
I have only played the game twice. And in both cases i acquired the binding agent organelle after the "victory" message (i dont know if it's actually important, will keep testing). Shortly after binding to another cell from my own species the game crashes.

**Comment by hhyyrylainen** [comment]
Does it happen always? I'm aware that there's a few crashes related to the binding, but none of them are super consistent.
It does kinda seem like from the logs that the action of forming a colony crashes the game.

This is the release version, right? I think we already fixed the colony forming related crashes on master branch.

**Comment by nabm-utn** [comment]
Yes, its the release version. I couldn't find a similar issue here on github, so i posted it. Sorry if it was already reported.

I loaded the last save available and tried to form another colony. 1 second after binding the game crashed (again). 
Here is the new log: https://pastebin.com/F83JDBfK

PS: at the end the log says "Output is too long, it was truncated! See the log file for full output."
Though the logs in the "mono_logs" folder are all empty files :/

**Comment by hhyyrylainen** [comment]
The mono logs are basically always empty. You want to look at the logs in the game logs folder (there's a button in the options menu to open that).

**Comment by hhyyrylainen** [comment]
I chatted with the team members who are more familiar with the colony code, and we determined that the crash you most likely have, is one that we very quickly fixed after 0.5.5 release. If you rely on just playing the public releases, then the fix will be available to you in the next release (0.5.6).
