### ISSUE TITLE
Godot Editor goes Fullscreen

### ISSUE THREAD

**Issue by takko** [Revolutionary-Games/Thrive#2629]
When opening Thrive in Godot, the Godot editor goes into fullscreen, with no option to restore or resize the window.
I cannot exit the Fullscreen mode with either Esc or F11.

Operation System is Windows 10.

I found that the problem depends on the ingame fullscreen setting.
When I switch the game to windowed and restart Godot, the editor is a normal window.

**Comment by hhyyrylainen** [comment]
For me the option gets stuck. It might help if we tweak the settings apply delay (which fixes some warnings being thrown around). Another thing to check would be to check the Godot currently active tags / flags to see if the editor is currently being ran.
I experienced a very similar problem myself, but didn't get around to opening an issue with Godot about getting stuck with the editor always opening in fullscreen mode: https://github.com/godotengine/godot/pull/32056#issuecomment-921621895
