### ISSUE TITLE
Shape ownerId can be 0.

### ISSUE THREAD

**Issue by Kemikal1** [Revolutionary-Games/Thrive#2671]
**Describe the bug**

The shape owners can be 0, which is also tthe error value of the function getShapeOwner().
May fix more bugs,but currently it should fix the pili at #2670
Waiting for the engine to be update with my PR:
https://github.com/godotengine/godot/pull/53990

**Comment by hhyyrylainen** [comment]
I think the fix in Godot was merged so we can now detect between 0 and invalid value.
