### ISSUE TITLE
Add tutorial for negative ATP balance

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2683]
I think a tutorial that pops up the first time the player has negative ATP would be nice.

It could say something like:
> Your ATP balance is negative. This means that when running all processes and moving your creature will run out of energy and die.
Consider adding more ATP producing organelles for the energy sources you plan to use.
Or alternatively you can add storage to make a cell that can only move in bursts.

And then a button to close at the bottom as I don't think there's a really good trigger that would close the tutorial. And I think the tutorial should be positioned on top of the middle of the microbe editor.

A bit wordier than many of the tutorials, so maybe there's a way to make this more concise without removing any advice

This should be relatively easy to implement by just adding the new tutorial class, GUI panel, and new tutorial signal triggered when ATP calculation is negative. ~~Note that this should be only started after the almost complete GUI change PR is complete: https://github.com/Revolutionary-Games/Thrive/pull/2387~~

**Comment by TrialDragon** [comment]
Hiya. I'd like to take on this issue. I've actually already got it working locally for the most part (still want to do further testing and double checking everything is good before I do a pull request tho.) I'd like a clarification before I proceed. By negative atp balance, do you mean when there is less production than energy consumed whilst stationary, or less production than energy consumed whilst moving, or what?

**Comment by hhyyrylainen** [comment]
This should trigger when not being able to move constantly. So the non-stationary ATP balance being negative should be the trigger (and of course only if the undo organelle place tutorial is already done so that this can't interfere with that). There's already an extra confirmation required when exiting the editor with stationary ATP balance being negative as that's a very serious condition. So that is already taken care of with a warning popup.
