### ISSUE TITLE
Make MicrobeStage.random be saved

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2691]
it should be saved for consistency of randomness when loading and saving

needs to be compatible with older saves, I put an idea in the TODO comment regarding how to do that.

**Comment by Kavokan** [comment]
I am going to try to work on this issue; I have everything set up for it. Where to I view this TODO comment?

**Comment by hhyyrylainen** [comment]
It's in the MicrobeStage class file, but here, I searched for it in there for you:

https://github.com/Revolutionary-Games/Thrive/blob/badaf91a832d98bf68098862165f66321c572ce1/src/microbe_stage/MicrobeStage.cs#L49

**Comment by Kavokan** [comment]
Thank you I couldn't find it; for some reason I thought it was a github thing because I haven't really worked with GitHub a whole lot. I will take a look and let you know how it goes.
