### ISSUE TITLE
Compound reserves should be reset on reproduce.

### ISSUE THREAD

**Issue by Untrustedlife** [Revolutionary-Games/Thrive#270]
Right now you keep all of the compounds from before you reproduce, this results in cells that run out of room because the vacuoles get filled with atp. Resetting compound reserves to 0 when you click the "reproduce button", would force the player to get compounds again, which would lead to more fun game-play, and less frustration due to being unable to hold the compounds required for the production of reproductase.

**Comment by Moopli** [comment]
Already fixed in #197, I'll leave this open until that merges.
