### ISSUE TITLE
Create a simple arrow model and add it to the game

### ISSUE THREAD

**Issue by jjonj** [Revolutionary-Games/Thrive#271]
It will be used to illustrate which direction is forward in the microbe editor

Remember to check this tutorial: http://thrivegame.forum-free.ca/t1402-basic-blender-modeling-animation-and-exporting-to-ogre-tutorial

**Comment by ChizuNordenstam** [comment]
It should just be a simple arrow? (but sorta unique still of course)

**Comment by jjonj** [comment]
Yeah I suppose, I don't have any great artistic ideas myself so readability and re useability would be all I could request

**Comment by TritiumH** [comment]
Made this simple arrow model hope it gets the job done, sorry Cheese just saw you assigned for it...
https://www.dropbox.com/s/ic2f44qsra1iusr/Arrow.rar?dl=0

**Comment by jjonj** [comment]
Nice one!

**Comment by ChizuNordenstam** [comment]
Yeah, really cool design. It'll be cool to see that in the game.
 Heh, now I don't have to make one :P

**Comment by jjonj** [comment]
I added it to the game but I need to know what the animation is called so I can call it :) 

Also if you could rename the material to something more descriptive to avoid collisions in the future. (I've just been renaming e.g. the material for ammonia to "ammonia"). You can do this in blender ofc, but you can also just edit it straight in the .mesh.xml (in two places) and .material (in two places) files with a text editor.  
If you're feeling particularly busy or lazy you can also just send me the .mesh.xml or the .blend file and I can do it!

**Comment by TritiumH** [comment]
https://www.dropbox.com/s/gdkcgh4mi2czqce/Arrow2.rar?dl=0
Named the material and added another one, animation name is "Stand" . How is the models orientation btw, i've forgotten what it should've been?

**Comment by jjonj** [comment]
An arrow models orientation is less relevant as we can simply rotate it as we want. The previous issues we're having to rotate the model in one direction while the actual object was rotated in another.

**Comment by LoonyToony** [comment]
Cool, one less thing to worry about.

**Comment by Moopli** [comment]
fixed by 652038f
