### ISSUE TITLE
Resolve performance degradation from LineChart

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2715]
When messing in freebuild I noticed that I was only getting 150 FPS in the editor, when I usually get 400 (the limit). After stopping in debugger I noticed the main thread was busy in LineChart.cs _Process, and returning early from there (using save made, I also went back to the editor to confirm that nothing I did in the previous session caused it) greatly improved performance.

Before:
![2021-10-29_17 04 50 5972](https://user-images.githubusercontent.com/3796411/139449626-5a10ab95-5f7a-4251-9ce7-a7f86cf65744.png)

This is the code change I tested:
![Kuvakaappaus - 2021-10-29 17-05-44](https://user-images.githubusercontent.com/3796411/139449660-5d1e8a39-860e-440a-9734-7098c05bcc92.png)

And the FPS recovered after rebuild and restart (I also confirmed that undoing that change and loading the same save, gives 150 FPS again):

![2021-10-29_17 05 41 5031](https://user-images.githubusercontent.com/3796411/139449738-870e7b2d-0c21-4a19-a060-605db3f9be80.png)

So I think that LineChart needs to smartly only update points while animating, and rest of the time skip updating them to not sap performance.

**Comment by Kasterisk** [comment]
Would you mind to share the save so I could test it with #2718?

**Comment by hhyyrylainen** [comment]
For some reason it looks like I don't have the save anymore. Actually looks like there's a serious quick save non-rotating issue.
You can make a save like that yourself if you take my auto-evo branch and move a few times to different patches and let like 10-15 generations to pass to really fill the graphs with various species.
