### ISSUE TITLE
Check if new main menu theme is cycled in, otherwise fix

### ISSUE THREAD

**Issue by jjonj** [Revolutionary-Games/Thrive#273]
Oliveriver: 
> I haven't yet heard the new theme (not sure whether they're randomly chosen and I'm just incredibly unlucky)

**Comment by jjonj** [comment]
Any version of the game seem to be stuck on always playing one or the other first every time. This could be related to the RNG seed or a bug in the soundsourcecomponent.

**Comment by Untrustedlife** [comment]
Ill take a look at this when I have the time.

**Comment by Untrustedlife** [comment]
Sounds like a seed problem to me.
