### ISSUE TITLE
Update to Godot 3.4

### ISSUE THREAD

**Issue by skyace65** [Revolutionary-Games/Thrive#2742]
Godot 3.4 officially released today. a blog post covering the main changes can be found [here](https://godotengine.org/article/godot-3-4-is-released).

Unfortunately thrive does not currently build on 3.4. There are five errors related to `ulong` and `long` types. Typically 3.x releases shouldn't break compatibility, and I'm not great at C# so I'm not sure what's going on here. Either something in the engine broke, changed, or it's finding errors it wasn't finding before. If something in Godot is broken an issue should be opened on its repository.

**Comment by Blisto91** [comment]
The minor version increment is allowed to have minor breakage according to [their docs](https://docs.godotengine.org/en/stable/about/release_policy.html)
Though I haven't looked into Thrives case

**Comment by hhyyrylainen** [comment]
I haven't also tried building GodotSteam (but it seems they already tagged a version for 3.4, so probably no issues there) for the new version. Due to me being very busy with finalizing the steam release, I think this engine version update should be pushed back to the release after 0.5.6.
