### ISSUE TITLE
Load game screen is totally empty without saves.

### ISSUE THREAD

**Issue by takko** [Revolutionary-Games/Thrive#2748]
Without a save to load, the load game screen is totally empty. This looks very weird.
There should at least be a message saying no saves to load.
Or maybe the load game button should be disabled.

**Comment by hhyyrylainen** [comment]
I think the SavesList component should be updated to handle this case by just creating a simple label saying that no saves exist, that way all places that show saves will work properly. Should be very easy to fix and a good first issue for someone to get into Thrive.
