### ISSUE TITLE
Check if oxytoxy emission is ejecting well enough

### ISSUE THREAD

**Issue by jjonj** [Revolutionary-Games/Thrive#275]
This comment was made: 
>When I put a toxic vacuole, and created oxytoxy, the oxytoxy was created inside of my microbe, damaging, and each time I released oxytoxy, my microbe was hurt. I think that happened because the oxytoxy is produced at the front side of the microbe, and I placed the toxic vacuole on the back side of the microbe. The oxytoxy should be produced always outside of the microbe.

It doesn't need to be perfect, but it should at least do an angle away from the center of the microbe still

**Comment by MontySpud** [comment]
I can confirm this to be fixed

**Comment by jjonj** [comment]
I managed to reproduce it with a default microbe that has 3 random organelles pertruding from the nose followed by a toxin organelle at the tip. I'm currently working on a much better solution using collision detection
