### ISSUE TITLE
Add Takko to Easter Egg Name List

### ISSUE THREAD

**Issue by adQuid** [Revolutionary-Games/Thrive#2761]
takko has been an active dev for some time now, but there is still a 0% chance of a species emerging called Premium Takkivium to eat the player.

**Comment by hhyyrylainen** [comment]
I guess we'd need the general `ko` suffix, and then in the general other developer's name place `tak` can be added. 
Though maybe someone when doing this change should add code to generate random names until the right name pops up to confirm that it works.
