### ISSUE TITLE
Create a custom icon for auto-evo prediction being calculated

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2768]
I reused the help button question mark but it should get its own icon.

**Comment by hhyyrylainen** [comment]
The icon is now done: https://dev.revolutionarygamesstudio.com/api/v1/download/33760

**Comment by Kasterisk** [comment]
I'm starting on this but can't seem to find where to apply that icon in, any pointers?

**Comment by hhyyrylainen** [comment]
I *think* it might be here:

https://github.com/Revolutionary-Games/Thrive/blob/2563939c386b496677e459aa66fed504121add23/src/microbe_stage/editor/CellEditorComponent.GUI.cs#L394

I have some kind of memory that I used to explicitly set the pending icon but then someone (might have been you even) refactored that pending state to just reuse the unknown value feature of the comparison control.

**Comment by Kasterisk** [comment]
Thanks, that got me back on track (and yes it is indeed me 🙂).
