### ISSUE TITLE
[Windows] Game opens on wrong screen

### ISSUE THREAD

**Issue by CoenraadS** [Revolutionary-Games/Thrive#279]
I have a dual monitor setup like so:

[Secondary (1600x900)] [Primary (1920x1080)]

Running Thrive will launch it at 1080p, but on the secondary monitor, causing the bottom to get cutoff, and the right to overlap onto my primary monitor.

Image: http://i.imgur.com/5isavPU.jpg

Expected behavior: Should launch on primary monitor until adding monitor preference is added.

**Comment by jjonj** [comment]
Thanks for reporting!
Until we can get it fixed, perhaps you want to run it in non-fullscreen mode!
To do that you would editor or delete the ogre.cfg file

**Comment by hhyyrylainen** [comment]
This will probably be in the options menu at some point. Might make it in the next release

**Comment by hhyyrylainen** [comment]
This WILL be fixed by engine_refactor
