### ISSUE TITLE
Clear old saves button should delete save upgrade backups

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2794]
to not leave them hanging around

**Comment by shagen9285** [comment]
Hey! Could I work on this issue?

**Comment by hhyyrylainen** [comment]
Yes you can, I'll assign you on this issue.

**Comment by KJ002** [comment]
@shagen9285 Are you still working on this issue because if not I would like to. What is meant by "save upgrade backups"? I am not quite sure what this refers to.

**Comment by hhyyrylainen** [comment]
When a save from an earlier version is upgraded a backup file is created first before upgrading the save with the original name. So the cleanup should find those upgrade backups, for example `nodamage.backup.thrivesave`, and clear them as well.

I cleared the assignees on this issue.

**Comment by KJ002** [comment]
I have done it all up to the point of adding it to `DELETE_ALL_OLD_SAVE_WARNING` which I don't know how to do because it would mean adjusting already existing translations.

**Comment by hhyyrylainen** [comment]
In this case as we need to make a significant formatting change, I recommend the translation key would be renamed to `DELETE_OLD_SAVE_WARNING_2`. You can find info on how to work with translations here: https://github.com/Revolutionary-Games/Thrive/blob/master/doc/working_with_translations.md#updating-the-localizations
