### ISSUE TITLE
Binding agent stays membrane colour after exiting membrane tab in editor

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2797]
Steps:
- Go to the editor and place a binding agent
- Switch to the membrane tab and select a colour
- Switch back to the structure tab
- Notice how the binding agent is coloured the membrane colour while other organelles are not

**Comment by FuJa0815** [comment]
Is this related to the bug where the BAs membrane randomly recolors? (Couldn't find the issue, is there one for that?)

**Comment by hhyyrylainen** [comment]
At least there's no open issue for that. I searched for "binding" in open issues and nothing like that turned up.

**Comment by Kasterisk** [comment]
I think this is because the color for the binding agent's membrane itself is from the tint which is what is changed when the cell membrane color is changed. A fix would probably be having the color set on the texture, this should also fix the random membrane recolor.
