### ISSUE TITLE
Add performance profiling

### ISSUE THREAD

**Issue by Nimbal** [Revolutionary-Games/Thrive#28]
Profiling is essential for identifying bottlenecks and optimization opportunities. We could use an instrumenting profiler like callgrind, but they tend to slow things to a crawl, possibly distorting the results and deterring developers from profiling routinely.

The alternative is manual instrumentation, which requires adding profiling instructions to the source code, telling the profiler what we are interested in. There is the [Shiny](http://sourceforge.net/projects/shinyprofiler/) profiler, but it is only suited for single threaded applications. 

Then there is the [High Performance C++ Profiler](https://code.google.com/p/high-performance-cplusplus-profiler/), described in detail in [this blogpost](http://floodyberry.wordpress.com/2009/10/07/high-performance-cplusplus-profiling/). It's a little old, but probably still works.

Finally, we could roll our own profiling library, tailored to our needs. Getting this right will require some research to keep the profiling overhead to a minimum, so it's no small feat. But it would allow us to, e.g. render the profiling data in an overlay directly in the game.

**Comment by hhyyrylainen** [comment]
I'm going to add a Lua profiler to the next release. The c++ code can be profiled with valgrind and as jjonj said pretty easily with gprof.

I don't think we need this issue open anymore as I created a new one for the Lua profiler
