### ISSUE TITLE
Reentering microbe stage with "Finish" or load game plays strangely queued soundeffects

### ISSUE THREAD

**Issue by jjonj** [Revolutionary-Games/Thrive#283]
To reproduce click New Game -> reproduce() -> editor -> Finish
And you will hear a soundeffect as soon as the game enters even when there was no recent event to trigger it. 
This has seems to be the microbe bump sound for me, but oliveriver has reported other sound effects.

**Comment by hhyyrylainen** [comment]
As the cell stage should resume from where you left off (and play any sound effects that weren't finished) I think this is the intended behaviour.
