### ISSUE TITLE
UI Issues in GLES2 Mode (in virtual machine)

### ISSUE THREAD

**Issue by RacerBG** [Revolutionary-Games/Thrive#2860]
**Describe the bug**

* The checkboxes are invisible but are still functional if I click on them.
* The theming of the game is not applied on the lists (from what I can see it uses the GNOME theming by default in my case).
* The hex grid in the editor is almost invisible.
* This one is not on the screenshots and I can't confirm if GLES2 is to blame here - the save game screenshots are black.

**Screenshots**

![Screenshot from 2021-11-26 19-11-30](https://user-images.githubusercontent.com/68707872/143615002-f1cfcdf5-ba01-462d-b72f-83a5a43ceff2.png)

![Screenshot from 2021-11-26 19-11-44](https://user-images.githubusercontent.com/68707872/143615006-58eac2f6-99aa-480a-b9bb-7d0795ee4ba6.png)

![Screenshot from 2021-11-26 19-12-58](https://user-images.githubusercontent.com/68707872/143615009-f3a32ad3-9529-47ab-88aa-cab5cf7d5778.png)

**Comment by Kasterisk** [comment]
I'm on GLES2 and never had this happen but this is a pretty serious breakage, did this always happen in previous versions or was this only in 0.5.6 RC?

**Comment by hhyyrylainen** [comment]
I think this happened on one specific old computer? So maybe it has really bad old intel drivers? At least it was the case back in the Ogre days that a lot of intel older drivers just crashed the game and didn't work at all.

**Comment by RacerBG** [comment]
> I think this happened on one specific old computer? So maybe it has really bad old intel drivers? At least it was the case back in the Ogre days that a lot of intel older drivers just crashed the game and didn't work at all.

Let me explain - this is a Debian 11 virtual machine which I'm using for testing Thrive, created in Virtual Box with Guest Additions enabled. I have a suspicion that it may be related to the VMSVGA drivers (I had never tested this on real hardware) so if this can't be replicated by other people, then probably Virtual Box is to blame here.

**Comment by hhyyrylainen** [comment]
Okay, VM drivers are something that are notoriously bad, I'll edit the issue title to reflect that. This means that this is even lower priority to fix, but if it happens in a specific VM, then it might actually be possible for a developer of Godot to get the exact same issue.

**Comment by hhyyrylainen** [comment]
Godot 4 has a vastly different fallback renderer which seems much more feature complete so I'll close this issue as likely fixed.
