### ISSUE TITLE
Save false success when saving with special symbols like `/`

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#2862]
![image](https://user-images.githubusercontent.com/60734649/143676433-c80abc19-bd75-46d2-867a-b6aa098abaf8.png)

![image](https://user-images.githubusercontent.com/60734649/143676396-3834aa80-c4d3-41eb-a09f-045689294e85.png)

```
Creating a save with name: {}[]|\/.thrivesave

ERROR: store_buffer: File must be opened before use.
   At: core/bind/core_bind.cpp:2265.
(The above error repeated for over a hundred times)

save finished, success: True message: Saving succeeded elapsed: 00:00:00.6036241
Jukebox: starting track: res://assets/sounds/soundeffects/microbe-ambience2.ogg position: 0

```

**Comment by 84634E1A607A** [comment]
On Linux Mint I get this:

```
System.IO.Path.GetInvalidFileNameChars()
  {char[2]}
    [0]: 0 '\0'
    [1]: 47 '/'
```

But on Windows I guess there's more. This may raise cross-platform issues.

**Comment by hhyyrylainen** [comment]
Ah, I guess we forgot to validate save name characters... we should use a pretty strict set of only allowing alphanumeric plus a few special characters.
Can make a regex with that pretty easily and then show the save name box in red if the name is invalid and don't allow pressing the save button in that case.

**Comment by 84634E1A607A** [comment]
And also species name (

**Comment by hhyyrylainen** [comment]
I guess yeah, we need sanitation when converting those to save names as the regex there is much more forgiving than what can be used for file names.

**Comment by 84634E1A607A** [comment]
> we should use a pretty strict set of only allowing alphanumeric plus a few special characters

Wait, that's a bit too strict for non-Eng users.

**Comment by hhyyrylainen** [comment]
What do you suggest instead? Allow all characters except the ones that are banned on Windows (as Linux banned characters is a subset of those): https://gist.github.com/doctaphred/d01d05291546186941e1b7ddc02034d3 ?

**Comment by 84634E1A607A** [comment]
As for species name I agree on using only alphanumeric, but for save name I prefer banning `<>:\"/\\|?*\0`.

**Comment by hhyyrylainen** [comment]
What about those special names that are banned on windows and will break if used?

**Comment by 84634E1A607A** [comment]
`<>:\"/\\|?*\0` these are.

**Comment by hhyyrylainen** [comment]
If you read my link, you'll see that file names like `CON, PRN, AUX, NUL, COM1` etc. are also banned on Windows as they make Windows try to use a device instead of writing to a file. That's DOS legacy for you.

**Comment by 84634E1A607A** [comment]
Well then...
We can let exception handling do the rest.

**Comment by hhyyrylainen** [comment]
But wasn't the problem that invalid file names don't even throw an exception, just the writing fails and the game reports it as success?

**Comment by 84634E1A607A** [comment]
It's because `file.Open(target, File.ModeFlags.Write);` returns an `Error.Failed` but we haven't caught that.

**Comment by hhyyrylainen** [comment]
I guess error checking there needs to be added as well.

**Comment by 84634E1A607A** [comment]
Or a better way in my opinion is that we use `System.IO.Path.GetInvalidFileNameChars()` to filter chars and error checking added to handle exceptions.

**Comment by hhyyrylainen** [comment]
Does not work. Saves need to be compatible between platforms for sharing save files and for Steam Cloud sync to work.

**Comment by 84634E1A607A** [comment]
Okay
