### ISSUE TITLE
Reduce duplicate AI attribute calculations

### ISSUE THREAD

**Issue by adQuid** [Revolutionary-Games/Thrive#2865]
Currently, the microbe AI relies to comparisons between the value of a species personality attribute and the max value for that attribute to make decisions. An example here: https://github.com/Revolutionary-Games/Thrive/blob/master/src/microbe_stage/MicrobeAI.cs#L214

These calculations are currently made on the fly, meaning each microbe repeats the same division 3 times per second during game play, times however many attribute checks the AI happens to make that cycle. So far this doesn't seem to slow things down prohibitively, but this is still something that should be fixed.

I can see two ways to resolve this: either pre-calculate the ratios, or normalize all personality attributes to values between 0 and 1 (they currently go from 0 to 400, but units never show in game)

**Comment by hhyyrylainen** [comment]
The AI actually only runs for each cell every `Constants.MICROBE_AI_THINK_INTERVAL` so each cell only runs the AI code about 3 times per second.
Still any efficiency improvements would be welcome.
