### ISSUE TITLE
Binding to a "disposed" microbe blocks the player from unbinding from it.

### ISSUE THREAD

**Issue by Kemikal1** [Revolutionary-Games/Thrive#2876]
**Describe the bug**

The player remains stuck in a colony, cant leave if trying to bind to a disposed microbe.
Seems to happen when alot of colony members are invovled.
**To Reproduce**
Steps to reproduce the behaviour:
Bind to "disposed" microbe.

**Screenshots**
![image](https://user-images.githubusercontent.com/11059623/143950997-078010c7-cb1d-4aee-b369-2ae5c36ec8fd.png)

**Logs**
https://pastebin.com/HKs3TziW

**Additional context**
Related to the issues people have been reporting recently.

**Comment by Kemikal1** [comment]
The only way i see for this is if we add a guard for IsDisposed() at colony creation/destruction. Because the engine might bug out and dispose of objects somewhere where we dont have a reach.

**Comment by hhyyrylainen** [comment]
That's not possible. So far every single case where someone has thought that Godot is disposing objects behind our backs, it's been a case of our code deleting a Godot Node and it getting disposed. Just need to utilize the on destroyed callbacks / physics area leave callbacks to detect when something is removed.

**Comment by Kemikal1** [comment]
done
