### ISSUE TITLE
Move extinct species on species list dropdown to the bottom

### ISSUE THREAD

**Issue by Kasterisk** [Revolutionary-Games/Thrive#2886]
All extinct species in the species population graph's dropdown list should be moved to the bottom of graph for easier finding. Maybe a new extinct section can be added.

**Comment by hhyyrylainen** [comment]
I think this should be in addition to the normal details, otherwise looking through that data it is hard to see quickly if a species is extinct without scanning through the patch list that species is in visually to see if all the numbers are 0.
