### ISSUE TITLE
Replacing cytoplasm placed in the current editor session should refund it

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2900]
to avoid players wasting MP that way. I don't want to remove the usability feature of replacing cytoplasm with an organelle afterwards.

**Comment by hhyyrylainen** [comment]
This should be investigated if the dynamic MP now properly handles this.

**Comment by 84634E1A607A** [comment]
Dyn MP handles this properly, (but the MP prediction is wrong when an organelle replaces more than one cytoplasm).
