### ISSUE TITLE
Check if we should include the Harmony dll for moddabilitiy by default

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2901]
There's this useful tool called harmony that allows modifying existing C# code on the fly, very useful for modding.

There's also a mod that adds the harmony libraries for use by other mods: https://community.revolutionarygamesstudio.com/t/0-5-6-0-thriveharmony-2-0/4040

I think we should consider including harmony by default to make modding just a tiny bit easier to do.

This might be as easy as updating our readme files to mention harmony license and just refer to the nuget package for it in our csproj.

**Comment by I-Have-No-Idea-What-IAmDoing** [comment]
i think it be useful for it to automatically patch mods after loading them except for certain mods that want more control but i think that be only a few mods
