### ISSUE TITLE
Make only last membrane change in editor session count for remaining MP

### ISSUE THREAD

**Issue by Maxonovien** [Revolutionary-Games/Thrive#2905]
Part of the dynamic MP computation series, changing membrane twice depletes MP bar while only the last one should actually count.

**Comment by hhyyrylainen** [comment]
I kinda don't think we need a separate open issue about this.
Links for future reference:
https://github.com/Revolutionary-Games/Thrive/issues/1644
https://github.com/Revolutionary-Games/Thrive/pull/2445

(the tags would need to be set to difficult and impeded if this was left open)

**Comment by Maxonovien** [comment]
Well, this is a subpart of the issue, which could be fixed independently (hence the smaller difficulty), in case the other PR stalls.

**Comment by hhyyrylainen** [comment]
I don't think it's worth any time to implement just *this* without for example fixing the rigidity slider. At that point you are basically doing it as difficult as the full dynamic MP implementation as you need to remember the original state of multiple variables and compare them. If this were to be done any other way, then this would just dirty up the code with special case logic that needs to be removed soon.
