### ISSUE TITLE
Bottom of loading screen tip is cutoff and it doesn't use bbcode

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2908]
Testing loading a save with a lot of stuff I had some time to read through some of the loading tips and I noticed some issues:

![Kuvakaappaus - 2021-12-05 10-39-42](https://user-images.githubusercontent.com/3796411/144838287-c2cd9507-951d-4453-90b7-1437299ba79e.png)
![Kuvakaappaus - 2021-12-05 15-41-37](https://user-images.githubusercontent.com/3796411/144838301-a53adf23-367b-4672-811d-392223e4fcba.png)

![Kuvakaappaus - 2021-12-05 15-45-34](https://user-images.githubusercontent.com/3796411/144838313-ab45f925-a751-4f8f-bf00-4a00c139b57a.png)

The text needs to be moved up a little bit so that it doesn't get cutoff and it also needs to be updated to use our custom bbcode node for it to support the bbcode tags.

**Comment by Kasterisk** [comment]
IMO It needs wrapping so it doesn't go over the status indicator elements. In addition, I actually think there has to be a maximum character/word length for the loading screen tips. Maybe to enforce it could be by adding ellipsis if the text has crossed the max length.

**Comment by hhyyrylainen** [comment]
I mean if we have line wrapping on and set the max visible lines to like 3 or 4, there's quite a ton of text that can fit in. We just need to be a bit careful not to make super long English text and I doubt no translations would end up too long either, then.

**Comment by Kasterisk** [comment]
Yeah, this is just for an extra measure in a sense.
