### ISSUE TITLE
Add an extra mode to the F3 FPS display panel to show game entities

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2909]
to help in diagnosing performance issues. I think something like if shift is held down while the F3 is pressed (or perhaps a separate key could be configured for it) to toggle an extended mode with extra info like, game entity counts (separate count for cells and other entities), player position, used memory / rendering data if we can get that from Godot. Stuff like that to help in testing and debugging.

**Comment by Kasterisk** [comment]
I believe this is now added with the performance metrics panel?

**Comment by hhyyrylainen** [comment]
Yes, it is. I just forgot to link this issue so this wasn't closed.
