### ISSUE TITLE
Investigate and fix iron compound food source

### ISSUE THREAD

**Issue by adQuid** [Revolutionary-Games/Thrive#2912]
**Describe the bug**
I'm pretty sure the compound food source for iron is broken.

It is defined here
(https://github.com/Revolutionary-Games/Thrive/blob/master/src/auto-evo/simulation/PopulationSimulation.cs#L159)

Like all compound food sources, it takes dissolved compounds.
https://github.com/Revolutionary-Games/Thrive/blob/master/src/auto-evo/simulation/food_source/CompoundFoodSource.cs#L15

But iron is never found dissolved, it's only found in chunks.
https://github.com/Revolutionary-Games/Thrive/blob/master/simulation_parameters/microbe_stage/biomes.json#L101

Either the compound food source needs to be modified to handle this, a new food source class should be made, or I'm totally wrong and there's some other reason the auto-evo hates iron eaters. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a patch with iron but no glucose (modifying the biomes file will speed this up)
2. Be a pure iron-eater
3. Observe your auto-evo prediction

**Expected behaviour**
A non-zero population prediction

**Screenshots**

**System info (please complete the following information):**
- OS: [e.g. Windows 10]
- Graphics card (you can find this in the game logs) [e.g. OpenGL ES 3.0 Renderer:
    GeForce GTX 1080 Ti/PCIe/SSE2]
- Thrive version [e.g. 0.4.0.2]

**Logs**

Please use a text hosting service (for example https://pastebin.com/) to submit your logs.
You can copy the launcher output or the contents of the following files: `log.txt` and mono
log file. You can find these log files by reading the game log to see their location.
For example:
```
Mono: Logfile is: /home/hhyyrylainen/.local/share/godot/mono/mono_logs/2020_07_21 23.10.26 (265121).txt
Game logs are written to: /home/hhyyrylainen/.local/share/Thrive/logs latest log is 'log.txt'
```

**Additional context**

**Comment by hhyyrylainen** [comment]
Isn't it wrong for all non-environmental compounds to use that source?
For iron it is found in clouds as well as iron chunks. So the amounts available from those need to be summed up for the iron eating species to get energy from.

**Comment by Maxonovien** [comment]
Iron isn't found (currently) in native clouds, but in clouds vented from chunks. Of course, this could happen, but this is the same logic as marine snow in a sense. I'll try to propose something based on that.

**Comment by hhyyrylainen** [comment]
This is now otherwise done except the large iron chunks are very OP, and also marine snow got very heavily nerfed.
