### ISSUE TITLE
Factor movement into Compound Food Source 

### ISSUE THREAD

**Issue by adQuid** [Revolutionary-Games/Thrive#2918]
Realistically, a microbe that survives off of compounds needs to be able to move, and can't be slow, sessile, or metabolically unable to support movement. Currently, https://github.com/Revolutionary-Games/Thrive/blob/master/src/auto-evo/simulation/food_source/CompoundFoodSource.cs doesn't support that.

**Comment by hhyyrylainen** [comment]
Umm, currents? It's very much a planned feature that completely immobile plants will be able to survive off compounds they drift into.

**Comment by Maxonovien** [comment]
In any case, current-drifting and actively swimming are two different strategies with their pros and cons, and should be accounted for in some way. So I think this would just expand the issue rather than close it anyways.

**Comment by hhyyrylainen** [comment]
Well auto-evo accuracy fixes are also not a thing that happens fast. I suspect that unless someone now out of spite does this quickly, this would take in the range of 6 months to a year before this is done.

But fine, I'll leave this open. Then someone better in the future rename the compounds food source to be related to swimming around and finding the compounds and adding a new food source that is for just casually drifting into clouds.
