### ISSUE TITLE
Fonts should adapt dynamically to space in GUI for translations

### ISSUE THREAD

**Issue by Maxonovien** [Revolutionary-Games/Thrive#2926]
Otherwise it leads to situations like this ugly (and not most readable) "environnement" display, in French:

![image](https://user-images.githubusercontent.com/16361817/145380450-60ec5484-a60c-47f1-b096-2cd9a48ffa33.png)

**Comment by hhyyrylainen** [comment]
This is a too broad issue, I'd say. Every single text that can get too long needs manually either clipping or text wrapping enabled. Instead there should be one issue opened each time a new batch of texts that don't behave well is found. I'm not aware of any overall general solution that could be done.

**Comment by Maxonovien** [comment]
Cant we do something like font size reduction? Along the lines of:

```
while (GetOccupiedSpace(font, text.length) >= displaySupportWidth){
    font.Size *= .8
}
```

(Or any method that can compute that directly without a while. I'm not experienced at all with GUI)

**Comment by hhyyrylainen** [comment]
We'd have to replace every single Label used in the GUI, if not a thousand, there's probably at least multiple hundred, with a custom class.

**Comment by hhyyrylainen** [comment]
I'll close this for now until there is a realistic solution, until then specific instances of text Labels that need word wrapping / clipping enabled should be reported.
