### ISSUE TITLE
Bacteria

### ISSUE THREAD

**Issue by Moopli** [Revolutionary-Games/Thrive#293]
Small entities that serve as compound bags and simple processors. This issue serves mostly to get basic ones into the game, so here are a bunch of features of these bacteria which could be done later:
- Swim around (run-and-tumble behaviour,  of course)
- Aggregate in clumps, strings, and networks
- Perhaps use particle system

**Comment by jjonj** [comment]
So a couple of questions:
- These would just be microbes with some specialized behavior right?
- Should we delay the tumbling behavior until fluid dynamics?

**Comment by Lepticidio** [comment]
Bacteria don't have organelles, for example, and are the size of an hexe or two at most, although they make chemical reactions. For example, some make photosynthesis, others have aerobic respiration...
Perhaps they won't evolve as the microbes. Mitochondria and chloroplasts shouldn't be available until you absorb certain bacteria, perhaps with a 1/10 chance of assimilate them.

**Comment by Moopli** [comment]
@jjonj Bacteria are tiny, generally around the size of emitted compound particles. They're much more simple than microbes: no organelles, just a compound container, one process that runs over contained compounds, compound emission/absorption, tiny mesh, and movement. Tumbling doesn't involve any fluid dynamics stuff, as all we'd see is the bacterium pivoting around a bit while position stays constant, before doing another short dash. So, the bacterium has two states: one at constant orientation (and constant velocity), the other at constant position; and switches state in short intervals.

**Comment by Untrustedlife** [comment]
looks to me like a bacteria is about 1/5th the size of a red blood cell
http://www.microbiologyonline.org.uk/about-microbiology/introducing-microbes/overview

**Comment by Moopli** [comment]
1. Bacteria come in all sorts of sizes, from tenths to rare hundreds of microns. Though the ones we'll be dealing with will likely all be in the 0.5-5µm range. 
2. Red blood cells are small -- note the paramecium on that scale, that's the general size range we're in.
So I stand by my point, all but the biggest bacteria will essentially be dots several pixels large at default zoom. That's why an important way to differentiate them in-game will be by their self-organization: one species you might find forming thin, straight threads, another forming heavily intermeshed networks of filaments, others free-swimming, etc.

**Comment by Untrustedlife** [comment]
https://www.uoguelph.ca/foodscience/book-page/microorganisms
heres another source.

**Comment by Untrustedlife** [comment]
Woah, I seem to have found that Mitochondria are about 1 upm in size, same size as a bacteria.
http://book.bionumbers.org/how-big-are-mitochondria/
neat. What scale will we sue for them?

**Comment by NickTheNick** [comment]
Actually, for mitochondria, some cells have over a thousand, whereas with
our system it would be impossible for a cell to even be 1000 hexes big, let
alone 1000 hexes of mitochondria. That will be something we will have to
revisit when we switch to a dynamic membrane system. With no discrete
minimum size for organelles, we can make mitochondria smaller and thus
allow for more in a cell (I'm thinking tjwhale's system of membrane
generation would work really well for this).

**Comment by Lepticidio** [comment]
Sorry for huge post

First things first, yeast is an eukaryotic cell, in fact, is fungi : 
http://en.wikipedia.org/wiki/Yeast
Mitochondrion are 4 upm long and 1 upm wide (diameter). 
http://htwins.net/scale2/
http://en.wikipedia.org/wiki/Mitochondrion



Early microbe cells should be smaller than later microbe cells. So, by the end of microbe stage, you cell can be as big as a big eukaryotic cell (paramecium can be 200 upm and amoeba 350 upm) and in the beginning of the microbe stage, as small as yeast (4 upm) or red cells (7 upm). So, if 1 hexe is  1 upm, cell at the end of microbe stage would be like 200 hexes long, which is too big. 
However, cells in multicellular organisms tend to be smaller than 100 upm (largest cell in the human body, the Ovum, is 120 upm, skin cell 35 upm. As the ultimate objective of your microbe is to be part of a multicellular organism, the final size of your microbe would be something like 50 upm. Perhaps the best thing would be to make an hexe 4 upm long.

 E Coli would be 0.5 hexe long (2 upm)
A mitochondrion would  be 1 hexe long (4 upm)
Yeast 1 hexe long (4 upm)
Cell nucleus 2 hexe long (7 upm) 
Red blood cell 2 hexe long (7 upm)
Chloroplast 2 hexe long (8 upm)
White blood cell 2.5 hexe long (10 upm)
Skin cell 9 hexe long (35 upm)
Human ovum 15 hexe long (120 upm)
Paramecium 50 hexe long (200 upm)
Amoeba 87 hexe long (350 upm)

http://htwins.net/scale2/

**Comment by Moopli** [comment]
Nice numbers! Adding on to that, the choanoflagellates (our closest non-animal relatives) are about 3-10µm in size, so that's likely about how big the earliest animal cells were. Note though, about mitochondria: I found a paper once (sadly I can't find it now) that demonstrated that mitochondria are not small pill-shaped things, but are actually larger networks, and pill-shaped appearance in electron micrographs is due to the microscope getting a cross-section of a particular branch of a mitochondrion. The strange shapes likely arose through a long history of living within a host that provides scaffolding (cytoskeleton), so I guess the early ones would likely still be pill-shaped.

**Comment by Seregon** [comment]
I see bacteria as filling a few separate roles, in terms of filling out the microbe stage gameplay:
- a less dangerous food source for 'herbivorous' microbes (they may be toxic, but won't actively fight back
- a way of concentrating background compound levels to a point where they're worth consuming
- a way of carrying out processes that eukaryote life either can't, or hasn't yet evolved too, typically decomposition, possibly also clean up of toxins.  Also, a way to fill gaps that might make an ecosystem in-viable (e.g.: lack of photosynthesisers), though this may make different environments too uniform.
- later on in development we might want to consider them as another environmental threat, a source of disease perhaps (though viruses would be more appropriate)

There are two basic ways we can represent bacteria, as small agents (possibly even particles), or as clouds.  I don't think having them as agents adds much, as they'll just be smaller, less capable, AI cells.  They would add a sense of more life to the game (as there could be more of them), as well as some more diversity, but I'm not convinced this makes them a worthwhile addition.

Representing them as clouds (which is somewhat reasonable as they can be vastly smaller and more numerous than eukaryotic cells) would add a more novel factor to game play, and one which would need to be dealt with entirely differently by the player.  This has several more possible advantages:
- a cloud seems more like part of the environment than agents do, which would add variety to what is currently a very featureless space.  Depending on how transient these populations are, they may also add some sense of terrain, with semi-permanent populations acting as a landmark to either navigate by, avoid, or visit for the compounds they provide.
- a cloud of bacteria might interact more cleanly with the clouds of compounds they process
- depending on how we represent compound/bacterial clouds, they may give the same aesthetic effect of business/diversity.  e.g.: if bacteria particles were spawned by the cloud, and moved within it.
- possible downside - clouds (even with spawned particles) don't play very well with the endosymbiosis concept.  It's not impossible, but it'd be a change from consuming individual cells for a small % chance of an unlock vs grazing continuously on them for an even smaller % chance

All of this is speculation though, and I know from previous experience that diffuse clouds can be somewhat finicky to work with, at least aesthetically.  So I've created a prototype ([here](https://github.com/Revolutionary-Games/thrive-prototypes/tree/master/bacterial_cloud)) of interacting bacterial clouds, compound clouds, and microbe agents, to test if and how this might be fun.  It's very much WIP (and right now, if anything, suggests this is a terrible idea), so any feedback is very welcome.

**Comment by TritiumH** [comment]
On that scale bacteria are clearly visible as different entities tough, 
https://www.youtube.com/watch?v=TwqBsRtciX8
I would say that displaying them as clouds would be worse as there would be less organisms in the environment to interact with, as you said Seregon bacteria could be a source of compounds, competition, or be real danger to the player (for instance oxygen is very reactive and is toxic for anaerobic organisms, that means that cyanobacteria are a thread if you still don't have mitochondria) Another thing we should look into is that glucose and amino acids don't just appear into the water, they are however in good quantity in bacteria( that are primary food for protozoan cells). So i would say that prokaryotic fauna deserves to be looked into not just for realism but more interesting gameplay.

**Comment by Lepticidio** [comment]
I agree with Tritium, to treat bacteria as clouds in this stage is unrealistic. As we discussed before, your cell could be as small as 10 upm, which is only 5 times bigger than average bacteria. Perhaps when multicellular is reached and you achieve certain size we could replace the bacteria agents with bacteria clouds.

**Comment by Untrustedlife** [comment]
I agree with both tritium and Lepticidio

(and what seregon said about endosymbiosis as I believe that mechanic to be very important)

**Comment by Moopli** [comment]
I do like the idea of bacteria providing colour and interest to the environment, but I think seregon is mistaken to suggest that bacteria can only be environmental if they are clouds. What I've suggested several times before (which nobody yet has argued against) is that a lot of (maybe even most) bacteria could be found in colonies of various forms, whether the long networked strands of cyanobacteria or small floating staphylococcus-like lumps that grow around dead eukaryotes, they won't be swimming around, just floating there, and will range from small environmental features to large-scale terrain. Large microbial mats (stromatolites, or the microbial mats that covered much of the bottom of shallow tropical seas before the Cambrian Substrate Revolution) form important biomes for early eukaryotes, so it isn't at all unreasonable to spend a lot of your time swimming through huge jungles of cyanobacteria. Obviously, microbes-as-clouds wouldn't give you that, but that's okay, becasue the important point of wanting a more interesting environment is fulfilled.

**Comment by DrChewbacca** [comment]
From a gameplay perspective being able to have terrain would be awesome. It allows so much more depth.

**Comment by tjblazer85** [comment]
Hey Guys, I'll try to make a few bacteria models

**Comment by tjblazer85** [comment]
I've searched for pictures of Bacteria and I've made a few models today!

Here is the Spore-Forming Bacteria:
![spore-forming bacteria](https://cloud.githubusercontent.com/assets/4619968/6769883/e453885a-d0e7-11e4-84fa-dd3ab4bb6d2d.png)

And here is the Bacillus Anthracis:
![bacillus anthracis](https://cloud.githubusercontent.com/assets/4619968/6769899/a1e8531e-d0e8-11e4-95df-4d6f723587d4.png)

The files for the models are in this link: https://dl.dropboxusercontent.com/u/137682043/Bacteria.rar

**Comment by tjblazer85** [comment]
Oh, I forgot to mention in the last post. I didn't subdivide the model that much because based on the other posts here, it's gonna be sized down a lot, so I thought that if it was just small the people playing it wouldn't notice that it's no that rounded. It would also help the engine run better since it's not rendering that many vertices and tris.

**Comment by tjblazer85** [comment]
Alright! I've made three more models! Diplococci, Cocci Tetrad, and Sarcina.

Here they are:
![diplococci](https://cloud.githubusercontent.com/assets/4619968/6775212/bc741f1c-d168-11e4-9e46-353c6fd35a2c.png)
![cocci tetrad](https://cloud.githubusercontent.com/assets/4619968/6775223/d392ea0c-d168-11e4-8d3e-fc64d97636a1.png)
![sarcina](https://cloud.githubusercontent.com/assets/4619968/6775225/d6694f96-d168-11e4-877c-4691d46f2a7b.png)

By the way, I've been using this as a reference image to make the models:
![bacteria picture](https://cloud.githubusercontent.com/assets/4619968/6775258/21067196-d169-11e4-99f9-4f53f0ea175a.jpg)

Can anyone give me the file for the flagelum model? I need it to make the ones on the right of the image above and also for the one in the very center of the image. However if the Flagellum can just be attached by the game to the model then I won't need it.

**Comment by jjonj** [comment]
This isn't the most up to date version but might be good enough: https://www.dropbox.com/s/eip0xe9gzb1pf0y/FlagellaTest3.blend

**Comment by tjblazer85** [comment]
Hey Guys, I've been looking at the other models and I wanted to make my models much better, and I figured out how to use the texture tab in blender! Hopefully my models are now up to par. I've redone the Bacteria models I've made and here's how they look like now.

The New and Improved Bacteria Models:
![spore-forming bacteria new](https://cloud.githubusercontent.com/assets/4619968/6841575/73b52990-d3c7-11e4-950a-fd6e7a9c4a82.png)
![bacillus anthracis new](https://cloud.githubusercontent.com/assets/4619968/6841566/5e23b7cc-d3c7-11e4-972b-9114995a75cd.png)
![diplococci new](https://cloud.githubusercontent.com/assets/4619968/6841577/7bcdc6be-d3c7-11e4-9b5c-6b7fbb2d5de5.png)
![cocci tetrad new](https://cloud.githubusercontent.com/assets/4619968/6841581/83a7cb64-d3c7-11e4-8179-907985c00352.png)
![sarcina new](https://cloud.githubusercontent.com/assets/4619968/6841584/875ab9e2-d3c7-11e4-8bce-20aedf318b3b.png)

New download link here: https://dl.dropboxusercontent.com/u/137682043/New%20Bacteria.rar

**Comment by Moopli** [comment]
Is the anthracis model a chain of bacteria, or did you just set up several copies for the render? I'd prefer to have them separate (or at least, in short chains) so we can make them form long, flexible chains and networks. The diplococci, tetrad, and sarcina will work without being split, since those types of bacteria naturally float around in groups of that exact shape and size (note though, that those ones shouldn't look like spheres, but look more fused together). Can you also produce a monococcus which we can use for strepto- or staphylo- cocci?

About their textures: do you think you could work in a shader that scales opacity to be highest edge-on and lowest head-on? If that's beyond your Cycles knowledge that's fine, I'm just interested in seeing if that we can get a microscope sort of look.

**Comment by tjblazer85** [comment]
Thanks for the feedback! I'll get to work on what you've posted, but before I start, I need some clarification. Do you want the cocci models to be just one model that the game will fuse together by itself or do you want the 3 models right now but I'll fuse them together more rather than have them be just fused next to eachother like it is now? Also can you elaborate more on how you want the models to be shaded or textured? Currently their shaded like that because I keep the light directly above the models or beside them when I render the inages.

**Comment by TheCreator--** [comment]
@tjblazer85, all you need to do is use a frenel shader. That way it will be fairly transparent when you look at it directly, but colorful on the sides.

If you guys want, I can send you a .blend file that I did for thrive a while ago.

Here is the link of it in action:
http://youtu.be/_kBdRXBu1MY

**Comment by Moopli** [comment]
@tjblazer85 We'll be using the models quite a bit, so I think it would be great to have the diplococci, tetrad, and sarcina meshes look like fused pairs/quartets/octets of spheres. 

One thing I'm not sure about is whether you should keep the interior meshes once you've made fused models. On one hand, the models are more lightweight if all the interior surfaces (the membranes between the bacteria) are gone, but on the other, the interior membranes would be visible using a transparency fresnel shader.

@TheCreator-- Thanks, I'd forgotten what that kind of shader is called. I thnk tjblazer might find that blend file really useful. Good reference -- I think we might want transparency to scale even stronger, so only the very edge is visible, so if you have some time to fiddle with the shader that would be awesome.

**Comment by TheCreator--** [comment]
@Moopli, fixing the shader to make it even more transparent should be extremely easy, I'll put a few tests onto here when I get home. 

@tjblazer85, if you use metaballs it should be extremely easy to make the cells fused.

**Comment by TheCreator--** [comment]
How is this?
https://youtu.be/rMO7ZI-iPpo

**Comment by tjblazer85** [comment]
@Moopli, @TheCreator-- , I'll try out the metaballs and the fresnel shader, I'll upload the models a little later if possible, if not then maybe by tomorrow.

**Comment by tjblazer85** [comment]
@Moopli, @TheCreator-- , I've made a quick test to see if I'm using the Fresnel Shader correctly. Should there still be color inside, none at all, or maybe somewhere in between?
![fresnel bacteria test](https://cloud.githubusercontent.com/assets/4619968/6880265/4b60e7aa-d565-11e4-8c20-862726dd055b.png)

**Comment by tjblazer85** [comment]
Here's a test with the Diplococci:
![diplococci metaballs](https://cloud.githubusercontent.com/assets/4619968/6880421/3553d78c-d56b-11e4-9791-a96654fc9216.png)
![diplococci metaballs 2](https://cloud.githubusercontent.com/assets/4619968/6880422/38ee607e-d56b-11e4-9f01-27bef9ed6325.png)
I'll put up a download link once we decide on how the textures should be like.

**Comment by TheCreator--** [comment]
Great job, that looks a whole of a lot better. Just don't forget to convert the metaballs back to meshes when you're done. 

Personally I prefer the one on the top. Also, if you want you could try using a colorramp to give it a light edge. Want me to send you my .blend file?

One more thing, is the bumpy look part of the actual geometry or did you use a bump map?

**Comment by tjblazer85** [comment]
Thanks! 

It would help if you could send me the file.

The Bumpiness is actually just a texture with a 0.700 normal applied on it. I like to keep my models for this game as simple as possible without comprimising how it looks, that way the game doesn't need that much ram to run.

**Comment by TheCreator--** [comment]
@tjblazer85, could you give me your email address because I am having trouble putting the link on dropbox.

**Comment by tjblazer85** [comment]
Sorry I wasn't able to post the models sooner but I've been busy and it was Holy Week last week, and Easter Sunday. However, without further delay, here are the new models!

![baccili](https://cloud.githubusercontent.com/assets/4619968/7040783/37986312-de05-11e4-9481-c9b7cc6fe1ef.png)
![spore-forming baccili](https://cloud.githubusercontent.com/assets/4619968/7040798/40f264a8-de05-11e4-8c54-364b101edb7e.png)
![diplococci](https://cloud.githubusercontent.com/assets/4619968/7040799/44b33748-de05-11e4-8f0a-f042fb3b81c4.png)
![cocci tetrad](https://cloud.githubusercontent.com/assets/4619968/7040804/48d46fa4-de05-11e4-9489-595527acebe1.png)
![sarcina](https://cloud.githubusercontent.com/assets/4619968/7040807/51ff6f5c-de05-11e4-9ccb-c595b07c15dd.png)

Download Link here: https://dl.dropboxusercontent.com/u/137682043/Bacteria%20(Fresnel%20Shaded).rar

P.S. The models look more rounded when they were metaballs. Speaking of which, I also have the metaball versions of the models in the rar. file just in case we need them. There are also metaballs for the Baccili but not the Spore-Forming Baccili because they don't combine into Baccilus Arthracis (Unless I'm wrong about that.).

@TheCreator--  My e-mail is tjtomenes@yahoo.com. Also I've tried a color ramp with the models.

**Comment by apinanaivot** [comment]
Hello. I modeled some particles/bacteria in blender
![paricles](https://cloud.githubusercontent.com/assets/12139741/7352578/3a1645b8-ed15-11e4-881d-ede8a3296add.PNG)
Download the blend file here:
https://drive.google.com/file/d/0BwiCSjcuG4RiQXBJMzkxU1V0VjQ/view?usp=sharing

**Comment by TheCreator--** [comment]
@apinanaivot Wow! That shader is amazing.

**Comment by jjonj** [comment]
> By the way, how high quality should the models be?

I have very little experience in pushing polys myself, all I know is that we haven't run into any issues yet.
Did you use anything fancy for that model? Our exporter doesn't support many of the more advanced features. You can find more here http://thrivegame.canadaboard.net/t1402-basic-blender-modeling-animation-and-exporting-to-ogre-tutorial

**Comment by TheCreator--** [comment]
Just wodering, would it make sense for all the bacteria to be procedurally generated? Because even if we have a lot of different models, we will probably always have more bacteria on the screen at any given point in time.

**Comment by Moopli** [comment]
That's a good idea, but I think it's just much easier to keep them looking bacteria-like when they're all artist-made, and there are few enough basic shapes that we can afford to do so.

Most bacteria on the screen would appear in large clouds -- all with the same model, etc. There would probably be no more than 10 distinct bacteria species on-screen at a time (and usually a lot less), so I think we could get by without too many. Much like compounds currently, you'll probably want to easily recognize the various bacterial shapes, so that probably precludes having too many different models anyway.

@apinanaivot: sorry for forgetting to respond -- we might have tons of them (low hundreds, even) on-screen at a time, and the most numerous would be tiny, but the biggest and least numerous would be on the scale of a hex, so we have a pretty wide poly-count range.

**Comment by TheCreator--** [comment]
Okay, and I assume we currently plan for them to have the swarming behavior prototyped by tjwhale?

**Comment by Moopli** [comment]
For the true swarms of bacteria, something even simpler would work perfectly fine. I wouldn't really consider it worth the developer effort to get the swarmiest bacteria pathing around intelligently, and if bacteria pathing ends up being the heaviest part of the game loop, then it wouldn't be worth anyway.

**Comment by lukaandjelkovic** [comment]
Is this still open? For which version is scheduled?

**Comment by jjonj** [comment]
It was scheduled for 0.2.5, but we're past that already so it'll just come in whenever it is ready.   
I expect moopli will finish it when he has the time!

**Comment by TheCreator--** [comment]
Here are the current release plans if you're interested:
http://forum.revolutionarygamesstudio.com/t/future-release-plans/129

**Comment by Untrustedlife** [comment]
They will perhaps be simply microbes without a nucleus that can be 1, or two hexes long, (which is in line with numbers, chloroplast being 2 hexes as stated earlier (in thrive they are 1 hex) mitochondria are 1 hex. have a chance of having flagella, and when absorbed would grant you something, eg a mitochondria, a chloroplast, a vaculoe etc. They will probably have their own membrane material (so they dont look like normal microbes). They will be subject to auto evo, which means they can change colors occassionally and could have cilia or flagella randomly given to them.  They could emit a cloud.(toxin vaculoe bacteria emitting their poisonous agent cloud) They will likely not be given AI and if they are given AI it will be very simple so we can still have many on the screen at a time, at this point im thinking spawning them in colonies of 2-4 would be good for our purposes.

They will act as goody bags/competitors.  Maybe we could occasionally give them pilus aswell.

**Comment by Untrustedlife** [comment]
I started implementing this last night, its going rather swimmingly.

**Comment by Untrustedlife** [comment]
![image](https://user-images.githubusercontent.com/4032123/38341802-0eb31c42-3840-11e8-9723-ef7a34e5ac78.png)

here is the state of the new implementation

**Comment by Untrustedlife** [comment]
status after tonight: 
![image](https://user-images.githubusercontent.com/4032123/38346765-e449fad0-385c-11e8-8067-210edba87f73.png)

**Comment by hhyyrylainen** [comment]
@Untrustedlife That's pretty cool. Did you expose the membrane generation parameters and tweak them for the bacteria that @TjWhale said that could make the bacteria look a lot different.

**Comment by Untrustedlife** [comment]
Lots of progress: bacteria now get cell walls, in fact you can now choose whether any microbe has a cell wall, a membrane, or whatever over covering you want to give them (as long as you are willing to make the shader, write the wrapping code for it) , it can also be set in json, and in default microbe lists, and bacteria get lots of other cool stuff and look like actual bacteria: 
![image](https://user-images.githubusercontent.com/4032123/38783880-61f5768e-40ce-11e8-92ef-8d9456950ab8.png)

**Comment by hhyyrylainen** [comment]
Everything except the models are implemented by this pr: https://github.com/Revolutionary-Games/Thrive/pull/564

**Comment by Untrustedlife** [comment]
This issue has been resolved, a contunation for the issue can be found here (for fleshing bacteria out more now that they are implemented) #565
