### ISSUE TITLE
Make species name capitalization conform to scientific naming (lower case second part)

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2937]
We've been told twice now that species names in real life only have the *first* word capitalized. So I guess we should update the default species name and name generator to only capitalize the first word.

**Comment by adQuid** [comment]
We might want to consider separate genus and species field. As a non-scientific nobody, I wouldn't think there was any rule I couldn't name my species "Steve" if I wanted.

**Comment by hhyyrylainen** [comment]
There is an error popup if you press enter with an invalid name.
Also this issue was meant as a way to make scientists more happy, not cry harder than before...
