### ISSUE TITLE
Review chunk food source balancing

### ISSUE THREAD

**Issue by Maxonovien** [Revolutionary-Games/Thrive#2943]
For 0.5.6.1 we nerfed total energy from big chunk by adding a 0.01 exponent to compound amount, arguing that it accounted for venting, but that's a) too much (should be closer to 0.66 for volume-to-surfact ratio) and b) uses a temporal logic that is absent else where in the auto-evo. It should thus be reconsidered. 

A possible lead is that big chunks and small have close or equal densities (like in the vents), yet an amount ratio of 300, which would arguably make big iron chunk an OP source IRL as well. So we should probably consider making them much rarer, with a lower density, among other solutions. Note that this will probably have gameplay implications to account for!

**Comment by hhyyrylainen** [comment]
I assume the new auto-evo makes this irrelevant, @GameDungeon ?

**Comment by hhyyrylainen** [comment]
I see. Someone did still at least have to read the code and move it to the new place. So maybe you can glance at it again to see if there are tweaks that are needed? If not then this can stay closed.
