### ISSUE TITLE
Choppy intro video on some hardware after Godot 3.4 update

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2946]
Got a report today and noticed on my laptop that in 0.5.6.1 (where we updated to Godot 3.4) the intro video playing is really choppy, like it shows single frames for like half a second type bad.

Most likely a Godot regression.

Seems like the microbe intro plays mostly fine, but towards the end that also gets choppy.

Opened a Godot issue: https://github.com/godotengine/godot/issues/55815

**Comment by RacerBG** [comment]
I can reproduce this too..

**Comment by hhyyrylainen** [comment]
Could you post what hardware you have? The Godot renderer line in the launcher output.

**Comment by RacerBG** [comment]
OpenGL ES 3.0 Renderer: AMD Radeon R7 250 Series
OpenGL ES Batching: ON

**Comment by hhyyrylainen** [comment]
And this is with a Godot version you downloaded / at least this isn't the steam version? I'm just confirming so that I can say this isn't a problem with my compiled Godot version, but their official binaries.

**Comment by RacerBG** [comment]
> And this is with a Godot version you downloaded / at least this isn't the steam version? I'm just confirming so that I can say this isn't a problem with my compiled Godot version, but their official binaries.

Yes, this is the official release from GitHub.

**Comment by Zireael07** [comment]
Worth reporting to the Godot engine repo IMHO.

**Comment by hhyyrylainen** [comment]
Didn't find an existing issue, so opened a new one: https://github.com/godotengine/godot/issues/55815

**Comment by RacerBG** [comment]
> Didn't find an existing issue, so opened a new one: [godotengine/godot#55815](https://github.com/godotengine/godot/issues/55815)

It's on Windows 7 SP1 but it doesn't really matter. I'm using the latest (supported) drivers and in the case of CPU I have AMD FX 8320 3.5 GHz 8 cores.

**Comment by hhyyrylainen** [comment]
Okay so based on the latest comment on the Godot issue, Godot has removed optimized webm playback (at least for Windows). So seems like we either need to get our own Godot builds going with better with better videoplayer format support (it's a separate plugin for Godot) or we need to convert our videos to theora format. That latter should be pretty easily doable however, I think we need higher bitrate with it to get as good video quality, causing a slight file size increase. Optimally we'd have the source video files to convert, but those might be lost to time. I can at least grab the intro video from 0.4.2 release as I think it was in a different format before the move to Godot.
