### ISSUE TITLE
Investigate auto-evo generated species that immediately starve to death

### ISSUE THREAD

**Issue by adQuid** [Revolutionary-Games/Thrive#2947]
There should be existing functionality that penalizes species that can't move without running out of ATP:
https://github.com/Revolutionary-Games/Thrive/blob/master/src/auto-evo/simulation/PopulationSimulation.cs#L260

But in practice this still happens often, with species emerging that immediately die off in game. This video has a lot of examples in the later half:
https://www.youtube.com/watch?v=fH2-gjqrZXw

It seems like this happens frequently in some games and not at all in others, suggesting that there might be a certain "scenario" that the set of species can get in (the environment is the same for all games at the time of writing) where non-osmoregulation species become viable, that occurs only in some games.

With any solution, implementer will need to make sure that auto-evo is still able to fill all sorts of niches. The reason the penalty was not set to set population result to zero (which might be a solution to this problem) was to give the AI a better chance of evolving some of the more complicated and expensive organelles.

**Comment by Maxonovien** [comment]
Do you mean what happened around 21'00, e.g.?

**Comment by Maxonovien** [comment]
It might be related to the fact that species get penalized *after* energy was actually shared (so after they had the opportunity to send other competitors to the ground). So they may actually get the best part of it and still be able to sustain the hit.

I didn't go in the details to check, but that's a lead I can offer.

**Comment by hhyyrylainen** [comment]
It would be pretty big change to change the logic of first determining good mutations etc. and only after then doing the final population calculations using the *original* species.

**Comment by Maxonovien** [comment]
I'd just suggest that we move such osmoregulation (or movement) penalties to energy share computations. But I haven't looked at the details of it, so perhaps I'm missing something here.

**Comment by hhyyrylainen** [comment]
This probably is maybe done now with the new auto-evo making much better species?

**Comment by hhyyrylainen** [comment]
I'll assume so and close this.
