### ISSUE TITLE
Make auto-evo not claim a species is extinct if external effects rescue it

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2958]
and conversely if external effects cause it to go extinct, that should be reflected in the report properly.
Should be a case of adding special handling in the report generation to detect if external effects exist for the current species and if they do, apply them. This might be better to do after https://github.com/Revolutionary-Games/Thrive/pull/2623 as I think that makes external effects record the patch they happened in

**Comment by CI09** [comment]
What would be the easiest way to trigger this bug?

**Comment by hhyyrylainen** [comment]
I think the player is affected (?) so you can make a really bad species that is stuck at 50 population and auto-evo should claim on the timeline or the report (with the red x) that the player is extinct each generation.
