### ISSUE TITLE
Add max length to the savename

### ISSUE THREAD

**Issue by FuJa0815** [Revolutionary-Games/Thrive#2969]
Linux and windows has a max filename of 255, which means 244 characters are usable (without the `.thrivesave` ending). The user can enter longer filenames and the saving crashes.

**Comment by hhyyrylainen** [comment]
Windows might additionally have total max path length limitation (depends on which API Godot uses to open a file for writing).

**Comment by hhyyrylainen** [comment]
@84634E1A607A what's the situation regarding this issue and your closed PR #2972 ?

**Comment by 84634E1A607A** [comment]
In my pr we agreed on adding aurowrap to save name. In the second pr I tested and proved that at least for now Godot is using an Windows API that only allow max path 260 (10) and 256 (11) (\0 included).

I have a local branch where I add a check before saving to test if a file can be created and written, but I came across some UI issues.
