### ISSUE TITLE
Make doubleclicking on a save save / load it

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#2970]
EDIT

When:

1. In SaveMenu double-clicking a save should display a override confirmation dialog and save the current game state using the item's name. (Current behavior: when you double-click on a save you select it then deselect)
2. In LoadMenu double-clicking a save should load it. (Current behavior: you select it then deselect)

There's a strange thing, that if you have selected a save to override, you can select one after it (appears downwards), but not one before it.

**Comment by hhyyrylainen** [comment]
Could you clarify *where* this should happen?

**Comment by hhyyrylainen** [comment]
Based on the forum thread (https://forum.revolutionarygamesstudio.com/t/save-load-menu-function/842) this seems to suggest that we add a new signal to save list that is triggered on double click and then the save and load menus handle it. The save menu should select the name of the double clicked file and trigger the save action. And the load menu should immediately trigger the load action for the double clicked save.

I think those will be fine changes.
