### ISSUE TITLE
Add an editor tutorial that triggers with negative ATP balance

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2976]
explaining the player that they can only move in bursts and saying they should probably reconsider if a storage heavy burst like movement is their wanted playstyle or if they should undo.

Alternative the tutorial could trigger the first time the player tries to exit the editor with negative ATP balance instead of immediately when placing something making their ATP negative.

**Comment by hhyyrylainen** [comment]
The tutorial should probably have the tutorial highlight on the organism statistics panel where the player can see the info.

**Comment by ender-titan1** [comment]
isn't this already implemented?

**Comment by hhyyrylainen** [comment]
Yep, you are right, this is a duplicate of: https://github.com/Revolutionary-Games/Thrive/issues/2683
