### ISSUE TITLE
Complete quoting for parameters of some CMake commands

### ISSUE THREAD

**Issue by elfring** [Revolutionary-Games/Thrive#298]
Some parameters (like "[${ASSET_DIRECTORY}/models](https://github.com/Revolutionary-Games/Thrive/blob/7488252efb4b4af4d7e022fc204f9c6b00ecef9f/CMakeLists.txt#L24)" and "[${CMAKE_CURRENT_SOURCE_DIR}/component.cpp](https://github.com/Revolutionary-Games/Thrive/blob/356f0070899c2b16009ad053566866eb1f393231/src/engine/CMakeLists.txt#L3)") are passed to CMake commands in your build scripts without enclosing them by quotation marks. I see that these places will result in build difficulties if the contents of the used variables will contain special characters like semicolons.

I would recommend to apply [advices from a wiki article](http://cmake.org/Wiki/CMake/Language_Syntax#CMake_splits_arguments_unless_you_use_quotation_marks_or_escapes. "CMake splits arguments unless you use quotation marks or escapes.").

**Comment by elfring** [comment]
Thanks for the improvement of your build scripts.

**Comment by jjonj** [comment]
Thank hhyyrylainen :)
