### ISSUE TITLE
Duplicate mod entry appears if refresh is pressed after disabling a mod

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2986]
but the changes are not applied

https://cdn.discordapp.com/attachments/544711481900662812/922669942518710312/InterstignThriveBug.webp

So:
- go to the mod manager
- enable a mod and apply changes
- disable that mod but don't apply changes
- hit refresh, a duplicate entry should now appear
- re-enable the mod, now there are two of the same mod in the enabled mods list

**Comment by Generatoror** [comment]
Just to make sure, the intended behaviour is that the mod remains on the available list but does not reappear on the enabled list?
Regardless of the case i believe a simple fix can be done for 0.5.7 although a sligthly more complex fix may be better long term.

**Comment by hhyyrylainen** [comment]
Yeah, there shouldn't be multiple entries. And the one that there is should be in the list that makes sense (so if the player hits "apply" what happens should match where visually the mod is).
