### ISSUE TITLE
Organelle move's same-position check doesn't take into account organelle rotation

### ISSUE THREAD

**Issue by Kasterisk** [Revolutionary-Games/Thrive#2993]
Doing a "move" action for a hex but not exactly moving it, however with a different rotation just outright cancels the action when you finishes the move action. The common expectation would be for it to be accepted as a valid move since the rotation has changed (and costs no MP as per the code documentation).

**Comment by hhyyrylainen** [comment]
What exactly do you mean? Is this related to: https://github.com/Revolutionary-Games/Thrive/issues/2105 ?

At least multi hex organelles can be rotated in-place. So is the issue that rotating a single hex organelle is not correctly detected as it being changed when using the move action?

**Comment by Kasterisk** [comment]
Yes, so for example when moving flagellum into its exact position but different rotation, the game doesn't interpret it as a move action and thus the final placement just falls back into the previous rotation.

The problem described in that issue sounds similar so yeah it might be the same.

**Comment by hhyyrylainen** [comment]
Where was this implemented? If I remember right even the dynamic MP stuff still has the TODO comment for this.

**Comment by Kasterisk** [comment]
As far as I know moving organelles in-place is now possible, it was the main complain of this issue.

**Comment by hhyyrylainen** [comment]
Ah yeah, you are right, I was thinking of this issue: https://github.com/Revolutionary-Games/Thrive/issues/2105 so if you tested this 2993 issue as fixed, then that's fine.
