### ISSUE TITLE
Hook up Afrikaans and Romanian in the game

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3019]
they were created on the translations site, sadly they haven't been started yet, but to keep the language files up to date they need to be added to the update script and might as well add to the game locales list at the same time.

https://translate.revolutionarygamesstudio.com/projects/thrive/thrive-game/af/
https://translate.revolutionarygamesstudio.com/projects/thrive/thrive-game/ro/

**Comment by hhyyrylainen** [comment]
Added those two to the update localization script, didn't yet add them to the game as the progress is 0%.

**Comment by GodOfKnowledge** [comment]
Lol, the title gave other ideas, looks good tho.
