### ISSUE TITLE
Make proper collision shapes for the game objects

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3022]
instead of using hundreds of vertices large shapes that seem mostly to be directly converted from the visual meshes.
![Kuvakaappaus - 2022-01-14 15-37-23](https://user-images.githubusercontent.com/3796411/149526296-a3cab417-4605-4513-a2eb-71ed1bdfb3b1.png)

We can either use primitive shapes or vastly simplified meshes for them (that's why I tagged both modelling and programming).

**Comment by Kiloku** [comment]
It's possible to generate "simplified" versions of the meshes at runtime and use them as collision shapes, using the [CreateConvexShape](https://docs.godotengine.org/en/stable/classes/class_mesh.html#class-mesh-method-create-convex-shape) function from Godot.   
I wish this was more controllable, so there could be varying levels of simplicity, but even then, this would immediately reduce the complexity of collision shapes. 
I did it crudely as an experiment, and it worked in the sense that it definitely used simpler shapes with less polygons, but I don't know if it had a noticeable impact on physics processing time. It also made the collision of large iron chunks a bit too simple, so you could end up colliding with the collision shape despite visually not touching it yet.  
![image](https://user-images.githubusercontent.com/4577144/182928210-97827fb7-4fd3-4998-9309-88f0f885f455.png)

**Comment by Kertit** [comment]
Found this short but useful video for blender artist. 
Explaining how to manually add collision shape to any created mesh https://www.youtube.com/watch?v=rkVT252z1y8

**Comment by hhyyrylainen** [comment]
That video doesn't exactly match our workflow. We just use whatever method to get a mesh instance into the game and that can be converted into a collision shape and saved with the Godot editor as a ".shape" file. Currently most organelles use their *visual* model with hundreds of triangles as their collision shape, which is very terrible.

**Comment by hhyyrylainen** [comment]
Also one thing to consider would be a code approach where we could make a script that when ran would go through all the existing models and do that automatic conversion and then save the results, though that would need more programmer time rather than using something like Blender to create the low-poly collision meshes.

**Comment by Kertit** [comment]
mhhh.. okay I see. 
I admit this is not a very usual way to make good 3D models/collisions. 
The usual way is to model the collision shape in same time we model the visual model. It was not asked/mentionned for all the previous model so yeah now it would require to them all. 
Never heard of a programmer way to generate good collision. that might take a huge time/effort compared to any artist making a very low poly collision shape

**Comment by K0chiko** [comment]
I am creating collision meshes.

**Comment by K0chiko** [comment]
I created meshes with collisions for iron chunks. If these items are ok, I will be work on the rest.

You can found it there 
https://dev.revolutionarygamesstudio.com/files/Assets/Environment?sortDirection=Descending

There is a raw file
https://dev.revolutionarygamesstudio.com/files/Raw%20Assets/Models/Environment

**Comment by hhyyrylainen** [comment]
The file formats seem fine. So that takes care of all of the iron chunks. There's still some other chunk types. And maybe the organelles though maybe the consensus there will be that they don't need models (just using small spheres will be enough).

I'm in the middle of a huge refactor of code and I can't really well interrupt that work, so some other programmer will need to put these into the game.

**Comment by K0chiko** [comment]
I added icehard and cilia with cube collision.
Cilia 
https://dev.revolutionarygamesstudio.com/files/Assets/Organelles/cilia.glb?sortDirection=Descending

Ice and Iron
https://dev.revolutionarygamesstudio.com/files/Assets/Environment?sortDirection=Descending

I found just 5 iron chunks. In the godot iron1 and iron2 named as IronRock1 and IronRock2 (I don't why).
Are there other chunks?
I didn't find anything else

**Comment by hhyyrylainen** [comment]
I renamed those two files as the iceshard had a typo and I clarified the cilia is the collision.

And the 5 irons + iceshard are the current models used by chunk collisions. I don't know why the iron files are named like that either, they've been like that for a really long time.

For reference this is the full list of used shapes currently by floating chunks (I think, other chunks / when spawned as cell corpse chunks just use a sphere with radius 1 as the collision shape):
```json
              "convexShapePath": "res://assets/models/Iceshard1.shape"
              "convexShapePath": "res://assets/models/Iron3.shape"
              "convexShapePath": "res://assets/models/Iron4.shape"
              "convexShapePath": "res://assets/models/Iron5.shape"
              "convexShapePath": "res://assets/models/IronRock1.shape"
              "convexShapePath": "res://assets/models/IronRock2.shape"
              "convexShapePath": "res://assets/models/organelles/Chemoplast.shape"
              "convexShapePath": "res://assets/models/organelles/ChemoSynthesizingProteins.shape"
              "convexShapePath": "res://assets/models/organelles/Chloroplast.shape"
              "convexShapePath": "res://assets/models/organelles/Chromatophore.shape"
              "convexShapePath": "res://assets/models/organelles/Metabolosome.shape"
              "convexShapePath": "res://assets/models/organelles/Mitochondrion.shape"
              "convexShapePath": "res://assets/models/organelles/Nitrogenase.shape"
              "convexShapePath": "res://assets/models/organelles/NitrogenFixingPlastid.shape"
              "convexShapePath": "res://assets/models/organelles/Nucleus.shape"
              "convexShapePath": "res://assets/models/organelles/Oxytoxy.shape"
              "convexShapePath": "res://assets/models/organelles/Rusticyanin.shape"
              "convexShapePath": "res://assets/models/organelles/Vacuole.shape"

```

**Comment by K0chiko** [comment]
Done!)
All organelles meshes from list above here
https://dev.revolutionarygamesstudio.com/files/Assets/Organelles/Organelles%20with%20collision?sortDirection=Descending
Raw file here (organelles with collision.blend)
https://dev.revolutionarygamesstudio.com/files/Raw%20Assets/Models/Organelles

**Comment by HexapodPhilosopher** [comment]
I can take over this issue, as I seem to have found the right workflow for it.

I still haven't managed to get collision shapes to show for debugging in game, though. How is this activated?

**Comment by hhyyrylainen** [comment]
> How is this activated?

You need a debug version of the Thrive native library, then F7 toggles between physics debug levels (and running Thrive from Godot editor to make the game prefer the debug version).
I'll just compile a debug variant now and upload so that it can be gotten with the native fetch script when provided with the `-d` parameter.

**Comment by hhyyrylainen** [comment]
Iron models are now done, but removing the scale workaround now means that the organelle models need updating soon to get them back to working. Once that is done this issue should be fully taken care of.
