### ISSUE TITLE
Add caching for membrane data

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3024]
I think much of the small lag spikes associated with moving around in the microbe stage are related to cells spawning in. From my profiling it seems the most time intensive part of this is the membrane generation. I think we could improve this by having a global cache of membrane data.

I think we'll need to consider how big the cache should be, but then again I think it could be as big as 100MB and wouldn't be a problem, but if someone plays for a while there certainly should be some kind of cleanup going on to remove membranes that aren't needed.

Additionally this could be rolled into like a ProceduralDataCache singleton node that could also hold other kind of data as well. It could clean itself up like once a second (at least partially to not make it not take that long, as a consistent slow frame every second wouldn't also feel the best). And as one final thing that singleton could be told which stage is entered in the game so it could clear unnecessary data immediately on stage change.

**Comment by Zireael07** [comment]
If lag spikes occur when spawning in, then in my experience it's likely it's shaders compiling...

**Comment by hhyyrylainen** [comment]
All microbes use the same shader, and yeah, I think there is a bit of extra lag when the stage is started first when all of the shaders are first used. But the membrane generation shows up in profiling results as one of the most expensive methods https://forum.revolutionarygamesstudio.com/t/increasing-game-performance/841
