### ISSUE TITLE
Make our custom colour picker set non-scrollable property on the colour value bars

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3037]
otherwise trying to scroll over them causes the values to change.

Noticed this is especially bad in the organelle modify menu for the chemoreceptor, and causes warnings about a control that can't grab focus

**Comment by hhyyrylainen** [comment]
What's a value box? I can't think of what you mean...

**Comment by 84634E1A607A** [comment]
The the value box to the right of the scroll bar.

**Comment by 84634E1A607A** [comment]
When it grabs the focus, you can scroll it with the mouse to change its value.

**Comment by hhyyrylainen** [comment]
Presumably when it has focus the scroll bar doesn't move or? If that's the case then we have a bunch of other value input boxes that are in scrollable containers.
