### ISSUE TITLE
Make chemoreceptor upgrade auto select the compound's colour

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3043]
could make the chemoreceptor auto select the compound's colour when selecting one, this would make it faster to configure multiple chemoreceptors for different compounds to look for.

Just needs a callback for the option button to detect when it changes value, and then just looking up the compound colour and setting that on the colour picker. Could maybe only change the colour if it is white or one of the other compound's colour. That would make it less annoying for players as if they first selected a custom colour and then selected a different compound, they'd lose that colour without that check.

**Comment by 84634E1A607A** [comment]
What about getting compound colors to presets?

**Comment by hhyyrylainen** [comment]
I guess that could be an alternative, though I didn't add a separate preset group for the chemoreceptor. That's because I thought it makes more sense for the player to be able to carry over the presets they set on the membrane tab to the chemoreceptor colour picker.
