### ISSUE TITLE
CustomDialog corner drag cursor sometimes fails to show

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#3048]
Now drag at the corner works fine but no proper cursor is displayed.

**Comment by Kasterisk** [comment]
It displays the proper cursor for me, maybe this is platform-specific issue.
![2022-02-01](https://user-images.githubusercontent.com/54026083/151929125-c1d4454c-713a-4dd4-9ec7-ee94ff580b59.png)

**Comment by hhyyrylainen** [comment]
Shows correct cursor for me as well on Linux.

**Comment by 84634E1A607A** [comment]
Not working for me.

Linux Mint 20.3 x86_64
Kernel: 5.4.0-96-generic
DE: Cinnamon 
WM: Mutter (Muffin)
WM Theme: Mint-Y-Dark-Blue (Mint-Y-Dark)
Icons: Mint-Y-Dark-Aqua [GTK2/3]

**Comment by hhyyrylainen** [comment]
Perhaps related to your desktop environment or icon set?
Working for me on Fedora 35 with the default Gnome desktop.

**Comment by 84634E1A607A** [comment]
![image](https://user-images.githubusercontent.com/60734649/151948376-ebc2da23-4cd2-463c-aec6-cb94883129c9.png)

This is my cursor set. OS uses drag cursors on line 2, while we use those on line 5 and corner drag not available. Maybe a Godot problem.

**Comment by 84634E1A607A** [comment]
Mostly an engine problem.

**Comment by RacerBG** [comment]
On Windows 7 SP1 64 bit it works as intended with version 0.5.7 RC1.

**Comment by 84634E1A607A** [comment]
I'll just close this because this problem went away after upgrading my Mint to 21.1.
