### ISSUE TITLE
Pause menu overlay doesn't cover the whole screen if window is resized

### ISSUE THREAD

**Issue by Kasterisk** [Revolutionary-Games/Thrive#3061]
Due to Popup's nature of not resizing automatically relative to anchors (afaik). May need to have PauseMenu inherits CustomDialog instead to use the FullRect property to fix this.

**Comment by 84634E1A607A** [comment]
But dialog has its background...

Add a connection to viewport is a solution, but it produces duplicated code.

**Comment by Kasterisk** [comment]
We can add a new property to CustomDialog to disable decorations.
