### ISSUE TITLE
Chemoreceptor should have option to detect other cells

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3072]
some kind of selection for specific species or like predator or prey (based on some criteria).

**Comment by silentiumNoxe** [comment]
user cell has an invisible circle for detection of some objects
each game tick each cell should check "I inside in detection circle?". Formula x^2 + y^2 <= R^2 where R - radius

**Comment by adQuid** [comment]
There is existing code in Microbe AI to look for nearby microbes: https://github.com/Revolutionary-Games/Thrive/blob/master/src/microbe_stage/MicrobeAI.cs#L393

Existing code for hunting compounds is here: https://github.com/Revolutionary-Games/Thrive/blob/7fbc7f7cf18cc3565d1854b9d6990f306cbae3bc/src/microbe_stage/Microbe.cs#L883

I'm not sure where the Microbe class would get the list of all microbes from.

**Comment by hhyyrylainen** [comment]
Probably nowhere, I think putting this into the stage class likely makes sense as that's where the player compound detections is also handled. That also means that the performance impact can be tuned just right by modifying how often the player guidance lines find new targets.

**Comment by hhyyrylainen** [comment]
Hmm, well a bunch of AI species will get just all organelles slapped on them by auto-evo. So it might not be much more useful to have a general "detect any cells not of player species" option. Also we should have some scientific basis for the detection, organelles probably don't cause cells to emit certain compounds when they have them, so detecting organelle types wouldn't be necessarily realistic.

**Comment by hhyyrylainen** [comment]
One theorist chimed in saying that it is probably not possible to detect what organelles are contained in other cells. So I really think the original description: allowing detecting cells of a certain species, cells of the player species, or cells of non-player species should be the options. For picking the player's prey / predator a change like: https://github.com/Revolutionary-Games/Thrive/issues/3652 would be good way to tell the player what species they should configure chemoreceptors to find.
