### ISSUE TITLE
Timeline should not claim the player is extinct if rescued by external effects

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3086]
If auto-evo thinks the player should go extinct, but the player manages to get to the editor without dying they will get 50 population from reproducing. This causes the timeline to show each time the editor is entered that the player is extinct even though currently auto-evo can't make the player extinct.

**Comment by hhyyrylainen** [comment]
Also other species should have external effects taken into account before saying they went extinct (entirely or in a patch).

**Comment by Kasterisk** [comment]
This likely depends on #2958.
