### ISSUE TITLE
Add a hotkey to toggle the microbe stage pause feature

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3108]
this will make it easier to pause the game while trying to mouse over a cell.

This should be easy just need to:
- add key to godot project
- to our JSON config
- add translations
- add the code to the microbe stage that uses our input system to detect when it is pressed and forward that to where the clicks on the pause button go

**Comment by Kasterisk** [comment]
I'd suggest <kbd>P</kbd> for the key as usual in most games but that's already taken by the phosphate cloud spawn cheat... so maybe backtick button? And if we end up adding command console then it can just use the tilde button, that is <kbd>Shift</kbd>+<kbd>`</kbd>

**Comment by hhyyrylainen** [comment]
Might be good to try the new physical keys here as backticks and other punctuation that could be used here varies by keyboard layout. Then again maybe it makes more sense for the cheat keys to get moved to the weirder keys.
