### ISSUE TITLE
Clean up all systems and components and ensure compliance

### ISSUE THREAD

**Issue by jjonj** [Revolutionary-Games/Thrive#311]
Systems should handle all logic and components should only contain data and some flagging capabilities. This is in part for serialization which we handle quite well, but also for parallelization.

This will present some challenges due to things sometimes depending on instant effects and other tricky situtations but it should at least to cleaned up as much as possible.

**Comment by hhyyrylainen** [comment]
I'm not 100% if we should go for this as many systems don't follow the "components are just data" principle.

**Comment by hhyyrylainen** [comment]
In fact I'll close this.
