### ISSUE TITLE
Feature request: go back to last split

### ISSUE THREAD

**Issue by JanKaifer** [Revolutionary-Games/Thrive#3115]
I advanced to an environment without Amonnia and didn't equip any ammonia-making organelles.
That means I can survive, but I can't reproduce and therefore I'm stuck here until I restart.

I just started the game and advanced to the second "Patch".

EDIT: I was just not able to find it. Looked again at the Path info and It had 4%.

**Comment by hhyyrylainen** [comment]
Regarding actually making bad decisions in the editor and needing to go back, I opened an issue about making a tutorial how to get out of it a while ago: https://github.com/Revolutionary-Games/Thrive/issues/2979
