### ISSUE TITLE
Figure out a way to clear dependencies between systems to make ordering unimportant.

### ISSUE THREAD

**Issue by jjonj** [Revolutionary-Games/Thrive#312]
Some systems currently require other systems to run first, this is e.g. the case for physics running before rendering and a number of other things that causes crashes and bugs. Fixing these would be necessary to make things run in parallel, although it wouldn't be required that everything be independant for some things to run in parallel.

Good luck!

**Comment by hhyyrylainen** [comment]
This is probably impossible to do well, so I say we should just focus on getting as much parallelism as possible: https://github.com/Revolutionary-Games/Thrive/issues/314
