### ISSUE TITLE
Refactor components to lie continiously in memory.

### ISSUE THREAD

**Issue by jjonj** [Revolutionary-Games/Thrive#313]
Components are currently spread all over the heap but we want them to lie grouped in memory. This will likely involve some custom allocators and/or object pools. It will also be necessary to stop lua from creating component objects itself, but instead rather request them from C++ side and have C++ handle the memory management.

**Comment by jjonj** [comment]
I worked on this issue for a while but there kept being some issue with invalid memory that I couldn't quite get to the bottom of, mainly relating to code going through luabind.
http://pastebin.com/3mz0Rt2c

**Comment by hhyyrylainen** [comment]
This is done with the new engine.
