### ISSUE TITLE
Timeline history cleaning logic has a bug (in global timeline view)

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3135]
It's been reported that the timeline always removes events at 2100 Myr to 2700 instead of actually removing the oldest stuff like it should. Probably the way it detects the oldest things to delete is wrong.

**Comment by hhyyrylainen** [comment]
Save file where this issue occurs:
[Devonium_Spiculum.zip](https://github.com/Revolutionary-Games/Thrive/files/8392135/Devonium_Spiculum.zip)

**Comment by CI09** [comment]
[2100Myr.zip](https://github.com/user-attachments/files/16522542/2100Myr.zip)
I can't get this to happen. Consider this no longer a thing maybe?
