### ISSUE TITLE
Job scheduling system

### ISSUE THREAD

**Issue by jjonj** [Revolutionary-Games/Thrive#314]
Not all systems need to run every frame, and once they're more decoupled (see #311 and #312) we can make use of a job scheduler (or task scheduler) which queues up systems to run, and forks out threads to run them. 

In the simplest case, a job is just the name of a system, and the job queue is just that, a simple queue which worker threads pull jobs off of.

We might need a bit more sophistication going forward:
- Task dependencies -- certain types of calculation (eg, CPA) will be split across several systems which should run in a certain order.
- Task urgency/priority -- some tasks are long-running, or don't need to run too often, and could afford to wait longer in case there's a system which needs to run every frame that should take precedence.
  - This might just be solved by having seperate queues and worker threads for long- vs. short-running jobs.
- A more complicated queue system, to avoid contention between workers.

http://www.gamasutra.com/view/feature/132675/sponsored_feature_doityourself_.php?print=1
http://fabiensanglard.net/doom3_bfg/threading.php

**Comment by Moopli** [comment]
https://molecularmusings.wordpress.com/2012/04/05/building-a-load-balanced-task-scheduler-part-1-basics/

**Comment by hhyyrylainen** [comment]
This needs engine support to allow specifying which systems depend on each other and then running non-conflicting ones simultaneously.
