### ISSUE TITLE
Auto-evo prediction panel and extra info don't react to language change

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3147]
they are already LocalizedStringBuilder instances so just should need to hook up so that they are reconverted to strings and passed to Godot when language changes.

**Comment by CI09** [comment]
Is this bug still present? I couldn't get it.

**Comment by hhyyrylainen** [comment]
I can confirm the prediction panel now reacts to language change. I likely fixed this when converting to showing the total gathered energy but did not remember to close this issue.
