### ISSUE TITLE
[Bug]Zooming out causes microbes to become darker

### ISSUE THREAD

**Issue by Alex-the-666** [Revolutionary-Games/Thrive#315]
Title explains all.

**Comment by Moopli** [comment]
Not sure if bug or feature, it's because we decided to attach the light source to the camera.

**Comment by Alex-the-666** [comment]
Hmm. maybe you could have the light fixed for box X position and Z position, however making Y position static would be a simple fix.

**Comment by jjonj** [comment]
Yeah should be an easy fix, also low priority for the moment ;)

**Comment by Alex-the-666** [comment]
ok

**Comment by MontySpud** [comment]
This one seems to be solved already.
