### ISSUE TITLE
Add some way to view preview images of species in the report tab

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3152]
now that I got this done: https://github.com/Revolutionary-Games/Thrive/issues/2882 the hard part of this is done, images of species can be generated (well at least cells, might need a tiny bit of extra plumbing to hook things up to make images of Species objects directly). Should be implemented something like hovering over species names or clicking them opening a small hovering panel to open that shows the image (and maybe some other stats of the species).

**Comment by GameDungeon** [comment]
Is this now complete with the thrivopedia being implemented? https://suggestions.revolutionarygamesstudio.com/posts/58/show-pictures-of-other-species-as-they-look-in-the-editor-so-we-can-see-what-evolution-is-doing

**Comment by 84634E1A607A** [comment]
I think this wants to add preview to the editor, while thriveopedia being a separate, independent feature.

**Comment by hhyyrylainen** [comment]
Yeah, this is talking about a way to preview in the editor directly, I imagined that hovering over a species name anywhere in the editor would show a tooltip that shows basic info and image of the species. This is related to https://github.com/Revolutionary-Games/Thrive/issues/4043 but not the same, I imagine as I said before, that this would be a really quick preview and that issue #4043 is about making the names clickable to take the player to full info about the species.

**Comment by hhyyrylainen** [comment]
Follow up "bug": https://github.com/Revolutionary-Games/Thrive/issues/4842
