### ISSUE TITLE
Prevent unintentional cannibalism when species type changes to multicellular

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3155]
cannibalism is possible while there exists cells of the player's previous species as the microbe species instance is not equal to the early multicellular species instance

**Comment by Doomsdayrs** [comment]
Is that bad? I think its pretty fun to try and eat out the older species

**Comment by hhyyrylainen** [comment]
It's not open as an issue but I think there's a comment in the source code that says that cannibalism is prevented until a proper drawback is designed and implemented in the game for it. As such multicellular shouldn't unexpectedly turn into a cannibalism feast.
