### ISSUE TITLE
Species Name Requirement

### ISSUE THREAD

**Issue by Alex-the-666** [Revolutionary-Games/Thrive#317]
Currently, the species name is a small box at the top right of the microbe editor. It is easy to miss, and new players are likely to pass over it. This is bad because later in the game the player(and their species) would simply be referred to "species". I suggest that as soon as a new game is created a prompt comes up to name the genus of your species. The Genus could be completely handled and customized by the player, while the species could be completely randomized each time the player evolves. It's also possible for players to assign their species a "nickname" of sorts, but only after sapience has been achieved, so that's still a while into the future. 
some examples include:

genus species (nickname)

Tyrannosaurus rex (Tyrannosaurus)
Vulpes zerda (Fennec Fox)
Eublepharis macularius (Leopard Gecko)
Ambystoma maculatum (Spotted Salamander)
Anomalocaris canadensis (Anomalocaris)
etc.

**Comment by MontySpud** [comment]
Ive got this Covered, i think. The files are done!

**Comment by Moopli** [comment]
Issues shouldn't close until the fix is on master, or we choose not to fix it.
