### ISSUE TITLE
Fix lag spikes when rotating player cell for some players

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3177]
We've had quite a few reports here and there about lag spikes when rotating. Here's a video demonstrating it: https://cdn.discordapp.com/attachments/958598553389903913/962563059925254164/Build_2022.04.09_-_21.59.18.02_Trim.mp4

Seems that only some players are impacted. I had one player report that when they used a different mouse the problem went away.

This is a very weird issue as there shouldn't really be anything special happening when the player cell is rotated.

**Comment by RacerBG** [comment]
I can confirm this but I thought that it was an issue related to the multicellular prototype. Cell rotation during the microbe stage does not cause any visible lag at least for me.

**Comment by hhyyrylainen** [comment]
So the rotating lag might be related to rotating larger physics bodies? If there is some special extra check that snapping the rotation causes, then this lag might be fixed by https://github.com/Revolutionary-Games/Thrive/issues/2112

**Comment by Kemikal1** [comment]
"So the rotating lag might be related to rotating larger physics bodies"
I agree, it kinda makes sense because you change the position suddenly for a lot of shapes

**Comment by hhyyrylainen** [comment]
Shows up on SonOfmowgef's latest thrive video near the end: https://www.youtube.com/watch?v=XCmyJGFSf00

Another user also reported that it seems that the lag is proportional to how fast the player is rotating around.

**Comment by MalgosYT** [comment]
Yup, that was me. I have also found that when other multicellular creatures other than the player rotate it does not cause the lag spike at all which might be because of the difference in how the player rotates versus the AI as the mouse gives a lot more information about where to rotate

**Comment by MalgosYT** [comment]
https://youtu.be/qR3wy9fKeWg
All the lag in this video is because of the rotation
I have an RTX 2060, an I5 9600k and 16GB ram

**Comment by hhyyrylainen** [comment]
Thanks for having the metrics panel on. I see slight peaks in the physics processing time, but nothing really conclusive in there. Might truly be an engine bug where mouse input handling or something is very slow. I hope it isn't caused by our tooltip system or something having too many nodes to check mouse hover with...

**Comment by hhyyrylainen** [comment]
Duplicate of: https://github.com/Revolutionary-Games/Thrive/issues/3001
