### ISSUE TITLE
Find a way to force ogre to enable anti aliasing

### ISSUE THREAD

**Issue by jjonj** [Revolutionary-Games/Thrive#318]
Otherwise the game will flicker after the upgrade with ogre 2.0
A solution to this could be to handle the graphics settings ourselves instead of having the ogre dialog.

**Comment by TheCreator--** [comment]
You guys are using OpenGl instead of DirectX, right? If not, I might be able to help—I am currently working on a DirectX 11 engine that supports multi-sampling and full screen.

**Comment by hhyyrylainen** [comment]
Wouldn't that be a bit of an overkill? A simple config file parser and a
launcher dialog would be sufficient,  and probably easier to integrate.
9.7.2015 6.33 "TheCreator--" <notifications@github.com> kirjoitti:

**Comment by jjonj** [comment]
> You guys are using OpenGl instead of DirectX

We are using openGL indeed but thanks anyway!  

I'm halfway making in-game graphics settings which we would need eventually anyway!

**Comment by jjonj** [comment]
Closing this as flickering was already fixed
