### ISSUE TITLE
Mention binding related keys in the help menu

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3183]
the keys for binding mode and unbinding aren't mentioned in the help menu.

Can be done on weblate.

**Comment by RacerBG** [comment]
https://translate.revolutionarygamesstudio.com/translate/thrive/thrive-game/en/?q=binding&sort_by=-priority%2Cposition&offset=1

> By binding with other cells, you can build a cell colony where the cells share the compounds they absorb and produce with each other. In order to be able to bind with another cell, you need to have the binding agents organelle and move into them after entering binding mode by pressing [thrive:input]g_toggle_binding[/thrive:input]. You can only bind with cells of your own species. While in a colony, you can't divide your cell and enter the editor (for now). To enter the editor, first leave the colony once you have collected enough compounds, and then enter the editorby pressing [thrive:input]g_unbind_all[/thrive:input] and then collect the required compounds. Large cell colonies are the way towards multicellularity (not in the game yet).

This should close the issue once it's approved.

**Comment by hhyyrylainen** [comment]
Done on Weblate now.
