### ISSUE TITLE
Toxins in other cells in a colony need to fire as well (oxytoxy vacuoles)

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3192]
at least this has been complained related to multicellular that other cells should fire as well in a colony

**Comment by Doomsdayrs** [comment]
What also should be a case is selective vs unselective firing.

Selective: Firing at where the mouse is pointing to
Unselective: Firing in all directions

**Comment by hhyyrylainen** [comment]
This was already done: https://github.com/Revolutionary-Games/Thrive/pull/3307
