### ISSUE TITLE
Add tooltip for the become macroscopic button

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3205]
right now it has none.

**Comment by CI09** [comment]
Sorry for bothering, but where is tooltip data (the messages for specific GUI elementd) stored? Is it some JSON file?

**Comment by hhyyrylainen** [comment]
You can check the microbe HUD scene for how it is done. Looks like it us using just a basic tooltip.

![image](https://github.com/Revolutionary-Games/Thrive/assets/3796411/13381169-939f-4a57-9a2c-2a6bcc0593c8)

So just set a translation key on the hint, run the localization script tool and then fill in the text with Poedit in `en.po`.

**Comment by CI09** [comment]
I tried to run localization script tool `dotnet run --project Scripts -- localization` and it gave me error back complaining about msgmerge not installed or not in PATH. I installed gettext v0.21 and added msgmerge.exe in bin folder to PATH so I don't know why is that happening.

**Comment by CI09** [comment]
Is it okay if various .po files are marked as changes with changes being things such as POT creation date and some changes related to lines in certain scripts? Should I add them to commit?

**Comment by hhyyrylainen** [comment]
If you run the code checking tools locally, you'll discover what's my opinion on it (it must be immediately deleted).
