### ISSUE TITLE
Add this to the mingw readme somewhere

### ISSUE THREAD

**Issue by jjonj** [Revolutionary-Games/Thrive#321]
To let codeblocks run thrive and have things like breakpoints work
"You need to go to Project->Properties->Build Targets then select Install on the left and Type: from GUI application to Console application.  Finally change Output Filename to "dist\bin\Thrive.exe" (without the quotes). If it tells you that the file already exist or something like that click okay. Finally, click okay and exit. To check to see if it works click the Run button (green arrow). "

**Comment by TheCreator--** [comment]
Done!
