### ISSUE TITLE
Add installing export templates to setup instructions

### ISSUE THREAD

**Issue by rothn** [Revolutionary-Games/Thrive#3220]
The instructions at doc/setup_instructions.md or doc/making_releases.md should include guidance to install export templates in the GUI. Without this installed, the script will fail.

**Comment by hhyyrylainen** [comment]
For linux it should be mentioned that there is a script included in the repo (https://github.com/Revolutionary-Games/Thrive/blob/master/scripts/install_godot_templates_linux.rb) that can install the templates.
