### ISSUE TITLE
Difficulty distinguishing clouds

### ISSUE THREAD

**Issue by MiniAlfa** [Revolutionary-Games/Thrive#3234]
#### Compound clouds are very difficult to distinguish

this is because of the following:
1. When overlapping they create different colors
2. The colors blend with the background, resulting in different colors in every biome.

I think this issue is even worse for the colorblind.

#### Possible solutions
1. Replace compound clouds with molecules.
<img src="https://user-images.githubusercontent.com/39923434/163852416-0912836a-858e-4114-9a16-7afa2b39744f.jpg" width="500" alt="Image of thrive with molecules on compound cloud">

2. Indicate clouds with overlay text
<img src="https://user-images.githubusercontent.com/39923434/163852449-0002e0f1-c546-4329-ad02-c635a5a470f1.jpg" width="500" alt="Image of thrive with overlay text on compound cloud">

3. ??????

**Comment by hhyyrylainen** [comment]
The top right hover panel is what is meant for distinguishing the clouds. I'll leave this open for a little bit while I consult other team members whether this is worth it (this would absolutely have to be tied to a specific option that is off by default).

**Comment by hhyyrylainen** [comment]
After asking other developers there really wasn't that supportive reaction regarding accepting this as a feature for us to work on. So I'll close this issue to not have this hang around in our long backlog forever, **but** we'll accept a PR implementing this if someone wants to make it (with a specific option to turn on this mode).

**Comment by MiniAlfa** [comment]
Would something like this suffice?

<image src="https://user-images.githubusercontent.com/39923434/173127776-557c53f9-9756-4002-b623-6c85bca1f7c8.PNG" width=49%> <image src="https://user-images.githubusercontent.com/39923434/173127889-9bccd7de-cb1a-4159-9f9a-0013488b9654.PNG" width=49%>
<image src="https://user-images.githubusercontent.com/39923434/173128124-f6d60142-a6ab-4b19-add3-cc0586709815.PNG" width=49%>

**Comment by hhyyrylainen** [comment]
I think something like that could work. Note that there's been plans for a long time to convert toxins into compound cloud type things. And as we'd really run out of colours with those, texturing those clouds differently (like in your images) has been suggested.

**Comment by Kasterisk** [comment]
I think my and also other in dev discord complaint that I agree with is that this could generate a lot of visual noise, my suggestion is that of similar to this concept art: 
![f057d1e2327b8b61133bc6fd564d078fe21787da](https://user-images.githubusercontent.com/54026083/173175739-f434bed3-527b-48c3-b248-1098ff0381b5.jpeg)
Where there's only a single associated icon hovering over the cloud's center of mass.

**Comment by MiniAlfa** [comment]
> I think my and also other in dev discord complaint that I agree with is that this could generate a lot of visual noise, my suggestion is that of similar to this concept art: ![f057d1e2327b8b61133bc6fd564d078fe21787da](https://user-images.githubusercontent.com/54026083/173175739-f434bed3-527b-48c3-b248-1098ff0381b5.jpeg) Where there's only a single associated icon hovering over the cloud's center of mass.
> 
> Though I really like how you make the icons complement on top of each other when the clouds blend, I think it's a neat idea.

That's indeed a better idea, but i think that with clouds overlapping it might still be confusing.
Compound clouds could even be replaced by just compound items, since dissolved compounds don't really sit in clouds there is no need to simulate a fluid system. I'll wait and see what direction you want to go in and see if I can help.

**Comment by hhyyrylainen** [comment]
I'll mention that I mentioned this issue in a different discussion: https://forum.revolutionarygamesstudio.com/t/slime/906/7

**Comment by Zireael07** [comment]
> That's indeed a better idea, but i think that with clouds overlapping it might still be confusing.

I think it ought to be tried before forming an opinion on the "confusing" part, and imho it's better than the status quo.

Some ideas I have of minimizing the confusion: introduce some sort of minimum separation between clouds' centers of mass, show icon for cloud you're in or closer to the center of as outlined/bigger...

**Comment by MiniAlfa** [comment]
> I think it ought to be tried before forming an opinion on the "confusing" part, and imho it's better than the status quo.
> 
> Some ideas I have of minimizing the confusion: introduce some sort of minimum separation between clouds' centers of mass, show icon for cloud you're in or closer to the center of as outlined/bigger...

I meant confusion about situations such as the image below, which can only be prevented if clouds cannot mix.

<image src="https://user-images.githubusercontent.com/39923434/180062030-301f026d-fdaa-4ab0-9c08-5f54b7a4b285.png" width="50%"></image>

**Comment by MiniAlfa** [comment]
Something like this would also be possible:

![suggestion](https://user-images.githubusercontent.com/39923434/181795579-ae456450-eb56-41e2-843a-26db7463e774.PNG)
