### ISSUE TITLE
Luabind problems in compilation

### ISSUE THREAD

**Issue by issuerx** [Revolutionary-Games/Thrive#325]
Hello, i have some issues about luabind when running make, its my whole output https://bpaste.net/show/2d762d7782ee

**Comment by jjonj** [comment]
Thanks for the report. 
Perhaps the luabind sub-repository that we pull from changed something. I'll see if I can reproduce that tomorrow!
Did you download the dependencies from the mega link?

**Comment by issuerx** [comment]
From what mega link ? I was read in README.md what dependencies im need and i was install it from my repo.

**Comment by jjonj** [comment]
My bad! I assumed you were on windows since most people are and you didn't specify otherwise, the mega thing is a windows only thing.
To start with I would recommend mooplies suggestion from the forums and upgrade boost to 1.58

**Comment by issuerx** [comment]
i cant upgrade my luabind maybe ? I was search for some but no results but maybe u know what upgrade luabind can solve problem ?

**Comment by jjonj** [comment]
Luabind hasn't been updated in several years. There might be some third party clones that have made updates that fixes the issue but I couldn't find any with a short search.

**Comment by issuerx** [comment]
Okay but how can i downgrade my boost then ? I wanna two versions, ill change path to 1.55 version for thrive but im just downloaded sources of boost.1.55 i was run bootstrap, after that im run b2 and i have no boost files in my /usr, how u recommend me to add boost 1.55 from sources ?

**Comment by jjonj** [comment]
That's a CEGUI header file that suggest that you have an older version of CEGUI.
You'll need to compile CEGUI yourself from their "default" branch.
The specific commit we have used so far is 
https://bitbucket.org/cegui/cegui/commits/0de4973e25fbfd31fac5b40391de85eeb25beaba?at=v0-8

**Comment by issuerx** [comment]
I have older cegui ? ver - 0.8.4-8 on site cegui.org.uk the newer one is 0.8.4 too, so i dont think i have older cegui, i have the newer one, arch is distro on the edge so i allways have the newest packages...

**Comment by hhyyrylainen** [comment]
I might not be up to date on this issue anymore, but when I updated Thrive to use Ogre 2.0 you had to use an unreleased version of CEGUI. Meaning you had to build it yourself using for example the commit that jjonj suggested.

**Comment by issuerx** [comment]
I dont know what that commit mean and how to use that, im downloaded cegui from that site but i had a problem with compilation that.

**Comment by jjonj** [comment]
Sorry for the late reply
"A commit" is a term from git.
Every time you make a change to a git project you create a new commit, so it becomes kind of a new mini version, you can think of it as an alpha of the next release. 

For example, you can see all of thrives commits here: https://github.com/Revolutionary-Games/Thrive/commits/master

CEGUI 0.8.4 is the newest version but it is still too old for us, we need some new features that aren't in an official release yet, so we go to the development of CEGUI and find a specific commit (version of cegui) that works for us.
So what you need to do is to download the commit I linked, you can use this link to download:
https://bitbucket.org/cegui/cegui/get/0de4973e25fb.zip
and then compile that version!
