### ISSUE TITLE
Make sure ATP can be shared between colony members

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3250]
On person reports that in a multicellular colony it doesn't seem possible to make propulsion only cells, ie. only flagella and no ATP generation, because they seemingly take ATP damage all the time. So it seems that maybe ATP can't be shared between colony members? Maybe we should rectify things so that it can be shared.

**Comment by 84634E1A607A** [comment]
**Never** in a multicellular creature can ATP be shared between cells. This is out of the question.

**Comment by Kemikal1** [comment]
maybe we should make an option to control the flow of compunds, one type gets more compunds than the other, seems pretty realistic, some types of tissues consume more energy, but dont share ATP only compunds.

**Comment by hhyyrylainen** [comment]
Now that I think about this again, yeah, maybe it's not a good idea to allow ATP sharing. And energy producing compounds should already be shared properly, so I'll close this.
