### ISSUE TITLE
Add a very simple text tutorial to the game

### ISSUE THREAD

**Issue by Oliveriver** [Revolutionary-Games/Thrive#326]
Given that a few playtesters so far have appeared to not have a clue what they're doing, it's probably wise to add at least some form of tutorial to the game as soon as possible.

While [the full tutorial](http://thrivegame.wikidot.com/gdd-microbe:progression#toc1) is quite a way away and not yet worth the effort to add, a few screens of text which appear after the player clicks 'New Game' or enters the editor should help. Text alone is never a very effective tutorial, but it should be massively better than nothing.

I'll volunteer to write the text if no one else particularly wants to.

Another, possibly additional, option could be tooltips which appear when the player hovers over each button.

**Comment by TheCreator--** [comment]
Just to give everyone a heads up, we apparently already have a tutorial in the game, there is a button in the bottom left corner that brings it out. All that needs to be done is to change the text and make sure the tutorial is opened when the player first enters the environment.

**Comment by Moopli** [comment]
Something GUI/code-wise that would be really awesome is to make a simple, clean, text box. The thing that serves as the help panel right now is all oddly-shaped, meaning it's practically impossible to align text nicely within it.

**Comment by TheCreator--** [comment]
I was thinking that we could have something like this text box:
https://youtu.be/4CnkJd0HZNU?t=51s
It seems that although the textbox itself is unregularly shaped—the text is aligned to a rectangular box, more or less.

**Comment by Oliveriver** [comment]
Does anyone have any ideas on how we could get some more detailed guidance into the game? Not a full tutorial for the time being, but some sort of overview screen when the player starts? It's something we should include for 0.3.2 in my opinion.

I put more info here: http://forum.revolutionarygamesstudio.com/t/tutorial/106/6

**Comment by TheCreator--** [comment]
Well, we already have this:
[screenshot](https://cloud.githubusercontent.com/assets/6326563/13477252/6d1fa6ca-e080-11e5-80aa-8d0d3eb8d45a.png)
I guess we can just make it pop up automatically?

**Comment by Moopli** [comment]
Fixed by #419
