### ISSUE TITLE
Playing audio with a soundsource in an init function, activate or the first frame, doesn't work

### ISSUE THREAD

**Issue by jjonj** [Revolutionary-Games/Thrive#328]
I added a sound to main menus gui sound entities soundsourcecomponent and tried to play it in the main_manu_hud.cpp's init and activate functions and it failed. I tried playing it on the first update called which also failed. Only by waiting two frames did it not fail.

No sound will be played and cAudio will print an error in the console

**Comment by hhyyrylainen** [comment]
There's probably no such issue with the new engine, but verification would be nice.
