### ISSUE TITLE
Multithreading crash when engulfing

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#3291]
**Describe the bug**
![image](https://user-images.githubusercontent.com/60734649/166100460-d5807fcb-64fe-46e3-bffb-1ad7e25b5e01.png)

It seems that when the microbe is checking for engulfing target, the list is modified by another thread.

I happen to be recording screen. The crash happened right after I stopped the screen record.
https://1drv.ms/u/s!AmQa4DeAoN8FlhWrIV5PJZ-4yTx5?e=xZcQwb

Full debug log:
https://1drv.ms/u/s!AmQa4DeAoN8FlhazIQBPoH_jNgl3?e=YLjVRJ

**Comment by 84634E1A607A** [comment]
Sorry... My local debugging has caused this.

**Comment by hhyyrylainen** [comment]
Good that you found that out. I had tested my changes quite extensively where I engulfed smaller cells and hadn't seen this problem.
