### ISSUE TITLE
Get CAudio to stop spamming the console

### ISSUE THREAD

**Issue by jjonj** [Revolutionary-Games/Thrive#330]

**Comment by lukaandjelkovic** [comment]
This is very easy, but can you say me in which file it spam??? I can't find.

**Comment by jjonj** [comment]
Well the actual spamming is from cAudios source code, what I was thinking is that we should be able to give parameter or somehow tell cAudio to not print out all the information.
We initialise cAudio here: https://github.com/Revolutionary-Games/Thrive/blob/master/src/sound/sound_manager.cpp#L72
cAudios source code can be found here: https://github.com/R4stl1n/cAudio

**Comment by TheCreator--** [comment]
So I messaged the guy who is developing cAudio, and this was his response:

> Create a custom logger and remove the default one. Thats the easiest way to do it.
