### ISSUE TITLE
Microbe editor: Performing an action while move action is in progress throws an exception

### ISSUE THREAD

**Issue by Kasterisk** [Revolutionary-Games/Thrive#3312]
For instance when you press confirm or changing rigidity. It's a `NonImplementedException` on `CellEditorComponent.GUI.OnActionBlockedWhileAnotherIsInProgress`. Instead of throwing this exception, perhaps it's better to show a brief popup saying "Action blocked while another is in progress".

**Comment by hhyyrylainen** [comment]
Yes, it was definitely not my intention that NotImplementedException gets thrown in that case.
