### ISSUE TITLE
Replace ThriveGeneric file

### ISSUE THREAD

**Issue by Oliveriver** [Revolutionary-Games/Thrive#332]
Pretty simple: replace the old ThriveGeneric image with the new one I posted on Slack.

**Comment by jjonj** [comment]
Image: https://slack-files.com/files-tmb/T02T175Q8-F0D55CBT6-8af28dbb0f/thrivegeneric_720.png

**Comment by jjonj** [comment]
Image is not quite ready for implementation due to size differences in old and new image

**Comment by jjonj** [comment]
Done!
