### ISSUE TITLE
Combine subsequent behaviour slider changes into a single action

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3346]
so that undoing is easier.
Probably need to tweak the general action part as when new actions are added GetInterferenceModeWithGuaranteed doesn't get called so there's currently no logic to combine the just added action into the latest action in the editor history, which is the way I think this issue should be solved.

This is basically the same as: https://github.com/Revolutionary-Games/Thrive/issues/1496 but for a different set of sliders

**Comment by 84634E1A607A** [comment]
Actually when I abandoned the my last pr #2442, what I found most difficult is to implement this without breaking the Dynamic mp part. In my memory, this works in a different class, so that there are sync problems.

**Comment by hhyyrylainen** [comment]
With my dynamic MP cleanup, I actually put in a comment where in the action history it could be detected that the new action is basically a continuation of the latest action: 

https://github.com/Revolutionary-Games/Thrive/blob/0e0b88c43cce9d505ebda3ab9cf876d98cc4621d/src/microbe_stage/editor/EditorActionHistory.cs#L141

it shouldn't be now too hard to implement a way for actions to tell the action history that they want to get squashed into a single action (basically a method that checks if that is possible and creates the combined action). After that similar logic which I used in the early multicell editor to combine more data into an existing action, can be used to overwrite the action in the history to add the new part of the action data into it.

**Comment by 84634E1A607A** [comment]
And, I really have difficulty with clumsy `SingleEditorAction<T>`'s <T> cast

**Comment by hhyyrylainen** [comment]
If you have a specific bit of code that has the problem you can show that, I can't really know what you are having a problem with from just that description.

**Comment by 84634E1A607A** [comment]
![image](https://user-images.githubusercontent.com/60734649/173069085-85614ede-3144-45a0-ac7e-028063e2b638.png)
I'm going to create a new Action here without knowing what <T> is.

**Comment by hhyyrylainen** [comment]
I handled that situation by having abstract methods in the base action data which will then handle creating the concrete types. Also that kind of "know when you can combine things" should not be the responsibility of the ActionHistory, instead like I suggested before, the action data classes should have that long logic put into them to figure out if they want to combine with something or not.
