### ISSUE TITLE
Design and create graphic assets for an options menu

### ISSUE THREAD

**Issue by jjonj** [Revolutionary-Games/Thrive#335]
Menu should be able to hold things like graphics settings and video settings.
This would possibly involve a dropdown list for resolutions, a volume slider and a number of icons.

**Comment by lukaandjelkovic** [comment]
Also control settings, to change current controls - That would not be hard to develop, (That doesn't need any alghoritms and maths to do that)

**Comment by TheCreator--** [comment]
Honestly, changing the controls [i]would[/i] be hard to develop, since currently they are all hardcoded in.

**Comment by lukaandjelkovic** [comment]
@TheCreator-- hey, i want to help in C++ programming. What can i do?
Also, can you say me what can i do with Lua?

**Comment by jjonj** [comment]
@lukaandjelkovic are you able to compile the game yet? 
Are you asking which parts we use lua for and which parts we use C++ for, or are you just saying you can help in either language?

**Comment by lukaandjelkovic** [comment]
@jjonj, well i learned little part of Lua here, but i dislike the 1337 MinGW and other similar programming preparations and packages. (I was using the "New Project>C++" in Visual Studio for my old failed projects).

**Comment by hhyyrylainen** [comment]
This is basically required for engine_refactor for changing any of the graphical settings

**Comment by Untrustedlife** [comment]
Shoot. this is REQUIRED?
ugh

**Comment by hhyyrylainen** [comment]
We got a stylised options menu in 0.5.0
