### ISSUE TITLE
Create a simple new game setup screen for seed and LAWK setup

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3355]
Make a simple new game setup screen that allows to set the seed for the procedural patch map so that the seeds can be shared, and also a LAWK toggle as that is blocking thermoplast (though doing this now probably won't by itself make progress happen again on the thermoplast).

https://forum.revolutionarygamesstudio.com/t/implementing-new-game-settings/884/2

**Comment by Kasterisk** [comment]
This issue already exist https://github.com/Revolutionary-Games/Thrive/issues/873.
