### ISSUE TITLE
Fix remaining minor issues for release

### ISSUE THREAD

**Issue by jjonj** [Revolutionary-Games/Thrive#336]
- [x] Fix save/load
- [ ] Make sure F1 works

**Comment by TheCreator--** [comment]
- [ ] Fix save/load
- [ ] Make sure F1 works
- [ ] the game crashes on exit
- [ ] organelle models of NPC species overlap.
- [ ] Images and opening cutscene are sometimes stretched and distorted
- [ ] Nucleus blinking and temporary material
- [ ] Change tooltips text
- [ ] Change the version number at the bottom right
- [ ] Deleting an organelle in the editor keeps the cytoplasm hex there
- [ ] Undoing a delete crashes the game
- [ ] New microbe button does not work
- [ ] Cells and emitters are rendered inside the view rectangle (looks bad and causes jittering when an emitter is rendered underneath a cell)

**Comment by Moopli** [comment]
For that last one, I'd say "spawned", much clearer.

To fix it, we'd have to know the camera's distance, know the FOV and aspect ratio, and then funnel that data to the very ad-hoc spawn-radius system. It's something that might just introduce tons of bugs, so if nobody wants to tackle it right now I would forgive them.

**Comment by TheCreator--** [comment]
Couldn't we just have it spawn outside the maximum permitted viewing rectangle temporary until we get a proper fix? No that I know how to do that, but I thought it might have been easier.

**Comment by Moopli** [comment]
That's a good point, it doesn't have to be a variable spawn range.

**Comment by TheCreator--** [comment]
I propose deleting this issue: Images and opening cutscene are sometimes stretched and distorted
from the current release and fixing it when we get the in-game options.

Maybe this one as well: the game crashes on exit (it will take to much time and isn't too big of a deal imo.

**Comment by jjonj** [comment]
> Images and opening cutscene are sometimes stretched and distorted

How/when?

**Comment by TheCreator--** [comment]
I'm not too sure about it, but I believe @oliveriver said that if he starts the game in non-fullscreen mode and then maximizes it, he observes the stretching.

**Comment by jjonj** [comment]
All issues except the stretching (which now has it's own issue) was fixed
