### ISSUE TITLE
Launcher hangs when verifying download

### ISSUE THREAD

**Issue by chriscamacho** [Revolutionary-Games/Thrive#3366]
using the app image from releases, it downloads the latest version and then hangs (44.38%) Couldn't find any error messages or logs, I'm running with 64bit linux 5.15.39_1 on i7-1165G7 using integrated graphics

**Comment by hhyyrylainen** [comment]
This repo is for Thrive. Launcher issues need to be reported for the launcher.

This seems to be an existing issue already: https://github.com/Revolutionary-Games/Thrive-Launcher/issues/137
