### ISSUE TITLE
Update ogre to fix crash on exit

### ISSUE THREAD

**Issue by jjonj** [Revolutionary-Games/Thrive#337]
Our crash on exit is caused by this bug: https://ogre3d.atlassian.net/browse/OGRE-479
The bug has been fixed recently but we use an ogre version that is a few months old, so needs updating.
This would be a good chance to switch from my fork of ogre to the official version as the reason that we use a fork currently is because of a different bug that should also have been fixed on the official branch.

**Comment by Moopli** [comment]
Official version being the latest ogre 2.0?
