### ISSUE TITLE
Editor: Mutation point bar segment no longer animating (broken resulting MP calculation)

### ISSUE THREAD

**Issue by Kasterisk** [Revolutionary-Games/Thrive#3397]
Didn't see a related issue exist yet so I opened a new one. So originally the MP bar have a segment that shows visually how much the to-be-placed organelle would cost, this would animate the bar segment to the resulting mutation point. This now seems to be broken.

**Comment by hhyyrylainen** [comment]
I accidentally opened a duplicate titled "Mutation point bar no longer shows resulting MP after action". So there is something that causes the resulting MP calculation to fail which in turn then prevents the animation from showing how much MP the action would take as that amount has not been successfully calculated.

**Comment by hhyyrylainen** [comment]
Closed the duplicate issue https://github.com/Revolutionary-Games/Thrive/issues/3397 where I showed a screenshot of how this looks:

![2022-06-16_13 28 54 4447](https://user-images.githubusercontent.com/3796411/174051594-45e7e8d4-35fd-4c74-afa3-926838c7c75b.png)
