### ISSUE TITLE
Back button on save load screen nonfunctional

### ISSUE THREAD

**Issue by MiniAlfa** [Revolutionary-Games/Thrive#3407]
**Important**
Please only submit technical bug reports here. This is not a place to make feature requests
or suggestions. For that please visit our community forums:
https://community.revolutionarygamesstudio.com/

**Describe the bug**

Pressing the back button on the save loading screen does nothing. But pressing escape (key on keyboard) does bring you back.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to "Load Game" from the main menu
2. Click on "Back"

**Expected behaviour**
The button should bring you back to the main menu

**System info (please complete the following information):**
- OS: Windows 10
- Graphics card: Intel HD Graphics Family
- Thrive version: 0.5.9-alpha

**Comment by Kasterisk** [comment]
Tested locally and it doesn't happen to me, Godot probably mess up the signal connections in your end which seems to be a common occurance, try git restoring the problematic scene file and see if that'll fix it.
