### ISSUE TITLE
Timeline G/L button overlaps VScroll

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#3411]
So you have to scroll down instead of dragging vertical scroll. Annoying especially when you have a BIG timeline
![image](https://user-images.githubusercontent.com/60734649/173724361-56fd705d-6f06-4091-aca7-c767cceaa2dc.png)

**Comment by Kasterisk** [comment]
I don't think it overlaps, the buttons clearly make room for the scrollbar?

**Comment by 84634E1A607A** [comment]
But the fact is that I cannot drag the scroll bar there.

**Comment by Kasterisk** [comment]
Ah yes just tested this, seems like they block mouse inputs with the scrollbar, even though visually they should not.

**Comment by hhyyrylainen** [comment]
Probably a case where the horizontal spacing element has the wrong mouse mode so it prevents clicks even outside the buttons.
