### ISSUE TITLE
Create icon for axon

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3423]
for use in multicellular prototype.

https://en.wikipedia.org/wiki/Axon

I added a placeholder icon based on one of the stylised images on Wikipedia, but it isn't very good. You can see how that looks in this other issue: https://github.com/Revolutionary-Games/Thrive/issues/3424

**Comment by Kertit** [comment]
Axon Icon done
https://dev.revolutionarygamesstudio.com/files/Asset%20development/Organelles/Axon/Axon_Icon.png

**Comment by hhyyrylainen** [comment]
This graphics task is now fully done.
