### ISSUE TITLE
Create icon for myofibril (muscle fiber)

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3424]
for use in multicellular prototype

Otherwise it'll look like this forever:
![2023-02-24_11 20 12 4864](https://user-images.githubusercontent.com/3796411/221141514-4899c6ff-e581-4816-ab33-34d4fa25d0a2.png)

**Comment by Kertit** [comment]
Model + Texture ready and uploaded in DevCenter
https://dev.revolutionarygamesstudio.com/files/Asset%20development/Organelles/Axon

**Comment by hhyyrylainen** [comment]
And the myofibril is here: https://dev.revolutionarygamesstudio.com/files/Asset%20development/Organelles/Myofibril

This and the axon are now just missing the icons.

**Comment by Kertit** [comment]
Icon done
https://dev.revolutionarygamesstudio.com/files/Asset%20development/Organelles/Myofibril/Myofibril_icon.png

**Comment by hhyyrylainen** [comment]
All graphics assets are now done for this.
