### ISSUE TITLE
Make NPC cell division respect entity limit

### ISSUE THREAD

**Issue by Oliveriver** [Revolutionary-Games/Thrive#3434]
I've noticed that performance can sometimes get out of hand if NPC cells keep reproducing, since the daughter cells aren't currently included in the entity limit tracking. It would be helpful if division could be delayed until the number of entities dropped below the entity limit. Or, if that's too complicted, don't let them divide at all if the entity count is too high.

**Comment by hhyyrylainen** [comment]
> since the daughter cells aren't currently included in the entity limit tracking.

I'm 99% sure they are. Otherwise the spawn system wouldn't despawn them on patch change.

> It would be helpful if division could be delayed until the number of entities dropped below the entity limit. Or, if that's too complicted, don't let them divide at all if the entity count is too high.

So this is the point of the issue. This will have pretty big gameplay implications and players may notice and wonder why some cells can't divide.

**Comment by Oliveriver** [comment]
> I'm 99% sure they are. Otherwise the spawn system wouldn't despawn them on patch change.

Sorry, phrased that badly. Yes, the point is that they can spawn despite the entity limit having been reached, not that they aren't tracked for despawning.

It will have gamplay implications. Hopefully not major though. I very much doubt many players are paying attention to other cells dividing at the moment.

**Comment by hhyyrylainen** [comment]
One thing that I'd like to see if this is fixed is that there's some forgiveness in the values, for example 10 or 15%, so that as cells usually fill up the entire entity limit, they can still reproduce so that we can still get that darwinian population change effect.
