### ISSUE TITLE
Basis.Quat can give non-normalized quat

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#3445]
```CSharp
(new Basis(new Vector3(0.08525315f, 0, 0.9963162f), new Vector3(0, 0.9999571f, 0), new Vector3(-0.9963162f, 0, 0.08525315f))).Quat()
  {(0, -0.6762713, 0, 0.7366246)}
    Length: 0.999979317
    LengthSquared: 0.999958634
    w: 0.736624599
    x: 0
    y: -0.676271319
    z: 0
```

```CSharp
(new Basis(new Vector3(0.08525315f, 0, 0.9963162f), new Vector3(0, 0.9999571f, 0), new Vector3(-0.9963162f, 0, 0.08525315f))).Quat().Xform(Vector3.Forward)
  Stack empty. (Unhandled exception, crashed. I'm using Rider's runtime external console, so no stack info.)
```

**Comment by 84634E1A607A** [comment]
https://github.com/godotengine/godot/issues/42241

**Comment by 84634E1A607A** [comment]
https://github.com/godotengine/godot/issues/55349

**Comment by 84634E1A607A** [comment]
So either Basis or Quat should be normalized.

**Comment by hhyyrylainen** [comment]
Why is this opened as an issue? I noticed the same thing when doing my late multicell prototype and basically just added a .Normalized() call in there when needed.
If there's specific places where we need to fix this, that'd be a good issue but a general issue like this, I don't see what can be done. Feel free to clarify and re-open.

**Comment by hhyyrylainen** [comment]
Opened an issue for the specific identified case: https://github.com/Revolutionary-Games/Thrive/issues/3448

**Comment by 84634E1A607A** [comment]
Fine. Earilier I thought that Basis.Quad *should* return a normalized quad.
