### ISSUE TITLE
What is the license of `thrive.ttf`?

### ISSUE THREAD

**Issue by throwaway1037** [Revolutionary-Games/Thrive#3465]
The license should be documented.
Please may it be released under a free (as in freedom) license if it is not already?

**Comment by hhyyrylainen** [comment]
The thrive font is already said it is under the license most of our other assets are under. See the readme in the assets folder: https://github.com/Revolutionary-Games/Thrive/blob/master/assets/README.txt

**Comment by throwaway1037** [comment]
That file was confusingly worded which led me to the conclusion that `thrive.ttf` was not licensed under the same license as most of the other files, nor under the same license as the fonts.

**Comment by hhyyrylainen** [comment]
If you or anyone else has better wording to suggest, feel free to open a pull request.
