### ISSUE TITLE
Cloud brightness multiplier doesn't actually affect cloud brightness

### ISSUE THREAD

**Issue by Oliveriver** [Revolutionary-Games/Thrive#3468]
The current system for changing cloud brightness according to biome doesn't work.

As far as I can tell, this is because the brightness of each cloud is set by iterating over the clouds before any clouds are initialised. Moving the following few lines from `SetBrightnessModifier` to `UpdateCloudContents` in `CompoundCloudPlane` fixes the issue, but maybe @hhyyrylainen would have a different approach in mind.

```
        foreach (var cloud in clouds)
        {
            cloud.SetBrightness(currentBrightness);
        }
```

**Comment by hhyyrylainen** [comment]
So it looks like. Wrong ordering in the initialization seems to be the problem.

Here's how I would fix it:
![Kuvakaappaus - 2022-07-03 23-26-36](https://user-images.githubusercontent.com/3796411/177056177-74aae3e2-ab04-4708-ae52-af8c6a25aa72.png)

Just need to add a comment on that moved line saying why it needs to be initialized so early, something about OnGameStarted already applying the patch settings
