### ISSUE TITLE
Cellulose and Chitin membranes say they are invulnerable to engulfment, but silica and calcium don't

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#3482]
Is there misunderstandings?

![image](https://user-images.githubusercontent.com/60734649/177901656-7865419f-331e-48ad-86f7-bd10e121d5e8.png)

**Comment by buckly90** [comment]
Silica and calcium are not invulnerable, therefore they do not say so.

**Comment by 84634E1A607A** [comment]
Don't they?

**Comment by buckly90** [comment]
Silica and Calcium are digested with lipase which is default so they do not require any special adaptation to digest
