### ISSUE TITLE
DraggableScrollContainer doesn't drag well in all directions

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3484]
I've experienced that dragging the map left moves nicely, but dragging to the right doesn't move the map barely at all. Same seems to also happen with the up/down directions where the other direction works but no the other.

**Comment by Kasterisk** [comment]
Have you checked that it's just the scroll container having scrolled into its maximum boundaries?

**Comment by hhyyrylainen** [comment]
It does scroll all the way to show the content, when I put a lot of effort into it. It would be very weird if the scroll container ended while only a part of a patch or a connection line is shown.

**Comment by 84634E1A607A** [comment]
Cannot reproduce?

**Comment by hhyyrylainen** [comment]
Here's a video showing the issue, especially the up and down movement reacts very strangely to my inputs:

https://user-images.githubusercontent.com/3796411/178106111-d768b326-d250-4886-85e9-54082ab6a0ca.mp4

It's a bit hard to tell when you don't know when I'm clicking, but experiencing this myself it is very clear something is wrong with the game the reacts to my mouse drag movements.

**Comment by Oliveriver** [comment]
Hmm, that is weird. I can't reproduce this either.

**Comment by hhyyrylainen** [comment]
Could be platform specific then? Is anyone on Linux and *doesn't* experience this issue?

**Comment by hhyyrylainen** [comment]
I'll tag this platform linux as we haven't gotten that much reports about this and the only other report was also from a linux user.
