### ISSUE TITLE
Seed `69` causes an infinite loop when generating patch map

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#3505]

**Comment by hhyyrylainen** [comment]
Didn't you already fix this in your open PR? So there was no need to open this issue. Or did I misread that one commit message?

**Comment by 84634E1A607A** [comment]
Yes. But I still opened it as this is brought up by someone in the community.

**Comment by hhyyrylainen** [comment]
I would not still bother opening a "pointless" issue if I immediately was able to fix the problem (even if the fix was not merged immediately).

**Comment by 84634E1A607A** [comment]
Okay
