### ISSUE TITLE
Moving into a different patch after going extinct will cause the population in the patch you move in to drop to 1

### ISSUE THREAD

**Issue by stoptakingusernames** [Revolutionary-Games/Thrive#3526]
**Description**
If you go extinct inside a patch then move into a patch you were already populating, the population in the patch you move into drops to 1, when it should stay completely unaffected. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Start thrive and reproduce then move to the next patch
2. Kill yourself and cause yourself to go extinct in the patch you just moved into
3. Go back to the patch you were in before with the in-game patch map after going extinct

**Expected behaviour**
The population in the patch you move into should stay the same, as you did not go extinct in said patch

**Screenshots demonstrating the bug**

![a](https://user-images.githubusercontent.com/33234241/178995282-0faa694b-f8bf-4064-aa02-bf24dee2d0d9.png)

![b](https://user-images.githubusercontent.com/33234241/178995302-f9cb25b6-ceb0-44fc-bffd-f884daf01226.png)

**Additional context**
Before the merging of #3524, this bug would cause the population to drop to 0 instead, which broke saving due to the game thinking you were extinct

**Comment by stoptakingusernames** [comment]
I'll close this issue then since this has already been addressed

**Comment by hhyyrylainen** [comment]
> when it should stay completely unaffected.

Actually, it should not be unaffected, but it was a bug that it was always set to 0. In the new game options PR it was accidentally switched to multiply the population with a negative number. After my changes the population loss in the patch that is moved to will be as intended and won't always drop immediately to 0.
