### ISSUE TITLE
Cells can spawn in the wrong patch

### ISSUE THREAD

**Issue by Oliveriver** [Revolutionary-Games/Thrive#3544]
I moved to a patch that had no other species in, and saw a species from the previous patch spawning quite often in this new location. I suspect the spawn system isn't clearing spawners properly.

**Comment by hhyyrylainen** [comment]
So I guess this is still a problem. This would also explain why obsolete species spawn...
I've looked through the patch manager system multiple times for this issue but have not seen what might be causing this.

**Comment by Oliveriver** [comment]
Update on this: it only appears to happen when you stay in one patch for at least two generations, then move to a new patch. I can reproduce it every time by staying in my starting patch once, then moving to a new patch.

**Comment by hhyyrylainen** [comment]
I think I found out what causes this, the shuffle bag seems to end up with a bunch of duplicate spawners and items are kept in there that shouldn't exist:
![Kuvakaappaus - 2022-08-04 16-52-16](https://user-images.githubusercontent.com/3796411/182864393-65f4c1a2-b9fb-46d5-bfa6-325e7d99c4a8.png)

**Comment by hhyyrylainen** [comment]
This was a pretty embarrassing bug I caused when trying to make right spawners get cleaned on becoming multicellular. Turns out instead it just created vastly more duplicate spawner objects.

Here's a PR that tries to fix this: https://github.com/Revolutionary-Games/Thrive/pull/3662
