### ISSUE TITLE
Ingested Matter amount can be NaN

### ISSUE THREAD

**Issue by stoptakingusernames** [Revolutionary-Games/Thrive#3548]
The ingested matter bar can say NaN instead of the actual digested amount. Digestion still happens as usual regardless though

**To Reproduce**
I don't know how exactly to reproduce this bug, so I'll just share what I did before I got it
1. Play the game and become multicellular 
3. Load the multicellular save again after quitting
4. Play the game as a multicellular organism (I noticed at this time that the ingested matter bar did not even appear at all)
5. Die, then ingest another cell
6. See the bug

**Expected behaviour**
Ingested amount show how much ingested material you currently hold

**Screenshots**

![c](https://user-images.githubusercontent.com/33234241/179401713-d08ef168-ebaa-4531-89f2-f7991b54773b.png)

**Additional context**
This bug only happened in the multicellular stage for me.

**Comment by hhyyrylainen** [comment]
One potential lead as to what might cause it or make it more likely: loading a early multicellular save, then dying, and finally trying to engulf an iron chunk.

**Comment by jacekku** [comment]
Hello there! I've encountered this bug in my play through, when going to multicellular stage. I decided to investigate and debug a bit. What I discovered was the fix that was implemented for CompoundBags with `FixNaNCompounds()` BUT, the items I was digesting didn't seem to hit that method ever, resulting in NaN's still existing in the digested body, corrupting the values on every update. I added `containedCompounds.FixNaNCompounds();` in the digesting logic and that seemed to fix it. 

Excerpt from the modified file looks like this:
```CSharp
Microbe.Interior.cs
   private void HandleDigestion(float delta)
            //...
            var containedCompounds = engulfable.Compounds;
            var additionalCompounds = engulfedObject.AdditionalEngulfableCompounds;

            var totalAmountLeft = 0.0f;

+           containedCompounds.FixNaNCompounds();

            foreach (var compound in compoundTypes.Values)
            {
                if (!compound.Digestible)
                    continue;
            //...
```

Hope this helps.

**Comment by Kasterisk** [comment]
For posterity, this is now masked with the above workaround, the actual causing issue however has not been found (and fixed).

**Comment by hhyyrylainen** [comment]
I guess that's good enough, so I'll remove this from the milestones to not have this hang around in there indefinitely.

**Comment by hhyyrylainen** [comment]
This might no longer happen with the ECS refactor (but there is a probably related bug: https://github.com/Revolutionary-Games/Thrive/issues/4794).

**Comment by hhyyrylainen** [comment]
I'll finally close this now with well over a year since this was last observed.
