### ISSUE TITLE
Specific sequences of editor actions can result in nonsensical dynamic MP result

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3558]
We have a couple of reports of some cases where the MP results don't make sense. I didn't get anyone to confirm these steps so they might not be accurate but here's at least one report:
> i removed a spike for the mouth. (which was fine, loss of mp like normal) then i added like 3 lysosomes when i should have only had enough mp for 1. same thing happened with when i was adding spikes for the outer cells and when i was putting on more mitochondria for the speed cells. i found out the signaling agent one by placing and undoing things and seeing if i lost or gained mp.

Those steps should cause:
![unknown](https://cdn.discordapp.com/attachments/958598553389903913/998010618055499837/unknown.png)

This might be early multicellular specific. Also I think I saw a related problem in a video where placing an organelle at one specific position was 5 MP cheaper than elsewhere, even though undo was used, but this might be a different problem. This issue is basically here to call attention that the dynamic MP system has at least one bug with inconsistency.

**Comment by ijedi1234** [comment]
I found a method to reproduce a nonsense -5MP deficit. Might be related to #3562 .

This reproduction method can be easily done when one first enters the microbe editor in a new game, and appears to exist when three or more mutations are done. Order matters in these reproduction steps.
Steps to reproduce 3 item MP deficit error:
1. Add 2 Cytoplasms and 1 Thylakoid, in that order. You should have 6 MP left.
2. Right click on the 2nd Cytoplasm you placed and remove it. You should now see 23 MP left, when you are supposed to see 28 MP left.
3. Interestingly, deleting the 1st Cytoplasm or the Thykaloid shows the right MP remaining afterwards.

Steps to reproduce 2 item, membrane mutation MP deficit error:
1. Place 1 Cytoplasm. 78 MP left.
2. Change the Membrane some other type, such as Double. 28 MP left. (Note this problem also appears if you alter the setting on the Fluid-Rigid slider instead during this step)
3. Place a 2nd Cytoplasm. 6 MP left.
4. Delete the 2nd Cytoplasm. You should now see 23 MP left, when you should see 28 MP left.
5. Interestingly, settings the membrane back to Normal (or set the slider back to the middle) or deleting the 1st Cytoplasm shows the right MP remaining.

Steps to reproduce 4 item MP deficit error:
1. Place 4 Cytoplasms. 12 MP left.
2. Deleting any Cytoplasm other than the 1st one will show 29 MP left. Deleting the 1st Cytoplasm correctly shows 34 MP left.
3. If you delete the 1st Cytoplasm, and then the 2nd Cytoplasm, you will see the correct 56 MP left. However, deleting the 1st, then 3rd or 4th shows 51 MP left.

**Comment by 84634E1A607A** [comment]
https://discord.com/channels/464846402732687391/465937305849298956/1001848105425182741

I looked into the dy MP code earlier. 

https://github.com/Revolutionary-Games/Thrive/blob/d22ef267582126bc18daddede845b2a8821224df/src/microbe_stage/editor/EditorActionHistory.cs#L34

https://github.com/Revolutionary-Games/Thrive/blob/d22ef267582126bc18daddede845b2a8821224df/src/microbe_stage/editor/EditorActionHistory.cs#L70

These two functions are 100% buggy, because they try to combine to the first combinable action instead of trying to find the best action. So:

1. Place 1.1
2. Place 1.2
3. Place 2.1
4. Remove 1.2

Goes to:
1. Move 1.1 -> 1.2
2. Place 1.2
3. Place 2.1
