### ISSUE TITLE
Moving rigidity slider far in a single step can go down to -5 MP

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3562]
can go to -5 MP in the fluidity/rigity slider if you move your cursor onto the extremes with less then the amount it would need

Needs to be prevented by adjusting the rigidity change action so that it doesn't cause negative MP.

**Comment by 84634E1A607A** [comment]
How? I think this is already prevented.

**Comment by hhyyrylainen** [comment]
That's one of the reports we got recently from a player. I gave up trying to get people to playtest these things, so I just opened issues without confirming. If you can be sure that with those steps (and potentially the discounts applied in new game settings and multicell editor) it's not possible to get this problem to happen, this can be closed.

**Comment by hhyyrylainen** [comment]
This may now be fixed by: https://github.com/Revolutionary-Games/Thrive/pull/3700

**Comment by hhyyrylainen** [comment]
Let's assume the latest release will fix that in two days when it is out.
