### ISSUE TITLE
Occasional use of freed memory

### ISSUE THREAD

**Issue by jjonj** [Revolutionary-Games/Thrive#360]
Only shows up with gdb like this: 
http://i.imgur.com/sieZevK.png
Doesn't cause a crash.

**Comment by TheCreator--** [comment]
Okay, I fixed this issue. Unfortunately, it resulted in some cells not having a membrane. I'll look into this.

**Comment by TheCreator--** [comment]
Fixed with 178f300ed8c17884c2cb74ff54cc25db9bdb44f6
