### ISSUE TITLE
Add fog of war for the patch map

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3602]
only show the patches next to where the player's species is or the player has been before. We can probably make it persistent so that once some patch has become visible it stays permanently visible. Regions with no visible patches should probably be hidden. Visible regions should probably have their connection lines to other regions visible to give a hint where there are more regions. Freebuild should ignore the fog of war.

**Comment by 84634E1A607A** [comment]
I'm a little confused, that the report (or the later evolutionary tree) will (may) tell you what patches it has. This wants to make player know less but those wants to make player know more. Why?

**Comment by hhyyrylainen** [comment]
This is all about making the player need to move around the patch map to discover what patches are where.
I guess after the basic implementation we can also hide the patch info from the player from elsewhere as well, but that isn't needed for the core gameplay reason this feature is wanted.

**Comment by ender-titan1** [comment]
I'm currently working on this issue and personally, I think it would be better if undiscovered patches in regions with already discovered patches should be visible, but be disabled and the patch icon replaced by a question mark or other such texture, would this be a good change?

**Comment by 84634E1A607A** [comment]
I think so. However, sea / ocean regions' structure is mostly fixed right now, so this will only affect land regions.

Personally I am unsure about the things as follows:

- Shall we hide the region linkage line or not? If so, when shall we display the connection line?
- Shall we hide the region border or not? (Hiding the region border will hide the cave from users until they find them)
- Shall we hide the patches that are in the same region but not adjacent or not?
![image](https://github.com/Revolutionary-Games/Thrive/assets/60734649/a37a9f9d-5d9e-4cf1-80ff-56357450e956)

**Comment by ender-titan1** [comment]
I have implemented a basic version of this already, I will probably open a draft PR once I clean it up a little so we can decide how to handle these things from there.

**Comment by hhyyrylainen** [comment]
I think the map should show patches (and connections) as question marks that the player has not visited yet, but are next to a patch the player is already in / has been.

That way the layout of the map is not immediately entirely revealed, but the player needs to guess / make strategic choices to move towards patch types they want to go to.

**Comment by ender-titan1** [comment]
Do we have a suitable icon for unknown patches in the game files already or does a new one need to be made?

**Comment by buckly90** [comment]
Not presently, though placeholders are perfectly acceptable.

If you wish to tackle this issue now, just using a quickly put together question-mark icon would work just fine.

**Comment by hhyyrylainen** [comment]
Or maybe just using a Label with "?" as the text on it? I don't think unknown areas would even need to have a fancy border or anything around them, just a casual question mark character might be entirely suitable.
