### ISSUE TITLE
Global timeline doesn't show total population correctly

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3611]
There's probably some logic difference between the local and global timeline that causes the global timeline to have incorrect numbers. See issue reported here: https://github.com/Revolutionary-Games/Thrive/pull/3605#pullrequestreview-1052801452

**Comment by Kasterisk** [comment]
It could be that the global population is not adjusted by external effects.

**Comment by hhyyrylainen** [comment]
The global population definitely should be calculated at the end of auto-evo from all of the patches, but it's of course possible there to be a bug in there or it happening at the wrong time.
