### ISSUE TITLE
Improve performance of the evolutionary tree view

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3624]
it seems due to having a lot of Godot buttons in it it can really tank the performance to single digit FPS. We might need to custom rendering for the round buttons in it or find some way to make the Godot buttons perform better. This is kind of critical to do before the evolutionary tree is included in the main game.

**Comment by 84634E1A607A** [comment]
Due to DrawLine antialiasing.

**Comment by hhyyrylainen** [comment]
So the performance was *not* caused by Godot buttons but the line drawing? Antialiasing being on with straight horizontal or vertical lines probably didn't do anything in the first place to improve the look...
