### ISSUE TITLE
Add button to run multiple worlds in a row in auto-evo exploring tool and collect statistics

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3626]
there needs to be a feature to do a multi run (run up to generation 25 or so, then restart with a new start) and general multiple run statistics for auto-evo exploring tool. 

Slightly modified description from the earlier issue about the auto-evo exploring tool:
A key feature for developing auto-evo with this tool would be to have a mode to run like 25 auto-evo runs in a row and collect some overall statistics.

To compare multiple different runs (with different code) it'd be nice to be able to save the collected statistics to a file for later viewing. That file could also have a dump of some extra data that would be too much to show in the GUI.

**Comment by nickthenick** [comment]
Would be good to add:

- Tooltips for the variables whose names don't immediately explain what they mean/do
- Overall world statistics like the total number of species formed, total number that have gone extinct, total number that are extant (currently exist), total number of patches in the world, total number of organisms, etc.

**Comment by hhyyrylainen** [comment]
I'll leave a small counterpoint and say that overtly specific tooltips have a real danger of being outdated (so wasted work) once we get auto-evo development going on again (there hasn't been that many auto-evo algorithm changes lately, but I hope we'll get major reworks in the future).
