### ISSUE TITLE
Text seems bigger in full screen mode

### ISSUE THREAD

**Issue by jjonj** [Revolutionary-Games/Thrive#363]
According to oliveriver

> I don't know why, but in full screen mode the text in all the buttons is much larger than it should be. This has happened to me since 0.2.4, and again it's not a major issue so it's not vital to fix, but it might be something to add to the issue list in future.

**Comment by hhyyrylainen** [comment]
CEGUI has automatic text scaling so that is probably the reason. The new GUI should be made to properly scale for big screens.

**Comment by hhyyrylainen** [comment]
This can be checked once options menu is done.
