### ISSUE TITLE
Make evolutionary tree's timeline bar float at the top of the container

### ISSUE THREAD

**Issue by Kasterisk** [Revolutionary-Games/Thrive#3632]
As the tree is basically some kind of timetree and it's important for the timeline to stay visible. The timeline should float, this way even if you move to the bottom of the tree it won't disappear and if you zoom in/out on the tree, the timeline should lengthen or shorten accordingly so that it won't go off sync.

**Comment by 84634E1A607A** [comment]
I think this is not "intermediate" because you can't use DraggableScrollContainer then. And you need to support two different types of dragging (on the timeline and on the tree), and you need to make sure Buttons not overlapping the timeline.
