### ISSUE TITLE
Cell splitting can give player an overwhelming amount of glucose

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#3637]
https://community.revolutionarygamesstudio.com/t/cell-spitting-a-surplus-of-excess-glucose-after-evolution/5177

**Comment by hhyyrylainen** [comment]
https://community.revolutionarygamesstudio.com/t/cell-spitting-a-surplus-of-excess-glucose-after-evolution/5177/11?u=hhyyrylainen

**Comment by 84634E1A607A** [comment]
I am sure that I reproduced the bug on the latest master several hours ago (but not able to reproduce). It seemed random but the problem surely exists.

**Comment by hhyyrylainen** [comment]
As determined in that thread the "problem" is that when your storage gets cut in half you can have a lot of glucose that gets vented. As described in the title here, there is no that kind of problem that seems to exist.
