### ISSUE TITLE
Fluid-Rigid Slider Costs are no longer Consecutive when not at Center

### ISSUE THREAD

**Issue by ijedi1234** [Revolutionary-Games/Thrive#3639]
**Description**
When you change the Fluid-Rigid slider to no longer be at the center, go through one generation, and return to the editor, the incremental cost is no longer always 2. However, the speed and HP still changes, allowing slight modification to the cell for free.

**Reproduction Steps**
I have created 4 save files to help demonstrate this error.
[SliderSettingSaves.zip](https://github.com/Revolutionary-Games/Thrive/files/9239926/SliderSettingSaves.zip)
FluidSlider has the slider all the way at fluid, FluidSliderHalf has the slider at the midpoint between the center and the Fluid end, RigidSliderHalf has the slider at the midpoint between the center and the Rigid end, and RigidSlider has the slider all the way at rigid.

The MP remaining appears to be correct on the other end of the Center, so I will omit that information. I have the wrong MP remaining in Bold. The MP remaining for each setting is:
**Slider, End to Center**: 100, 98, **98**, 94, **94**, 90, 88, 86, 84, 82, 80
**SliderHalf, End to Center**: 90, **94**, 94, **98**, 98, 100, **100**, **98**, 94, 92, 90

**Expected behaviour**
The correct MP remaining should be:
**Slider, End to Center**: 100, 98, 96, 94, 92, 90, 88, 86, 84, 82, 80
**SliderHalf, End to Center**: 90, 92, 94, 96, 98, 100, 98, 96, 94, 92, 90

**System info**
- OS: Windows 10
- Graphics card: OpenGL ES 3.0 Renderer: NVIDIA GeForce GTX 970/PCIe/SSE2
- Thrive version: 0.5.9.0

**Comment by hhyyrylainen** [comment]
I'm going to guess that this has something to do with the Godot slider control rounding or something like that as the problem sounds like it only happens on multiple editor cycles (the GUI is recreated each time the editor is entered).

**Comment by hhyyrylainen** [comment]
@ijedi1234 could you playtest a PR that tries to fix this: https://github.com/Revolutionary-Games/Thrive/pull/3700 ?
