### ISSUE TITLE
Process Rate Calculations

### ISSUE THREAD

**Issue by Moopli** [Revolutionary-Games/Thrive#364]
Process rate calculations need to be more flexible, to allow different processes to use different rate laws, and to allow feedback regulation for the processes which require it.

**Comment by TheCreator--** [comment]
We also need to redo the current compound system. I made it slightly better, but it is still not ideal. For one, it is impossible for a cell to absorb a compound particle that contains 2 compounds (m_potency = 2).

**Comment by Moopli** [comment]
Why 2?

And yes. I've been working on getting this stuff in tickets, chunking up the work, etc.

**Comment by TheCreator--** [comment]
Sorry, didn't get notified about your comment. Well, two was just an arbitrary number. I mean that it is impossible to absorb a compound with a potency of greater than 1. The reason you might want to do this is when you absorb the compound clouds, which might have a large concentration at one spot.
