### ISSUE TITLE
New Compounds and Processes

### ISSUE THREAD

**Issue by Moopli** [Revolutionary-Games/Thrive#365]
Compounds:
- Pyruvate
- Fatty Acid
- Protein
- Nucleotide
- Nucleic Acid

Processes:
- Glycolysis: 1 Glucose -> 2 Pyruvate + 2 ATP
- Modify Respiration: 1 Pyruvate + 3 Oxygen -> 3 CO2 + 18 ATP (we asume Ac-CoA as an implicit intermediary)
- Protein Synthesis: 1 Amino Acid + 4 ATP -> 1 protein
- Protein Digestion: 1 Protein -> 1 Amino Acid (yup, you don't get the ATP back)
- Deamination: 1 Amino Acid -> 2 ATP + 1 Pyruvate + 1 Ammonia (deamination produces an NADH which is equivalent to 2 ATP through the electron chain)
- Modify Amino Acid Synthesis: 1 Pyruvate + 3 ATP + 1 Ammonia -> 1 Amino Acid
- Fatty Acid Synthesis: 9 Pyruvate + 56 ATP -> 1 Fatty Acid + 9 CO2
- Fatty Acid Digestion: 1 Fatty Acid -> 6 Pyruvate + 45 ATP (again, assuming conversion between pyruvate and Acetyl CoA. It might just be easier to have both..)
- Nucleotide Synthesis: 1 glucose + 7 ATP + 2 Amino Acid -> 1 Nucleotide
- Nucleotide Digestion: Not sure yet. Possibly directly to uric acid, or not digested at all but reused.
- Nucleic Acid Synthesis: 1 Nucleotide + 1 ATP -> 1 Nucleic Acid (ATP represents the energy within the triphosphate group)
- Nucleic Acid Digestion: 1 Nucleic Acid -> 1 Nucleotide

**Comment by DrChewbacca** [comment]
I tried to make a list of processes here and I balanced the formulae, which I thought was helpful. I had many less amino acids per protein :) Anyway ignore it if it's not helpful.

http://thrivegame.canadaboard.net/t1491-cpa-master-list

**Comment by Moopli** [comment]
Thanks! The formulae don't necessarily need to be balanced, for example, electrons certainly aren't balanced.

I googled for an average length of protein chains over a wide variety of species, conveniently enough somebody had already done such a survey article so I got my number which was 360.

It might be better to measure protein by mass, measured in number of amino acids. I think that would be a lot more transparent actually, we'd just measure the conversion between free amino acids and ones bound in protein chains.

Maybe it would be good to do the same with the other bulk polymers, ie, nucleic acids and glycogen, as well (if we decide to account for glycogen and not just assume that intracellular glucose is implicitly stored as glycogen, anyway).

**Comment by TheCreator--** [comment]
I think protein should only be around 10 amino acids, though.

**Comment by Moopli** [comment]
Well my point is that the decision of exactly what ratio to use in the accounting between protein and amino acids is mostly arbitrary -- if we change the ratio between protein and amino acids, then we simply change how 'many' (much) protein we need to repair x organelle, or to reproduce x microbe or to produce x amount of y agent. There are different reasons for different numbers though. 1:360 gives us an approximately realistic mole ratio, and 1:1 gives us an approximately realistic mass ratio (okay, maybe it should be about 1.1:1 in that case). What benefit does a 1:10 ratio give us?

**Comment by TjWhale** [comment]
I think the chief reason for balancing the equations is that you want to make sure there isn't some cycle you can do which increases the amount of some compound in the game. It's possible to balance things without actual equation balancing but it is one way of making sure it's correct.

You just don't want a -> b -> c -> 1.1 a or something like that. 

The number of amino acids per protein can be balanced with how much protein you need to grow / make agents / reproduce and that can be set for good gameplay. You want the recharge time on your agents to feel right / fun. That could easily be recharging 1 protein which takes 360 AA's or 360 proteins that require 1 AA each so it doesn't really matter. 

However if you want to set growth as "you need this much weight of protein to grow this much weight of cell" then we are going to have to be careful to have some parameter we can balance to make sure the gameplay is not tedious.

**Comment by Moopli** [comment]
Ah, but the chief reason *against* balancing is that cells cannot live forever simply by recycling materials, there has to be a bit of ATP 'decay' to ensure that cells will make use of some energy source. 

On top of that we'd have a bunch of tweaks to ensure that cycles don't run continuously burning off ATP (for example, protein synthesis and digestion constantly). We'd have a separate pool for ingested vs manufactured NAs and protein (since ingested stuff gets digested and manufactured stuff gets used), and the amino acid and fat production-digestion cycles would use upcoming process system tweaks which will make the forward/reverse rates strongly anticoupled, so if you get a sudden glut of fat or amino acids through feeding, the production reactions would strongly scale back, and the excess would be digested for energy (this could even be a tunable parameter for cell behaviour -- is your cell programmed to hoard food for later use, or do you digest it for energy now?).

For balancing growth requirements between realism and fun, I agree -- we could start by finding numbers for dry weights of various organelles, so we get a sense of the protein/(phospho)lipid/other-stuff ratio for each organelle, then simply scale down requirements, or scale up organelle throughput, until the amount of game-time it takes to produce a microbe's worth of ingredients is good for the game's pace.

**Comment by Untrustedlife** [comment]
What about a thermoplast process?

**Comment by hhyyrylainen** [comment]
@NickTheNick what's the status on this, are these good things to add to the game or should this go back to the design phase?

**Comment by NickTheNick** [comment]
Since we aren't planning on adding pyruvate anymore, and we've removed O2, CO2, and the FAN (fatty, amino, nucleic) acids as compound clouds, we'll have to rewrite these in equivalent terms of the current compound system (though some of the processes I think are not necessary).

**Comment by NickTheNick** [comment]
Converting moopli's list into the current system, these are what are applicable:
•	Protein Synthesis: 1 Amino Acid + 4 ATP -> 1 protein
•	Amino Acid Synthesis: 1 Glucose + 6 ATP + 2 Ammonia -> 2 Amino Acid
•	Fatty Acid Synthesis: 9 Glucose + 112 ATP -> 2 Fatty Acid + 18 CO2
•	Nucleic Acid Synthesis: 1 Glucose + 2 Amino Acid + 8 ATP -> 1 Nucleic Acid (The 8th ATP represents the energy within the triphosphate group)

So it might be worth comparing these to what numbers we currently use to see the difference. Also if we consider organelles having a cost in amino acids, fatty acids, and nucleic acids to produce, we can use these processes to find the equivalent of that in glucose, ammonia, and ATP. 

Also interestingly it seems that here he suggests the phosphorous from nucleic acids come from ATP and not a phosphorous compound, like phosphate. That is an idea we could consider and test out.

**Comment by Untrustedlife** [comment]
We removed  all of these, this issue is now irrelevent

**Comment by hhyyrylainen** [comment]
But this lists potential processes. Do we have still an issue open about fixing the processes? If not we need one.

**Comment by Untrustedlife** [comment]
We removed the majority of these compounds though? The only one in this list we didn’t remove is pyruvate.

**Comment by Untrustedlife** [comment]
If there isn’t we should create a new issue.
