### ISSUE TITLE
Replace auto-evo report text with a visually more interesting representation

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3652]
Some ideas here:
https://forum.revolutionarygamesstudio.com/t/explaining-the-auto-evo-prediction-to-the-player/836/3

basically we want to end up with some kind of fancy visual way to show the report tab of the editor to the player with just a bit of text but mostly icons and images of the species showing the population changes, migrations etc. and it could also show some food sources and predation relationships though showing all of those on the primary screen might be too much info and too much visual clutter (showing everything could be on the food chain tab then).

I'll tag this as 2D art as we probably need at least a few new icons.

Update: this will make updating the text to be better translatable obsolete: https://github.com/Revolutionary-Games/Thrive/issues/1996

Combining this with: https://github.com/Revolutionary-Games/Thrive/issues/3152 being directly in the report might be very good.

**Comment by dligr** [comment]
Is this issue still relevant, given that the auto-evo is now not text-based, after the PR #5516?
#1996 could also be closed along with this one, if it's obsolete now.

**Comment by hhyyrylainen** [comment]
I suppose yeah this should be closed. I won't close #1996 as there is some extra info missing from the graphical report so I'm thinking that we'll add a button back to still view the text report for people wanting those extra details.

**Comment by hhyyrylainen** [comment]
I think the text report serves a different purpose in that it lists all of the species migrations, splits etc. in a single place so it is much more convenient than checking 8 species specific pages. And also it should take like 10 minutes to slap together the GUI for displaying the text report again. I *think* I left in all the background code to still generate the auto-evo summary text as well, but if not digging it up from git history won't take that long.
