### ISSUE TITLE
Fix multicellular colony divide offset for new cell being too low in some cases

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3653]
Sometimes the offset to spawn the extra cell at doesn't work correctly and it ends up overlapping a lot on the colony it spawns inside of.
This is the code:
https://github.com/Revolutionary-Games/Thrive/blob/67ab283bf9ebb617b83da86b78e15e1eda776376/src/microbe_stage/Microbe.Interior.cs#L374

Video:
https://cdn.discordapp.com/attachments/465937305849298956/1004672047345041428/1.mp4

**Comment by 84634E1A607A** [comment]
#1435

**Comment by hhyyrylainen** [comment]
This uses custom logic (one that I linked in the description), so while that might impact this issue as well, this isn't the same as that.

**Comment by hhyyrylainen** [comment]
There's a related TODO in the code also here:

https://github.com/Revolutionary-Games/Thrive/blob/fbcfc8dce7bc59235d43f8c62f97a45f9bec0758/src/microbe_stage/MicrobeStage.cs#L513
