### ISSUE TITLE
Chloroplast unlock powerup looks identical to agent vacuole

### ISSUE THREAD

**Issue by Moopli** [Revolutionary-Games/Thrive#366]
I get that it's a small thing and will be fixed when we do endocytosis, but it's an easy fix, simply replace "AgentVacuole.mesh" with "chloroplast.mesh" in https://github.com/Revolutionary-Games/Thrive/blob/master/scripts/microbe_stage/setup.lua#L208 and maybe tweak the scale.

**Comment by Moopli** [comment]
Wait a tic, even more importantly, we aren't even *spawning them*.

**Comment by TheCreator--** [comment]
Do you want me to fix it for next release (just commit to master) or upload a new 0.3.0 zip?

**Comment by jjonj** [comment]
I feel like we can go for a more complete solution regarding unlocks, with a fix for this.
Oxytoxy was always just meant to be a temporary agent, so creating a number of models for various usable agents as well as a model for chloroplast would be a good idea

**Comment by Moopli** [comment]
I'll leave this open so we can discuss refactoring the spawn system and powerups.

**Comment by Moopli** [comment]
I fixed this a while ago
