### ISSUE TITLE
Improve performance when changing shown patch on the report tab

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3660]
With a bunch of data that causes quite big lag spikes. In our code the biggest things seem to be https://github.com/Revolutionary-Games/Thrive/issues/3659 as well as:
![Kuvakaappaus - 2022-08-04 14-48-30](https://user-images.githubusercontent.com/3796411/182839823-68033bff-8ccc-480f-ad0c-ca0584fc1ace.png)

and:
![Kuvakaappaus - 2022-08-04 14-48-54](https://user-images.githubusercontent.com/3796411/182839843-563b1e39-dfee-4e31-97c3-5dc95b165fe4.png)

I think ultimately the biggest performance thing is how many Godot objects get destroyed and recreated each time. I think instead we'll need to either cache the timeline display objects and update them or make bigger rich text blocks to have fewer overall objects.

**Comment by hhyyrylainen** [comment]
I set this as high priority as the lag is experienced much more often with: https://github.com/Revolutionary-Games/Thrive/pull/3658

**Comment by 84634E1A607A** [comment]
> we'll need to either cache the timeline display object

https://github.com/Revolutionary-Games/Thrive/blob/0f74a727c530a3042f4cbd05b56d26b5d7300a28/src/microbe_stage/editor/TimelineTab.cs#L76

We can split eventsContainer into globalEventsContainer and localEventsContainer so that only local events will be updated; and custom rich text label count can be reduced.

**Comment by hhyyrylainen** [comment]
> We can split eventsContainer into globalEventsContainer and localEventsContainer

That sounds like a pretty simple change with the potential to improve performance a lot.

**Comment by 84634E1A607A** [comment]
https://github.com/Revolutionary-Games/Thrive/blob/0f74a727c530a3042f4cbd05b56d26b5d7300a28/src/gui_common/tooltip/ToolTipManager.cs#L373

This uses plain search. Dictionary / Binary search will improve performance a lot. (First Pic, 0.42%)

**Comment by 84634E1A607A** [comment]
https://github.com/Revolutionary-Games/Thrive/blob/0f74a727c530a3042f4cbd05b56d26b5d7300a28/src/gui_common/charts/line/LineChart.cs#L696

Skip animation (or even entire draw) if line is not drawn.

**Comment by 84634E1A607A** [comment]
![image](https://user-images.githubusercontent.com/60734649/183231749-4a69ac41-d953-4d14-8a4e-009021959bb3.png)

**Comment by hhyyrylainen** [comment]
Moving to a patch has always had a lag spike, mostly due to: https://github.com/Revolutionary-Games/Thrive/issues/1085

**Comment by 84634E1A607A** [comment]
src/microbe_stage/editor/MicrobeEditorReportComponent.cs `UpdatePatchDetails` called twice.
