### ISSUE TITLE
Wording on the invulnerable to engulfment membrane tooltips needs improving

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3665]
the wording that it is invulnerable to engulfment is confusing as it is no longer actually true, instead it is only true when the attacker doesn't have the necessary lysosomes. So the wording of that bit should be improved without making it too much longer. Or the tooltip needs to be reworked some other way.

**Comment by Oqwert** [comment]
Just changing it to "Resistant to engulfment" instead would probably be good enough.
