### ISSUE TITLE
Investigate if using QueueFree instead of Free always is better

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#3667]
It looks like Free takes a lot of performance. May want to always use QueueFree.

**Comment by hhyyrylainen** [comment]
QueueFree takes time at the end of a frame for Godot to process. I would imagine the overall performance impact is the exact same, but it's just that Godot internally needs to spend all the time freeing the resources.

**Comment by 84634E1A607A** [comment]
They are basically the same. (Free() and QueueFree() 10000 buttons both take 12.5s on my end)

**Comment by Seubmarine** [comment]
godotengine/godot#62444 this pr is speeding freeing time if necessary

**Comment by hhyyrylainen** [comment]
Does that affect the relative performance impact of Free versus QueueFree?
