### ISSUE TITLE
Add thrive icon to exe

### ISSUE THREAD

**Issue by jjonj** [Revolutionary-Games/Thrive#367]
https://thrivegame.slack.com/files/nickthenick/F0G1EEGPQ/thrive_icon.ico  
I don't currently know how we can do this.

**Comment by TheCreator--** [comment]
Could we simply create a shortcut in the root folder (instead of the batch file) and change the icon of the shortcut?

**Comment by jjonj** [comment]
I tried that, but you can't move the shortcut to a different computer and have it keep the icon (icons can't have relative paths), we'd need an installer to copy an icon to their windows directory for that to work

**Comment by jjonj** [comment]
Fixed with  c88a8af
