### ISSUE TITLE
Convert save screenshot to PNG to buffer directly instead of using a temporary file

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#3672]
https://github.com/Revolutionary-Games/Thrive/blob/0f74a727c530a3042f4cbd05b56d26b5d7300a28/src/saving/Save.cs#L212

screenshot.SavePngToBuffer()

**Comment by Dartexxy** [comment]
I can take care of this.

**Comment by hhyyrylainen** [comment]
Sure, I'll assign you to this issue. Let us know if you need help or can no longer work on this issue.
