### ISSUE TITLE
Auto-evo can change alpha value of cell membrane (although it is effectless)

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#3675]
Noticed this from Discord:

![image](https://user-images.githubusercontent.com/60734649/183606331-ef5b264d-9bc8-49b5-a38c-d9e7e84fd95f.png)

**Comment by thelayeredmind** [comment]
I would like to help out. 
Just to summarize:  You want the Auto-evo to not affect the alpha value of the membrane while mutating, correct?

**Comment by 84634E1A607A** [comment]
Yes

**Comment by thelayeredmind** [comment]
One more question before I begin: Is there a built-in devmode or workflow to skip evolution steps for testing?

**Comment by hhyyrylainen** [comment]
There's cheat codes, but I believe that screenshot in the issue description is actually from the auto-evo exploring tool which is made exactly for quickly testing how auto-evo does.

**Comment by hhyyrylainen** [comment]
Here's proper issue about this situation: https://github.com/Revolutionary-Games/Thrive/issues/3831
