### ISSUE TITLE
Decide if enabling physics interpolation is the right thing to do

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3679]
Godot 3.5 adds physics interpolation that can be enabled. We might get some benefit from enabling that.

**Comment by Zireael07** [comment]
Considering you had some physics performance issues, I'd try reducing physics fps and turning interpolation on ;)

**Comment by hhyyrylainen** [comment]
I'm not actually convinced our problem is the physics performance. It seems in all kinds of profiling the physics processing time doesn't really go up at all, really... though to conclusively say someone could turn interpolation on and reduce the physics framerate to see if it actually would have an effect, but my guess is it wouldn't have more than a few percent effect.

**Comment by hhyyrylainen** [comment]
Now with the Jolt physics it would need to first be investigated if this is even possible to do anymore.

**Comment by Zireael07** [comment]
I must have missed where you switched to Jolt...

**Comment by hhyyrylainen** [comment]
It was just merged yesterday: https://github.com/Revolutionary-Games/Thrive/pull/4521 (shows up above as an event on this issue being closed by that).
