### ISSUE TITLE
Linux GCC overflow warning levels

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#369]
Using GCC 5.2.1 on Linux Thrive fails to compile
```
[ 41%] Building CXX object CMakeFiles/ThriveLib.dir/src/bullet/collision_shape.cpp.o
/home/hhyyrylainen/Projects/Thrive install scripts/thrive/src/bullet/collision_shape.cpp: Jäsenfunktio ”void thrive::CompoundShape::removeChildShape(const Ptr&)”:
/home/hhyyrylainen/Projects/Thrive install scripts/thrive/src/bullet/collision_shape.cpp:303:1: virhe: assuming signed overflow does not occur when changing X +- C1 cmp C2 to X cmp C2 -+ C1 [-Werror=strict-overflow]
 CompoundShape::removeChildShape(
 ^
```
The code 
```
void
CompoundShape::removeChildShape(
    const CollisionShape::Ptr& shape
) {
    m_bulletShape->removeChildShape(shape->bulletShape());
    auto iter = m_childShapes.begin();
    while (iter != m_childShapes.end()) {
        if (iter->shape == shape) {
            iter = m_childShapes.erase(iter);
        }
        else {
            ++iter;
        }
    }

}
```
seems to be correct meaning that GCC warning levels are cranked too high as this question on stackoverflow indicates that this warning can give false positives http://stackoverflow.com/questions/18521501/assuming-signed-overflow-does-not-occur-in-if-statement

I tried rewriting the code multiple times but it seems that `iter = m_childShapes.erase(iter);` is the line that causes the error and it is quite hard to get rid of that. After commenting that the compilation gets to the second file in the bullet folder and gives two warnings about the overflow.
It just seems to be impossible to have this warning on and get anything to compile.

**Comment by hhyyrylainen** [comment]
Changing `-Wstrict-overflow=5` to `-Wstrict-overflow=2` suppresses those warnings

**Comment by jjonj** [comment]
I don't see anything against using the solution above! This issue can be fixed by editing cmake_modules\compiler_flags.cmake

**Comment by Moopli** [comment]
Fixed with the merge of @hhyyrylainen's fork.
