### ISSUE TITLE
Create new ambient tracks using royalty-free and locally made SFX

### ISSUE THREAD

**Issue by nickthenick** [Revolutionary-Games/Thrive#3694]
Ideally creating a set of ambient tracks and ambient noises that can be layered on top of each other, based on the biome the player is in. 

Some of these can also be tied to specific actions and events (cells bumping into each other, rock chunks colliding, etc), giving more audio immersion to the world. 

Is currently being discussed in this thread: https://forum.revolutionarygamesstudio.com/t/microbe-biome-ambience/700

Requires the following issue to be completed before the tracks can be made to be specific per biome: https://github.com/Revolutionary-Games/Thrive/issues/3586

**Comment by hhyyrylainen** [comment]
We had a sound artist who had gigabytes of sound effects recorded by them. We should really try to use those if possible to not have to add like 100 lines of used asset licenses to the game.

**Comment by hhyyrylainen** [comment]
I'll tag this as programming (without specifying language) as adding new ambient tracks will be possible by editing the music json file to specify more ambient tracks to play randomly from.

**Comment by nickthenick** [comment]
Do you know who? 

I know that Twitchywhalez has recorded a bunch and is planning to add it to a Google Drive for us to use (perhaps you were thinking of him). Hopefully his SFX are sufficient. But just in case, we could tap into royalty-free sounds from online if we need to.

**Comment by hhyyrylainen** [comment]
> I know that Twitchywhalez has recorded a bunch and is planning to add it to a Google Drive for us to use (perhaps you were thinking of him). Hopefully his SFX are sufficient. But just in case, we could tap into royalty-free sounds from online if we need to.

That's exactly who I was referring to.

**Comment by hhyyrylainen** [comment]
A raw sound pack is now uploaded to the devcenter (downloaded by devs): https://dev.revolutionarygamesstudio.com/files/Asset%20development/Sounds/Raw%20sounds/Thrive%20Water%20Sound%20Compilation

**Comment by hhyyrylainen** [comment]
We've now replaced all the ambiance tracks in the game. I'll move this to the backburner and mark as impeded as this can't really progress much further (other than finishing a bunch of sounds that can't be put in the game yet): https://github.com/Revolutionary-Games/Thrive/issues/3586

**Comment by hhyyrylainen** [comment]
As we've got now a bunch of sounds, and also some finished new ambiance tracks to be put in the game: https://github.com/Revolutionary-Games/Thrive/issues/4218 I'll consider this issue to have served its purpose and will close this.
