### ISSUE TITLE
Investigate the "orphaned" tooltips

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#3696]
Got a HUGE amount of tool tips after several patch changes.

137 tool tip groups, many having 10+ tool tips.
![image](https://user-images.githubusercontent.com/60734649/184346869-8535015c-105d-4bde-a1d4-3b4ff52e40b2.png)

The worst:
![image](https://user-images.githubusercontent.com/60734649/184347180-3fb85ba9-d766-44cc-a5bf-1f2e1b06ed12.png)

It is obvious that some code which adds a tooltip fails to remove it.

**Comment by 84634E1A607A** [comment]
Full log (another instance) on [pastebin](https://pastebin.com/CGDftpn0)

**Comment by hhyyrylainen** [comment]
Reading your recent PR it got me thinking that the charts probably don't remove tooltips at all, which they likely should so that we don't end up in this situation.

**Comment by Kasterisk** [comment]
Charts do remove tooltips when the call to clear a chart is called:
https://github.com/Revolutionary-Games/Thrive/blob/a2c49627e8a3dc3c10a11fe2a97c6a158b230ca3/src/gui_common/charts/line/LineChart.cs#L492-L497

Perhaps that high quantity of tooltips was just because of the huge datasets for species pop graph, thus increasing the amount of points spread over many timesteps?

**Comment by hhyyrylainen** [comment]
> Charts do remove tooltips when the call to clear a chart is called:

Does that happen automatically when the node is removed from the tree? I guess the charts might not detect that they need to clean up tooltips when the editor scene is exited.

**Comment by Kasterisk** [comment]
Oh yeah, that might be it, the charts are not cleared for when you exit the editor, so that's a good start.

**Comment by 84634E1A607A** [comment]
I can reproduce this bug even if I did not exit an editors scene. Basically I just changed patches about 20 times. Thus there must be some sort of chart failing to clear tooltips.
