### ISSUE TITLE
Windowed mode

### ISSUE THREAD

**Issue by Alex-the-666** [Revolutionary-Games/Thrive#371]
Unable to have a windowed mode when selecting OpenGL in the Ogre launch Gui.

**Comment by jjonj** [comment]
Is this option not available to you? http://i.imgur.com/IDfIGJB.png  
If not could you show a screenshot of the options you have

**Comment by Alex-the-666** [comment]
Well, I think I accidentally just pressed "go" or whatever. How do I go back to the ogre launch GUI?

**Comment by jjonj** [comment]
delete ogre.cfg

**Comment by Alex-the-666** [comment]
Thanks, would have never solved that one without your help! :D
