### ISSUE TITLE
Add the suggestions board link somewhere in the game

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3714]
Thrive itself should have a button to "suggest a feature" that opens https://suggestions.revolutionarygamesstudio.com when clicked

Note that when https://github.com/Revolutionary-Games/Thrive/pull/3697 is done, this'll be an easy add to the other revolutionary games links, but I think additionally we should have a button maybe in the extras or options menu as well for this.

**Comment by TheHungryBandito** [comment]
I am adding the suggestions button to the extras menu.

I can't find where the button text for the extras menu is being formatted. (Trying to format the new button text like the other buttons)

**Comment by hhyyrylainen** [comment]
Static text in the game is set in the Godot scene files. So the extras button text is in the main menu scene file. I assume that's what you are asking.

**Comment by TheHungryBandito** [comment]
So in the main menu scene file, all the letters are capitalized in both the inspector and on scene.
But in-game, the first letter of each word is capitalized.
So I'm looking for where this takes place so I can do the same with the suggestions button.

**Comment by hhyyrylainen** [comment]
Unless text is marked PLACEHOLDER it is used as translation keys. https://github.com/Revolutionary-Games/Thrive/blob/master/doc/working_with_translations.md#adding-new-content-into-the-game-with-translation-in-mind

**Comment by TheHungryBandito** [comment]
When I run 'dotnet run --project Scripts -- localization' it updates all .po files with the new "SUGGESTIONS" key but keeps trying to remove the "QUESTIONS" Key from some files.

I'm not quite sure why, is this okay?

**Comment by hhyyrylainen** [comment]
If some key is no longer used anywhere it is expected to be deleted. Did you remove the last question mark button or something? If so I'd add one back to like the tools menu or something.

Incorrectly removed translation keys is a sign that some tool is not the right version on your system.
