### ISSUE TITLE
Tutorial should be prevented if game is entered through the auto-evo exploring tool

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3718]
similarly to how tutorial is disabled when in freebuild.

For some reason even though the auto-evo exploring tool enables freebuild mode, I noticed the tutorials show up in the game. Should be relatively easy to find why the tutorials don't get disabled.

**Comment by TheHungryBandito** [comment]
I'm would like to take on this issue as my first issue.
I found the cause.

Problem:
When AutoEvoExploringTool.cs [initializes the game](https://github.com/Revolutionary-Games/Thrive/blob/8572b4e3a365164f0ce0f3eceaf26f40ddf9ec43/src/auto-evo/AutoEvoExploringTool.cs#L324), it starts a [new microbe game](https://github.com/Revolutionary-Games/Thrive/blob/8572b4e3a365164f0ce0f3eceaf26f40ddf9ec43/src/general/GameProperties.cs#L61) without passing in true for freebuild mode but enables [freebuild later](https://github.com/Revolutionary-Games/Thrive/blob/8572b4e3a365164f0ce0f3eceaf26f40ddf9ec43/src/auto-evo/AutoEvoExploringTool.cs#L803) when transitioning to the microbe editor. 
This bypasses the GenerateRandomSpeciesForFreeBuild() as well as the TutorialState.enabled = false.

Should it be bypassing the random species generation?

**Comment by 84634E1A607A** [comment]
Bypassing random species generation is intentional (to prevent multiple roots in the evolutionary tree). Not disabling the tutorial is a bug.

**Comment by hhyyrylainen** [comment]
I think one of two things probably make sense as a starting point:
- make a new constructor that allows separately disabling tutorials and enabling freebuild
- make a method / call one if one already exists, that can disable tutorials after creating the game, and then use that in the exploratory tool.

**Comment by TheHungryBandito** [comment]
Cheers, I used the "TutorialState.Enabled" property to disable the tutorial as the game starts in AutoEvoExplortingTool.cs.
