### ISSUE TITLE
Fixing Thrive on Linux

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#372]
Currently it is impossible to even build Thrive on linux.

I'm currently trying to get Thrive to build. I had to already make some changes:
- Replace FindFFMPEG.cmake with the one found in OgreFFMPEG
- Add install support to OgreFFMPEG CMakeLists.txt (I haven't made a pull request for that yet)
- Use a specific revision of cAudio as the latest one is broken
- Rename references to CEGUIVector2 to CEGUI::UVector2
- Fix CMakeLists.txt to not try to find DEBUG versions on Linux (the find.cmake file doesn't support that)

I also made a setup script for Thrive on linux: https://gist.github.com/hhyyrylainen/dd6e2194987182c45aa0 
Should work on Fedora, but I haven't tried to use with a clean install to see if I forgot some packages. On Ubuntu it might work, as I had to guess the package names.

As a side note:
I just now I found "#include <windows.h>" in membrane.h... I mean seriously you can't get more platform specific than that. Is there any reason for including that or should there be a preprocessor definition like THRIVE_WINDOWS_BUILD set by cmake to 1 on windows?

**Comment by TheCreator--** [comment]
Oh Beligum. That's my fault. You should be able to safely delete. I was just doing all of my prototyping on a Win32 application and then basically just copied and pasted the code.

**Comment by jjonj** [comment]
Thanks for doing this hhyyrylainen!  
You're right it's in a scrappy place for linux atm! Did you read my comments in the other linux thread, where I listed some of the workarounds we did to get it working?  https://github.com/Revolutionary-Games/Thrive/issues/368#issuecomment-164187122 and you can remove the windows.h np, it's not used

**Comment by hhyyrylainen** [comment]
I finally got it to compile after adding swresamble to the list of libraries Thrive.lib links against.
And the main menu shows up correctly which is great, though the game crashes when trying to launch.
Adding a bit of debugging statements and this is why it crashes:
```
Removing workspace 0xa19afb0
Removing workspace 0xa19afb0
```
Now I just need to figure out why the same workspace is added to the list of workspaces twice.

**Comment by hhyyrylainen** [comment]
Created a pull request: https://github.com/Revolutionary-Games/Thrive/pull/373
