### ISSUE TITLE
Make LAWK mode the default in new game settings

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3724]
I think as a science education game we should have the LAWK mode on by default so players who don't really know will just leave it on. And if it turns out they wanted it anyway, they can do another playthrough with the new parts.

The suggestion I made got decent enough votes: https://suggestions.revolutionarygamesstudio.com/posts/3/make-lawk-the-default-mode

**Comment by HyperSoop** [comment]
I think being an education game is not the main focus - the main focus is to be a fun game. If someone wants scientifically accurate gameplay, they have the option - but it's in no way the majority of people who want to sacrifice fun for scientific accuracy.

**Comment by hhyyrylainen** [comment]
This suggestion was already accepted when I asked on the dev discord, also that suggestion has relatively good votes.

**Comment by HyperSoop** [comment]
Yet still it makes no logical sence to block the user off a major part of the game's content if they forget to uncheck a checkbox.

**Comment by nickthenick** [comment]
It's not about adding game content, it's about changing the rules of the game. Eventually there'll be plenty of content such that LAWK being on or off will not appreciably change the amount of content the player notices in the game. However the significance of the setting is that it allows ways of life to evolve that break rules of chemistry, physics, and evolution that we have observed, which can change in-game metas and lead to very different outcomes of life on their playthroughs.

**Comment by hhyyrylainen** [comment]
@nickthenick in my understanding anything non-LAWK still has to follow the laws of physics at least mostly, so it's not a feel free to do everything crazy kind of permission, but more like it allows features that kind of seem possible in a physics sense, but for some reason don't exist on Earth.

If I can find the button I'll lock this discussion to just contributors as debating this here is completely pointless as the team is supportive of this change.
