### ISSUE TITLE
[ feature ] Thinking about adding (active) transport proteins into game

### ISSUE THREAD

**Issue by CicadaSeventeen** [Revolutionary-Games/Thrive#3726]
In short, I thinking add active transport to game can improve game experience and also make it more scientific. 
Transport proteins (or carrir proteins. They are slightly different but I do not want to say too many details here) can help to move materials, and especially there is something called active transport which is the movement of molecules across a cell membrane from a region of lower concentration to a region of higher concentration. In a word, it can help cells to concentrate materials. So adding transport proteins to help cells to gain compounds (glucose, ammonia, hydrogen sulfide, phosphate and iron) at some cost of ATP is reasonable and not there is not big scientific problem. In fact, such strategy is used by most species. Using transport proteins to make concentrate atmosphere gasses is also reasonable but probably not really suit for Thrive’s system.
As for gamming experience, I find I have to worry about getting phosphate all the time and sometimes I have to spend tens of minutes to search phosphate to get evolution. Seeking iron or hydrogen sulfide is even more worrying because it is a life-or-death problem. I must be a quick cell otherwise compounds are likely to have been eaten before I get there. And even if my species is quick, I need to compete with other cells of my own species. I know it is reasonable in fact, but it does hurt my experience. So why not allow player to be a carefree autotrophic cell with the help of transport proteins?

**Comment by hhyyrylainen** [comment]
Github issues are for tracking concrete bugs and accepted new features to be completed. If you want to provide general feedback or suggestions, please head over to our community forums: https://community.revolutionarygamesstudio.com/
