### ISSUE TITLE
Improve model for the mucilage jet

### ISSUE THREAD

**Issue by MirrorMonkey2** [Revolutionary-Games/Thrive#3743]
Related to this feature: https://github.com/Revolutionary-Games/Thrive/pull/3590
Should look something like this: https://cdn.discordapp.com/attachments/464846906971914250/1008891677659897896/another_vase.png

**Comment by hhyyrylainen** [comment]
The feature was just merged: https://github.com/Revolutionary-Games/Thrive/pull/3590
It's still missing:
- Icon
- Model file needs fixes to move around like other organelles and the render order problem in the graphics needs to be resolved
