### ISSUE TITLE
"Microbe Stage" appears as "MicrobeS"

### ISSUE THREAD

**Issue by Alex-the-666** [Revolutionary-Games/Thrive#375]
Just the normal gui. http://i.imgur.com/m0r1iQC.png

**Comment by TheCreator--** [comment]
This thread shows the current work done on the microbe stage GUI:
http://forum.revolutionarygamesstudio.com/t/microbe-gui/111/13

**Comment by lukaandjelkovic** [comment]
Fixed by #392.

**Comment by TheCreator--** [comment]
Fixed with #397!
