### ISSUE TITLE
Player cell in the early multicellular prototype can get damaged if another colony cell's pilus gets hit with a toxin (physics engine bug)

### ISSUE THREAD

**Issue by stoptakingusernames** [Revolutionary-Games/Thrive#3760]
**Describe the bug**

If your multicellular organism contains another cell with a pilus, all the damage that would happen to the specified cell would instead transfer to the player cell if a toxin shot hits the specified cell's pilus

**To Reproduce**
Steps to reproduce the behaviour:
1. Enter the early multicellular prototype
2. Create a new cell with a pilus and add it to your organism
3. Let the added cell's pilus get hit with a toxin shot from an enemy cell
4. See the player cell being damaged instead

**Expected behaviour**
The toxin should damage the cell that has the pilus, and not the player cell

**Additional context**
[You can see this bug in action in this video at 21:00](https://www.youtube.com/watch?v=fcG1mqGMi0c)

**Comment by hhyyrylainen** [comment]
I'm 99% sure that this is a Godot physics engine bug where it gives us an obviously false sub shape index (it does that a ton), and we can either guess something or assume the colony lead cell got it (this is the current behaviour).
