### ISSUE TITLE
Add save filename parsing safeguards against invalid numbers

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3763]
to prevent a crash like: https://community.revolutionarygamesstudio.com/t/crash-upon-opening-microbe-editor-v-0-5-9/5414/3?u=hhyyrylainen

This is likely the code where we need to change something:
```c#
                int found = Convert.ToInt32(match.Groups[1].Value, CultureInfo.InvariantCulture);
```

I think the regex is probably already fine so we just need to guard against a case where the user smashes the keyboard and makes a name like `34523454554455456565656` by either switching to `long` or switching to `TryParse` and skipping files that don't seem to match our naming scheme.

**Comment by hhyyrylainen** [comment]
I'll assign you to this issue. Let me know if you have problems or if you can no longer work on this.

**Comment by blouflashdb** [comment]
Should totalCount be incremented for all files in the save folder or just the ones matching the save file naming?

**Comment by hhyyrylainen** [comment]
Save counting is called separately for auto saves and quick saves. If it counted all saves then it would result in wildly incorrect results in terms of preserving the selected number of saves of each type in the options menu.
