### ISSUE TITLE
Organelles past the "arrow" sign in the microbe editor do not have a membrane

### ISSUE THREAD

**Issue by Alex-the-666** [Revolutionary-Games/Thrive#377]
http://i.imgur.com/Mo4nRqQ.png

putting organelles past the arrow sign or directly above it causes the cell membrane not to envelop the organelles, making them float around in nothing :P

**Comment by Moopli** [comment]
Any organelles placed far away from most of the other organelles will do the same. The membrane calculations do some averaging to produce a smooth shape, and that leaves some artifacts.

Would probably require a new membrane algorithm though.

**Comment by TheCreator--** [comment]
Nope, that's actually partially my fault. The membrane starts with a square of constant length and makes it smaller. So this could easily be fixed by calculating the distance between the two fartherst away organelles and setting the "membrane square" side-length to be that distance.

**Comment by jjonj** [comment]
Fixed with #e26bf68a12f
