### ISSUE TITLE
Console Spam + FPS drop when cell makes noise

### ISSUE THREAD

**Issue by Alex-the-666** [Revolutionary-Games/Thrive#378]
Whenever another cell makes a noise the console is spammed and the FPS drops drastically. http://i.imgur.com/gr3tjz3.png

**Comment by TheCreator--** [comment]
I'm pretty sure its not the cell noise that drops the FPS, but rather the fact that there are a bunch of new microbes that enter the screen that need to be calculated. Other than that, this issue is identical to #330.
