### ISSUE TITLE
Unable to press suicide button

### ISSUE THREAD

**Issue by Oliveriver** [Revolutionary-Games/Thrive#3787]
Due a regression, mouse input for the suicide button is blocked while hovering over the icon inside the button.

I tracked the regression down to this commit: https://github.com/Revolutionary-Games/Thrive/commit/ef9f55664e30bd9bfed574e42832665f6edc2dd7

**Comment by hhyyrylainen** [comment]
I'm pretty sure I found the problem, the hotbar overlaps the bar area now that there's one more button there:
![kuva](https://user-images.githubusercontent.com/3796411/190575286-c513fa35-cc37-42b6-8adc-0af0502b8172.png)

I'll reduce the size of the hotbar slightly, as I think keeping it centered is important.
