### ISSUE TITLE
Pressing R (or whatever mucilage is binded to) still plays the mucilage sound effect even if your cell has no mucilage

### ISSUE THREAD

**Issue by stoptakingusernames** [Revolutionary-Games/Thrive#3791]
**Describe the bug**

The mucilage ability sound effect will play when using it's activation keybind even if you don't actually have any mucilage on your cell

**To Reproduce**
Steps to reproduce the behaviour:
1. Start a new game
2. Press the mucilage ability button (default r)

**Expected behaviour**
The mucilage ability sound effect should only play when you actually have the organelle and ability

**Comment by Oliveriver** [comment]
Turns out this was a typo. My bad.

Fixed here: https://github.com/Revolutionary-Games/Thrive/pull/3793
