### ISSUE TITLE
Main menu doesn't appear

### ISSUE THREAD

**Issue by ptkato** [Revolutionary-Games/Thrive#381]
When starting the game it opens fine, the music plays, but there's no menu. It was reported at [reddit](https://www.reddit.com/r/thrive/comments/3wrm3w/starting_game_has_no_menu_help/?ref=share&ref_source=link) a few weeks ago.

![no menu appearing](http://i.imgur.com/7cw5FXj.jpg?1)

I'm using Windows 7 and 0.3.0 release.

**Comment by Oliveriver** [comment]
Hmm...whenever this has come up I've always been really confused, and to finally see a screenshot makes it even weirder. The background is even handled by exactly the same set of files as the GUI, so I have no idea what could be going on.

Could you check a couple of things to make sure it isn't something simple we've been missing:

 - Are there files called ThriveGeneric.png and ThriveGeneric.imageset in the game files? (gui -> imagesets) If there are could you upload them somewhere so we can check they don't have any issues?
 - Does the planet change position to centre itself if you resize the window?
 - Do you have the same issues in version 0.2.4?

**Comment by ptkato** [comment]
Yes, there are the files: [ThriveGeneric.zip](https://github.com/Revolutionary-Games/Thrive/files/96717/ThriveGeneric.zip)

I don't know, never realized that, but I guess it centres itself. About the 0.2.4, the latest release (0.3.0) is the first one that I'm really running, so I can't state anything.

**Comment by jjonj** [comment]
Could you try replacing your assets/gui/layouts/MainMenu.layout with this file (rename it to .layout instead of .txt) and lemme know if you just get a black screen with a bit of text or if you see the buttons:

[MainMenu.txt](https://github.com/Revolutionary-Games/Thrive/files/97719/MainMenu.txt)

**Comment by ptkato** [comment]
I got only a black screen with no text.

![no menu](http://i.imgur.com/YXd52GG.png)

**Comment by Oliveriver** [comment]
@jjonj Could it be that there's something wrong with the PolyButton definition? Since 0.2.3 only the buttons have been breaking, all other element types seem to work fine.

**Comment by jjonj** [comment]
We could try letting ptkato use a normal button to find out, it's just really strange though

**Comment by ptkato** [comment]
Well, I got rid of Windows, can't test it anymore, but my video card is an onboard one called Ironlake Mobile.

**Comment by hhyyrylainen** [comment]
This is probably fixed in engine_refactor (or will be once we are ready to merge), not much can be done about graphics drivers. (Maybe now the game will refuse to run on bad drivers as opengl 3.3 is required).
