### ISSUE TITLE
Respawn location

### ISSUE THREAD

**Issue by TjWhale** [Revolutionary-Games/Thrive#382]
ATM the player respawns where they died which is a problem for cells that can't move and may become a problem later on if there are particularly vicious predators. It might be good to make the player respawn in a new place.

**Comment by Untrustedlife** [comment]
Ill fix this tonight

**Comment by Untrustedlife** [comment]
actually maybe we shoudl wait on this (it s labeled 4.1, and random respawn locations would cause debugging issues)

**Comment by Untrustedlife** [comment]
Hmmm, maybe this can be added now?

**Comment by Untrustedlife** [comment]
Fixed it in this commit:
https://github.com/Revolutionary-Games/Thrive/commit/2c88b92f27d6300dd0efec70ae0776337f02a2b3
