### ISSUE TITLE
Stop cells that join a colony from independently using mucilage

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3844]
https://community.revolutionarygamesstudio.com/t/colony-members-automatically-use-mucilage-jet-thrive-0-5-10/5574

this is not fully confirmed but it may be that the mucilage emit timer still has time in it when a cell joins a colony and as a result emits mucilage independently from the main cell's control in the colony for some time.

**Comment by hhyyrylainen** [comment]
After redoing a bunch of stuff for the ECS refactor, there is a timed mucilage emission timer, so it should be pretty easy to just clear any queued time when a colony member is attached.

**Comment by CI09** [comment]
Would clearing force queued enough?

**Comment by hhyyrylainen** [comment]
I think it would be as AI cells can no longer think when they join so the mucilage emission when cleared on attach will then stay cleared. Of course it'll only be certainly known after trying.
