### ISSUE TITLE
Modify auto-evo prediction to show total energy first (and population second)

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3845]
this way players can see their energy gain of their species, this should hopefully reduce people incorrectly interpreting becoming bigger having a negative impact on their population.

https://forum.revolutionarygamesstudio.com/t/redefining-species-success/964

I'd say the display should be "energy (population)", and the tutorial about the prediction should be also updated a bit to make this clear. If there's an icon to be shown it should be for the total energy and not the less important, secondary value of population.

**Comment by CI09** [comment]
Like this?
![image](https://github.com/Revolutionary-Games/Thrive/assets/100433934/4dc4730b-d2d1-4d88-ba6f-a9b791e0343c)
Should I write simply "Total Energy Gathered", or this and also a tooltip?

**Comment by hhyyrylainen** [comment]
Depends on how it was done. I would like to keep the panel simple and short to not look overwhelmingly complex. That's why I suggested the approach of switching it to display things like "1235 (212)" where the first number is the energy and second is just the population and letting the tutorial (and probably a tooltip) carry out explaining what the numbers are.

**Comment by CI09** [comment]
![image](https://github.com/Revolutionary-Games/Thrive/assets/100433934/d04324e6-9ab6-44f4-b217-ece66e8b6bfe)
Should I try making the 

> "1235 (212)"

method?
(Also how do I make so inside a string I can put some value there, like `string string1 = "abc${nextThreeLetters}ghi";`? I saw it somewhere but I couldn't find anywhere how to do it.)

**Comment by hhyyrylainen** [comment]
>  Should I try making the

Yes.

>  a string I can put some value there, like string string1 = "abc${nextThreeLetters}ghi";? 

Do you mean `$"string with {variable} inside it"`? That feature is called string interpolation: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated

**Comment by CI09** [comment]
![image](https://github.com/Revolutionary-Games/Thrive/assets/100433934/cb4cb524-0d35-49c6-a720-5c2f245a619b)
Might need some adjustments. I'll remove energy gathered indicator later.

I kinda don't know if the code is pretty enough though:
![image](https://github.com/Revolutionary-Games/Thrive/assets/100433934/4e06a16c-d923-4f41-ae40-edb7d1b19f31)

**Comment by hhyyrylainen** [comment]
There's a method in the codebase to format things with K and M suffix so that very long numbers aren't shown. `StringUtils.ThreeDigitFormat`

**Comment by CI09** [comment]
![image](https://github.com/Revolutionary-Games/Thrive/assets/100433934/f9984f6c-1d43-4e8e-a4f8-697bfbbf9717)
Variable name is still `totalPopulationLabel`, should I change it?

**Comment by hhyyrylainen** [comment]
I guess it would be good to change it to reflect what it is actually used now.
