### ISSUE TITLE
Can't start game (W10 - "l'application a cessé de fonctionner")

### ISSUE THREAD

**Issue by Levi59** [Revolutionary-Games/Thrive#385]
Hi!

I have downloaded  the last zip of thrive and when i launch the bat file, i get a black screen and then windows says that thrive has crashed and search for a solution. The first time, I've been prompt to choose option so I have chosen the only choice (opengl) and nothing more But it don't display anymore.

Am i forgetting something?

**Comment by jjonj** [comment]
I also posted in the forum post you made but perhaps you missed it. Try this version and let me know if it works: mega.nz/#!URJi0SCT!47BC69Z1wRphzhHkQ9ykeTjn6IMu1sVXa96RQR5l-n4
