### ISSUE TITLE
Export Auto-Evo Explorer Data

### ISSUE THREAD

**Issue by GameDungeon** [Revolutionary-Games/Thrive#3862]
While the in-game tool is very nice, the ability to easily export the data and analyze it in other software would be beneficial. If nothing else, just being able to freely create graphs from it, without dealing with godot, would go a long way to help understand the systems we have in place.

**Comment by hhyyrylainen** [comment]
This is kind of an alternative to: https://github.com/Revolutionary-Games/Thrive/issues/3626 but I think 3626 is more important as each people individually having to write or get ready-made spreadsheets to make sense of the data would be a huge extra hassle.

**Comment by hhyyrylainen** [comment]
As I said, this is technically a different feature request, which is why I didn't close this as a duplicate, though less useful in my opinion for the average developer using the auto-evo explorer.

**Comment by GameDungeon** [comment]
I feel at least easier to implement though if we just want to get something done for it.

**Comment by 84634E1A607A** [comment]
Auto evo explorer holds a huge amount of data. It is possible to make snapshots, but it will be as complex as a regular save. As for - exporting the data, I doubt if it is necessary to import a whole office library / database library just for this function.

**Comment by hhyyrylainen** [comment]
Surely it would be exported as either JSON or CSV? There's no need for a spreadsheet library to do CSV.

**Comment by 84634E1A607A** [comment]
Actually I think that exporting to JSON makes little sense, as JSON strings are still hard for most to tackle. CSV will do, (but an external lib is still preferred because we need to convert a horizontally-structured list to a vertical one)

**Comment by GameDungeon** [comment]
I will stand by that you don't at all need an external lib for CSV. It is really easy to handle, and honestly in this case an external lib would likely perform far worse than something we could cook up.

**Comment by 84634E1A607A** [comment]
https://github.com/JoshClose/CsvHelper seems to be a good CSV library.
