### ISSUE TITLE
Game cannot load a corrupt save with broken compressed data

### ISSUE THREAD

**Issue by mcDandy** [Revolutionary-Games/Thrive#3864]
**Important**
Please only submit technical bug reports here. This is not a place to make feature requests
or suggestions. For that please visit our suggestions site:
https://suggestions.revolutionarygamesstudio.com/

Or our community forums for longer discussions
https://community.revolutionarygamesstudio.com/

**Describe the bug**
Cannot load save saved in multicellural stage. (or I had bad luck and my save got corrupted)

**To Reproduce**
Steps to reproduce the behaviour:
1. Save game in multicellural stage (I had 3 types of cells where 1 was unused)
2. exit the game
3. open the game
4. load saved game

**Expected behaviour**
A clear and concise description of what you expected to happen, instead of what actually
happened.
World would load.

**Screenshots**

**System info (please complete the following information):**
- OS: [e.g. Windows 10] Windows 11 (22h2)
- Graphics card (you can find this in the game logs) [e.g. OpenGL ES 3.0 Renderer:
    GeForce GTX 1080 Ti/PCIe/SSE2] OpenGL ES 3.0 Renderer: Quadro P1000/PCIe/SSE2
- Thrive version [e.g. 0.4.0.2] 0.5.10.0

**Logs**
File load crash log: https://pastebin.com/bvWTFnGF
Mono log: [2022-11-19_23.33.37_9704.log](https://github.com/Revolutionary-Games/Thrive/files/10048077/2022-11-19_23.33.37_9704.log)
Log file: [log.txt](https://github.com/Revolutionary-Games/Thrive/files/10048078/log.txt)

Please use a text hosting service (for example https://pastebin.com/) to submit your logs.
You can copy the launcher output or the contents of the following files: `log.txt` and mono
log file. You can find these log files by reading the game log to see their location.
For example:
```
Mono: Logfile is: /home/hhyyrylainen/.local/share/godot/mono/mono_logs/2020_07_21 23.10.26 (265121).txt
Game logs are written to: /home/hhyyrylainen/.local/share/Thrive/logs latest log is 'log.txt'
```

**Additional context**
[save.zip](https://github.com/Revolutionary-Games/Thrive/files/10048085/save.zip)

**Comment by hhyyrylainen** [comment]
I'd say you had very bad luck. This is the first time I'm seeing a fully corrupt Thrive save. Even extracting with a normal ".tar.gz" extractor the file is broken. So there's nothing the game can do to load a corrupted compressed file.
We haven't changed the file writing really that significantly any time recently so I don't know why the game would suddenly now create a corrupt save other than really bad luck on your part (as I said this is the first corrupt save file for Thrive I've ever seen).

**Comment by hhyyrylainen** [comment]
I'll slightly tweak how saves are written to make sure there's no pending data that doesn't get written, but I doubt that'll have much of an effect. So I've opened an issue about the game verifying the save files it writes to make sure they aren't broken: https://github.com/Revolutionary-Games/Thrive/issues/3865
