### ISSUE TITLE
Add a button somewhere in the game menu to report a bug

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3882]
with the new launcher Thrive itself should have a button to open the link to: https://community.revolutionarygamesstudio.com/c/bug-reports/13

**Comment by d0tplus** [comment]
I started working on adding this in.

In terms of game menu location, I was thinking of adding the button to the PauseMenu. Is there any other potential locations that this button should possible go? 

![editor_screenshot_2023-02-10T031341-0800](https://user-images.githubusercontent.com/95166858/218079778-a723581d-1e78-410f-a84b-e0854007d9ef.jpg)

**Comment by hhyyrylainen** [comment]
Maybe it could also be in the popup that opens in the main menu with the bottom left social icon buttons? The leftmost button is for our links.
