### ISSUE TITLE
Microbe Editor - Flagellum glitch

### ISSUE THREAD

**Issue by lukaandjelkovic** [Revolutionary-Games/Thrive#389]
If i click flagellum, and then set it into cell, one flagellum would spawn at right side of cell, rotated 90 degrees into left.

 Sorry for my bad english, also another litle question:

Why are you coding half in Lua and half in C++? C++ is fastest language, idk why would scripts folder be in Lua.

**Comment by jjonj** [comment]
Hrmm, could you give a screenshot of the problem you're seeing?

We use lua for two reasons:
 - It's a lot faster to program things in when we don't need to recompile every time  
 - It enables modders to change the game

Things where speed is important we want to use C++

**Comment by TheCreator--** [comment]
Fixed with #397!
