### ISSUE TITLE
Enable day/night cycle by default (once more polished)

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3895]
Once these are done the day/night cycle should be enabled by default:
- [x] https://github.com/Revolutionary-Games/Thrive/issues/3881
- [x] https://github.com/Revolutionary-Games/Thrive/issues/3888
- [ ] https://github.com/Revolutionary-Games/Thrive/issues/3890
- [x] https://github.com/Revolutionary-Games/Thrive/issues/3891
- [x] https://github.com/Revolutionary-Games/Thrive/issues/3892
- [x] https://github.com/Revolutionary-Games/Thrive/issues/3893
- [ ] https://github.com/Revolutionary-Games/Thrive/issues/3894
- [x] https://github.com/Revolutionary-Games/Thrive/issues/3918
- [x] https://github.com/Revolutionary-Games/Thrive/issues/3919
- [x] https://github.com/Revolutionary-Games/Thrive/issues/4067
- [x] BUG: https://github.com/Revolutionary-Games/Thrive/issues/4286
- [x] ~~Existing saves tested from 0.5.10 that they don't break (and get day/night enabled).~~ No longer relevant as we'll have at least one save breakage point before day/night is enabled by default so all started games will have the light cycle data in them.
- [ ] https://github.com/Revolutionary-Games/Thrive/issues/5147

Not entirely necessary but would be nice to have:
- https://github.com/Revolutionary-Games/Thrive/issues/3920

Note that we might need a save upgrade step for 0.5.10 saves that are loaded (as going from value missing to enabled by default might cause bugs), or alternatively testing and fixing any problems with enabling day/night cycle with missing objects from older saves needs to be made to work. 
Also need to update the explanation in the new game setup to no longer have a warning about it making photosynthesis harder.

Edit: added a pretty serious GUI bug to the list.

**Comment by ender-titan1** [comment]
Im planning to pick up #3881 and #3891

**Comment by CI09** [comment]
- https://github.com/Revolutionary-Games/Thrive/issues/3891
Honestly, in my opinion this not necessarily should be implemented. In that case it would be like "let go of the hand" of the player. That would add that element of uncertainity that would add up to overall experience.
 - https://github.com/Revolutionary-Games/Thrive/issues/3890
Theoretically, night could be balanced (or unbalanced) in such way, that it is very punishing and unforgiving. It could be something to fear off that would be in back of the head of players to always take care of when designing a species. But that's subject to be discussed over a bit.
 - https://github.com/Revolutionary-Games/Thrive/issues/3893
I can do this. I can make it give glucose amount dependant on amount photosynthetic organelles/proteins.

**Comment by hhyyrylainen** [comment]
> Honestly, in my opinion this not necessarily should be implemented. In that case it would be like "let go of the hand" of the player. That would add that element of uncertainity that would add up to overall experience.

I don't agree because before we added the ATP balance bar to the editor, basic ATP balance was a major hurdle for many players.

> Theoretically, night could be balanced (or unbalanced) in such way, that it is very punishing and unforgiving. It could be something to fear off that would be in back of the head of players to always take care of when designing a species. But that's subject to be discussed over a bit.

We have difficulty levels so night should only be punishing on hard difficulty.

>  I can do this. I can make it give glucose amount dependant on amount photosynthetic organelles/proteins.

That is an immediate fix, but a full fix would be to add general code that detects compounds that are less available during the night and compensates those. That's needed because there is a "threat" from the game design team that some other compound except sunlight will be made to vary throughout the day in the future.

**Comment by CI09** [comment]
>That is an immediate fix, but a full fix would be to add general code that detects compounds that are less available during the night and compensates those. That's needed because there is a "threat" from the game design team that some other compound except sunlight will be made to vary throughout the day in the future.

Well, glucose (I think) doesn't vary currently during the cycle and I don't think it should by itself so I don't know how would that be handled.

**Comment by hhyyrylainen** [comment]
A generic method should be written that detects compounds that vary. I mean that hardcoding sunlight using processes to only be considered for adding compounds to survive the night shouldn't be done. Instead the code should find processes that will vary throughout the day no matter what the inputs to that process are.

**Comment by hhyyrylainen** [comment]
I've taken care of most of these issues and I'll still have time for this release to take care of the blocking other parts of this. I'm closing this issue as I've enabled day/night by default already as I'm confident we can get it good enough for this release. I'm keeping track of the still open parts separately of this.
