### ISSUE TITLE
Make player movement in microbe stage more readable

### ISSUE THREAD

**Issue by Nimbal** [Revolutionary-Games/Thrive#39]
Currently, players have very few reference points to gauge their movement speed and direction. Even if there are other objects on the screen, they might be moving, too, distorting the perception player movement.

To remedy this, design and implement a system for displaying "floaters". Floaters are small, mostly transparent particles that are overlayed onto the game world as if looking through dirty water. Those particles are dense enough to be easily visible without occluding the game world.

Floaters will not interact with other objects, but only react to player movement. They will always move in the direction opposite of the players'. When the player stands still, the floaters stand still also.

**Comment by TheCreator--** [comment]
Should be easy to fixe with a parallax background.

**Comment by TheCreator--** [comment]
There is now a parallax background in 0.3.1
