### ISSUE TITLE
When max ATP is really high it gets cutoff in the GUI

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3902]
This is the second time we've been reported that the max ATP doesn't match what the player has stored:

![screenshot](https://thrivecommunity-uploads.b-cdn.net/original/2X/c/cc33b2d4bb21b4ea3a6ca644eaefa0989675072e.jpeg)

We need to either line wrap and allow the box to grow in size or come up with some thing to do like a "k" suffix to get smaller numbers.

**Comment by Sur3** [comment]
How about letting the cell self-ignite if there is more than 900 ATP? I mean there is only limited chemical energy you can store in limited space until something bad will happen..

**Comment by JrSti** [comment]
"How about letting the cell self-ignite if there is more than 900 ATP? I mean there is only limited chemical energy you can store in limited space until something bad will happen..
Also in multicellular setting we could use the average per cell instead of the total ATP." I agree with that.

**Comment by hhyyrylainen** [comment]
There's already an almost complete PR fixing this: https://github.com/Revolutionary-Games/Thrive/pull/4099
