### ISSUE TITLE
Please add a real-time clock

### ISSUE THREAD

**Issue by Sur3** [Revolutionary-Games/Thrive#3904]
The game should have a real-time clock similar to the fps counter, because I am totally loosing my time-sense when playing the game.

**Comment by hhyyrylainen** [comment]
This is not really a technical problem or a thing most games have, as such this should be suggested on the suggestions site: https://suggestions.revolutionarygamesstudio.com/

**Comment by Sur3** [comment]
Ok I created a suggestion ticket for this feature: https://suggestions.revolutionarygamesstudio.com/posts/282/add-a-clock-overlay-for-real-time-and-in-game-time
