### ISSUE TITLE
Add fast-forward button multiplying game speed.

### ISSUE THREAD

**Issue by Sur3** [Revolutionary-Games/Thrive#3905]
Being a sessile plant and waiting for the phosphate and ammonia to accumulate can become quite boring. It would be nice to have a fast forward button beside the pause button to increase the game speed at such times to move faster to the next mutation.

**Comment by hhyyrylainen** [comment]
The game already lags enough at normal speed, and also a kind of early strategy mode is planned to be the way to handle that gameplay being extremely boring otherwise.
In case it wasn't clear enough from there just being a bug report template, Github is not the place to request features.

**Comment by Sur3** [comment]
I found a related suggestion ticket for this: https://suggestions.revolutionarygamesstudio.com/posts/29/add-time-lapse-mode-for-sessile-gameplay
