### ISSUE TITLE
Microbe Stage - GUI weird on extreme resolutions (low and high)

### ISSUE THREAD

**Issue by ghost** [Revolutionary-Games/Thrive#391]
I just tried to load Thrive 0.3.0 into 640 x 480, and the buttons and menus were so large that i even wasn't able to see what is around my cell.

Should implement the basic GUI scaling.

**Comment by jjonj** [comment]
http://thrivegame.freeforums.net/thread/420/high-resolution-bugs

**Comment by hhyyrylainen** [comment]
This needs to be checked once the GUI for 0.4.0 is finalized.
