### ISSUE TITLE
Early multicellular body plan editor and cell editor can end up displaying at the same time

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3910]
obviously they shouldn't be able to display at the same time but every now and then someone shows a screenshot of that happening, like this:

![screenshot](https://steamuserimages-a.akamaihd.net/ugc/1988932273942179975/FF6C87E81620740C0C49D68C52E992CC75EF9DC2/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false)

This should be easy enough to fix once someone comes up reliable step of instructions that cause the bug to appear.

**Comment by hhyyrylainen** [comment]
Here's potential instructions on how to trigger that (from this video: https://www.youtube.com/watch?v=_G5_akrWCtg):

- Enter early multicellular
- Place another stem cell
- Duplicate the stem cell type
- Place a cell of the duplicated type
- Modify the stem cell type
- Delete an organelle
- Move an organelle
- Switch to the editor tab (by pressing the tab button, not NEXT)
- Place cell of stem type
- Place a cell of the duplicated type
- Modify the duplicated type again
- Do the exact same edits to the modified type now as the stem type
- Add an extra organelle of the removed type (different position than it was removed from)
- Switch back to the editor tab
- Place a cell of the modified type
- Place a cell of the stem type
- Switch back to the cell editor tab
- Move the organelle you last placed to the same position (but different rotation) than it was deleted from earlier
- Switch back to the editor tab
- Try to place a cell of the duplicated type (but fail due to not enough MP)
- Select the stem cell type
- Hit undo
- See the bug with both the cell and body plan editor world objects being visible

**Comment by 84634E1A607A** [comment]
A clear seq:

1. Add a cell
2. Move that cell
3. Go to cell editor
4. Hit undo

**Comment by Kashnox** [comment]
The same root issue of the multicellular editor not switching between tabs when actions are undone/redone can lead to a deleted cell type being shown in the Cell tab following these steps:

1. Duplicate any cell type
2. Modify that cell type
3. Undo the duplication while the Cell tab is still open

This problem should also be fixed with this issue.
