### ISSUE TITLE
Infinite MP achieved by abusing `Duplicate` and `Delete` to cell types

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#3912]
To reproduce:

![image](https://user-images.githubusercontent.com/60734649/205853207-08e73564-8340-4067-a29d-8bdf2b61ec42.png)

1. Do something

![image](https://user-images.githubusercontent.com/60734649/205853331-46bbbe7d-81b7-4268-814a-737db68a9269.png)

2. Duplicate cell type
3. Undo all changes (MP regain, but Stem2 still preserves all changes)
4. Loop 1-3 until you are satisfied
5. Add the final cell and delete the initial one. Now you can delete all medium celltypes
6. You can do anything with 25 MP (or less)

![image](https://user-images.githubusercontent.com/60734649/205853976-2738cca9-78a7-484f-9406-cc686c4326da.png)

(Sorry there isn't any more images because I accidentally triggered #3906 and crashed it.)

**Comment by Sur3** [comment]
The fix would be the solution I suggested in #3906 that every cell type gets its own history of changes and corresponding MP, and when copying a modified cell the MP and maybe even the change history is copied as well. Then we would just need to display costs for copying a specific cell type, and only when it is an unmodified cell type the cost would be zero.

**Comment by Sur3** [comment]
A possible simpler solution would be to include duplications and deletes in the undo history. But I think my former solution is more profound.

**Comment by hhyyrylainen** [comment]
The undo/redo history already contains pseudo entries for when a new cell type modification starts and ends. The problem is just that the action combining doesn't work correctly in some specific cases.
