### ISSUE TITLE
Compound clouds should not allow negative compound taking

### ISSUE THREAD

**Issue by Oliveriver** [Revolutionary-Games/Thrive#3927]
In this save, the player cell has ~0.9 glucose but only 0.5 glucose capacity.

https://www.dropbox.com/s/d8qrrqqphtn2bw2/glucose_bug.thrivesave?dl=0

The mitigations in https://github.com/Revolutionary-Games/Thrive/pull/3926 prevent this leading to an infinite compound venting glitch, but the root cause should still be fixed. We can then throw an error if we try to take negative compounds from a cloud.

**Comment by hhyyrylainen** [comment]
I renamed this issue to be against the actual hack to be added to the cloud system to fix this I wrote on my TODO list:
> issue to properly change to exception and fix everywhere after release
