### ISSUE TITLE
Implement system for tracking progress of part unlocks

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3935]
and add a few conditions to cut down on the initial number of organelles available to the player. As it was decided only the player should need to unlock the parts (AI species can evolve just like before) we can just put an unlock progress object into the GameWorld.

When unlocking an organelle there should probably be a popup in the cell editor that displays for a few seconds that a new part is unlocked.

https://forum.revolutionarygamesstudio.com/t/organelle-unlocks/696

**Comment by hhyyrylainen** [comment]
There's a partially done implementation of this feature here: https://github.com/Revolutionary-Games/Thrive/pull/4457 that may unfortunately never be completed, but it can serve as the base for the next person trying to tackle this issue.

**Comment by ender-titan1** [comment]
Im gonna have a lot of free time soon, so I've fetched the changes from the old PR into my own branch and I plan to do this once fog-of-war gets merged. As most of the work is already done this shouldn't take too long.
