### ISSUE TITLE
Implement endosymbiosis lite

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3936]
endosymbiosis lite is a system whereby engulfing prokaryotes the player can unlock organelles based on what the eaten bacteria had. On top of the base functionality there should be at least some tutorial somewhere letting the player know that this is possible. Maybe triggered when the player engulfs a cell for the first time?

Related to unlocking organelles: https://github.com/Revolutionary-Games/Thrive/issues/3935

**Comment by Nunez2196** [comment]
where should one start implementing this; what do we need at a minimum short term?

I'm guessing the absolute beast of a file that is Microbe.cs? Do we need #3935 before this can realistically go anywhere?

**Comment by hhyyrylainen** [comment]
#3935 doesn't need to be fully done before this, but these both systems should use the same kind of data storage system.

I guess minimally this system would need at least some eukaryotic organelles to be locked and unlocking of them would then be triggered by engulfing things. Also for merging tooltips and unlock condition hints would be needed to not make the understandability of the game much worse.

**Comment by hhyyrylainen** [comment]
In basically all endosymbiosis discussions I've seen, it would only really apply to the player and the AI mutations would be left alone, so AI wouldn't need to care about the restrictions we design for the player about gaining new organelle types.

**Comment by hhyyrylainen** [comment]
I'm marking this as impeded now as this depends on another major system that needs to get pushed through first (or at the same time if someone wants to make a really massive PR) as a base for this: https://github.com/Revolutionary-Games/Thrive/issues/3935
