### ISSUE TITLE
AI shoots toxin too early (while still turning)

### ISSUE THREAD

**Issue by adQuid** [Revolutionary-Games/Thrive#3938]
**Important**
Please only submit technical bug reports here. This is not a place to make feature requests
or suggestions. For that please visit our suggestions site:
https://suggestions.revolutionarygamesstudio.com/

Or our community forums for longer discussions
https://community.revolutionarygamesstudio.com/

**Describe the bug**

Currently when the AI decides to fire toxin at something, it chooses to look at the target then immediately queues a shot (https://github.com/Revolutionary-Games/Thrive/blob/master/src/microbe_stage/MicrobeAI.cs#L734) After the reduction in turning speed, this often results in AI species firing toxin wildly into the void. I suspect that this can be fixed organically by comparing the normalized lookAtPoint of the microbe with the facing direction.

**To Reproduce**
Steps to reproduce the behaviour:
1. Swim behind something that can and will shoot toxin at you

**Expected behaviour**
AI microbe turns, then shoots toxin when facing the target.

**Actual behavior**
AI fires as it starts to turn, then finishes turning towards the target.

**Comment by hhyyrylainen** [comment]
Probably an effect of the non-instant turning and the AI still doesn't know about it. Probably pretty easy to fix by comparing the actual angle of the AI to the target position to see when it is close enough to fire.
