### ISSUE TITLE
Create the missing symmetry buttons

### ISSUE THREAD

**Issue by jjonj** [Revolutionary-Games/Thrive#394]
All we have currently I don't think we need any greyed out version called SymmetryUnavailable
This involves editing assets/gui/imagesets/ThriveGeneric.png and assets/gui/imagesets/ThriveGeneric.imageset
"The white line signifies the symmetry and is supposed to change to a cross for 4-way symmetry, and six intersecting lines for hexagonal."

**Comment by Oliveriver** [comment]
I have the images somewhere from when I first created the GUI, I just need computer access to get them (which I'll have in like a day or two).

**Comment by TheCreator--** [comment]
We'll need to create a new type of button, though, right? Because we want it to cycle through the images. Or would it be possible to just have 4 different buttons and replace them depending on which one is selected?

**Comment by TheCreator--** [comment]
Fixed with #397!
