### ISSUE TITLE
Species colour doesn't always apply to all organelles properly

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3942]
Got a report that sometimes species show up with only partially correctly coloured organelles (the fossilize popup shows things correctly):

![fossilize screenshot](https://cdn.discordapp.com/attachments/958598553389903913/1052455524433657866/image.png)

![closeup](https://cdn.discordapp.com/attachments/958598553389903913/1052455524815343698/image.png)

**Comment by 84634E1A607A** [comment]
Possible cause: The previous generation has a different color than the current one.

![image](https://user-images.githubusercontent.com/60734649/208067069-edcf646c-dfce-4c1c-a6f2-32e57e9eaba8.png)
![image](https://user-images.githubusercontent.com/60734649/208067128-b95e19bd-06bc-4489-9f1a-a18ef3fe42c9.png)


So the old parts have the old color, while the new parts have the new color.

**Comment by hhyyrylainen** [comment]
> So the old parts have the old color, while the new parts have the new color.

That could explain things if there is a bug in the color applying. But I'm pretty sure that if the player changes colour in the editor, then their colour is correct after exiting even if they don't die. Though maybe we have special logic for that? And instead we could maybe make microbes copy their species colour when they spawn? Or something as that would be a bit annoying in terms of save compatibility or requiring extra compatibility code.
