### ISSUE TITLE
Remove redundant checks for engulfing / binding to disposed microbe

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#3945]
https://github.com/Revolutionary-Games/Thrive/blob/c9dc42df6904a1d19cb776ee909e30f362dc7d28/src/microbe_stage/Microbe.Contact.cs#L437-L437
https://github.com/Revolutionary-Games/Thrive/blob/c9dc42df6904a1d19cb776ee909e30f362dc7d28/src/microbe_stage/Microbe.Contact.cs#L1383-L1383
https://github.com/Revolutionary-Games/Thrive/blob/c9dc42df6904a1d19cb776ee909e30f362dc7d28/src/microbe_stage/Microbe.Contact.cs#L1680-L1680

I think these had stopped happening after https://github.com/Revolutionary-Games/Thrive/pull/3258 and https://github.com/Revolutionary-Games/Thrive/pull/3292

**Comment by hhyyrylainen** [comment]
I think there's a very significant bug related to disposing: https://github.com/Revolutionary-Games/Thrive/issues/3922

**Comment by 84634E1A607A** [comment]
Well I successfully crashed Thrive... I think I bound to a engulfed cell?
