### ISSUE TITLE
Refactor organelle addition

### ISSUE THREAD

**Issue by TheCreator--** [Revolutionary-Games/Thrive#396]
To add a cytoplasm organelle I have to add multiple lines in 4 different files, and this was before I even added the things that the cytoplasm was supposed to be. It was just a plain organelle. This should somehow be refactored to a single function that adds an organelle to the scroll bar.

**Comment by lukaandjelkovic** [comment]
I should first read some kind of documentation of Thrive code to help...

**Comment by femiaf13** [comment]
I'd like to tackle this while at the same moving as much organelle code to C++ as I can.

**Comment by hhyyrylainen** [comment]
@femiaf13 Are you done working on this?
Or is this possibly solved by someone else?

**Comment by hhyyrylainen** [comment]
This will be done when the engine_refactor is complete. Or at least this will be different then, so further fixes might still be required.

**Comment by hhyyrylainen** [comment]
The adding new organelles is now pretty different, so I'll close this. If this is still an issue this can be reopened.
