### ISSUE TITLE
enviroment glucose 

### ISSUE THREAD

**Issue by Dawn-Xu-helloworld** [Revolutionary-Games/Thrive#3961]
I believe that environmental glucose levels should vary with biomass rather than decreasing from generation to generation.

In this current version, only autotrophs survive to the end, no heterotrophs

**Comment by hhyyrylainen** [comment]
Github issues are for tracking concrete bugs and accepted new features to be completed. 

This is a bit too of a thing that requires an in-depth gameplay design discussion which should be done on the community forums: https://community.revolutionarygamesstudio.com/

Making the glucose reduction follow species amounts (and maybe only species that consume glucose) could make the reduction effect slightly more accurate, but I don't fully see why the need to have an open issue hanging around in our backlog about this.
