### ISSUE TITLE
[Crash] Clicking play world in auto evo crashes Thrive in certain situations

### ISSUE THREAD

**Issue by mcDandy** [Revolutionary-Games/Thrive#3979]
**Important**
Please only submit technical bug reports here. This is not a place to make feature requests
or suggestions. For that please visit our suggestions site:
https://suggestions.revolutionarygamesstudio.com/

Or our community forums for longer discussions
https://community.revolutionarygamesstudio.com/

**Describe the bug**

Crash when clicking play world in auto-evo tool

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to auto-evo tool
2. Simulate 100 generations
3. click play game button (or how does it names)

**Expected behaviour**
Game does not crash

**Screenshots**

**System info (please complete the following information):**
- OS: [e.g. Windows 10] Windows 11 22H2 (22623.1037)
- Graphics card (you can find this in the game logs) [e.g. OpenGL ES 3.0 Renderer:
    GeForce GTX 1080 Ti/PCIe/SSE2] Quadro P1000/PCIe/SSE2
- Thrive version [e.g. 0.4.0.2] 25dec12ff5a8ab04ed225c5049fa14a0f39074df

**Logs**
log: [log_2023-01-08_00.26.36.txt.zip](https://github.com/Revolutionary-Games/Thrive/files/10367394/log_2023-01-08_00.26.36.txt.zip)
mono log: [2023-01-07_18.44.41_6376.log](https://github.com/Revolutionary-Games/Thrive/files/10367396/2023-01-07_18.44.41_6376.log)

Please use a text hosting service (for example https://pastebin.com/) to submit your logs.
You can copy the launcher output or the contents of the following files: `log.txt` and mono
log file. You can find these log files by reading the game log to see their location.
For example:
```
Mono: Logfile is: /home/hhyyrylainen/.local/share/godot/mono/mono_logs/2020_07_21 23.10.26 (265121).txt
Game logs are written to: /home/hhyyrylainen/.local/share/Thrive/logs latest log is 'log.txt'
```

**Additional context**

**Comment by 84634E1A607A** [comment]
I suspect that this is because LFS objects not downloaded properly. This should not happen.

**Comment by hhyyrylainen** [comment]
I agree, this seems to be a problem with the local clone, either git LFS is not initialized properly, or @mcDandy didn't open the Godot editor once before running the game as that's what imports all the assets and prepares them to run (it generates the .stex files).
