### ISSUE TITLE
Localization script should not ignore `hint_tooltip` translation key when editor description says `PLACEHOLDER`

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#3984]
so that controls with placeholder text can have translatable builtin tooltip.

**Comment by hhyyrylainen** [comment]
This might need to be done in the Python data extractor https://github.com/Revolutionary-Games/pybabel-godot-thrive

**Comment by hhyyrylainen** [comment]
There's a workaround regarding this issue in the method `ApplyPlaceholderTooltipTranslationKey` in auto-evo exploring tool.
