### ISSUE TITLE
Game restarts when i pick up Chloroplast

### ISSUE THREAD

**Issue by lukaandjelkovic** [Revolutionary-Games/Thrive#400]
I was just testing Thrive, and set these settings:
1366x768
FSAA=0
Fullscreen=Yes
VSync=Yes
VSyncInterval=1
And i saved a game immediately when cell eaten me.
I had two chloroplast organneles.
Restarted game, and run'd it again.
I pressed Load game.
Now if you pick up chloroplast, game crashes with OpenAL error : Invaild value.

**Comment by TheCreator--** [comment]
@lukaandjelkovic, next time when you have a bug or issue, could you try to post it [here](http://thrivegame.freeforums.net/board/19/bug-reports)? I think that sub-board would be more appropriate than making a new Github issue every time you find something. Thanks!
