### ISSUE TITLE
OpenAL spews out errors if you load a saved game.

### ISSUE THREAD

**Issue by ghost** [Revolutionary-Games/Thrive#401]
I was just testing Thrive, and set these settings:
1366x768
FSAA=0
Fullscreen=Yes
VSync=Yes
VSyncInterval=1
And i saved a game immediately when cell eaten me.
I had two chloroplast organneles.
Restarted game, and run'd it again.
I pressed Load game.
Now if you pick up chloroplast, game crashes with OpenAL error : Invaild value.
Should be graphics problem.

**Comment by TheCreator--** [comment]
@lukaandjelkovic, next time when you have a bug or issue, could you try to post it [here](http://thrivegame.freeforums.net/board/19/bug-reports)? I think that sub-board would be more appropriate than making a new Github issue every time you find something. Thanks!

**Comment by hhyyrylainen** [comment]
Is this still an issue?

I'll check later whether there are these errors shown, but if someone knows right now about them, feel free to comment.

**Comment by Untrustedlife** [comment]
sounds work differently now, so this pis probably resolved?

Though saving and loading isnt fully reimplemented

**Comment by hhyyrylainen** [comment]
That's why this only has the review label as in it needs to be verified before release if this is still an issue or not.
