### ISSUE TITLE
I can't compile Thrive

### ISSUE THREAD

**Issue by lukaandjelkovic** [Revolutionary-Games/Thrive#402]
When i'm tried to compile Thrive, while i was compiling i get "Can't find GCC bla bla..." so i checked up the directory where it was installed, setted it up to (C:/MinGW, where it really is) but i noticed that in your precompiled RAR file of Mingw, wasn't the normal gcc executables, they were i686-gcc.

**I AM REALLY SORRY FOR THIS BAD ENGLISH. I HOPE YOU WILL UNDERSTAND WHAT AM I TRIED TO SAY.**

**Comment by jjonj** [comment]
Hrmm. i686 means that it's made for 32bit on a standard intel or amd cpu. Are you running an ARM processor?

**Comment by lukaandjelkovic** [comment]
Oh, sorry i didn't responded, No, i'm running x64 bit processor. I have no gcc executables in .rar file you gived on the Mega cloud in your tutorial to setup C++ developement.

**Comment by jjonj** [comment]
The i686 files should work then, what problem are you experiencing?

**Comment by lukaandjelkovic** [comment]
"Can't find GCC executables.

**Comment by jjonj** [comment]
If it's cmake making that error, did you make sure to give it the toolchain like described here: https://github.com/Revolutionary-Games/Thrive/blob/master/mingw_setup/readme.txt#L163   

Or if it's codeblocks giving the error did you try this:https://github.com/Revolutionary-Games/Thrive/blob/master/mingw_setup/readme.txt#L180 ?

**Comment by lukaandjelkovic** [comment]
No it isn't any of them.

**Comment by jjonj** [comment]
Sorry for the late reply, Could you provide a screenshot or some more details on when the error occurs then?
