### ISSUE TITLE
Temperature is shown in the patch compounds graph (report tab)

### ISSUE THREAD

**Issue by stoptakingusernames** [Revolutionary-Games/Thrive#4024]
Temperature appears as a percentage in the compound graph, always displayed as a red graph and at 0%

**To Reproduce**
Steps to reproduce the behaviour:
1. Reproduce
2. Go into the report tab and look at the Compounds graph

**Expected behaviour**
Temperature should only be visible in the physical conditions graph, and not displayed as a percentage

I am pretty sure this issue has been happening ever since the thermosynthesis implementation, I have checked by installing versions 0.5.10 and lower

**Comment by hhyyrylainen** [comment]
Can confirm the bug:

![kuva](https://user-images.githubusercontent.com/3796411/212562633-f31b351a-edef-4c57-b236-90cc08b744c9.png)
