### ISSUE TITLE
Rename suicide button translation key to reflect the new content

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#4026]
All the English text referring to the suicide button should be updated to refer to "perish instantly". As this is a pretty major tone change, renaming the translation keys might also be good, but not absolutely necessary. At least no code variables referring to the button need changing.

**Comment by stoptakingusernames** [comment]
I have made a suggestion on [the translations website](https://translate.revolutionarygamesstudio.com/translate/thrive/thrive-game/en/?offset=1&q=has%3Asuggestion&sort_by=-priority%2Cposition&checksum=) , suicide has been replaced with “Perish instantly”, the translation key is left unchanged

**Comment by hhyyrylainen** [comment]
The button is also referenced by the string `TUTORIAL_MICROBE_STAGE_ENGULFED_TEXT`

**Comment by hhyyrylainen** [comment]
I'll assume no one wants to edit the translation key, as this is very related to a discussion I'm replying to right now (https://forum.revolutionarygamesstudio.com/t/replacing-the-translations-extracting-tool/979/3).
