### ISSUE TITLE
Remove trailing newlines from translation text (and set it in code instead) in auto-evo exploring tool

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#4031]
`MICROBE_ORGANELLE_STATISTICS`,  `ALL_WORLDS_STATISTICS`, and `CURRENT_WORLD_STATISTICS` have the English text end with a newline, Poedit complains about this loudly. So the newlines at the end should be moved to the C# code instead of the translation.

Also updating styleguide to say that translation text should not end with a newline.

This is high priority because I get an error message each time I use Poedit (and that's the recommended editor in our setup instructions).

**Comment by 84634E1A607A** [comment]
Well I use vscode to edit the locale file so I won't remember that unless pre-commit complains about it. I remember you pointed that out when I wrote the species details text. I will make changes tomorrow.

**Comment by hhyyrylainen** [comment]
That's a good idea, I opened a separate issue about making such a check: https://github.com/Revolutionary-Games/Thrive/issues/4036
