### ISSUE TITLE
Clear the input rebinding controls when options menu is closed

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#4032]
as otherwise the buttons just stay in the background forever listening for each input event, which is completely unnecessary drain on performance. A simple method on `InputGroupList` when the options is exited (there's already detection for that for the unsaved settings check) to clear its children should be enough.

**Comment by d0tplus** [comment]
Hello. I was trying to fix this, and I was able to get InputGroupList to clear its children on the OptionsMenu exit. However, when I try to open the OptionsMenu menu again after clearing children I am meet with with the error:

`E 0:00:51.415   IntPtr Godot.Object.GetPtr(Godot.Object ): System.ObjectDisposedException: Cannot access a disposed object. Object name: 'InputGroupItem'.`

I am not 100% on how to resolve this error. I tried swapping the FreeChildren method with other methods for freeing up nodes, but to no avail. I made a draft PR to see how I was going about solving this bug. If anyone has a bit of extra time, any leads to what I may be doing would be appreciated! Thank you!

**Comment by hhyyrylainen** [comment]
I suspect the problem is that when freeing the children, you are forgetting to clear some reference to them. The usual pattern I use is to queue free the children and then clear the lists or whatever data structures are holding references.

Also if you run the game in a debugger (or even just check the Godot editor expanded info on the error), you'll see where the bad access is happening which is a pretty big clue towards figuring out what place is incorrectly keeping references to freed objects.
