### ISSUE TITLE
{Idea} : Add Gitter chat

### ISSUE THREAD

**Issue by lukaandjelkovic** [Revolutionary-Games/Thrive#406]
Almost every repository (which have more than 80 stars and 40 watches and more) have it own Gitter chat. Don't add (Not really an issue.)

**Comment by Oliveriver** [comment]
[We do have one actually.](https://gitter.im/Revolutionary-Games/Thrive?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link)

We set it up back when we weren't sure what conversation platform we should be using (mostly in response to reaching the 10,000 message limit on [Slack](https://slack.com/), which we've now learnt to live with and are using as the main developer chat). I guess if you want to use our Gitter chat go ahead, but not many other people will be.
