### ISSUE TITLE
Toggling the fullscreen option in the options menu doesn't update the resolution label

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#4061]
it still keeps showing the last value (for example just 720p resolution when the window is fullscreened on a much bigger monitor).

**Comment by 84634E1A607A** [comment]
Isn't the game resolution always 720p?

**Comment by hhyyrylainen** [comment]
That is the Godot design resolution, but the game does not render at that resolution, otherwise it would be a total blurfest on 4K screens.

**Comment by BrainFuck42** [comment]
seems to work correctly now in 0.6.1

**Comment by hhyyrylainen** [comment]
I can't confirm this works. Still shows the incorrect resolution when toggling fullscreen (it just keeps showing the previous value it had).

**Comment by BrainFuck42** [comment]
may be a platform dependent issue, works for me on windows 11, both steam release and running from godot

**Comment by hhyyrylainen** [comment]
Doing a few more tests I determined that if I resize the window at all and then fullscreen the resolution is correct, but if I go to fullscreen from exactly the default sized window, the issue is visible.
