### ISSUE TITLE
Fix the editor tab buttons overlapping the light level bar

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#4067]
I just noticed when testing something else this problem (I had forgotten to test my changes with day/night cycle enabled):
![2023-01-27_15 55 38 5802](https://user-images.githubusercontent.com/3796411/215104321-45d5d6ea-fbca-438e-974b-0d8791369f5f.png)

This should be fixed ASAP, but luckily should just be a case of moving one panel around in the editor a tiny bit.

**Comment by Adhityanarayan** [comment]
Hi @hhyyrylainen, I've looked into this issue. As you have mentioned I changed the editor panel size, as is the below left panel size to make it fit accordingly. please find below screenshot after making the change.

![image](https://user-images.githubusercontent.com/45228715/215282727-9dcf84e1-fad3-461c-bcf8-500f7c858f05.png)

**Comment by hhyyrylainen** [comment]
Does the change work when the controller prompt buttons are shown, and does it work in the multicellular editor (where there are 4 buttons)?

**Comment by hhyyrylainen** [comment]
I did a quick test of the PR and found issues exactly with those points I feared might not work: https://github.com/Revolutionary-Games/Thrive/pull/4070#issuecomment-1407463587
