### ISSUE TITLE
Am I supposed to swallow nutrients?

### ISSUE THREAD

**Issue by nerai** [Revolutionary-Games/Thrive#407]
I built a J shaped cell, so the nutrient sources were collected and stored inside me simply by driving by. Like gathering rain in an umbrella lying on the wrong side. Of course I never had ATP or similar trouble ever again.

What's more, it seems that aggressive cells only shoot toxin when they are close to my nucleus. Since the J shape added a big 'butt', they simply gathered behind me, never attacking me, as I was slowly crawling forward.

**Comment by TheCreator--** [comment]
Don't worry, this is already fixed on the CompoundClouds branch. We no longer have discrete compound emitter; they have been replaced with compound clouds.
