### ISSUE TITLE
AI cells can form a colony (while AI colony logic hasn't been implemented)

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#4080]
### Describe the bug

I thought I mentioned this before, but the possibility was dismissed.

### To Reproduce

I'm not sure, but I suppose:
1. Form a big enough colony
2. Enter engulfing state
3. Killing a cell in the middle of the colony (so that it splits, and branch cells detach from the current one
4. ***Binding state isn't instantly cleared***
5. Detached AI cells form a colony (I can't bind to any of them again)

### Screenshots

![image](https://user-images.githubusercontent.com/60734649/215713887-1a60f266-90e9-44e8-8a6c-aeb2308ef8ce.png)

A real mess:
![image](https://user-images.githubusercontent.com/60734649/215713995-8f4e84ff-f3aa-49d9-8670-c6bc601487e2.png)

### System information

/

### Game Logs

[log.txt](https://github.com/Revolutionary-Games/Thrive/files/10544567/log.txt)

**Comment by hhyyrylainen** [comment]
I'm not really sure this should be counted as a bug as AI colonies us a wanted feature...

**Comment by hhyyrylainen** [comment]
I'll close this as working kind of intended. This doesn't crash the game, right?

Here's the issue for making the AI aware of colonies: https://github.com/Revolutionary-Games/Thrive/issues/2348
