### ISSUE TITLE
Remove old unused systems

### ISSUE THREAD

**Issue by jjonj** [Revolutionary-Games/Thrive#410]
Examples:
~~SkySystem~~, OgreOverlaySystem and possibly others!

Also remove any associated tests that might exist

Good beginner assignment

**Comment by TheCreator--** [comment]
We need skysystem. That's what I use  for the parallax background. But
yeah, we don't need compoundemitter system.

**Comment by jjonj** [comment]
We don't need compound emitter?? Or did you mean to say overlay?

**Comment by TheCreator--** [comment]
We no longer need compound.h, compoundEmitter, compoundTimedEmitter and all those other stuff. They are now a part of compoundClouds and compoundAbsorber.

**Comment by jjonj** [comment]
Oh right ofc!

**Comment by TheCreator--** [comment]
I'll remove the systems that I "invalidated", but I'm not sure about many of the others.

**Comment by SBeausoleil** [comment]
There exists a feature in Eclipse for Java where it detects all the links towards a segment of code from all the other parts of the project. I'll see if it can be applied to C++.

**Comment by hhyyrylainen** [comment]
I'm currently doing a big engine refactor and could remove some unused systems.

Does anyone know for sure which ones I should remove? (I can of course use grep to find things nothing is referencing)

**Comment by hhyyrylainen** [comment]
I went on a deleting spree in engine_refactor and most of the old unused things are probably now removed.
