### ISSUE TITLE
Add pilus upgrade to turn it into an injectisome (change damage type to toxic)

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#4108]
making a new damage type to take the variant into account is probably the cleanest way, that way this upgrade can also have a different sound for the attack

**Comment by ender-titan1** [comment]
I get it I should make a new damage type called "toxic_pilus" or something like that, however, I don't know what the damage type itself should do. For example, should physical or toxin resistance or both be considered when calculating damage taken?

**Comment by hhyyrylainen** [comment]
If I remember right the intention was that the different damage type would completely ignore physical resistance and only apply the toxin resistance. The reason why the existing toxic damage type shouldn't be used is that that would play the toxin hit sound, whereas the toxic pilus should have a unique sound that is similar to the pilus sound.
