### ISSUE TITLE
Make multihex organelles send better positions to the membrane to improve wrapping

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#4117]
I suddenly remembered last night that someone said some time ago that the reason why some organelles can poke outside the membrane is that they only send their center coordinate to the membrane. Instead I think we'd be much better off if each organelle sent the farthest from origin hex's coordinate. That way the membrane probably would stay far enough from big organelles so that they wouldn't poke outside it.

**Comment by adQuid** [comment]
If you wanna cheat here was my take on a solution: https://github.com/adQuid/Thrive/pull/74/files#diff-55af6451a36834f2255a91efffdce5b5ed4581058e45aed647ec31912584588aR422

**Comment by hhyyrylainen** [comment]
Now with myofibril being a really long membrane, they still want to poke through the membrane even with the latest fix as they are just so long and thin.
