### ISSUE TITLE
Systems missing files required by the Lua scripts

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#413]
While fixing Thrive for linux (again) I had to comment out a few compound systems as one of the headers was deleted. Now it compiles fine but running it exits with this error

> ../scripts/microbe_stage/microbe.lua:284: attempt to index global 'CompoundAbsorberComponent' (a nil value):
    [C]:-1 (metamethod __index)
    ../scripts/microbe_stage/microbe.lua:284
>
>../scripts/microbe_stage/microbe.lua:284: attempt to index global 'CompoundAbsorberComponent' >(a nil value):
>    [C]:-1 (metamethod __index)
>    ../scripts/microbe_stage/microbe.lua:284
>
../scripts/microbe_stage/setup.lua:375: attempt to call global 'MicrobeSystem' (a nil value):
    [C]:-1 (global MicrobeSystem)
    ../scripts/microbe_stage/setup.lua:375 (local createMicrobeStage)
    ../scripts/microbe_stage/setup.lua:423
>
../scripts/microbe_stage/setup.lua:375: attempt to call global 'MicrobeSystem' (a nil value):
    [C]:-1 (global MicrobeSystem)
    ../scripts/microbe_stage/setup.lua:375 (local createMicrobeStage)
    ../scripts/microbe_stage/setup.lua:423
>
 O
>
std::exception: 'x����':
    [C]:-1
    [C]:-1 (method getChild)
    ../scripts/microbe_editor/microbe_editor_hud.lua:56
>
terminate called after throwing an instance of 'luabind::error'
  what():  lua runtime error

The fixes are here ready for pulling https://github.com/Revolutionary-Games/Thrive/compare/master...hhyyrylainen:linux_fix?expand=1

**Comment by Moopli** [comment]
It was a bad merge, it should be good now.

**Comment by hhyyrylainen** [comment]
I'm basically ready to do a linux binary the only issue is again with the scripts:
```
no static 'MICROBE_TUTORIAL' in class 'GameState':
    [C]:-1
    [C]:-1 (metamethod __index)
    ../scripts/main_menu/main_menu_hud.lua:98

terminate called after throwing an instance of 'luabind::error'
  what():  lua runtime error
```

Another broken merge?

**Comment by hhyyrylainen** [comment]
RunTests still fails to compile
```
libThrive.a(compound_cloud_system.cpp.o): Funktiossa ”thrive::CompoundCloudSystem::CreateVelocityField()”:
/home/hhyyrylainen/Projects/thrive_install/thrive/src/microbe_stage/compound_cloud_system.cpp:418: määrittelemätön viite kohteeseen ”PerlinNoise::noise(double, double, double)”
/home/hhyyrylainen/Projects/thrive_install/thrive/src/microbe_stage/compound_cloud_system.cpp:419: määrittelemätön viite kohteeseen ”PerlinNoise::noise(double, double, double)”
/home/hhyyrylainen/Projects/thrive_install/thrive/src/microbe_stage/compound_cloud_system.cpp:421: määrittelemätön viite kohteeseen ”PerlinNoise::noise(double, double, double)”
/home/hhyyrylainen/Projects/thrive_install/thrive/src/microbe_stage/compound_cloud_system.cpp:422: määrittelemätön viite kohteeseen ”PerlinNoise::noise(double, double, double)”
libThrive.a(compound_cloud_system.cpp.o): Funktiossa ”thrive::CompoundCloudSystem::CompoundCloudSystem()”:
/home/hhyyrylainen/Projects/thrive_install/thrive/src/microbe_stage/compound_cloud_system.cpp:174: määrittelemätön viite kohteeseen ”PerlinNoise::PerlinNoise()”
collect2: virhe: ld:n paluuarvo oli 1
CMakeFiles/Thrive.dir/build.make:130: recipe for target 'Thrive' failed
make[2]: *** [Thrive] Error 1
CMakeFiles/Makefile2:110: recipe for target 'CMakeFiles/Thrive.dir/all' failed
make[1]: *** [CMakeFiles/Thrive.dir/all] Error 2
make[1]: *** Odotetaan keskeneräisiä töitä....
libThrive.a(compound_cloud_system.cpp.o): Funktiossa ”thrive::CompoundCloudSystem::CreateVelocityField()”:
/home/hhyyrylainen/Projects/thrive_install/thrive/src/microbe_stage/compound_cloud_system.cpp:418: määrittelemätön viite kohteeseen ”PerlinNoise::noise(double, double, double)”
/home/hhyyrylainen/Projects/thrive_install/thrive/src/microbe_stage/compound_cloud_system.cpp:419: määrittelemätön viite kohteeseen ”PerlinNoise::noise(double, double, double)”
/home/hhyyrylainen/Projects/thrive_install/thrive/src/microbe_stage/compound_cloud_system.cpp:421: määrittelemätön viite kohteeseen ”PerlinNoise::noise(double, double, double)”
/home/hhyyrylainen/Projects/thrive_install/thrive/src/microbe_stage/compound_cloud_system.cpp:422: määrittelemätön viite kohteeseen ”PerlinNoise::noise(double, double, double)”
libThrive.a(compound_cloud_system.cpp.o): Funktiossa ”thrive::CompoundCloudSystem::CompoundCloudSystem()”:
/home/hhyyrylainen/Projects/thrive_install/thrive/src/microbe_stage/compound_cloud_system.cpp:174: määrittelemätön viite kohteeseen ”PerlinNoise::PerlinNoise()”
collect2: virhe: ld:n paluuarvo oli 1
```

**Comment by hhyyrylainen** [comment]
Fixed the remaining errors in my PR: https://github.com/Revolutionary-Games/Thrive/pull/420
