### ISSUE TITLE
Keys don't use physical keys

### ISSUE THREAD

**Issue by Anonymous941** [Revolutionary-Games/Thrive#4137]
### Describe the bug

I use a Dvorak keyboard layout, which means I have to manually have to set each control.  The controls should use Godot's physical key feature instead of the normal key.

### System information

OS: Linux

### Game Logs

N/A

**Comment by hhyyrylainen** [comment]
We had an existing issue open about this, so I edited that a bit: https://github.com/Revolutionary-Games/Thrive/issues/2887
