### ISSUE TITLE
Photosynthetic organelles tooltips randomly don't update correctly on patch change

### ISSUE THREAD

**Issue by MrNoide** [Revolutionary-Games/Thrive#4139]
### Describe the bug

So aparently, thylakoid is not capturing light from a place with 100% light, the chloroplast captures light though, So the issue must be with the thylakoid.

### To Reproduce

1. Start the game on the current version (0.6.1)
2. Start a new game
3. When creating a moddifying the cell, id you hover above the thylakoid, and if you are on a place with light, it will show that it will capture no light, whille the  the chloroplast shows that it can capture the light.

### Expected behaviour

It should show the ammount of light in the region, instead, it always shows 0%.

### Screenshots

![imagem_2023-02-19_125802388](https://user-images.githubusercontent.com/101360251/219949465-99ca40bc-0aca-482f-9c35-c4014015fe11.png)
![imagem_2023-02-19_125823247](https://user-images.githubusercontent.com/101360251/219949482-28e59a42-12e4-4b4b-a06e-d2be76753f50.png)

### System information

- OS: Windows 1o
- Graphics card: NVIDIA GeForce RTX 3060 Laptop GPU
- Thrive: 0.6.1

### Game Logs

https://pastebin.com/qpDL8bey

**Comment by hhyyrylainen** [comment]
I just tested and the thylakoid works fine in game (confirmed with process panel as well), but for some reason the tooltip doesn't update for it so it always shows 0% light. The chloroplast tooltip does update correctly.

My initial guess is that somehow the tooltip stuff for the thylakoid got removed from some place where it should have been processed to be updated correctly.

**Comment by MrNoide** [comment]
But it also does not provide ATP, sorry, I forgot to specify that.

**Comment by MrNoide** [comment]
When I started the game with I also did not get my sweet ATP, should re-install the game?

**Comment by hhyyrylainen** [comment]
That's not the case.

Here's me being just one thylakoid where both processes in the organelle run as expected:

![2023-02-19_15 23 42 0912](https://user-images.githubusercontent.com/3796411/219950946-cace2e87-bbe1-4f26-8324-4f6f8e817874.png)

I started a freebuild game, replaced my starting cytoplasm with the thylakoid and moved to a surface patch. Then in the stage I just opened the process panel and waited to gain some glucose.

**Comment by MrNoide** [comment]
Ok, I will try doing that and see if it works

**Comment by hhyyrylainen** [comment]
> When I started the game with I also did not get my sweet ATP, should re-install the game?

Very unlikely to do anything. As long as you see the right version in the main menu and the game starts fine, it's extremely unlikely that the game files could be corrupt in a way where it partially works.

---

I just tried retesting, and this time it was the chloroplast tooltip that didn't update. So it seems random which tooltip doesn't update correctly on patch change. The problem also persists when exiting the editor and coming back. Also when loading a save it seems.

On another run of the game I saw that both tooltips where broken. So I guess there's some kind of random bug with the photosynthetic organelle tooltips not updating correctly.

**Comment by MrNoide** [comment]
I ran another game and for some reason it works now
![imagem_2023-02-19_133101257](https://user-images.githubusercontent.com/101360251/219951377-79cc4c16-9b46-4f0d-ab59-fefff25b19a0.png)

**Comment by hhyyrylainen** [comment]
I think I found the root cause, it was because the changed process speed objects were detected to be equal (this change was needed to make the process panel work to fix a bug with it). I've made a fix now that the tooltips do a much stricter check and update their numbers more often: https://github.com/Revolutionary-Games/Thrive/pull/4140
