### ISSUE TITLE
Add an option to enable showMouseCoordinates for the hover panel

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#4151]
That variable was left to eventually allow re-enabling the showing on world coordinates in the mouse hover panel. It's not been done yet, so I'm opening this issue. The setting might be nice to have in the options menu for easy accessibility as it can be helpful in general debugging, not just when writing new code.

**Comment by Kasterisk** [comment]
> The setting might be nice to have in the options menu for easy accessibility

I prefer putting it in the debug overlay, this feels like a function too obscure be put in the options and only makes sense in the context of debugging.

**Comment by hhyyrylainen** [comment]
I guess if a generic enough name can be come up with that applies to other stages as well. Maybe related to just showing world coordinates? I didn't suggest that initially as I thought it'd be maybe a bit too stage specific thing to be put in there?

**Comment by Kasterisk** [comment]
Yes, many games have this function, Minecraft comes into mind when you hit F3 and the usual place for it is a debug more/development mode of some sort.
