### ISSUE TITLE
Convert all Thrive Settings properties to have private setters and `JsonPropertyAttribute`

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#4177]
so that it is clear that no one is allowed to re-assign the setting values as that breaks listeners etc.

This should not affect functionality at all and is pretty easy to check that custom settings are still loading. I made this high priority because this is a pretty serious area to make a silly mistake so this code problem should be fixed soon.

**Comment by Creidhne86** [comment]
I just got Thrive to compile/run on my machine.. It's not obvious to me where all of the Thrive settings properties are in the code.. could I get some help being pointed in the right direction?

**Comment by Creidhne86** [comment]
I think I found the relevant code: https://github.com/Revolutionary-Games/Thrive/blob/master/src/general/WorldGenerationSettings.cs

I assume the change should look like this after :
Old:
   public bool LAWK { get; set; }
New:   
   [JsonProperty]
   public bool LAWK { get; private set; }

**Comment by hhyyrylainen** [comment]
That is not actually correct. The Thrive settings are in the class called `Settings` which is at this path: `src/engine/Settings.cs`
