### ISSUE TITLE
Split MicrobeHUD to its own scene (and put common sub elements to their own scenes)

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#4181]
As it is unwieldy to have the HUD in the same scene as the stage scene itself. Also by splitting common sub components to scenes it'll be easier to keep them up to date across the later stages which will also use them.

I didn't tag this as C# as this *might* be doable just by modifying Godot scenes and not really needing to touch any C# code, just updating callback targets etc.

**Comment by CI09** [comment]
Is this up to date?

**Comment by hhyyrylainen** [comment]
Actually, no. There is now a separate MicrobeHUD.tscn file so this is now basically done.
