### ISSUE TITLE
Remove the classic map option as it has extra bugs (and no one really seems to want to work on it)

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#4200]
just so that there's no trap in the new game settings for getting a worse experience.

This one bug was open for a really long time without anyone giving it a thought really:
- https://github.com/Revolutionary-Games/Thrive/issues/3527

No one (at least on the dev team) seems to play the classic map that often so I think it'll be overall better to just remove the option instead of hoping that we don't break it anymore with further game changes.

**Comment by Creidhne86** [comment]
Would the goal of this issue be to remove all of the code associated with choices for patch map, and just have the code proceed automatically to the procedurally patch map?

**Comment by Creidhne86** [comment]
I drafted a pull request for this, but I'm getting an error I'm not 100% sure about..

E 0:00:05.065   get_node: (Node not found: "" (relative to "/root/MainMenu/NewGameSettings").)
  <C++ Error>   Method failed. Returning: nullptr
  <C++ Source>  scene/main/node.cpp:1465 @ get_node()
  <Stack Trace> :0 @ Godot.Node Godot.NativeCalls.godot_icall_1_673(IntPtr , IntPtr , IntPtr )()
                Node.cs:685 @ Godot.Node Godot.Node.GetNode(Godot.NodePath )()
                NodeExtensions.cs:47 @ Godot.OptionButton Godot.Node.GetNode<Godot.OptionButton >(Godot.NodePath )()
                NewGameSettings.cs:245 @ void NewGameSettings._Ready()()


I'm sure it's because I removed something that is referenced elsewhere, but I'm not sure the exact source

**Comment by Creidhne86** [comment]
To be clear, it builds and runs fine, but I get the error above from the debugger while it's running

**Comment by hhyyrylainen** [comment]
> I'm sure it's because I removed something that is referenced elsewhere, but I'm not sure the exact source

If you haven't yet committed the changes Godot automatically made to break everything, we have cleaning instructions on our wiki: https://wiki.revolutionarygamesstudio.com/wiki/Cleaning_Local_Thrive_Version

If you have already committed the changes. You should very carefully read through the changes to figure out what parts are unintended changes.

**Comment by Creidhne86** [comment]
Should we just remove the button on the NewGameSettings.tscn, and leave all the vestigial code for the old patch map?

**Comment by hhyyrylainen** [comment]
I think the method to generate the classic map should also be removed. I didn't yet comment on your PR as it was still a draft, but I noticed you didn't delete that method in the map generator class.

**Comment by Creidhne86** [comment]
I moved it out of draft, it's failing several of the automated checks, but those were intentional changes. I didn't look into updating translations
