### ISSUE TITLE
Can't run Thrive binary package in Ubuntu 16.04

### ISSUE THREAD

**Issue by FreeLikeGNU** [Revolutionary-Games/Thrive#421]
I tried Thrive in Ubuntu 16.04 beta and installed  libatomic1 and libzzip-0-13 then got:

```
./launch.sh 
terminate called after throwing an instance of 'Ogre::InternalErrorException'
  what():  OGRE EXCEPTION(7:InternalErrorException): Could not load dynamic library ./Plugin_CgProgramManager.  System Error: libCg.so: cannot open shared object file: No such file or directory in DynLib::load at /home/hhyyrylainen/Projects/thrive_install/ogreBuild/ogre/OgreMain/src/OgreDynLib.cpp (line 111)
Aborted (core dumped)
```

I then install libcg and got:
```
./launch.sh 
CEGUI::GenericException in function 'CEGUI::DynamicModule::DynamicModule(const CEGUI::String&)' (/home/hhyyrylainen/Projects/thrive_install/cegui/cegui/src/DynamicModule.cpp:236) : Failed to load module 'libCEGUIExpatParser.so': /usr/local/lib64/cegui-9999.0/libCEGUIExpatParser.so: cannot open shared object file: No such file or directory
terminate called after throwing an instance of 'CEGUI::GenericException'
  what():  CEGUI::GenericException in function 'CEGUI::DynamicModule::DynamicModule(const CEGUI::String&)' (/home/hhyyrylainen/Projects/thrive_install/cegui/cegui/src/DynamicModule.cpp:236) : Failed to load module 'libCEGUIExpatParser.so': /usr/local/lib64/cegui-9999.0/libCEGUIExpatParser.so: cannot open shared object file: No such file or directory
Aborted (core dumped)

```

**Comment by hhyyrylainen** [comment]
Oh yeah, I forgot that thrive loads those libraries at runtime and ldd can't see those. It seems I actually need to test the packages on a vm before making them official.

**Comment by Moopli** [comment]
Well these problems in particular are because Cg is a very recent dependency, newer than the last time you looked at it. When building ogre, there's a specific cmake flag for building CgProgramManager which we need to set.

**Comment by hhyyrylainen** [comment]
I just finished working on the packaging script: https://github.com/Revolutionary-Games/Thrive/pull/420

It now runs fine on a clean Fedora 23 vm. https://boostslair.com/files/thrive/Thrive.0.3.2.7z

@Moopli The package now includes libCg, which is quite large, so if it won't be required in the future it will be a good idea to remove it to save space.

**Comment by hhyyrylainen** [comment]
I've tested my binary packages on Ubuntu 16.06 vm and they work fine.
I'm going to close this and if there are still issues with specific distributions a new issue should be opened.
