### ISSUE TITLE
Iron is not shown in the Compunds section of the Report tab

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#4213]
![image](https://user-images.githubusercontent.com/60734649/223594977-0b05d8b8-7370-4ea9-b2d4-4ca83786bcfd.png)

The temperature part should have been fixed by #4142, but iron isn't listed.

**Comment by Kasterisk** [comment]
I debugged `snapshot.Biome.Compounds` and for some reason iron doesn't exist there, this is a deeper problem to the underlying patch BiomeConditions.

**Comment by hhyyrylainen** [comment]
> Edit: Ah I think I know what's up. It doesn't account for irons contained in chunks. I thought this was a regression but the problem is also present in all of older versions.

This was my exact reaction when reading the github notification email. The compound is not in the compounds list as it is not a cloud compound, rather it is contained in chunks only.
