### ISSUE TITLE
Create 2D icon for RuBisCo

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#4221]
https://forum.revolutionarygamesstudio.com/t/new-organelle-for-storing-atp-as-glucose/1001

Code implementation side of this issue: https://github.com/Revolutionary-Games/Thrive/issues/4222

**Comment by hhyyrylainen** [comment]
Is the model finished (around 300 triangles, exported as .glb)? If so it should be uploaded to the devcenter so that the files are not lost (also the same applies to the icon once it is finished, I think I only saw a low res preview of what the icon could be): https://dev.revolutionarygamesstudio.com/files/Asset%20development/Organelles

**Comment by Kertit** [comment]
Model is 480 tris, is that too much?

**Comment by hhyyrylainen** [comment]
It still looks about the same to me so that's much better. Probably better to ask on the dev discord graphics channel (well at least until some conclusion is reached here: https://forum.revolutionarygamesstudio.com/t/graphics-tasks-work-flow-discussion/1012) for feedback as only programmers hang out on Github.

**Comment by Kertit** [comment]
Model + texture Uploaded to DevCenter

**Comment by hhyyrylainen** [comment]
For reference the files are uploaded here: https://dev.revolutionarygamesstudio.com/files/Asset%20development/Organelles/RuBisCO

Direct link for [texture](https://dev.revolutionarygamesstudio.com/api/v1/download/39335) and [.glb](https://dev.revolutionarygamesstudio.com/api/v1/download/39334) (our organelle shaders currently only support an albedo map). Would be nice if some programmer could verify in Godot that the files are fine...

Now we just need the finished 2D icon for the organelle.

**Comment by hhyyrylainen** [comment]
Icon is now also uploaded here: https://dev.revolutionarygamesstudio.com/api/v1/download/39369

**Comment by hhyyrylainen** [comment]
The organelle was renamed to Glucose Phosphatase but I think we can still use the existing graphics assets for it, just need to rename the files for the new organelle name.
