### ISSUE TITLE
Make panoramic multicellular tidepool background

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#4226]
All the other backgrounds were added: https://github.com/Revolutionary-Games/Thrive/pull/4225

**Comment by Kertit** [comment]
https://dev.revolutionarygamesstudio.com/files/Asset%20development/Panoramas/TidePool.png

**Comment by hhyyrylainen** [comment]
I think there were some in progress tidepool background ideas for the panorama already shared on the graphics channel on discord, but they had some questionably fixed background objects kind of visible in them which people didn't like considering the 2D backgrounds looks and how people have been consistently wanting to remove the parallax layers from those.
