### ISSUE TITLE
Make late multicellular stage use patch specific backgrounds

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#4228]
Right now only one background is used regardless of patch: https://github.com/Revolutionary-Games/Thrive/pull/4225

In addition to changing the image, the ambient colour needs to change so the background image path and colour both probably should be added to the JSON data for biomes.

**Comment by CI09** [comment]
Since simulations parameters folder doesn't have multicellular folder in it, I assume there should be one which would contain for example panoramic background paths for patches?

**Comment by hhyyrylainen** [comment]
Well... for now there are actually not really any multicellular specific biome data, so I'd just put it in the current biomes.json because otherwise it would take scaffolding an entire new system to store multicellular maps to get this done. That was not what I had in mind when I tagged this "easy."

I don't recommend undertaking that whole new map system creation without first having a gameplay system reason to start implementing that.
