### ISSUE TITLE
Add endoplasmic reticulum organelle (converts glucose to lipids for more energy dense storage)

### ISSUE THREAD

**Issue by Vitzgraco** [Revolutionary-Games/Thrive#4233]
The endoplasmic reticulum would be a large organelle (3, 4 or 5 hexagons perhaps?) specialized in the conversion of sugars into lipids. This organelle is unlocked by having at least one nucleus.

What this organelle will do is extend the ability to store glucose, but activate once the cell reaches a certain amount of stored glucose (exceeding the standard maximum limit that would exist without the reticulum). The organelle will then begin to convert glucose into triglycerides.

The process of converting glucose to triglycerides will have small energy losses. The conversion will consume ATP equivalent to 25% of the ATP that glucose would produce.
When triglycerides accumulate, one or several yellow spheres will appear inside the cell, which will grow as more triglycerides accumulate.

The purpose of this organism is to improve storage, basically increasing the energy storage capacity up to 3, 4 or 5 times the capacity that the cell would normally have. But that energy would be stored in the form of triglycerides and not glucose.
If the cell runs out of glucose, it will start burning triglycerides. The process will generate ATP more slowly than in the case of burning glucose. The rate of respiration of triglycerides into ATP and CO2 will depend on the number of mitochondria or respiratory complexes within the cell.

**Comment by hhyyrylainen** [comment]
Github issues are for tracking concrete bugs and accepted new features to be completed. If you want to provide general feedback or suggestions, please head over to our community forums: https://community.revolutionarygamesstudio.com/ or our suggestions site: https://suggestions.revolutionarygamesstudio.com/
