### ISSUE TITLE
Create icons for microbe organism statistics

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#4253]
Split from: https://github.com/Revolutionary-Games/Thrive/issues/3695

We need icons for these:

- [x] Health. A heart.
- [x] Size. Four arrows pointing outwards.
- [x] Storage. A bubble (representing the vacuole).
- [x] Speed. An arrow pointing right.
- [x] Rotation. A circling arrow.
- [x] Percentage icon. Used to overlay the Digestion Efficiency icon.
- [x] Stopwatch icon. Used to overlay the Digestion Speed icon. We could settle to use the Hourglass icon if we prefer.
- [x] Digestion Efficiency. Either a stomach or an intestine. If a stomach, could be partially filled to show it's digesting. It's then overlaid with a percentage icon as a superscript or subscript.
- [x] Digestion Speed. Same as above, but it's overlaid with a stopwatch icon.

Here's a reference mockup of how the icons could look like:
![mockup](https://user-images.githubusercontent.com/110012298/184278138-8c575f1e-5aa0-4ed7-94ca-25b71a5e1e7a.png)

**Comment by Kertit** [comment]
Icons have been done and waiting for Feedback on Discord.

**Comment by Kertit** [comment]
Pack of Icon uploaded to Dev Center 
https://dev.revolutionarygamesstudio.com/files/Asset%20development/Icons/OrganismStatsIcons.zip

**Comment by hhyyrylainen** [comment]
Well no one complained about the looks of the icons so I'll consider this graphics task done and the programming task is now no longer impeded.
