### ISSUE TITLE
Decide a better color for the editor finish button's warning badge

### ISSUE THREAD

**Issue by Athriq** [Revolutionary-Games/Thrive#4258]
See discussion here: https://github.com/Revolutionary-Games/Thrive/pull/4252

From dev discord:
> hhyyrylainen: I think the idea is good but maybe a different colour would be better (right now it looks like a colour that's not used anywhere else in the game)

So basically, the badge needs a conforming color to the essence of current UI style.

**Comment by Kertit** [comment]
Is this issue still a thing? Just tried with master branch I don't see the badge anymore

**Comment by hhyyrylainen** [comment]
Did you trigger the condition that should show it? If it doesn't display any more that is not an intended change and is a regression instead.

**Comment by Kertit** [comment]
If I'm not wrong it should display when you have unsaved changes right?

**Comment by hhyyrylainen** [comment]
No, it is only on serious conditions like unconnected hexes or not enough ATP. Or when moving an organelle. Stuff that prevents you from exiting the editor (or in some cases where you really shouldn't want to exit the editor).

**Comment by Kertit** [comment]
oh okay got it. its well made it seems! the warning does not trigger if your ATP is too low due to externales consuming too much ATP when used. 
That's what made me think it doesn't work. 
Tried with oxytoxy and yeah it appeared.
I'll work on that color issue then
