### ISSUE TITLE
Refactor microbe reproduction

### ISSUE THREAD

**Issue by jjonj** [Revolutionary-Games/Thrive#429]
Currently when reproduction happens a copy of the cell is simply spawned on top of the existing microbes and the bullet physics system handles moving them apart. This sometimes cause crashes that we don't really have control over and while the current system looks OK, we can do better.    

One idea would be to spawn a new microbe on top like before but have them no collide eachother (engulfment code can be used for that) and then do some forced movement taking them apart.   

It would also be really nice to have the metaball membrane system render a membrane splitting up but this would be somewhat more complicated I imagine.

**Comment by TjWhale** [comment]
If the membrane still works the same as the prototype one way to do this would be as follows. If the code has been substantially changed then this method will be no help.

1. double all the organelles inside the cell. The membrane will keep it's distance from all the organelles.

2. start moving the two sets of organelles apart. Again the membrane will stretch to accommodate this.

3. when the organelles are the right distance apart split the cell in two. This means one set of organelles is deleted from the parent microbe. One set of organelles is spawned in the child microbe in the same places they were just deleted. Most importantly the child should inherit the membrane position of the parent. So now you have two cells side by side with their membranes overlapping.

4. Let the membrane code run it's course. It should shrinkwrap around the organelles in each cell, separating the cells. 

I think this would work pretty well and look good. It almost entirely uses code which is already implemented, which is nice. Anyway it may not be feasible.

**Comment by jjonj** [comment]
@TheCreator-- If you would be interested in tackling this when you have time!
You would probably have the easiest time creating a split effect in the membrane

**Comment by TheCreator--** [comment]
For now I'll just spawn two cells next to each other. Once we get a better
membrane system in, I'll try to work on a splitting animation.

**Comment by jjonj** [comment]
Alright, we want to move away from having the physics system responsible for moving the two cells apart as that is causing some rare crashes, so that's the most important part for a refactor.

**Comment by TheCreator--** [comment]
Yeah, I'll do that.

**Comment by TheCreator--** [comment]
Fixed with #481
