### ISSUE TITLE
Frequent crashes during play

### ISSUE THREAD

**Issue by jjonj** [Revolutionary-Games/Thrive#432]
Crashes seem to sometimes occur when colliding with other microbes and sometimes just by random e.g. entering microbe stage after editor. No output is seen in console. May be a single or multiple problems.
Crashes can usually be reproduced after a minute or two of play.

**Comment by jjonj** [comment]
I tried looking into the crashes by analyzing the stack traces but they are quite complicated and seem to somehow relate to double deletes that I'm having a hard time tracking down.    
I tried using dr memory to analyze thrive but it has had some memory problems that I haven't been able to resolve.   
Good news that I've now begun reverting back to previous versions to figure out when the crashes started and it seems they are quite recent (within the past two weeks at most) so should be possible to narrow down the issue, might just take some low effort time of building a lot of builds

**Comment by TheCreator--** [comment]
If it's within the last two weeks it could very well be the compound
absorbtion system or agent system. If you turn them off in the setup Lua
file, does the crash still occur? I'd try it on my own, but I cannot seem
to replicate it in the first place.

**Comment by jjonj** [comment]
I'll try that later.   
The way I've been most succesful reproducing crash is to enter microbe stage, reproduce with P, use the split button to enter editor, add a few organelles and click finish. That has always crashed for me after the first or second time doing it.

**Comment by jjonj** [comment]
Okay I idenfied one of the crashes to occur after a hostile microbe tries to attack you with agents: http://i.imgur.com/r7IiMLA.png @TheCreator Could you take a look at that one and see if you are able to reproduce?

**Comment by jjonj** [comment]
Some of the crashes will have been fixed by https://github.com/Revolutionary-Games/Thrive/commit/09075d766508ef76c384e2c957a70624e77c404a
I'll wait with closing this until I see if some of the other crashes show up again
