### ISSUE TITLE
Art gallery filter items by category button doesn't react to language change

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#4333]
This part of the art gallery doesn't react to language change:

![kuva](https://user-images.githubusercontent.com/3796411/234823400-e0cfc3aa-2208-4811-a95f-076c1d7827a5.png)

Only after switching a tab in the art gallery does that get updated. Probably just a missing call to translating that content when language is changed.

**Comment by jburrus1** [comment]
The function that refreshes the filter is exiting early when the user hasn't changed tabs in the gallery.
