### ISSUE TITLE
Art gallery slideshow feature doesn't work for models

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#4388]
I just noticed that the slideshow feature does nothing when viewing a model. When viewing the images the slideshow button works correctly and switches to new images.

**Comment by Brabygg** [comment]
Is there meant to be a fade transition on switching the displayed model, as with the image slideshow?

**Comment by hhyyrylainen** [comment]
I don't remember there being one. @Athriq probably knows for certain.
