### ISSUE TITLE
'Random.Next' always returns the same value

### ISSUE THREAD

**Issue by AndreyMoskalev565** [Revolutionary-Games/Thrive#4402]
### Describe the bug

Hello! I checked your code with the PVS-Studio analyzer and found a small [error](https://github.com/Revolutionary-Games/Thrive/blob/a23b90fa061353cff5e9e1a2b225ba62d9476a94/src/benchmark/microbe/MicrobeBenchmark.cs#L520):
```
private void SpawnMicrobe(Vector3 position)
{
  ....        
  cloudSystem!.AddCloud(  random.Next(0, 1) == 1 // <=
                          ? phosphates 
                          : ammonia,
                        ....);
}
```
The 'random.Next' method always returns 0, since 1 is not in the range of returned values.

### System information

- Thrive 0.6.2

### Game Logs

-

**Comment by hhyyrylainen** [comment]
I assume that the fix would be to have `random.Next(0, 2) == 1`? As the upper bound is exclusive at least I got the impression from a quick look through the documentation. There also could be other potential places in the code where this is incorrectly used.
