### ISSUE TITLE
Can you make one to play on Android?

### ISSUE THREAD

**Issue by muliangum** [Revolutionary-Games/Thrive#4428]

**Comment by muliangum** [comment]
> _未提供说明。_

**Comment by 84634E1A607A** [comment]
Months ago someone tried to export Thrive to HTML but it crashed right after entering main menu. (So did Android?) This is an engine problem and I don't think we can manage to make it running smoothly on Android any time soon.

**Comment by hhyyrylainen** [comment]
The FAQ on our wiki has a question about a potential mobile port (tl;dr; it would be very difficult, even though Godot now mostly supports it): https://wiki.revolutionarygamesstudio.com/wiki/Mobile_Version
