### ISSUE TITLE
Implement Surface Adjacency Bonus

### ISSUE THREAD

**Issue by Deus-Codes** [Revolutionary-Games/Thrive#4434]
Based on this post: https://forum.revolutionarygamesstudio.com/t/surface-area-volume-and-ratios/978/6

Boosting the stats of a part depending on how exposed it is to the the outer world would help approximate the effects of surface area in a mechanically simple way and help spruce up editor gameplay. We would need a way to measure how many surfaces of a tile are exposed to the outside world, or something along that lines, to measure bonuses.

**Comment by hhyyrylainen** [comment]
I'm at least temporarily closing this issue until this gets at least a bit more design on what this would actually *do*: https://forum.revolutionarygamesstudio.com/t/surface-area-volume-and-ratios/978/11
