### ISSUE TITLE
Allow AI to consider digestability when scanning for potential prey.

### ISSUE THREAD

**Issue by buckly90** [Revolutionary-Games/Thrive#4440]
AI predators currently do not consider if they can digest their prey or not when scanning for suitable prey in the area. This leads to predators repeatedly attempting to consume prey that they cannot digest to no avail.

When scanning for prey, AI should have a chance to consider if they can digest it or not (By taking into account cell walls and presence of pre-requisite lysosome enzymes) based off of their behavioral scales. Brave and/or opportunistic AI should be more likely to attempt to consume undigestable prey items.

**Comment by adQuid** [comment]
Can you describe the randomness a little more? Does a particular microbe have a 50% chance of deciding "yes I can eat you" and will stick to that opinion forever? Is this a "I'll try to eat something that isn't food every so often" situation, "every time I have to spit something out I roll again to see if I learned my lesson", or something else?

**Comment by buckly90** [comment]
I would say most preferably a "I'll try to eat something that isn't food every so often" situation to better avoid the "every time I have to spit something out I roll again to see if I learned my lesson" situation.

Really, it's just funny to see something try to eat what it can't, but we can't have it overstaying it's welcome when you get hounded and eaten repeatedly by the same animal.

**Comment by adQuid** [comment]
fair enough. Just keep in mind that that means that, given enough time, every microbe will attempt to eat you eventually.

**Comment by buckly90** [comment]
I suppose that's okay, even inline with how nature tends to work on earth. Just as  long as it doesn't get too extreme and the vegetation starts looking at you like a potential snack when they cannot eat you.

**Comment by hhyyrylainen** [comment]
Hmm, yeah it is true that `Microbe.CanEngulfObject` checks only that a microbe can engulf something, not if it can be digested. I think it would be a good idea to make AI less likely to try to engulf something it can't digest in the end.
