### ISSUE TITLE
Setup Script for windows fails "silently" due to 404 error

### ISSUE THREAD

**Issue by patowen** [Revolutionary-Games/Thrive#445]
The files needed by mingw-setup/ffmpeg/install.ps1:

"http://ffmpeg.zeranoe.com/builds/win32/dev/ffmpeg-20150828-git-628a73f-win32-dev.7z"
and
"http://ffmpeg.zeranoe.com/builds/win32/shared/ffmpeg-20150828-git-628a73f-win32-shared.7z"

no longer exist on the internet.

This has caused the following log:

```
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
At E:\Users\Patrick\git\Thrive\mingw_setup\ffmpeg\install.ps1:66 char:5
+     $CLIENT.DownloadFile("http://ffmpeg.zeranoe.com/builds/win32/dev/ ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

Downloading archive...
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
At E:\Users\Patrick\git\Thrive\mingw_setup\ffmpeg\install.ps1:76 char:5
+     $CLIENT.DownloadFile("http://ffmpeg.zeranoe.com/builds/win32/shar ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
```

This has caused more errors to propagate due to missing dependencies.

I believe a simple fix would be to use a newer version of ffmpeg that can be downloaded, but ideally, the setup script should be able to detect errors and notify the user that the setup failed and why.

(Perhaps a new issue should be created for this, as this seems like it would be a large task.)

**Comment by patowen** [comment]
It looks like we don't have to update to a new version. After a little more searching, it's clear that the URLs simply moved to:

"http://ffmpeg.zeranoe.com/builds/win32/dev/2015/ffmpeg-20150828-git-628a73f-win32-dev.7z"
and
"http://ffmpeg.zeranoe.com/builds/win32/shared/2015/ffmpeg-20150828-git-628a73f-win32-shared.7z"

Note the /2015/ that wasn't there previously.

**Comment by hhyyrylainen** [comment]
I assume this was fixed with that merge.
