### ISSUE TITLE
Unify the word cases in our JSON files

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#4464]
the oldest JSON files use camelCase but the latest style is to use PascalCase to match the C# source code, so this'd be a nice small housekeeping task to update all the old JSON files to use the new name cases everywhere.

**Comment by hhyyrylainen** [comment]
Our C# code already follows PascalCase naming convention. The only reason the current files work at all is because the C# variable name to JSON mapping is already case insensitive. All this means that changing the cases of the JSON properties does not require any changes to the C# side of things.

**Comment by elj40** [comment]
Thanks, will get started

**Comment by elj40** [comment]
It seems that some of the strings stored in json refers to other json objects. I also found some snake case and replaced them with PascalCase. Not sure how all the things link together so a bit worried that I might break everything by renaming soemthing I shouldnt have. Will be able to get back tomorrow as it has gotten late

**Comment by hhyyrylainen** [comment]
I think I should have clarified that all of the JSON property names inside objects are the ones that should be renamed. Internal names of registry objects (top level dictionary keys) should not be renamed, as that will break everything. Sorry I should have remembered to clarify earlier that only JSON object properties should be renamed, no string values or top level dictionary keys should be renamed as those need to exactly match. That's so obvious in my head that I didn't think to mention it before.

**Comment by elj40** [comment]
Sorry to bother again but just to make 100% sure:

`﻿{
  "default": {
    "name": "EPIPELAGIC",
    "background": "ocean",
    "icon": "res://assets/textures/gui/bevel/epipelagic.png",
    "sunlight": {
      "colour": {
        "r": 1,
        "g": 1,
        "b": 1,
        "a": 1
      },
      "energy": 1,
      "specular": 0.5,
      "shadows": true,
      "direction": {
        "x": 0.25,
        "y": -0.3,
        "z": 0.75
      }
    },
    "compoundCloudBrightness": 1.3,
    "conditions": {`

Should become:
`{
  "default": {
    "Name": "EPIPELAGIC",
    "Background": "ocean",
    "Icon": "res://assets/textures/gui/bevel/epipelagic.png",
    "Sunlight": {
      "Colour": {
        "r": 1,
        "g": 1,
        "b": 1,
        "a": 1
      },
      "Energy": 1,
      "Specular": 0.5,
      "Shadows": true,
      "Direction": {
        "x": 0.25,
        "y": -0.3,
        "z": 0.75
      }
    },
    "CompoundCloudBrightness": 1.3,
    "Conditions": {`

**Comment by hhyyrylainen** [comment]
Yes that seems about right.
