### ISSUE TITLE
Fix editor storage statistic not taking specialized vacuole into account

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#4496]
It should at least show the non-specialized storage like it did before. I'm not sure how it should really show the specialized storage amounts.

**Comment by ender-titan1** [comment]
Yeah, I was going to bring this up today. I can get this done rather quickly. My plan for this is to show the nominal capacity on the label and than show the other compounds in a tooltip similar to how we show digestion efficiency
