### ISSUE TITLE
Organelle context menu doesn't adjust to longer translation text (height doesn't increase)

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#4510]
The organelle right click popup context menu has a height constraint that really messes with the UI when the organelle name takes multiple lines (the modify option is not visible):

![problem screenshot](https://cdn.discordapp.com/attachments/787490550014017627/1159754437473091614/image.png)

**Comment by TrialDragon** [comment]
What would a good solution to this issue constitute? Is upping the minimum rect size of that particular pop up menu such that any [expected] translation text should fit good enough? Or should CustomPopUp menus be modified to consider minimum content size and such, similar to CustomWindow, or something along that line of thinking?

**Comment by hhyyrylainen** [comment]
I think the general popup menu GUI layout should be modified to respect minimum height, otherwise we'll forever need to tweak various popup menus and for shorter languages they'd have strange blank space in them.
