### ISSUE TITLE
Error message for using Ogre 1.9

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#452]
While helping knightos build thrive he didn't get a friendly error about using outdated Ogre version.
We should add an error message to cmake when Ogre version ISN'T 2.0

**Comment by Untrustedlife** [comment]
we arent using 1.9 anymore, so can this be closed?

**Comment by hhyyrylainen** [comment]
As some linux distributions have Ogre 1.9 in their package manager this would be an error about using THEM instead of 2.1. But with the new setup this shouldn't happen (it should prefer the version it compiles).
