### ISSUE TITLE
K+M not working after returning to main menu and back to game

### ISSUE THREAD

**Issue by KnightosMaster** [Revolutionary-Games/Thrive#454]
No inputs are registered after returning to the main menu from the game and back.

[https://youtu.be/q_RmSTeOtC8](url)

I am using Arch Linux x86_64

**Comment by hhyyrylainen** [comment]
This needs to be verified (hopefully this is not arch specific) once engine_refactor is done.

**Comment by hhyyrylainen** [comment]
I haven't experienced this at all after the remade return to menu and new game.
