### ISSUE TITLE
Linux (Debian) build fails

### ISSUE THREAD

**Issue by thomp** [Revolutionary-Games/Thrive#455]
While trying to build on Debian, the build trucks along but runs into "special times" while compiling thrive.

The console shows

```
Compiling Thrive 
-- Looking for OGRE...
-- Found Ogre Tindalos (2.0.0)
...
-- Finding CEGUI version 9999 for Ogre version 2.0.0
-- 
-- 
-- Check for library 'cAudio' -- found
-- Checking for module 'OpenAL'
--   No package 'OpenAL' found
CMake Error at CMakeLists.txt:639 (InstallFollowingSymlink):
  InstallFollowingSymlink Function invoked with incorrect arguments for
  function named: InstallFollowingSymlink


CMake Error at CMakeLists.txt:646 (InstallFollowingSymlink):
  InstallFollowingSymlink Function invoked with incorrect arguments for
  function named: InstallFollowingSymlink
```

The debian libopenal-dev and libopenal1 packages are installed.

Not sure if it's worth much but CMakeError.log has the following:

```
Determining if the pthread_create exist failed with the following output:
Change Dir: /home/thomp/downloads/games/thrive/Thrive-0.3.2/source_build/thrive/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_ba2d1/fast"
/usr/bin/make -f CMakeFiles/cmTC_ba2d1.dir/build.make CMakeFiles/cmTC_ba2d1.dir/build
make[1]: Entering directory '/home/thomp/downloads/games/thrive/Thrive-0.3.2/source_build/thrive/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_ba2d1.dir/CheckSymbolExists.c.o
/usr/bin/cc     -o CMakeFiles/cmTC_ba2d1.dir/CheckSymbolExists.c.o   -c /home/thomp/downloads/games/thrive/Thrive-0.3.2/source_build/thrive/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_ba2d1
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_ba2d1.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTC_ba2d1.dir/CheckSymbolExists.c.o  -o cmTC_ba2d1 -rdynamic 
CMakeFiles/cmTC_ba2d1.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0xa): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_ba2d1.dir/build.make:97: recipe for target 'cmTC_ba2d1' failed
make[1]: *** [cmTC_ba2d1] Error 1
make[1]: Leaving directory '/home/thomp/downloads/games/thrive/Thrive-0.3.2/source_build/thrive/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_ba2d1/fast' failed
make: *** [cmTC_ba2d1/fast] Error 2

File /home/thomp/downloads/games/thrive/Thrive-0.3.2/source_build/thrive/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/thomp/downloads/games/thrive/Thrive-0.3.2/source_build/thrive/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_f08fc/fast"
/usr/bin/make -f CMakeFiles/cmTC_f08fc.dir/build.make CMakeFiles/cmTC_f08fc.dir/build
make[1]: Entering directory '/home/thomp/downloads/games/thrive/Thrive-0.3.2/source_build/thrive/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_f08fc.dir/CheckFunctionExists.c.o
/usr/bin/cc    -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_f08fc.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.5/Modules/CheckFunctionExists.c
Linking C executable cmTC_f08fc
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_f08fc.dir/link.txt --verbose=1
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_f08fc.dir/CheckFunctionExists.c.o  -o cmTC_f08fc -rdynamic -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_f08fc.dir/build.make:97: recipe for target 'cmTC_f08fc' failed
make[1]: *** [cmTC_f08fc] Error 1
make[1]: Leaving directory '/home/thomp/downloads/games/thrive/Thrive-0.3.2/source_build/thrive/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_f08fc/fast' failed
make: *** [cmTC_f08fc/fast] Error 2
```

**Comment by hhyyrylainen** [comment]
```
/usr/bin/ld: cannot find -lpthreads
```

Could this be the issue, do you have pthreads dev package installed?

**Comment by thomp** [comment]
I did note the -lpthreads error with ld. The libc6-dev packages provides pthread.h and the libpthread files. libc6-dev is installed. 

Some of the content in CMakeCache.txt (below) suggests that the build system is (correctly) detecting the pthread library and is also (correctly) recognizing that the pthreads library isn't present.

```
//Have library pthreads
CMAKE_HAVE_PTHREADS_CREATE:INTERNAL=
//Have library pthread
CMAKE_HAVE_PTHREAD_CREATE:INTERNAL=1
```
Given this, is it possible that "-lpthreads" is an error and, instead, cc should be called  with "-lpthread"?

**Comment by hhyyrylainen** [comment]
I'm pretty sure that the linker command for standard pthreads is always `-pthreads`
So that might not even be the error. So maybe in CMakeLists.txt:639 some library isn't found and that's why trying to instruct cmake to install it fails.

**Comment by thomp** [comment]
I took a closer look at CMakeLists.txt and, indeed, the 'CgProgramManager' ogre plugin was not being built.

After installing some of the Debian cg packages (e.g., nvidia-cg-dev), the Cg program manager plugin was built. When the plugin is present, cmake handles OGRE_PLUGINS fine (althought it chokes later on in the build process with VideoPlayer.cpp).

Since I only encountered thrive about 24 h ago, I'm not all that familiar with the setup/build process. Is the Cg program manager plugin optional? If not, this fact should not be obscured -- rather, the build system should test for the presence of the plugin and clearly communicate to the end-user that absence of the plugin is an issue. If the plugin is optional, the build system should gracefully deal with the absence of the Cg program manager plugin.

**Comment by hhyyrylainen** [comment]
The game does run without the Cg plugin but many of the materials will just appear gray.
The setup script does set `-DOGRE_BUILD_PLUGIN_CG=ON` so if the script works correctly there is only the issue of copying over the resulting library. Also ldd won't help because it is Ogre that is instructed to look for the plugins during start up (I guess when we ditch the default Ogre initialization we could exit with a specific error message if a plugin is not found).

**Comment by thomp** [comment]
Would something like this make sense with respect to gracefully handling the situation when the optional plugin isn't present? (vs. the cmake complaints about InstallFollowingSymlink invocation)


```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 8cd4728..fa9a525 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -636,19 +636,23 @@ elseif(UNIX)
             OGRE_PLUGIN_LIB_REL
         )
         # Release
-        InstallFollowingSymlink(
+        if(${OGRE_PLUGIN_LIB_REL})
+          InstallFollowingSymlink(
             ${OGRE_PLUGIN_LIB_REL}
             bin
             Release
             True
-        )
+            )
+        endif()
         # Debug
-        InstallFollowingSymlink(
+        if(${OGRE_PLUGIN_LIB_DBG})
+          InstallFollowingSymlink(
             ${OGRE_PLUGIN_LIB_DBG}
             bin
             Debug
             True
-        )
+            )
+        endif()
     endforeach()
 
 endif()
```

**Comment by hhyyrylainen** [comment]
I'm not sure. That seems to be inside the installation support part for all UNIX systems. I don't install Thrive on linux so I'm not even sure if that works, but I think you could just comment out that whole thing and unless you want to install thrive locally (which isn't required) it shouldn't affect anything.

You might have to ask @moopli about that piece of code.

**Comment by hhyyrylainen** [comment]
Already closed other build fail issues
