### ISSUE TITLE
Recent commit broke Windows build with MinGW

### ISSUE THREAD

**Issue by pgelinas** [Revolutionary-Games/Thrive#458]
52805f1 changed the CEGUI dependencies for the Linux setup and a related field name (probably due to an error with the new version), but the MinGW setup uses an older version of CEGUI and now there's a compile error. What version should be used for this dependency? If it's the more recent commit, I can tried to update the MinGW setup... if it's the version from the MinGW setup, I can change the Linux setup to use the same version and fix the compile error (easiest route, I guess).

**Comment by hhyyrylainen** [comment]
Go to your CEGUI folder and run `hg update 869014de5669` and then rebuild CEGUI and it should work.
I guess the windows build script will need to be updated to use commit 869014de5669 for CEGUI.
@jjonj Seems to have been quite busy lately so I guess that's why it hasn't been updated.

**Comment by pgelinas** [comment]
Allright, so 869014de5669 it is then! I'll update the MinGW setup then with this and try re-installing/configuring to see where this leads me. Already tried this quickly before posting the issue, but it gave me so much more errors instead :stuck_out_tongue: guess I need to spend a little bit more time understand this MinGW stuff! I might need to also update the CEGUI-Dependencies' version then (used only on Windows and OSX...).

I can't just update via mercurial as the MinGW fetches an archive via bitbucket instead of using hg.

**Comment by jjonj** [comment]
I'll have a look!

**Comment by pgelinas** [comment]
I managed to make it compile yesterday evening, but there were more error that poped up when I changed the version. It's around the `CEGUI::String` class, the `c_str` method no longer returns a std::string but a char*... I fixed those, but I couldn't get the exe to execute: problem with missing libstd, surely my installation of MinGW that was foobar. I was planning to send a PR this evening when I got around to run the game ;)

**Comment by jjonj** [comment]
> , but I couldn't get the exe to execute: problem with missing libstd

Did you run the exe inside the dist/bin folder? the one inside build doesn't work

**Comment by pgelinas** [comment]
That could explain it then! Yes it was inside build, I searched for the dist folder based on my understanding of the CMake files, but I couldn't find it. Should it be sub-folder of build (wasn't there...) or is it somewhere else?

**Comment by pgelinas** [comment]
..... I should have read the mingw setup readme to the end. I'll check this tonight and send a PR :wink:

**Comment by hhyyrylainen** [comment]
@pgelinas How did you fix the issue with the strings?
It should be as simple as setting `cmake .. -DCEGUI_STRING_CLASS=1`

**Comment by pgelinas** [comment]
@hhyyrylainen I did not see that configuration in the same commit that changed the CEGUI version, so I changed the methods to return CEGUI::String instead, hence why I wanted to test it before sending a PR. I haven't looked much at the build yet, so where should this be added?

**Comment by hhyyrylainen** [comment]
Wherever the windows build script calls cmake in the CEGUI/build folder
And this has been the case for many versions before this version bump, I guess windows is just behind by that much.

**Comment by pgelinas** [comment]
Alright, thanks for the input! So this probably has to go in the install.ps1 script too then, I'll test this tonight.

**Comment by pgelinas** [comment]
Got it to work :smile: 

On a side-note: why does the *.ps1 files were encoded in UTF-16? I doubt you need all the extra characters and this doesn't play nice with git diff: git sees it as a binary file (which it is). Do you mind if I convert them to UTF-8 instead (another PR)?
