### ISSUE TITLE
Allow specialized vacuole to specialize for mucilage

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#4589]
Mucilage is stored in the normal storage so it doesn't make much sense why specialized vacuole can't be specialized for mucilage

**Comment by hhyyrylainen** [comment]
I'd say yes. I think mucilage will be a bit of a special agent as it is stored in normal storage.

**Comment by CI09** [comment]
Is it going to be alright if I apply logic like:
_compount isn't environmental compound and (is not agent or is "Mucilage")_?

**Comment by hhyyrylainen** [comment]
Yes, but you should check it being a mucilage by having variable that is fetched once that contains the mucilage compound to ensure the code can't get out of date if the internal names of the compounds are renamed.

**Comment by CI09** [comment]
How about checking if compound is _simulationparameters.instance.getcompound("mucilage")_?
