### ISSUE TITLE
Can't 'alt-tab' while in fullscreen

### ISSUE THREAD

**Issue by jjonj** [Revolutionary-Games/Thrive#460]
We might need to wait for an ogre fix for this.

**Comment by TheCreator--** [comment]
I think that's a windows 10 issue, as I can't alt tab in any fullscreen
games. Pressing the windows key works.

**Comment by hhyyrylainen** [comment]
I haven't tested other games than dota2, specifically, but I haven't had such issues with windows 10.

**Comment by jjonj** [comment]
If I spam the windows key a bunch, I can get it to overlay the windows task bar and start menu but regardless of what I do it stays in thrive

**Comment by lukaandjelkovic** [comment]
Cuz their gamebar.

**Comment by hhyyrylainen** [comment]
https://github.com/Revolutionary-Games/Thrive/pull/540 will use a different windowing library and this is fixed there.
