### ISSUE TITLE
Incorrect Health Calculation

### ISSUE THREAD

**Issue by JezzDawga** [Revolutionary-Games/Thrive#4634]
### Describe the bug

Whatever was changed in the latest update in regards to microbe stats has affected the HP calculations.

### To Reproduce

1.  Make a double-membrane max-rigidity cell with a HP of 130.
2. Confirm and play.
3. Notice your HP is not 130.

### Expected behaviour

HP should be 130.

### Screenshots

![1](https://github.com/Revolutionary-Games/Thrive/assets/149287621/915bb3df-1b70-4851-9ee8-1e36f5aaf1df)
![2](https://github.com/Revolutionary-Games/Thrive/assets/149287621/64c9c69c-df78-4f99-9abd-3d94e61050bd)

### System information

Windows 10
Thrive 0.6.4.0

### Game Logs

https://pastebin.com/qJR9e1iL

**Comment by hhyyrylainen** [comment]
Does the health get set correctly if you respawn (use the perish instantly button)? If so I suspect that this is just a case of a missing health re-apply after exiting the editor when applying the new cell settings to the player.

**Comment by JezzDawga** [comment]
Yes it does.

**Comment by hhyyrylainen** [comment]
Made a fix: https://github.com/Revolutionary-Games/Thrive/pull/4643
