### ISSUE TITLE
Change renaming slightly.

### ISSUE THREAD

**Issue by Untrustedlife** [Revolutionary-Games/Thrive#465]
Renaming is strange right now, we can fix that. f12 can be changed to the enter button among other things.

**Comment by MontySpud** [comment]
Making an easier way to rename your microbe would be one way. Maybe make a global variable that stores YOUR microbes id over a large swath of the game?

**Comment by Untrustedlife** [comment]
Its easier in the genustweak branch now, so thats good for now. The variable is a good test case for our little new "Flag" structure.
