### ISSUE TITLE
MP amount can go over 100 (by modifying injectisome pilus)

### ISSUE THREAD

**Issue by stoptakingusernames** [Revolutionary-Games/Thrive#4658]
### Describe the bug

By upgrading pilus into an injectisome and then upgrading it again in then next editor cycle into a regular pilus, you will gain 25 mp  and raise your mp count to 125

### To Reproduce

1. Place down pilus, upgrade it into an injectisome
2. The next time you enter cell editor, modify the injectisome pilus to make it into a normal pilus again

### Expected behaviour

You should only gain 25 mp as a refund for undoing the modification on the same editor cycle, afterwards on subsequent editor cycles it should cost MP to modify the organelle again

### System information

Release 0.6.4

### Game Logs

Not relevant

### Additional Context

I'm not sure if this is an intentional feature or not, but having it work like this would be more consistent with other features (All editor actions cost MP)

**Comment by hhyyrylainen** [comment]
This is basically caused by this root cause: https://github.com/Revolutionary-Games/Thrive/issues/4095 but this issue more explicitly says what that problem can cause in the title.
