### ISSUE TITLE
[Windows] Game messes up desktop resolution

### ISSUE THREAD

**Issue by Zireael07** [Revolutionary-Games/Thrive#471]
After quitting the game, which I think ran at 1024x768 while my Windows resolution was 1280x1024, I saw a messed-up desktop, with the wallpaper only occupying the 1024x768 part of the screen, the rest being black, while the system claimed I was running 1280x1024 resolution.

I fixed it by changing my Windows resolution to something else and back to normal, but the game shouldn't mess up the desktop resolution or wallpaper. Is this a quirk of the rendering engine you're using?

**Comment by hhyyrylainen** [comment]
This is most likely an Ogre issue. And is probably the same issue as this: https://github.com/Revolutionary-Games/Thrive/issues/460

**Comment by Zireael07** [comment]
Looks like it's the same thing, but I'll note I'm using Windows 7, not Windows 10.

**Comment by hhyyrylainen** [comment]
I'm using linux and I, too, have experienced my desktop resolution getting stuck after running an Ogre game. So I guess this is pretty universal issue.

**Comment by hhyyrylainen** [comment]
https://github.com/Revolutionary-Games/Thrive/pull/540 will use a different windowing library and this is fixed there.
