### ISSUE TITLE
Crash due to sound files

### ISSUE THREAD

**Issue by Anth0rx** [Revolutionary-Games/Thrive#472]
After downloading the recent v0.3.2 release for linux I have been experiencing crashes after playing Thrive for a few minutes. The error message is:

```
AudioManager: Failed to create Audio Source (microbemicrobemicrobe-pickup-organelle10097): Error creating audio source.
File ../sounds/soundeffects/microbe-pickup-organelle.ogg doesn't exist
*** SoundSourceSystem::restoreSound() - Sound with name: soundeffects/microbe-pickup-organelle.ogg failed to load!
./launch.sh: line 5: 19821 Segmentation fault      (core dumped) ./Thrive
```

I realized that the error occured because some of the .ogg-files (including the aforementioned "microbe-pickup-organelle.ogg") have not been executable.

Making all .ogg-files executable seems to fix this issue.

**Comment by hhyyrylainen** [comment]
Someone with svn access will need to fix this. (I hope svn allows committing changes to file permissions...)
I'm sure that either @Moopli or @jjonj has that

**Comment by Anth0rx** [comment]
Okay, nice

**Comment by pgelinas** [comment]
Yes, the following command can be used to maintain file permission on SVN:
`svn propset svn:executable true  <filename>`
from http://stackoverflow.com/questions/2920440/maintaining-file-permissions-across-svn-updates

**Comment by hhyyrylainen** [comment]
I think this is fixed now. But there might need to be a checking script or something for fixing this if this happens again in the future.
