### ISSUE TITLE
Weird colors, menu and text

### ISSUE THREAD

**Issue by Anth0rx** [Revolutionary-Games/Thrive#473]
In the release version 0.3.2 are weird visual issues regarding the text format, the components and right menu (in microbe editor) as shown below:

![thrive_graphic](https://cloud.githubusercontent.com/assets/10292489/18886015/73ba0576-84ee-11e6-8f90-a31f36b20592.png)

![thrive_text](https://cloud.githubusercontent.com/assets/10292489/18886016/73e4b69a-84ee-11e6-9cac-f145ec1e93e5.png)

**Comment by hhyyrylainen** [comment]
The top issue should be fixed: https://github.com/Revolutionary-Games/Thrive/issues/451 But the release hasn't been updated so that fix will be in the next release

**Comment by Anth0rx** [comment]
Okay :+1:

**Comment by crodnu** [comment]
was this fixed? can we delete this?

**Comment by hhyyrylainen** [comment]
I'm pretty sure this was fixed at some point by @Oliveriver tweaking the GUI layout a bit.
