### ISSUE TITLE
Make thrive native library debug (/ release) mode compile work on Windows

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#4785]
There's a warning from cmake about Jolt not working with debug builds on windows well, that I put in, but it kind of looks like it does work but always results in a kind of debug build that has debug rendering built into it.

So this needs fixing if anyone wants to compile the releasable physics library versions on windows.

**Comment by CI09** [comment]
Something happened https://github.com/Revolutionary-Games/Thrive/issues/4784
