### ISSUE TITLE
Player microbe name doesn't get updated when species name is modified

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#4924]
Got a report that when exiting the editor after renaming the player species the player cell still shows the old name when hovered over. I think that maybe the readable name component is not being updated on the player, which would explain this if someone confirms that respawning fixes the problem.

https://discord.com/channels/228300288023461893/958598553389903913/1211965857744420925

**Comment by CI09** [comment]
Respawning fixes the name

**Comment by hhyyrylainen** [comment]
Thanks. I think that pretty much confirms the bug is in not updating the name component on the player entity, then.
