### ISSUE TITLE
Mutation menu only shows first 3 categories -- not resolution dependent 

### ISSUE THREAD

**Issue by billythakidd04** [Revolutionary-Games/Thrive#498]
I've tried on two different systems, one with a resolution of 1280x1024 and 1920x1080. Both systems are Ubuntu 16.10 and using OpenGL. Obviously this makes adding offense and movement "upgrades" impossible.

![thrive_no_menu](https://cloud.githubusercontent.com/assets/888231/22412683/1766b876-e67f-11e6-9361-bd10444da628.png)

**Comment by hhyyrylainen** [comment]
The new GUI might replace that menu entirely so this doesn't need fixing.
@Oliveriver is the one making it so he know for sure what is going to be replaced in the next release.

**Comment by hhyyrylainen** [comment]
This doesn't apply anymore with the new GUI
