### ISSUE TITLE
Add documentation about building Thrive in Linux

### ISSUE THREAD

**Issue by Nimbal** [Revolutionary-Games/Thrive#50]
That documentation should list all dependencies (with versions) and common caveats when compiling them.

Additionally, an automated bash script (similar to the mingw_setup) would be nice. The documentation is still essential, though, because the script might not work as expected on all distributions.

**Comment by hhyyrylainen** [comment]
I have written a basic one and @billythakidd04 said that he would amend it with Ubuntu specific extra stuff. So this is done
