### ISSUE TITLE
Write about installing on Ubuntu

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#503]
Right now the package names are way off in SetupTHrive.rb on line 61.
And also Ubuntu users will need to compile their own ffmpeg: https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu

Should be written in: https://github.com/Revolutionary-Games/Thrive/blob/master/linux_setup/readme.md

**Comment by billythakidd04** [comment]
I have some updates for this coming down the pipe shortly
