### ISSUE TITLE
[Bug][Linux] Audio Manager Causes Crash

### ISSUE THREAD

**Issue by Marteon** [Revolutionary-Games/Thrive#504]
While testing the new 0.33 version it randomly crashes and the cause is always the audiomanager.
These are the only information given by the commandline. (I removed the FPS counter)

`AudioManager: Failed to create Audio Source (microbemicrobemicrobe-release-toxin4536): Error creating audio source.`
`./launch.sh: Zeile 7:  4379 Speicherzugriffsfehler  (Speicherabzug geschrieben) ./Thrive`

**Comment by hhyyrylainen** [comment]
Is this part: `Failed to create Audio Source (microbemicrobemicrobe-release-toxin4536)` always the same? or do the numbers change?

I assume that the `Failed to create Audio Source` part is always printed before the crash.

If you know how it would be very useful if you could save a core file at the point the program crashes. If you know how to run thrive in gdb you can dump a core file when it crashes with `gcore`. If you are going to upload one you should zip it to reduce the size.

**Comment by Marteon** [comment]
I don't know yet how to save a core file but I'm getting into it.
I was able to reproduce the bug and the numbers and the text changed.

```
FPS: 128.031
AudioManager: Failed to create Audio Source (microbemicrobemicrobe-pickup-organelle5331): Error creating audio source.
```

**Comment by hhyyrylainen** [comment]
Does the game crash after a certain amount of time has passed (like it crashes always after 5 to 6 minutes starting)?

I think there might be some issue with all audio playing slots getting filled up over time and then the crash happening. 

I'm currently working on something else but after I get it done I'm going to try to play the game for a while and see if I can get it to crash.

**Comment by Marteon** [comment]
Yes it always crashes after a certain amount of time. I don't know yet if it only crashes in Game or too in the Menu. But I am currently testing it and I'll post the results later.

**Comment by Marteon** [comment]
So after some time of testing it seems that your guess with the audio slots is right.
I tested the main Menu for like 2 Hours with no crash.
I also started a game but did nothing but playing the tutorial with no crash too. (I stopped the test after 15min witch was probably not the best idea) 

So right now I can confirm that it only crashes when too many different sounds are played.

**Comment by hhyyrylainen** [comment]
Closing as this will be fixed along with the engine refactor: https://github.com/Revolutionary-Games/Thrive/pull/540
