### ISSUE TITLE
The game still randomly locks up in the C# code

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#5072]
It has been confirmed that the game does lock up random during gameplay still. Could be related to specific thread counts, like really low thread count around 2-4 (which would explain why I haven't seen this). Or it just could be that it is very rare.

**Comment by ggkkaa** [comment]
> It has been confirmed that the game does lock up random during gameplay still. Could be related to specific thread counts, like really low thread count around 2-4 (which would explain why I haven't seen this). Or it just could be that it is very rare.

Are there any crash logs?

**Comment by hhyyrylainen** [comment]
There are no crash logs because the game doesn't crash. It just gets stuck and never does anything again needing to be force closed to get it to quit. 
It is possible to dump the thread callstacks with gdb and the C# callstacks with some C# introspection (I can push my really crude command line tool for this if anyone is interested). That's how I've identified some areas where the game could lock up and added workarounds (https://github.com/Revolutionary-Games/Thrive/issues/4989).

**Comment by hhyyrylainen** [comment]
Fixing https://github.com/Revolutionary-Games/Thrive/issues/5132 may have fixed this (at least this removed one freeze I was able to consistently get).

**Comment by hhyyrylainen** [comment]
This *seems* to no longer be the case as long as thread local or custom barrier is not used (those are tracked as separate issues that are currently disabled).
