### ISSUE TITLE
Check useTopDownOrientation in SoundListenerSystem really was meant to use FromEuler

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#5076]
I was unsure when converting the code. Can be tested in the game by listening if sounds come from left and right speakers correctly in relation to the player microbe.

**Comment by ggkkaa** [comment]
Wait let me check real quick

**Comment by ggkkaa** [comment]
Ah f*ck it looks like I bought fake headphones, they're supposed to be stereo but don't have left or right channels

**Comment by ggkkaa** [comment]
Wait I have built in stereo speakers

**Comment by ggkkaa** [comment]
I think it's meant to use FromEuler.

**Comment by hhyyrylainen** [comment]
So the sounds are correct now in the game (sounds to the left of the player come from the left speaker)?

**Comment by hhyyrylainen** [comment]
Still need someone to spend just a few minutes in the game and listen to the sounds to check that this is correct.

**Comment by hhyyrylainen** [comment]
I'm pretty sure the direction is correct. I put in test code allowing me to play a sound at my cursor and I think I'm hearing the things to the right of the screen from my right speakers and vice-versa.
