### ISSUE TITLE
Create options menu

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#509]
Thrive needs a built in options menu instead of the Ogre dialog.

Links/resources:
http://forum.revolutionarygamesstudio.com/t/options-menu-discussion/181
http://forum.revolutionarygamesstudio.com/t/main-menu-options-menu/244/15

Should include:
There is now a list on the forums:
https://forum.revolutionarygamesstudio.com/t/main-menu-options-menu/244/23?u=hhyyrylainen
(TODO: grab all those here as checkboxes)

**Comment by hhyyrylainen** [comment]
Depends on https://github.com/Revolutionary-Games/Thrive/issues/335

**Comment by Untrustedlife** [comment]
should this be 0.4.0 ?

**Comment by Untrustedlife** [comment]
Mabe it should be delayed to 0.4.1

**Comment by hhyyrylainen** [comment]
If someone works on this, this will be included for 0.4.1, but if no one does this then this is non-gating for 0.4.1 release and can be left out.

**Comment by Kasterisk** [comment]
Are any engine-side changes necessary for this to be possible?

**Comment by hhyyrylainen** [comment]
Yes, while changing the window resolution might be currently possible, changing any of the graphics options like full screen mode, anti-aliasing etc. is not possible. Also having a general framework in the engine to let code register for options changes (like changing keybindings would automatically update the key objects), would be really nice for thrive.

**Comment by hhyyrylainen** [comment]
Should we way more possible with Godot now. I started working on saving and loading the options from a json file.
