### ISSUE TITLE
[Linux][Launcher] Missing Libraries

### ISSUE THREAD

**Issue by Narotiza** [Revolutionary-Games/Thrive#513]
Apologies if I am doing something wrong; I have never used Github before.
This is an error I received when I tried to launch 0.3.3 after installing it with the launcher. Earlier, pre-launcher, I tried to install the game manually on Linux and got a similar error involving similar libraries. I had to place the missing libraries in the bin folder to fix the problem.
Log:
`Playing Thrive 0.3.3
Thrive is running. Log output:
Process Started
ERROR: /home/narotiza/Downloads/thrive-launcher-linux-x64/installed/LINUX_Thrive-v0.3.3/Thrive-0.3.3/bin/Thrive: error while loading shared libraries: librtmp.so.1: cannot open shared object file: No such file or directory
child process exited with code 127`

**Comment by Narotiza** [comment]
Yep I did this wrong god dammit

**Comment by hhyyrylainen** [comment]
Nope, this was right. This is issue with the linux packaging script, which is IN this repository.

**Comment by hhyyrylainen** [comment]
I've no included this in my working branch (`sol_lua`) once jjonj has finished checking it it will be merged.
Please let me know if you find any other missing libraries

**Comment by Narotiza** [comment]
These should be them:

librtmp.so.1
libnuma.so.1
libhogweed.so.4
libjasper.so.1

**Comment by surge9000** [comment]
```
surge@animal:/opt/a/games/thrive/Thrive-0.3.3$ ./launch.sh 
./Thrive: error while loading shared libraries: libunistring.so.2: cannot open shared object file: No such file or directory
surge@animal:/opt/a/games/thrive/Thrive-0.3.3$ apt-cache search libunistring
libunistring-dev - Unicode string library for C - development files
libunistring0 - Unicode string library for C
surge@animal:/opt/a/games/thrive/Thrive-0.3.3/bin$ ldd ./Thrive |grep 'not found'
./Thrive: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.22' not found (required by ./libgnutls.so.30)
	libunistring.so.2 => not found
	libnettle.so.6 => not found
	libhogweed.so.4 => not found

```

libnettle 6 is still missing as it was in Thrive version 3.2 and now there are a few more. This system is a recent STABLE system (Debian 8 "Jessie"), so the libraries aren't the most modern, but it's unreasonable to require every user to upgrade/install a development system to run it.
I've forgotten exactly how, but I think you can get gcc to compile with backward compatibility in mind, which should solve the glibc problem. As for the libraries, you'll just have to include them, or get yourself a stable/production system to compile against.

**Comment by hhyyrylainen** [comment]
I have now added all of these libraries to the upcoming release

**Comment by Translator5** [comment]
Hey there, just downloaded v.0.3.4.rc1 to my Linux Mint 18.1
There I had to download two libs at least;
```
libssh-4
libidn2-0
```
Maybe it is possible to add them into the download or add a wiki-page where all libs are listed in a "sudo command"?

**Comment by hhyyrylainen** [comment]
It's possible to run `ldd Thrive`to see what you are missing. Also the release is tested on Ubuntu so the next option is to install everything ubuntu has by default, or fedora, and not use a distribution that skimps on really common things like ssh libraries. 

The third option would be for us to get the package names for every single package manager  they aren't the same, not even ubuntu and fedora can use the same package names) so it would be really hard to find the package names for all of these libraries (and this isn't even all as some libraries are dynamically loaded and ldd doesn't find them):
```
        linux-vdso.so.1 (0x00007ffcdaf7c000)
	libavcodec.so.57 => /lib64/libavcodec.so.57 (0x00007fbac19e2000)
	libavformat.so.57 => /lib64/libavformat.so.57 (0x00007fbac15ed000)
	libavutil.so.55 => /lib64/libavutil.so.55 (0x00007fbac136f000)
	libswscale.so.4 => /lib64/libswscale.so.4 (0x00007fbac10e9000)
	libboost_chrono.so.1.60.0 => /lib64/libboost_chrono.so.1.60.0 (0x00007fbac0ee0000)
	libboost_date_time.so.1.60.0 => /lib64/libboost_date_time.so.1.60.0 (0x00007fbac0ccf000)
	libboost_filesystem.so.1.60.0 => /lib64/libboost_filesystem.so.1.60.0 (0x00007fbac0ab9000)
	libboost_thread.so.1.60.0 => /lib64/libboost_thread.so.1.60.0 (0x00007fbac0891000)
	libboost_system.so.1.60.0 => /lib64/libboost_system.so.1.60.0 (0x00007fbac068d000)
	libboost_atomic.so.1.60.0 => /lib64/libboost_atomic.so.1.60.0 (0x00007fbac048b000)
	libOgreMain.so.2.0.0 => /usr/local/lib/libOgreMain.so.2.0.0 (0x00007fbabfd75000)
	libOIS-1.3.0.so => /lib64/libOIS-1.3.0.so (0x00007fbabfb56000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fbabf938000)
	libBulletDynamics.so.2.83 => /lib64/libBulletDynamics.so.2.83 (0x00007fbabf693000)
	libBulletCollision.so.2.83 => /lib64/libBulletCollision.so.2.83 (0x00007fbabf386000)
	libLinearMath.so.2.83 => /lib64/libLinearMath.so.2.83 (0x00007fbabf169000)
	libBulletSoftBody.so.2.83 => /lib64/libBulletSoftBody.so.2.83 (0x00007fbabef24000)
	libCEGUIBase-9999.so.2 => /usr/local/lib64/libCEGUIBase-9999.so.2 (0x00007fbabeb05000)
	libCEGUIOgreRenderer-9999.so.2 => /usr/local/lib64/libCEGUIOgreRenderer-9999.so.2 (0x00007fbabe8d4000)
	libtinyxml.so.0 => /lib64/libtinyxml.so.0 (0x00007fbabe6bd000)
	libopenal.so.1 => /lib64/libopenal.so.1 (0x00007fbabe422000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fbabe21e000)
	libswresample.so.2 => /lib64/libswresample.so.2 (0x00007fbabdfff000)
	libcAudio.so.2 => /usr/local/lib/libcAudio.so.2 (0x00007fbabdd9a000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fbabda12000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fbabd709000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fbabd4f2000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fbabd12c000)
	libva.so.1 => /lib64/libva.so.1 (0x00007fbabcf0a000)
	libva-drm.so.1 => /lib64/libva-drm.so.1 (0x00007fbabcd07000)
	libzvbi.so.0 => /lib64/libzvbi.so.0 (0x00007fbabca7a000)
	libxvidcore.so.4 => /lib64/libxvidcore.so.4 (0x00007fbabc769000)
	libx265.so.110 => /lib64/libx265.so.110 (0x00007fbabc201000)
	libx264.so.148 => /lib64/libx264.so.148 (0x00007fbabbe8a000)
	libwebpmux.so.2 => /lib64/libwebpmux.so.2 (0x00007fbabbc7e000)
	libwebp.so.6 => /lib64/libwebp.so.6 (0x00007fbabba1d000)
	libvpx.so.4 => /lib64/libvpx.so.4 (0x00007fbabb614000)
	libvorbisenc.so.2 => /lib64/libvorbisenc.so.2 (0x00007fbabb36b000)
	libvorbis.so.0 => /lib64/libvorbis.so.0 (0x00007fbabb13f000)
	libvo-amrwbenc.so.0 => /lib64/libvo-amrwbenc.so.0 (0x00007fbabaf25000)
	libtwolame.so.0 => /lib64/libtwolame.so.0 (0x00007fbabacff000)
	libtheoraenc.so.1 => /lib64/libtheoraenc.so.1 (0x00007fbabaabe000)
	libtheoradec.so.1 => /lib64/libtheoradec.so.1 (0x00007fbaba8a3000)
	libspeex.so.1 => /lib64/libspeex.so.1 (0x00007fbaba68a000)
	libschroedinger-1.0.so.0 => /lib64/libschroedinger-1.0.so.0 (0x00007fbaba3a7000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fbaba191000)
	libopus.so.0 => /lib64/libopus.so.0 (0x00007fbab9f3e000)
	libopenjpeg.so.1 => /lib64/libopenjpeg.so.1 (0x00007fbab9d1a000)
	libopenh264.so.3 => /lib64/libopenh264.so.3 (0x00007fbab9a25000)
	libopencore-amrwb.so.0 => /lib64/libopencore-amrwb.so.0 (0x00007fbab9811000)
	libopencore-amrnb.so.0 => /lib64/libopencore-amrnb.so.0 (0x00007fbab95e7000)
	libmp3lame.so.0 => /lib64/libmp3lame.so.0 (0x00007fbab9370000)
	libmfx.so.0 => /lib64/libmfx.so.0 (0x00007fbab915a000)
	libkvazaar.so.3 => /lib64/libkvazaar.so.3 (0x00007fbab8e98000)
	libgsm.so.1 => /lib64/libgsm.so.1 (0x00007fbab8c8c000)
	libfdk-aac.so.1 => /lib64/libfdk-aac.so.1 (0x00007fbab89d4000)
	libnvcuvid.so.1 => /lib64/libnvcuvid.so.1 (0x00007fbab87ac000)
	libcuda.so.1 => /lib64/libcuda.so.1 (0x00007fbab7d55000)
	libssh.so.4 => /lib64/libssh.so.4 (0x00007fbab7ae3000)
	librtmp.so.1 => /lib64/librtmp.so.1 (0x00007fbab78c6000)
	libgnutls.so.30 => /lib64/libgnutls.so.30 (0x00007fbab755f000)
	libbluray.so.1 => /lib64/libbluray.so.1 (0x00007fbab7315000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007fbab7105000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007fbab6dc6000)
	libvdpau.so.1 => /lib64/libvdpau.so.1 (0x00007fbab6bc0000)
	libva-x11.so.1 => /lib64/libva-x11.so.1 (0x00007fbab69ba000)
	libOpenCL.so.1 => /lib64/libOpenCL.so.1 (0x00007fbab679b000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fbab6593000)
	libSM.so.6 => /lib64/libSM.so.6 (0x00007fbab638b000)
	libICE.so.6 => /lib64/libICE.so.6 (0x00007fbab616d000)
	libXext.so.6 => /lib64/libXext.so.6 (0x00007fbab5f5b000)
	libXt.so.6 => /lib64/libXt.so.6 (0x00007fbab5cf3000)
	libXaw.so.7 => /lib64/libXaw.so.7 (0x00007fbab5a8d000)
	libfreeimage.so.3 => /lib64/libfreeimage.so.3 (0x00007fbab57cf000)
	libzzip-0.so.13 => /lib64/libzzip-0.so.13 (0x00007fbab55c7000)
	libatomic.so.1 => /lib64/libatomic.so.1 (0x00007fbab53bd000)
	/lib64/ld-linux-x86-64.so.2 (0x000055fe1a092000)
	libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007fbab5112000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007fbab4e9f000)
	libsoxr.so.0 => /lib64/libsoxr.so.0 (0x00007fbab4c3c000)
	libdrm.so.2 => /lib64/libdrm.so.2 (0x00007fbab4a2b000)
	libpng16.so.16 => /lib64/libpng16.so.16 (0x00007fbab47f6000)
	libnuma.so.1 => /lib64/libnuma.so.1 (0x00007fbab45eb000)
	libogg.so.0 => /usr/lib64/libogg.so.0 (0x00007fbab43e4000)
	liborc-0.4.so.0 => /lib64/liborc-0.4.so.0 (0x00007fbab4167000)
	libGL.so.1 => /lib64/libGL.so.1 (0x00007fbab3ed9000)
	libnvidia-fatbinaryloader.so.378.13 => /lib64/libnvidia-fatbinaryloader.so.378.13 (0x00007fbab3c88000)
	libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007fbab3827000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007fbab35da000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007fbab32f4000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007fbab30c3000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007fbab2ebd000)
	libhogweed.so.4 => /lib64/libhogweed.so.4 (0x00007fbab2c91000)
	libnettle.so.6 => /lib64/libnettle.so.6 (0x00007fbab2a59000)
	libgmp.so.10 => /lib64/libgmp.so.10 (0x00007fbab27c6000)
	libp11-kit.so.0 => /lib64/libp11-kit.so.0 (0x00007fbab2561000)
	libidn2.so.0 => /lib64/libidn2.so.0 (0x00007fbab2344000)
	libunistring.so.2 => /lib64/libunistring.so.2 (0x00007fbab2012000)
	libtasn1.so.6 => /lib64/libtasn1.so.6 (0x00007fbab1dff000)
	libxml2.so.2 => /lib64/libxml2.so.2 (0x00007fbab1a97000)
	libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00007fbab1853000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007fbab162b000)
	libXfixes.so.3 => /lib64/libXfixes.so.3 (0x00007fbab1425000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007fbab121e000)
	libXmu.so.6 => /lib64/libXmu.so.6 (0x00007fbab1004000)
	libXpm.so.4 => /lib64/libXpm.so.4 (0x00007fbab0df2000)
	libjpeg.so.62 => /lib64/libjpeg.so.62 (0x00007fbab0b88000)
	libjpegxr.so.0 => /lib64/libjpegxr.so.0 (0x00007fbab0952000)
	libjxrglue.so.0 => /lib64/libjxrglue.so.0 (0x00007fbab0730000)
	libIlmImf-2_2.so.22 => /lib64/libIlmImf-2_2.so.22 (0x00007fbab0260000)
	libImath-2_2.so.12 => /lib64/libImath-2_2.so.12 (0x00007fbab004e000)
	libHalf.so.12 => /lib64/libHalf.so.12 (0x00007fbaafe0b000)
	libIex-2_2.so.12 => /lib64/libIex-2_2.so.12 (0x00007fbaafbeb000)
	libIexMath-2_2.so.12 => /lib64/libIexMath-2_2.so.12 (0x00007fbaaf9e6000)
	libIlmThread-2_2.so.12 => /lib64/libIlmThread-2_2.so.12 (0x00007fbaaf7df000)
	libopenjp2.so.7 => /lib64/libopenjp2.so.7 (0x00007fbaaf5a7000)
	libraw.so.15 => /lib64/libraw.so.15 (0x00007fbaaf2ca000)
	libtiff.so.5 => /lib64/libtiff.so.5 (0x00007fbaaf055000)
	libgomp.so.1 => /lib64/libgomp.so.1 (0x00007fbaaee27000)
	libGLX.so.0 => /lib64/libGLX.so.0 (0x00007fbaaebf6000)
	libGLdispatch.so.0 => /lib64/libGLdispatch.so.0 (0x00007fbaae93e000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007fbaae72f000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007fbaae52b000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fbaae310000)
	libffi.so.6 => /lib64/libffi.so.6 (0x00007fbaae108000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007fbaadee0000)
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00007fbaadcb6000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007fbaadab2000)
	libjasper.so.1 => /lib64/libjasper.so.1 (0x00007fbaad859000)
	liblcms2.so.2 => /lib64/liblcms2.so.2 (0x00007fbaad5fd000)
	libjbig.so.2.1 => /lib64/libjbig.so.2.1 (0x00007fbaad3ef000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007fbaad1c8000)
```
That would be the easiest for players but really tedious so it's most likely not going to happen.

You are of course free to add a list of packages to the readme in a pull request.

**Comment by Simbrine** [comment]
I also have missing libraries, although I'm only missing the iLBC and IDN 2 libraries

**Comment by hhyyrylainen** [comment]
@Simbrine What's the full name of the `iLBC`library? I'm not seeing that in the list I posted above.

**Comment by tim-oleksii** [comment]
It's something like this
`
./Thrive: error while loading shared libraries: libilbc.so.0: cannot open shared object file: No such file or directory
`

**Comment by hhyyrylainen** [comment]
Alright, so it looks like that some updated library now requires libilbc and I hadn't noticed, this will be fixed in the next release

**Comment by Simbrine** [comment]
Nice, thanks. I didn't realize to check my github notifications after posting this, thanks @tim-oleksii for answering for me instead

**Comment by dnulho** [comment]
When I try to run the game from the launcher, I get this output.

> Playing Thrive 0.3.4
> Thrive is running. Log output:
> Process Started
> ERROR: .../Thrive Launcher-linux-x64/installed/LINUX_Thrive.0.3.4/Thrive-0.3.4/bin/Thrive: error while loading shared libraries: libilbc.so.0: cannot open shared object file: No such file or directory
> child process exited with code 127

**Comment by hhyyrylainen** [comment]
This should already be fixed for the next release, but we haven't managed to make a new release in a while so the latest release still has this issue.

In the meantime you can fix this by getting libilbc from somewhere. For example arch linux packages it: https://aur.archlinux.org/packages/libilbc/

**Comment by dnulho** [comment]
Ah, Thanks.

**Comment by surge9000** [comment]
If you choose to support a binary glob, like this, may I suggest compiling it statically.
This usually involves `./configure --disable-shared` or some variant on the support libraries, and then making sure the linker only references .o objects (not .so) for thrive. The GNU linker is a real mess, so it will involve a little work, but certainly less than what you've already done, and will need to do in the future.
It will solve alot of your hassles here.

I keep coming back here to check on the status of this project because it sounds amazing, and I'd really like to play it, but until it actually works at all, it's always a dissapointment.

**Comment by hhyyrylainen** [comment]
@surge9000 The only library we use that has that style of configure script is ffmpeg, and even there we use parts of it which are LGPL licensed meaning that we *definitely* want to dynamically link it. Every other dependency uses cmake, it is far from guaranteed that everything works as static libraries. Also many of the libraries (SDL2, boost, XLib, FreeImage, zlib) are used from system packages, which for the most common distros are only provided as dynamically linkable. 

I've been thinking about providing a version that is guaranteed to work only on latest fedora (the smallest filesize), a version with a list of libraries that people are known to be missing, and then a flatpakked (https://www.flatpak.org/) version so no one can complain about missing libraries.

**Comment by hhyyrylainen** [comment]
Each project must add their own option of building them as static libraries with cmake. I haven't bothered to check all the dependencies, so this might turn into having to do pull requests to many of the dependencies to add that.

Boost libraries is a bad option as it is actually provided also as a static version. But FreeImage, not available for Fedora as statically compiled. So for us to statically link that someone needs to setup every single dependency (that not all distributions provide as a statically linked version) to be built by it. That's a ton of work.

I mentioned licensing because the engine that we switched to (https://github.com/hhyyrylainen/Leviathan) is MIT licensed and putting LGPL code in the same executable with it (statically linked) is a no go. So even if someone did a setup for static version (which would be encumbered by GPL) I will insist that the dynamically linked version will also be maintained.

So by using flatpak I can make a version of thrive that will run everywhere where flatpak is available without bloating the filesize with everything. I won't do a static version but someone else is free to try.

**Comment by kelargo** [comment]
this issue seems to persist.  I just downloaded the linux release "LINUX_Thrive.0.3.4.7z" 
and expanded it.  "7za x LINUX_Thrive.0.3.4.7z "   and then cd'd to the new directory and ran "launch.sh". 

I get the following : 

`$ ./launch.sh 
./Thrive: error while loading shared libraries: libilbc.so.0: cannot open shared object file: No such file or directory
`

**Comment by hhyyrylainen** [comment]
That release is one year old already (we don't have a newer release, yet). That library is no longer used by the new versions.

I think I already mentioned it somewhere but a way to fix it yourself is to grab the source code of libilbc, compile it and symlink that name to the compiled library.

**Comment by theonetoday** [comment]
I installed the libraries using your link up above. I ran the commands, ./configure, make, sudo make install and it seems to have gone smoothly but I'm not sure where libilbc.so.0 ended up. I was able to find libilbc.so but not the other. Any ideas?

**Comment by hhyyrylainen** [comment]
You need to create a symlink named libilbc.so.0 pointing to libilbc.so because the install doesn't create it. So locate the folder where libilbc.so is and create the symlink there with the correct name.

**Comment by theonetoday** [comment]
I thought they were two different files. I'll give it a shot, thanks.

**Comment by hhyyrylainen** [comment]
One more thing that can help with this issue is making the symlink in `/usr/lib` or `/usr/lib64` (depends on the distro which one you should use) pointing to the library. This is because default settings of LD on many distros don't automatically load libraries from `/usr/local/lib`.

**Comment by mbmcc** [comment]
@hhyyrylainen 
To fix this issue on Ubuntu 
(tested with ver 17.10)
I found that Ubutnu uses a usr/lib/x86_64-linux-gnu directory for its 64bit libraries.
I created a symbolic link in the /usr directory to named lib64 pointing to the x86_64-linux-gnu and that 
seemed to fix the problem.
```
sudo ln -s /usr/lib/x86_64-linux-gnu /usr/lib64
```

Can you include this lib directory in the next release?

**Comment by hhyyrylainen** [comment]
I have plans to have a flatpak version of thrive at some point but there's probably not enough time / energy for me to work on that before the next release. But I have reduced the uncommon libraries used by the bundled ffmpeg to 0 so this should be quite majorly mitigated. I've still yet to make a new packaging script but I plan to reuse the list of libraries that should be bundled in.

**Comment by NerdyShawn** [comment]
I tried on Ubuntu 18.04 x64 with no luck after making the mentioned sym link.
`sudo ln -s /usr/lib/x86_64-linux-gnu /usr/lib64`
./Thrive: error while loading shared libraries: libilbc.so.0: cannot open shared object file: No such file or directory

**Comment by hhyyrylainen** [comment]
The library needs to be put in a path where ld looks for it. The paths ld looks for are configured in
`/etc/ld.so.conf` which likely loads all files in `/etc/ld.so.conf.d/`. You can add additional paths in a .conf file in that folder and then regenerate the ld cache to get it to look in additional paths. It should work if you add `/usr/lib64` in a file there. The manual for this config is available online here: http://man7.org/linux/man-pages/man8/ldconfig.8.html

So you need to figure out which paths are included in ld search for libraries and put a symlink in one of them. Or add a new entry for the folder that has the library.

**Comment by surge9000** [comment]
Symlinks are unnecessary and it's not that difficult:

#!/bin/sh
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<wherever your included libraries are>
export LD_LIBRARY_PATH
./thrive

...there, 1/2 the work is done for you already.

**Comment by psychoticusrex** [comment]
I found this on Ubuntu works:

1. Do an: '_sudo apt-get install libssh-4_' to get the **libssh** library maintained by ubunutu installed.
2. Download libilbc library from website: '_https://aur.archlinux.org/packages/libilbc_/'.
3. Extract **libilbc-2.0.2.tar.bz2** (or whatever the latest version is) file to a sub directory somewhere.
4. Run '_sudo ./configure; make; make install_' from that sub directory.
5. Note that I found libilbc located in the **/usr/local/lib** directory.
6. Make a symbolic link '_ln -s <target> <name of link>_' from where you find yours to a target file name in the Thrive directory and the Thrive bin sub directory (I did both just to be sure there wasn't also a path error in the launcher).  Change the <name of link> to whatever version the launcher is asking for, mine was libilbc.so.o so I pointed THAT at libilbc.so.2.0.2 in the /usr/local/lib directory.
10. Launcher should now work on ubuntu, good luck.

**Comment by hhyyrylainen** [comment]
If no one has issues with 0.4.0 I'll close this.

**Comment by diogogomes** [comment]
Hello @hhyyrylainen, 

I think that the problem persists in the version 0.4.0 with Xubuntu 18.04:

`./Thrive: error while loading shared libraries: libilbc.so.0: cannot open shared object file: No such file or directory`

**Comment by hhyyrylainen** [comment]
Did you actually test with 0.4.0, because It hasn't been released yet (it will be released tomorrow)?
And with `ldd Thrive` I don't see anything about libilbc at all.

**Comment by hhyyrylainen** [comment]
0.4.0 has now been released. 

Is anyone still having issues?

**Comment by hhyyrylainen** [comment]
Looks like some libraries are missing to support a wider range of Linuxes.
One user got an error about `version `GLIBC_2.27' `.

**Comment by Untrustedlife** [comment]
Well thank you for playing our game :)

**Comment by Squidyman56** [comment]
> Looks like some libraries are missing to support a wider range of Linuxes.
> One user got an error about `version `GLIBC_2.27' `.

I have that problem too. I am really bad at understanding how to fix linux stuff, but I try. Could you explain how to fix this please?

**Comment by hhyyrylainen** [comment]
I'll close this as I think all the required libraries are in the release now, except for glibc as distributing that is turning out to be very difficult and it is probably better to aim for making flatpaks in addition to the generic linux zips (that for now will require glibc 2.27).
