### ISSUE TITLE
Can Unreal Engine 4 work with Travis CI?

### ISSUE THREAD

**Issue by richelbilderbeek** [Revolutionary-Games/Thrive#517]
I have volunteered (thanks to @hhyyrylainen) to see if UE4 can be built on Travis CI.

(I wish I could assign myself to this Issue)

**Comment by richelbilderbeek** [comment]
* [Unreal Engine forum post](https://forums.unrealengine.com/showthread.php?83432-UE4-Travis-CI&highlight=Travis)
 * [Older Unreal Engine forum post](https://forums.unrealengine.com/showthread.php?82746-Unreal-Engine-and-Travis-CI-Continuous-Integration)

Both posts have suggestions to use [gamebuildr.io](https://www.gamebuildr.io/).

**Comment by richelbilderbeek** [comment]
Unreal Engine 4 cannot work with Travis CI, as it requires Windows, according to 
[the Unreal Engine documentation](https://docs.unrealengine.com/latest/INT/GettingStarted/RecommendedSpecifications/index.html).

**Comment by richelbilderbeek** [comment]
@hhyyrylainen: the answer is a simple no.

Solved!

**Comment by hhyyrylainen** [comment]
@richelbilderbeek Where does it say that on the page?
Though, I'm sure that none of the graphical components will work on a build server.

**Comment by richelbilderbeek** [comment]
Blimey, I've been a klutz! Thanks for correcting me!

Back to work...

**Comment by hhyyrylainen** [comment]
Though, it might take too much compile time to be allowed to run as linux needs to build the engine from source and that takes like an hour...

**Comment by richelbilderbeek** [comment]
I also think that is the most likely scenario, but I'll measure...

**Comment by richelbilderbeek** [comment]
Setting it up on Linux is [described here](https://docs.unrealengine.com/latest/INT/Platforms/Linux/BeginnerLinuxDeveloper/SettingUpAnUnrealWorkflow/index.html)

**Comment by richelbilderbeek** [comment]
Created [a GitHub](https://github.com/richelbilderbeek/travis_qmake_gcc_cpp14_ue4) to test this in isolation.

**Comment by richelbilderbeek** [comment]
From [the Travis build log](https://travis-ci.org/richelbilderbeek/travis_qmake_gcc_cpp14_ue4#L381):

```
$ git clone https://github.com/EpicGames/UnrealEngine.git
Cloning into 'UnrealEngine'...
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/EpicGames/UnrealEngine.git/'
The command "git clone https://github.com/EpicGames/UnrealEngine.git" failed and exited with 128 during .
```

This means that even *I* can download the UE4, Travis CI cannot, as it does not have a GitHub.

No idea how to ?pass my credentials to Travis CI?

**Comment by richelbilderbeek** [comment]
Posted a question on [the UE4 forum](https://forums.unrealengine.com/), which is now awaiting moderation.

**Comment by richelbilderbeek** [comment]
Question and answer landed [here](https://forums.unrealengine.com/showthread.php?146029-Authorizing-Travis-CI-to-download-UE4)

**Comment by richelbilderbeek** [comment]
Answer seems to be: yes, if one has access to a paid GitHub and a paid Travis CI account, as UE4 is not FLOSS.

**Comment by hhyyrylainen** [comment]
Why is a paid github account required? Is it for having a private clone of
the unreal engine for Travis to clone?

27.6.2017 9.40 "Richel Bilderbeek" <notifications@github.com> kirjoitti:

**Comment by richelbilderbeek** [comment]
>  Is it for having a private clone of the unreal engine for Travis to clone?
Yes, a private GitHub is needed for having a private clone. Epic Games will not like it if you'd put the UE4 in a public GitHub.

**Comment by hhyyrylainen** [comment]
Closing this as this is no longer relevant, see: https://github.com/Revolutionary-Games/Thrive/issues/518
