### ISSUE TITLE
Fix .travis.yml

### ISSUE THREAD

**Issue by richelbilderbeek** [Revolutionary-Games/Thrive#518]
From [Travis CI build log, 195-build-server branch](https://travis-ci.org/richelbilderbeek/Thrive#L477):

```
E: Unable to locate package libogre-1.8-dev
E: Couldn't find any package by glob 'libogre-1.8-dev'
E: Couldn't find any package by regex 'libogre-1.8-dev'
```

I'll fix it.

(I wish I could assign myself for this Issue)

**Comment by hhyyrylainen** [comment]
Assigned you to this issue

**Comment by richelbilderbeek** [comment]
First use a newer distro. Then use OGRE 1.9 I'd say:

```
richel@lubuntu:~/GitHubs/Thrive$ aptitude search libogre
i   libogre-1.9-dev                 - 3D Object-Oriented Graphics Rendering Engi
p   libogre-1.9-dev:i386            - 3D Object-Oriented Graphics Rendering Engi
i A libogre-1.9.0v5                 - 3D Object-Oriented Graphics Rendering Engi
p   libogre-1.9.0v5:i386            - 3D Object-Oriented Graphics Rendering Engi
p   libogre-1.9.0v5-dbg             - 3D Object-Oriented Graphics Rendering Engi
p   libogre-1.9.0v5-dbg:i386        - 3D Object-Oriented Graphics Rendering Engi
```

**Comment by richelbilderbeek** [comment]
When using Trusty, I get the error:

```
$ svn co http://crovea.net/svn/thrive_assets assets
svn: E670002: Unable to connect to a repository at URL 'http://crovea.net/svn/thrive_assets'
svn: E670002: Name or service not known
```

**Comment by hhyyrylainen** [comment]
But we are already using Ogre 2.0? See SetupThrive.rb

Are you using the old assets url? My svn is pointing at: http://thrive@87.230.23.195/svn/thrive_assets

**Comment by richelbilderbeek** [comment]
I am just writing down what I see from the current/old `.travis.yml` build results. Thanks for pointing me to `SetupThrive.rb`!

**Comment by richelbilderbeek** [comment]
Note to self: hhyyrylainen wrote [a build tutorial for the ue4 engine version](https://github.com/Revolutionary-Games/Thrive/blob/ue4/BUILDING.md)

**Comment by hhyyrylainen** [comment]
@richelbilderbeek If you are still interested in this... we are no longer planning an ue4 version, so that should make setting up ci possible. Latest thrive engine changes are here: https://github.com/Revolutionary-Games/Thrive/tree/engine_refactor (this branch isn't complete and may not compile at times)

**Comment by richelbilderbeek** [comment]
That is IMHO great! I planned on leaving, as do prefer FLOSS libraries. I will happily go back work on this when I have finished my more pressing volunteer works.

**Comment by hhyyrylainen** [comment]
I'll setup circleci for thrive once https://github.com/Revolutionary-Games/Thrive/pull/540 is merged

**Comment by richelbilderbeek** [comment]
I unassign from this Issue and project as a whole. I love this project, yet teaching kids (as a volunteer) is even more important to me. Thanks for the great community, especially @hhyyrylainen !

**Comment by hhyyrylainen** [comment]
I'm no longer considering travis to be required. Tracking of setting up other ci solutions is in this issue: https://github.com/Revolutionary-Games/Thrive/issues/195
