### ISSUE TITLE
Closing the art gallery should force stop any playing music tracks

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#5185]
so that no track that was played by the player is going to overlap with the menu music

Should be just a case of making the audio player nodes force stop themselves when the art gallery is closed (as I'm not sure the art gallery contents are cleared when it is closed).

**Comment by GameDungeon** [comment]
Looked at this issue, but I can't actually seem to get any music to keep playing when I leave the art gallery.

**Comment by hhyyrylainen** [comment]
Alright, I asked in some places if other people can reproduce this issue. I'll test this also in time for 0.6.8 release and close if I cannot reproduce it.

**Comment by hhyyrylainen** [comment]
If I remember right I haven't been able to reproduce this issue anytime recently.
