### ISSUE TITLE
Toxin vacuole organelle unlock condition only takes into account organelles with OxyToxy NT upgrade

### ISSUE THREAD

**Issue by stoptakingusernames** [Revolutionary-Games/Thrive#5187]
### Describe the bug

Second unlock condition for the oxytoxisome organelle (requirement to contain at least 3 toxin vacuoles for 5 generations) does not take into account any toxin vacuole with upgrades other than the regular OxyToxy NT

### To Reproduce

1. Add 3 toxin vacuoles to cell, modify them to different types
2. Check the toxin vacuole unlock condition in the next editor cycle

### Expected behaviour

The unlock condition should be satisfied by any type of toxin vacuole

### Screenshots

![image](https://github.com/Revolutionary-Games/Thrive/assets/33234241/f639d8a8-8d6e-4261-8b47-00ebb8893f79)
![image](https://github.com/Revolutionary-Games/Thrive/assets/33234241/a0766bcb-eb0d-4ebd-b3e1-bb5106783f9b)
2/3 toxin vacuoles have different upgrades

### System information

Thrive verson 0.6.7 beta release candidate

**Comment by hhyyrylainen** [comment]
Can you provide a save where the problem can be observed? I just double checked the code and it should not be possible for this to happen because the organelle reproduction unlock condition doesn't care about organelle upgrades at all.

For reference this is the code for counting how many instances are present in a cell:
```c#
    private int CountOrganellesOfType(OrganelleDefinition definition, OrganelleLayout<PlacedOrganelle> layout)
    {
        int count = 0;

        foreach (var organelle in layout.Organelles)
        {
            // As the player grows before reproducing, this might end up double counting organelles so this skip is
            // here
            if (organelle.IsDuplicate)
                continue;

            if (organelle.Definition == definition)
                ++count;
        }

        return count;
    }
```

**Comment by ender-titan1** [comment]
Are you sure it's not because of the fact that you need to reproduce 5 times with the organelle? From the screenshot you provided it looks like you only reproduced once.

**Comment by stoptakingusernames** [comment]
> Are you sure it's not because of the fact that you need to reproduce 5 times with the organelle? From the screenshot you provided it looks like you only reproduced once.

Right, it seems that I definitely misunderstood what the count was for, thinking it was for the numbers of toxins instead of the reproduction count, that is on me

**Comment by stoptakingusernames** [comment]
The confusion was reinforced by me modifying another toxin organelle back to the oxytoxy NT and the reproduction count being 2 this time

**Comment by hhyyrylainen** [comment]
Good that this was solved.

I can't really think of any way to make the text clearer without making it much longer which would make the unlock conditions tooltip with many items much more unwieldy.
