### ISSUE TITLE
Some organelle icons are cutoff in the Thriveopedia organelle info box

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#5230]
Like this:

![kuva](https://github.com/Revolutionary-Games/Thrive/assets/3796411/bbdd1714-65eb-4c6c-8719-6c611e35bb89)

Probably a case of just using the wrong mode (should be scale to be contained and centered in the GUI element).

**Comment by feithless** [comment]
Sorry about the above -- I didn't realize that making the comments/amending the commit would make posts here.

**Comment by hhyyrylainen** [comment]
It's fine to do it once. Such references don't cause any notification emails or anything like that. Looks like you remade your commit multiple times which is why there's so many references.

**Comment by hhyyrylainen** [comment]
The [PR](https://github.com/Revolutionary-Games/Thrive/pull/5425) was merged but this didn't get closed for some reason...
