### ISSUE TITLE
Thermoplast suddenly becomes available to open in a LAWK game, but it shouldn't be, and there are no thermosynthases

### ISSUE THREAD

**Issue by Teashrock** [Revolutionary-Games/Thrive#5234]
### Describe the bug

I was playing a game in the LAWK mode (which means no thermosynthases or thermoplasts), and everything was fine. I was going to open a chloroplast by using thylakoids, but then I entered the Endosymbiosis screen, where I saw it available to be made from the species I engulfed. I then chose chloroplast, started the process and exited the editor. When I engulfed those species again (thus, progressing the symbiosis) and entered the editor, I saw this:

![image](https://github.com/Revolutionary-Games/Thrive/assets/12483854/34a2c4f8-95f5-4f6e-8eec-710c86d748aa)

Like I said, I'm playing a LAWK game, so thermoplast shouldn't be available. And it wasn't available before. It wasn't saying "x2", and there was only chloroplast to be opened. What's weirder is that it requires thermosynthases to open it, but I don't have any thermosynthases as an option in Proteins section:

![image](https://github.com/Revolutionary-Games/Thrive/assets/12483854/3b5e1873-9e1d-42d6-a816-f0b6bce40ccc)

The above screenshot shows all proteins that are available, so seeing Thermoplast being available without the previous one needed is definitely a bug. That's why I report it here.

### To Reproduce

1. Start a game with LAWK enabled.
2. Play until engulfing a species suitable for endosymbiosis.
3. Enter the editor.
4. Start the endosymbiosis into a chloroplast.
5. Exit the editor, engulf the same species once more, so it turns into a temporary chloroplast.
6. Enter the editor.
7. See the bug.

### Expected behaviour

Thermoplast shouldn't have appeared in the game at all. I've never expected to see it in my run.

### Screenshots

Provided above.

### System information

- OS: Windows 11
- Renderer: Vulkan API 1.3.250
- Graphics card: AMD Radeon Vega 8
- Thrive: 0.6.7

### Game Logs

https://pastebin.com/8PTBgegN

### Additional Context

Here's the save file link: https://www.mediafire.com/file/01e54ikpwr7yky1/Texola_precugolus_thermoplast_bug.thrivesave/file

**Comment by hhyyrylainen** [comment]
Could you provide a save from step 5 so that I could easily go into the editor and see the problem?

**Comment by Teashrock** [comment]
@hhyyrylainen 
Sure, I'll do evetually (not at my PC now). I assume the save file I attached doesn't duit, right?

**Comment by hhyyrylainen** [comment]
Your save might be fine, but when I played it I didn't see thermoplast in the editor, then I exited the editor and engulfed one of the endosymbiosis targets to get that done. Even after placing the endosymbiont I see that chloroplast is unlocked but I do not see thermoplast (or the eukaryotic variant) appearing.

![kuva](https://github.com/Revolutionary-Games/Thrive/assets/3796411/09f1c01d-6510-4884-b366-5bba418def1f)

I checked your log file again and it doesn't look like it has any errors related to this problem, though this is pretty interesting error as I've not seen that before:

```
USER ERROR: Cannot open file 'res://assets/models/organelles/Oxytoxy.shape'.
   at: load (core/io/resource_format_binary.cpp:1187)
USER ERROR: Failed loading resource: res://assets/models/organelles/Oxytoxy.shape. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:274)
USER ERROR: Error loading resource: 'res://assets/models/organelles/Oxytoxy.shape'.
   at: load (core/core_bind.cpp:73)
Physics shape data is not a Shape3D derived type, when loading path: res://assets/models/organelles/Oxytoxy.shape
USER ERROR: Cannot open file 'res://assets/models/organelles/Oxytoxy.shape'.
```

**Comment by Teashrock** [comment]
@hhyyrylainen 
Here's the save:
https://www.mediafire.com/file/sz3nl4wa30nb333/auto_save_12.thrivesave/file

This thing is the species you should engulf:
![image](https://github.com/Revolutionary-Games/Thrive/assets/12483854/d9347da2-424b-4601-9f1b-c5f3eec0bedb) ![image](https://github.com/Revolutionary-Games/Thrive/assets/12483854/efd91d1d-8ed5-492a-9aed-dcbe316b29e5)

**Comment by hhyyrylainen** [comment]
That error is doubly weird as there is no longer anything in the game that refers to "Oxytoxy.shape" the shape file has been renamed. Is this a save that was continued from an earlier Thrive version? If so I'd like to mostly chalk up this bug as having something to do with that.

> This thing is the species you should engulf:

If the endosymbiosis was already started in the other save, there's not another species I could have engulfed, so the bug quite clearly didn't trigger for me for some reason. Could you maybe verify if it happens each time for you (and maybe record a video so that I see the exact things you do)?

**Comment by Teashrock** [comment]
> Is this a save that was continued from an earlier Thrive version?
It is, yes.
> Could you maybe verify if it happens each time for you (and maybe record a video so that I see the exact things you do)?
Okay, I'll do this when I can.

**Comment by hhyyrylainen** [comment]
> It is, yes.

Could you also try starting a new game with 0.6.7 and seeing if the problem happens again? If it doesn't then this is a problem just when continuing an earlier save, and while it could be fixed in theory it's unlikely to be useful as in a few Thrive releases fixing this bug will become irrelevant.

**Comment by hhyyrylainen** [comment]
I'll close this issue so that this doesn't hold back 0.6.8 release, which might be next month, based on the fact that this seems to not be reproducible by anyone else. Feel free to reopen if someone else sees this issue or there is some way to trigger this without loading a save originally made with an older Thrive version.
