### ISSUE TITLE
Physics constraints

### ISSUE THREAD

**Issue by crodnu** [Revolutionary-Games/Thrive#527]
We need the [bullet constraints](http://bulletphysics.org/mediawiki-1.5.8/index.php/Constraints) in order to work on some features (in particular pili and multicellularity), but i'm afraid that seems to be above my abilities (i get crashes when i try it), so i might need some help.

**Comment by hhyyrylainen** [comment]
We need physics constraints

**Comment by hhyyrylainen** [comment]
After engine_refactor this needs to be added to the new engine, here: https://github.com/hhyyrylainen/Leviathan

**Comment by hhyyrylainen** [comment]
Added to the engine.
