### ISSUE TITLE
Organelle Upgrades

### ISSUE THREAD

**Issue by NickTheNick-zz** [Revolutionary-Games/Thrive#528]
Add the ability to upgrade/specialize organelles. 

Will edit this issue as I figure out github's format.

**Comment by hhyyrylainen** [comment]
We most likely will need new gui windows for doing this and new textures for the upgrade buttons etc. I added tags accordingly

**Comment by crodnu** [comment]
except this wouldn't involve c++ but scripts

**Comment by hhyyrylainen** [comment]
Actually, yeah, but I dream of the day when the core organelles are in C++ for the maximum performance.

**Comment by MontySpud** [comment]
Just for clarity

**Comment by Aestra** [comment]
Its your favorite programmer Aestra

**Comment by hhyyrylainen** [comment]
@NickTheNick what's the status on this issue? I moved this to release 0.4.1 milestone as I don't think this will make it in 0.4.0.

**Comment by NickTheNick** [comment]
Yup, it's on hold for now until the update after 0.4.0.

**Comment by hhyyrylainen** [comment]
This needs design work before implementing.

**Comment by hhyyrylainen** [comment]
This basically now depends on: https://github.com/Revolutionary-Games/Thrive/issues/3041
and then it's just a case of thinking up and making the organelle upgrades for (at least a couple of more organelles).

**Comment by hhyyrylainen** [comment]
I'm closing this issue in favour of smaller issues for each individual upgrade that is to be implemented: https://forum.revolutionarygamesstudio.com/t/organelle-upgrades/656/38
