### ISSUE TITLE
Enable sprinting by default (no longer an experimental feature)

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#5284]
This is a meta issue to track when all of these are done:
- [x] https://github.com/Revolutionary-Games/Thrive/issues/5278
- [ ] https://github.com/Revolutionary-Games/Thrive/issues/5279
- [x] https://github.com/Revolutionary-Games/Thrive/issues/5280
- [ ] https://github.com/Revolutionary-Games/Thrive/issues/5281
- [x] https://github.com/Revolutionary-Games/Thrive/issues/5283
- [x] https://github.com/Revolutionary-Games/Thrive/issues/5282

**Comment by TheESN** [comment]
Shouldn't be some issues closed as completed here now?

**Comment by hhyyrylainen** [comment]
Which ones? I think #5280 is done, and perhaps #5283 but I'm pretty sure none of the others are.

**Comment by TheESN** [comment]
What about #5279? Didn't #5293 adressed it?

**Comment by hhyyrylainen** [comment]
I think it maybe only partly did, @CI09 ? I thought it only made the AI sprint when in danger, but the AI is not able to for example use it to attack a target that is slightly faster than it.

**Comment by CI09** [comment]
It attached piece of code to EngagePrey so theoretically it should also attack with sprint. Sorry for not putting it in PR name.

**Comment by hhyyrylainen** [comment]
Alright then https://github.com/Revolutionary-Games/Thrive/issues/5279 is depending on a bit of testing / verification of the AI behaviour.

**Comment by hhyyrylainen** [comment]
I'll close this as the sprinting is enabled by default, but there's still the AI improving and sprinting balancing issues open.
