### ISSUE TITLE
Process System Panel

### ISSUE THREAD

**Issue by NickTheNick** [Revolutionary-Games/Thrive#531]
As discussed in this thread: http://forum.revolutionarygamesstudio.com/t/process-menu-and-new-help-panel/391/8

We are adding a new panel to explain the processes in the game. I know there are other links that explain this to so please post if you find them. 

This has been started on a branch: https://github.com/Revolutionary-Games/Thrive/tree/531_process_panel

**Comment by hhyyrylainen** [comment]
This should also be started soon (see my comment in: https://github.com/Revolutionary-Games/Thrive/issues/532)

**Comment by Untrustedlife** [comment]
Started soon? Its for 4.1 though.

**Comment by hhyyrylainen** [comment]
One note from discord: this panel is meant to open with the test tube button in the microbe stage GUI.
It should probably have similar info to what I proposed in this issue: https://github.com/Revolutionary-Games/Thrive/issues/1399

**Comment by hhyyrylainen** [comment]
I started on a branch doing some background stuff for this: https://github.com/Revolutionary-Games/Thrive/tree/531_process_panel
