### ISSUE TITLE
Help Panel

### ISSUE THREAD

**Issue by NickTheNick** [Revolutionary-Games/Thrive#532]
As discussed in this thread: http://forum.revolutionarygamesstudio.com/t/process-menu-and-new-help-panel/391/8

We are adding a help section to the game as a precursor to a sort of "Thriveopedia".

**Comment by crodnu** [comment]
Duplicated issue :/

**Comment by NickTheNick** [comment]
Yeah I did this in case we wanted to keep conversations on them separate.

**Comment by crodnu** [comment]
Oh i didn't notice the different titles, my bad. The descriptions were the same and i got confused xD

**Comment by hhyyrylainen** [comment]
Work should be started on this in engine_refactor (in a few days when I hopefully get the GUI situation sorted out).

**Comment by Untrustedlife** [comment]
Can we close this?

**Comment by hhyyrylainen** [comment]
Only half done, it doesn't show the names of species you hover over.

**Comment by hhyyrylainen** [comment]
This hasn't been even started.

**Comment by hhyyrylainen** [comment]
I think this is now definitely done.
