### ISSUE TITLE
Materials uploading error

### ISSUE THREAD

**Issue by NickTheNick** [Revolutionary-Games/Thrive#534]
It appears that we can inport meshes from blender but materials don't get ported properly. In theory you can "tweak" the materials **A LOT** to get them looking proper, but it's difficult to do that. The sooner we can fix this the sooner we can start uploading new graphics.

**Comment by hhyyrylainen** [comment]
I'd say a better approach would be to read the Ogre manual and write materials based on that instead of trying to get the material settings to export correctly from blender. 
I'm not sure how exactly the same the exported objects would look like even with correctly exported settings so it might not even be feasible to use blender to tweak the look of objects.

**Comment by crodnu** [comment]
I noticed a lot of our old meshes use textures, maybe that's how it was done before?
I just dont think it's really feasible to have an experienced programmer to do the materials too, there has to be a way for a modeller to do it somehow...

**Comment by hhyyrylainen** [comment]
Usually games have dedicated graphics programmers. 
Maybe we should try to get one of them to join our team.

**Comment by NickTheNick** [comment]
@crodnu : Would you be able to test or find someone to test the Ogre method of writing materials?

@hhyyrylainen : I was planning to do a little bit of outreach now that the engine is switched but the game features need to be ported over. I could fashion some of the ads to be targetted towards graphics programmers.

**Comment by crodnu** [comment]
When i said "experienced programmer" i was excluding myself... i don't have any experience and barely any knowledge of shader programming, and i don't think i'll have a lot of time in the nearby future to learn how to do it (after all, we should start adding new features to Thrive someday xD).
And sadly i don't know anyone that would be willing to join the dev team.

**Comment by NickTheNick** [comment]
In that case I think advertising for a graphics programmer with knowledge on programming shaders and materials would be our best bet. I'll post a draft of the advertisement later today.

**Comment by TheCreator--** [comment]
So as the graphics programmer on duty, let me explain how materials work in Ogre. Ogre uses its own material language which allows you to incorporate shaders in HLSL, GLSL, and CG. So any shader written in one of these 3 languages will work with Ogre. Unfortunately, Blender does not export materials in any of these formats and instead uses the Cycles rendering engine (or Eevee now, I guess). So how do we get around this? Well, there are 2 main ways. The easy way is to simply "Bake to texture" in Blender. This allows you to save all of the lighting, reflections, and other material properties into a few textures, which can then be trivially layered in Ogre. Unfortunately, this works ideally only for solid, nontranslucent materials. Anything more complex and, while it will look good from one particular angle, your texture will look flat and fake. Now the second option is how it is actually done in the industry. You write a separate application that allows you to import models from your game into an editor, where you use nodes or whatever to create your material. Then, this tool outputs a GLSL/HLSL file (which is basically a combination of preexisting, written shaders). Obviously, this will be too difficult a task for us to achieve, so its really out of the questions. The only solution is then to just bake to texture for simple models and have someone write the material for more complex models.

**Comment by hhyyrylainen** [comment]
I've now gotten a simple model imported to the game (in engine_refactor). So the solution to this is "we need a graphics programmer" to do shaders and materials as the exporter can't do them.
