### ISSUE TITLE
Can't download assets

### ISSUE THREAD

**Issue by alexban011** [Revolutionary-Games/Thrive#536]
Hi, i tried downloading thrive's assets but it seems like the site is not responding. Was it changed? 
I followed the steps in the readme but when i got to the step where i have to download the assets tortoisesvn gives me an error. I tried to do a ping command on the url and it says it timed out.

**Comment by hhyyrylainen** [comment]
The old svn has indeed shutdown. It was planned that it would be taken offline after the engine_refactor is merged, as that uses a new svn server. But it seems that it went down already (it was managed by an inactive team member).

The new svn server has the assets in different folders and there are some changes. So the best way to get assets would be to copy the assets folder from a thrive release. Hopefully that works as I'm not sure if changes were made to the assets after the latest release.

**Comment by Oliveriver** [comment]
Should the link in the master README be changed to stop this happening?

**Comment by hhyyrylainen** [comment]
@Oliveriver updating just the link won't work as the assets have changed. Adding my earlier comment as a note might work, but even if people can get the master branch compiling it is also broken (neither me or crodnu could make it run properly to do a release).

**Comment by hhyyrylainen** [comment]
The documentation has now been updated in the engine_refactor branch.
