### ISSUE TITLE
Improvements for colour blind players

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#538]
It's hard for colour blind players to distinguish a few of the compound clouds.

Suggested fixes:
- we should have an info box in one of the corners that shows what the player is hovering their mouse over (this is a good idea in general)
- It may be possible to get fully automatic fixes to any part of the game using filters. As described here: we should have an info box in one of the corners that shows what the player is hovering their mouse over https://tylerdavidhoward.com/thesis/ and there's this implementation of that: http://blog.noblemaster.com/2013/10/26/opengl-shader-to-correct-and-simulate-color-blindness-experimental/

**Comment by Untrustedlife** [comment]
Work was started on this, as we now have a readout of what compounds are where.

**Comment by hhyyrylainen** [comment]
This: https://github.com/Revolutionary-Games/Thrive/issues/566 is the progress @Untrustedlife is talking about.

**Comment by GatoCreador887** [comment]
I am somewhat colorblind myself, so I shall give some input:
Often hydrogen sulfide and ammonia look similar enough to me that I use the info box to tell which one it is.
