### ISSUE TITLE
Missing visual studio redistributables

### ISSUE THREAD

**Issue by Pull32423** [Revolutionary-Games/Thrive#539]
MSVCR120.dll was not found

**Comment by hhyyrylainen** [comment]
You are probably missing the specific visual c++ redistributable version.

For the next release we should verify that we include the right one. Or add support in the launcher to automatically install the right version once.

**Comment by hhyyrylainen** [comment]
So now I think that file is included but one player reports that:
There is an issue with missing `api-ms-win-crt-runtime-l1-1-0.dll`. This might be from the chromium precompiled dlls. 
The packaging script should be edited to include this.

Users should be able to work around this by downloading it from here: https://www.microsoft.com/en-in/download/details.aspx?id=48145

**Comment by hhyyrylainen** [comment]
I saw at least one error mentioning: libgcc_s_dw2-1.dll
This might be because ffmpeg is built with gcc on Windows. So that library should also be bundled in?
It's strange that there has been only one person with this issue.

**Comment by hhyyrylainen** [comment]
One new user had issues similar to this. Downloading the 2015 redistributables fixed it(https://www.microsoft.com/en-us/download/details.aspx?id=52685)

This is probably because we use a prebuilt CEF and that is probably made with that.
A solution is needed for making sure users have that also installed.

**Comment by hhyyrylainen** [comment]
The situation is that we have the 2017 redistributable properly included (but probably) because of CEF the players need to manually install 2015. I'm going to remove this from the milestone as this is kinda done.
