### ISSUE TITLE
Input actions with a modifier and an icon representing them in the inputs menu doesn't display the modifier at all

### ISSUE THREAD

**Issue by CI09** [Revolutionary-Games/Thrive#5396]
![image](https://github.com/user-attachments/assets/1d7071a6-98f0-4719-b61c-b76f70a50637)

Edit by hhyyrylainen: it looks like to me like the modifier isn't added when an icon can be generated for the action, so the bug is likely in the code generating that image then not adding text before it.

**Comment by hhyyrylainen** [comment]
Could you clarify the title a bit because I'm pretty sure the bug is specifically when there's a graphical display for the key, like mouse wheel, because I'm sure that "Shift+A" binding does show up correctly?

**Comment by hhyyrylainen** [comment]
I added the example image and further put in some initial analysis on this issue.

**Comment by hhyyrylainen** [comment]
There's quite a bit of extra spacing but I guess this should for now not be even seen by anyone, and I guess that spacing is mostly caused by the icon being a square:

![2024-08-28_15 01 24 7907](https://github.com/user-attachments/assets/c3c270e1-fdcc-4e26-a7d9-eefb316a02ca)
