### ISSUE TITLE
Process toggle buttons sometimes don't match process state

### ISSUE THREAD

**Issue by dligr** [Revolutionary-Games/Thrive#5420]
I was able to find two cases when this happens:
1. When exiting editor with a new organelle, the process speed of which is immediately zero (because of having no needed compound or something like that). For example, placing rusticyanin while having no iron or thylakoids in a patch with no light. The process is shown as turned off. After gathering needed resources, however, the process starts to run (the button still shows it as turned off).
2. If a process was manually turned off, it starts to run again after an editor session. However, it is still shown as turned off.

Picture after exiting editor and getting resources required for processes to run:
![image](https://github.com/user-attachments/assets/9f9f4fe0-25ad-441c-b4b4-26331a378ee8)
Some processes run, even though they are turned off.

**Comment by hhyyrylainen** [comment]
Good finds, I put this in the 0.7.1 milestone as this doesn't seem super critical and might take away from fixing much more immediately visible bugs for 0.7.0 release (but if you opened this issue as you wanted to work on this, you are totally free to do so).
