### ISSUE TITLE
Reimplementing editor showing organelles

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#543]
This issue is part of engine_refactor.

The editor hasn't been started and it needs to be reimplemented.

**Comment by Untrustedlife** [comment]
if whoever does this also adds a way to change cell color in the editor that would be awesome.

**Comment by hhyyrylainen** [comment]
I think there are only 2 critical things left:

- [ ] show organelle models in addition to the hexes in the editor
- [ ] make sure that deleting organelles work (I think it is currently broken)

Then some nice to have things are left like making the situation with the hover hexes fixed (the placed organelles should have specifically created hex entities for them instead of taking the hover hexes and possibly running out).

**Comment by hhyyrylainen** [comment]
Showing models is not so critical so I moved this to 0.4.1

**Comment by Untrustedlife** [comment]
All thats left is showing organelles

**Comment by hhyyrylainen** [comment]
This has been complete for a while.
