### ISSUE TITLE
Behaviour editor has slightly broken layout (in Godot 4)

### ISSUE THREAD

**Issue by TheESN** [Revolutionary-Games/Thrive#5431]
Looks like it happened during switch to Godot 4

Sidenote: I also noticed that species name is not in cursive anymore and green arrow looks weird now

That's how it looks now
![изображение](https://github.com/user-attachments/assets/fc7ac7fb-6e9a-4aed-9517-62b7db8b1be3)

That's how it looked before
![изображение](https://github.com/user-attachments/assets/da322d2a-6e47-4dbf-a20e-70bfb76fc010)

**Comment by hhyyrylainen** [comment]
I can't fix the arrow but the other stuff is probably pretty quick to fix in Godot by reapplying the styles that the Godot version converter couldn't keep.

**Comment by hhyyrylainen** [comment]
The vertical alignment I assume? Which looks slightly different in the screenshots.

**Comment by TheESN** [comment]
The one which is inside purple bar

**Comment by hhyyrylainen** [comment]
Yeah, the mutation points is inside a purple bar background. What I wanted to confirm is that the alignment that is wrong is the vertical one, because to my eyes the horizontal alignment looks fine.

**Comment by TheESN** [comment]
Yeah it's vertical one. Also btw I noticed that numbers of ATP bars are in the wrong place

**Comment by hhyyrylainen** [comment]
If the numbers are properly aligned, it is not a problem if they are slightly in a different place. The game doesn't have to always look the exact same as older versions.

**Comment by hhyyrylainen** [comment]
The vertical alignment of the text is already set to center, so there's no easy way to fix that. I'll make a PR from fixing the behaviour editor text alignment and the name box italic font and mark it as closing this.
