### ISSUE TITLE
Art Gallery doesn't disable main menu shader when viewing 3D models

### ISSUE THREAD

**Issue by TheESN** [Revolutionary-Games/Thrive#5433]
![изображение](https://github.com/user-attachments/assets/00a4b676-df2d-4ca5-9fb6-13bb7ad43b64)

**Comment by hhyyrylainen** [comment]
Duplicate of: https://github.com/Revolutionary-Games/Thrive/issues/5112
which has the root cause that the model viewer doesn't have its own world environment but inherits whatever the main menu scene is loaded.

**Comment by TheESN** [comment]
My bad, didn't notice
