### ISSUE TITLE
Background scrolling is broken

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#544]
I fixed the weird looking background but still all of the layers scroll at the same speed so there is no parallax effect.

This may be an Ogre bug.

**Comment by hhyyrylainen** [comment]
I just realized that in Ogre 2.1 multipass materials no longer work. So the background material and shader needs to be rewritten to combine the 4 layers in a single pixel shader pass to fix this.

**Comment by hhyyrylainen** [comment]
@Untrustedlife Isn't this working now?

**Comment by Untrustedlife** [comment]
Yep

**Comment by Untrustedlife** [comment]
it works fine now :)
