### ISSUE TITLE
Process equation arrow should be aligned lower to not look like it is top aligned

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#5454]
![kuva](https://github.com/user-attachments/assets/4f31cb95-980b-44a4-8455-a2e12c251dfe)

The left to right arrow there should be quite a few pixels lower to make it look good

**Comment by jonesleah** [comment]
I can fix this!

**Comment by hhyyrylainen** [comment]
Absolutely, please feel free to work on this. Once done, you can open a pull request and someone will review your changes.
