### ISSUE TITLE
[Suggestion] Add music selector in auto-evo explore tool

### ISSUE THREAD

**Issue by TheESN** [Revolutionary-Games/Thrive#5462]
Listening 2 repeating main menu music tracks in this tool can annoy after some time. I think it would be nice to give ability to player to select any music from the game in this tool

**Comment by hhyyrylainen** [comment]
This is a suggestion rather than a real bug so I'll close this on those grounds. You can repost this to: https://suggestions.revolutionarygamesstudio.com/
