### ISSUE TITLE
Increase minimum cell size for engulfing chunks

### ISSUE THREAD

**Issue by HexapodPhilosopher** [Revolutionary-Games/Thrive#5468]
Increase the minimum size a cell needs for it to be able to engulf whole floating chunks.

**Comment by hhyyrylainen** [comment]
More important than this would be increasing the size of the phosphate chunks, as that's the one that someone complained was unbalanced (in comparison no one has ever been unhappy about being able to engulf the big iron).

**Comment by hhyyrylainen** [comment]
I'll assume this is enough: https://github.com/Revolutionary-Games/Thrive/pull/5540
