### ISSUE TITLE
Fix compound clouds

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#551]
The compound clouds need to be fixed to look the same as before and the absorbing needs to be fixed. I also haven't made the clouds spawn around the player (currently there is just one cloud entity at 0,0,0) and the spawn system doesn't randomize the cloud coordinates so they also spawn at 0,0,0.

This is one of the last major issues in engine_refactor.

- [ ] Clouds work
- [ ] Spawn rate has been tweaked

**Comment by Untrustedlife** [comment]
Ill play with mirroring after i mow the lawn after i get home tonight

**Comment by hhyyrylainen** [comment]
This sort of maybe works now. Except of course the clouds only spawn near the origin so once they are confirmed to be fully working I'll do a system where new containers for the clouds are spawned around the players and see why the clouds always have coordinates 0, 0 when spawning.

**Comment by hhyyrylainen** [comment]
Currently it seems that the cloud scaling is off (the orientation of the cloud seems correct).
As the glucose spawn cheat spawns farther from the cursor the farther you are from 0,0.
And dynamically spawning the cloud entities as the player moves isn't done.

**Comment by Untrustedlife** [comment]
What is the status on this issue ytou think @hhyyrylainen ?

**Comment by hhyyrylainen** [comment]
I think it's good. We can do final balancing without having any issues open.
