### ISSUE TITLE
Reimplement AI

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#552]
The old AI from Lua is so complex in it's use of random tables and caching entities (which doesn't work the same way as before) that it needs to be rewritten, preferrably so that it is even better.

The other major issue left in the microbe stage for engine_refactor (there's of course still the editor left to do).

**Comment by hhyyrylainen** [comment]
The new AI should also be made to fix this issue: https://github.com/Revolutionary-Games/Thrive/issues/190

**Comment by Untrustedlife** [comment]
i feel like this is kinda impeded until compound cloud absorption actually works properly.

**Comment by Untrustedlife** [comment]
assigned myself to this, we need some other stuff for the full implementation (compound clouds for example) but at least we can get predator prey mechanics implemented.

**Comment by hhyyrylainen** [comment]
Even without compound cloud gathering it wouldn't be worse than in the previous version as that also completely ignored compound clouds.

**Comment by Untrustedlife** [comment]
Yeah thats fair, we will also need AI for 3 different methods of predation, pilus stabbing, toxin shooting, engulfment, this is where the aggression variable comes in, a predator should be more or less afraid to attack a particular cell based on their fear, aggression, their size, and the prey's size. And sometimes you shoudkl get interesting things, like  a hyper aggressive flagellated bacteria species that kills you via thousands of papercuts.

**Comment by Untrustedlife** [comment]
I'll be working on getting toxy shooting working, i think we should close this issue and create one more issue for pilus AI.

**Comment by Untrustedlife** [comment]
we should also open up an issue for run and tumble

**Comment by Untrustedlife** [comment]
The ai is done, all tahts left is runa nd tumble and we cant do that until compound clouds work.

**Comment by hhyyrylainen** [comment]
I'd like to leave this open until the code is actually complete. I'll add the impeded tag.

**Comment by Untrustedlife** [comment]
https://github.com/Revolutionary-Games/Thrive/commit/9e3deb53c28636665d9ed71ad0db1fd9acf432ad

It is now implemented
