### ISSUE TITLE
Remove oxygen and CO2 clouds

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#553]
As discussed here: https://forum.revolutionarygamesstudio.com/t/compound-rebalancing/386/22 they should be properties of a biome and not individual clouds.

- [x] Remove the oxygen and CO2 (+ Fatty Acids and Amino Acids) bars from the GUI
- [ ] Add an indicator for environmental oxygen and CO2 to the GUI
- [x] Add the property to the biome class in c++ and add loading of that property from the json files
- [x] Put some initial values to the json configuration (it should be scaled so that amount of 1 doesn't affect a process' speed, lower than 1 slows it down and higher than 1 speeds it up, initially the speed could be just multiplied by this if a process needs oxygen or CO2). This means about values of environmental oxygen and co2.
- [x] MOVED: https://github.com/Revolutionary-Games/Thrive/issues/570 It should be possible for the cell species to affect the amount of oxygen and CO2 (photosynthesisers) 
- [ ] Modify the process system ~~and the compound absorbing / releasing~~ to work with the environmental oxygen and CO2

**Comment by Untrustedlife** [comment]
For this issue The only parts left are:
- [ ] Add an indicator for environmental O2 and CO2 to the GUI
- [ ] It should be possible for the cell species to affect the amount of oxygen and CO2 (photosynthesisers) 
- [ ] Modify the process system and the compound absorbing / releasing to work with the environmental oxygen and CO2

**Comment by Untrustedlife** [comment]
What i posted is whats left, everything else is done, because i did all that already and its in fix_everything
We could move it to a new issue, but i dont see the point

**Comment by Untrustedlife** [comment]
I suppose though if it feels like it should be

**Comment by hhyyrylainen** [comment]
I edited it to be clear that the config meant about the environmental oxygen levels and also "It should be possible for the cell species to affect the amount of oxygen and CO2 (photosynthesisers)" is perhaps suited to be in a later issue.

**Comment by Untrustedlife** [comment]
Yeah those values are in the code now, look at the json and look at the biome code.

**Comment by Untrustedlife** [comment]
it even loads the oxygen and co2 per biome lol

**Comment by Untrustedlife** [comment]
We should add a temperature gauge to the GUI aswell

**Comment by Untrustedlife** [comment]
I suppose i can tackle this right now.

**Comment by Untrustedlife** [comment]
Fixed in #713
