### ISSUE TITLE
Individual Compounds

### ISSUE THREAD

**Issue by TjWhale** [Revolutionary-Games/Thrive#555]
The player can currently swim through a cloud of ammonia, become clogged with it and unable to breathe.

#Soln: Moving to individual compounds. That means each compound has its own storage which is separate from all the others. Taking @Untrustedlife ’s numbers as a starting place each cytoplasm will store 5 of each compound, each vacuole will store 25 (this will mean the current starter cell will have approx 100 storage as it does now).

**Comment by Untrustedlife** [comment]
I believe i added storage to cytoplasm, of course since clouds dont work properly yet, this is a bit harder to work out until we have that part done.

**Comment by Untrustedlife** [comment]
Fixed in commit:
https://github.com/Revolutionary-Games/Thrive/commit/6156cb1f5e3afe128efee7589b315b5bf807b193
and the ones before it

**Comment by Untrustedlife** [comment]
Someone else can confirm this, and re-open if they dont belive its fixed, but im sure its fixed .
