### ISSUE TITLE
Simplify Health System

### ISSUE THREAD

**Issue by TjWhale** [Revolutionary-Games/Thrive#556]
it is really painful to be close to unlocking the editor and then to be hit by a toxin X and have to recharge health before continuing with editor progress. 

Soln: Health to be separated from reproduction. Each cell will get 100 health when spawning and each time they are damaged they will lose a little. Health will regen at 1% per second. This is only a placeholder for a better health system which we can discuss in the future.

**Comment by Untrustedlife** [comment]
Ill probably hit on this after engulfing works (because damaging actually causes an error right now so i might as well change it, and fix it at the same time.

**Comment by Untrustedlife** [comment]
Did this
