### ISSUE TITLE
Basic win / lose conditions

### ISSUE THREAD

**Issue by TjWhale** [Revolutionary-Games/Thrive#558]
The game doesn’t really feel like a game, I often end up just swimming aimlessly around.

Solns:

A. The first population system to be added. You will start the game with 50 population. Each time you die you will lose 10 population, each time you exit the editor you gain 30 population. If your pop reaches 0 then the game is over.

B. If you survive for 15 generations a text pop-up comes onto the screen congratulating you for being a survivor.

**Comment by hhyyrylainen** [comment]
This is almost done after merging https://github.com/Revolutionary-Games/Thrive/pull/597
This just needs a few different bits:
- [ ] dying needs to work properly
- [ ] there needs to be a lose condition that stops the game

**Comment by Untrustedlife** [comment]
I assigned you this 1n

**Comment by Untrustedlife** [comment]
The lose condition now strops the game, i think we can close this.

**Comment by hhyyrylainen** [comment]
Do we already have the win text working as well?

**Comment by Untrustedlife** [comment]
Yep winning works: 
![image](https://user-images.githubusercontent.com/4032123/47684684-b7858a80-dba1-11e8-98e0-afec6240c360.png)
