### ISSUE TITLE
Add basic pilus 

### ISSUE THREAD

**Issue by TjWhale** [Revolutionary-Games/Thrive#559]
A pilus to be added to the game: if it touches another cell that cell will take some damage.

**Comment by Untrustedlife** [comment]
We need the cone collision support, after that it should be eaasy to implement assuming the physics engine switch doesnt totally break our collisions (and then we would have to fix those again ugh)

**Comment by Untrustedlife** [comment]
I suppos ei might aswell work on this. Ill need the model and a cone collision, perhaps keep this in mind @hhyyrylainen with the switching of the physics engine
