### ISSUE TITLE
Rework compounds and process system

### ISSUE THREAD

**Issue by TjWhale** [Revolutionary-Games/Thrive#560]
Phosphates and Hydrogen Sulphide to be added as compound clouds.

Chemoplasts to be added as an organelle. Toxin glands and chloroplasts will also be unlocked for the player to use in the editor.

The process system to be cut down to the following scheme, each second:

each cytoplasm will take 1 glucose and turn it into ATP
each mitochondria will take 6 glucose and turn it into ATP
each chemoplast will take 4 hydrogen sulfide and turn it into glucose
each chloroplast will make 2 glucose
each flagella, when operating, will use 3 ATP 
if there are both ammonia and phosphates in storage 1 of each will be taken and used to grow the cell. once growth hits 100% the editor button will be unlocked.

**Comment by hhyyrylainen** [comment]
@NickTheNick mentioned in the update that the compounds should start in "primordial soup" mode. So that is related to this issue, I think.

**Comment by Untrustedlife** [comment]
I did a good portion of this, in my last few commits where i added the two new compounds and changed the proces values.
The only thing left is The chemoplasts.
WHich i think would be a "good first issue"

**Comment by hhyyrylainen** [comment]
Also, I think the process system might be a bit broken (and balancing will definitely need to happen) but that will have to wait until the compound clouds work again.

**Comment by Untrustedlife** [comment]
I think that the process numbers are wrong (they dont comply to this exactly, also it isn't very clear, sure take 6 glucose and make it atp, but how much atp, etc. ), but it should be easy enough to make them conform to this :)

**Comment by TjWhale** [comment]
I think the process system does need quite a lot of work. I think, I may be wrong, that it's based on a supply and demand model with variable process rates based on how much of each compound is available.

I want to move to a system where it's just continually working at a constant rate. So if your glucose store is not full then a chloroplast will make a little glucose each second, at a constant rate. This will be much simpler and easier to build on.

**Comment by Untrustedlife** [comment]
Individual compounds is done, also after playing around with that, the phosphate/ammonia numbers for growth of organelles are not good, because they get fully grown almost instantly, so we probably need to make it so it cost s"more" to grow organelles.

**Comment by hhyyrylainen** [comment]
Or balance the clouds. But we shouldn't think about that before everything else is working again.

**Comment by Untrustedlife** [comment]
This is done now, however there are still some issues with the process code (i need to make sure, for example that it doesnt add too many compounds to your cell  (where you would go over storage)) so im not closing this just yet.

**Comment by Untrustedlife** [comment]
Okay, it is done.
