### ISSUE TITLE
Reimplement GUI

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#561]
The GUI was switched to HTML and needs to be reimplemented.

- [x] Bars need to be remade
- [x] Add icons for all the compounds (and editor and the compounds panel toggle buttons)
- [x] Make the pause menu work again and add all the help etc. there
- [x] The editor needs to be remade

**Comment by Untrustedlife** [comment]
I like how "remake the editor" is part of this issue.

**Comment by Untrustedlife** [comment]
I fixed the compound bar display so they dont get smashed together anymore

**Comment by Untrustedlife** [comment]
![image](https://user-images.githubusercontent.com/4032123/41326436-971d2d28-6e84-11e8-9ded-11075f19daae.png)

**Comment by Untrustedlife** [comment]
suicide button now works

**Comment by hhyyrylainen** [comment]
There are just some random screens and some buttons etc. that need to be implemented.

**Comment by Untrustedlife** [comment]
All thats left here is the editor correct?

**Comment by hhyyrylainen** [comment]
If I remember correctly I left this open because the help text (when you press the help button) is improperly aligned. Other than that I think that all the parts of the GUI are in the game but don't have logic implemented for them.

**Comment by Untrustedlife** [comment]
Okay, ill align the help text when i have a chance and close this when i do then

**Comment by Untrustedlife** [comment]
I fixed the issue with the helptext, can we close this now?
