### ISSUE TITLE
Flesh out the bacteria

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#565]
The implemented bacteria is a bit basic so this issue is a place holder issue for when improvements to it are decided and can start to be implemented.

**Comment by Untrustedlife** [comment]
Did a tad bit of this in my branch
https://github.com/Revolutionary-Games/Thrive/tree/768_and_737

**Comment by hhyyrylainen** [comment]
Let's just close it, and let people come up with concrete ideas to implement instead of keeping such a generic issue open.
