### ISSUE TITLE
Add panel to show what is under the cursor

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#566]
Add a panel to some corner (and make it toggleable) which shows all compounds and cells (including the player) that are under their mouse. So the player can check what compounds are in a cloud and how much and see what species some cell is.

**Comment by Untrustedlife** [comment]
this is a great idea

**Comment by Untrustedlife** [comment]
Moved to 4.0 because it is already half implemented and we needed a "training" issue

**Comment by Untrustedlife** [comment]
Now how do we make this grab cell species names..hmmm

**Comment by hhyyrylainen** [comment]
This is now done by: https://github.com/Revolutionary-Games/Thrive/commit/b4d8017f69b6373849dfc4c2d20f81168813eecf

It just doesn't show the fancy generated names because of this: https://github.com/Revolutionary-Games/Thrive/issues/599

![panel](https://i.imgur.com/fkgLcJE.png)
