### ISSUE TITLE
Error deleting main menu layout

### ISSUE THREAD

**Issue by Diadlo** [Revolutionary-Games/Thrive#568]
OS: Linux
When I try to start application I have this error message: "Error deleting main menu layout: Permission denied". It works with `sudo` but this is exactly wrong

**Comment by Kevin-Lu311** [comment]
No offense but maybe you should post bug reports here: https://community.revolutionarygamesstudio.com/c/bug-reports or in the discord.

Making a new github issue everytime you find a vague bug able to be caused by a variety of things is not the best way to go about.

**Comment by Mao5811** [comment]
No offense but maybe you should post bug reports here: https://community.revolutionarygamesstudio.com/c/bug-reports or in the discord.

Making a new github issue everytime you find a vague bug able to be caused by a variety of things is not the best way to go about.

**Comment by hhyyrylainen** [comment]
I would like to know further details about this like where is the error printed. Either here or on our forums (use the link that Mao posted).

**Comment by Diadlo** [comment]
@hhyyrylainen It's error from stdout

**Comment by hhyyrylainen** [comment]
Which version? The latest release or did you compile master or fix_everything? Did you run thrive as `./Thrive` in the build/bin folder. Also I tried with grep and I can't find that message anywhere in our code base.

**Comment by Diadlo** [comment]
1. Version is v0.3.4
2. Installed from [AUR](https://aur.archlinux.org/packages/thrive/)
3. It downloads archive from github [release page](https://github.com/Revolutionary-Games/Thrive/releases/download/v0.3.4/)
4. After install just have typed `thrive` and have 2 lines. The first is an error from #513 and the second is "Error deleting main menu layout: Permission denied"

**Comment by hhyyrylainen** [comment]
@Diadlo that's an unofficial release. 

In the previous version and also in the latest version (I plan to change this at some point) thrive writes logs etc to the current directory and the current directory must be the one that has the Thrive executable in it. So if you install it system wide (as I guess that package does) to a place where you don't have write access you get that access denied error.

**Comment by Diadlo** [comment]
@hhyyrylainen Ok. Thanks
