### ISSUE TITLE
Re-implement Faux-scientific Name Generator for species

### ISSUE THREAD

**Issue by Untrustedlife** [Revolutionary-Games/Thrive#569]
This is part of a Training issue for Citrusite

Species need mildly  comprehensible names for later use In numerous differnet systems.

Species need two new string variables that should be accessible in both the angel script and the c++ code:
Genus
Epithet 

These names need to be randomly generated so we should end up with species as such, this is just one example:
Primum (Thats our epithet)  Thrivieum (Thats our genus name)
https://en.wikipedia.org/wiki/Binomial_nomenclature Useful link, also looking at scientific names for other species would also be informative

The old prefix and suffix lists can be found here,
https://github.com/Revolutionary-Games/Thrive/blob/fix_everything/scripts/SimulationParameters/MicrobeStage/SpeciesNames.json

you could either move it out of the json and into the angel script, or keep it in the json (plenty of json code examples in biome.cs for example)  (this should NOT be generated in the c++, as it is something that should be moddable and c++ is for more generic things):

**Comment by Untrustedlife** [comment]
If you want to go really crazy you can make  so that when a new genus splits off it gets a new genus name (there is a comment in the code that tells you where a genus is splitting, right now that code just gives the species a new color when it splits into a new genus) .
Or having separate name generators for bacteria/normal species. But of course these arne't nessessary  just get it working for now :)

**Comment by Untrustedlife** [comment]
Really hoping we can get someone to do this

**Comment by hhyyrylainen** [comment]
This isn't a blocker bug but would be nice to have.

**Comment by Untrustedlife** [comment]
finished
