### ISSUE TITLE
Game close sometimes

### ISSUE THREAD

**Issue by AndreLZGava** [Revolutionary-Games/Thrive#571]
Sometimes game close automatically, behaviour is like I had press esc and than exit to desktop, but I didn't did that. I'm using windows 7

**Comment by hhyyrylainen** [comment]
The game is set to quit after a Lua error (in the current version). You need to use the launcher or run the game from cmd.exe to see the error output. The new version will have actual log files and will ignore non-fatal script errors.

**Comment by Untrustedlife** [comment]
If this is fixed why is it still open?

**Comment by hhyyrylainen** [comment]
This is open because this needs to be verified as fixed. I recently got 2 physics crashes with the latest version so I'll keep this open until the random crashing has been verified to be (mostly) gone.
