### ISSUE TITLE
Auto Save

### ISSUE THREAD

**Issue by AndreLZGava** [Revolutionary-Games/Thrive#573]
Please implement autosave. Users may like to recover that time when the game had the best moment (life or ATP). I 'm playing this game for 2 hours and I had to start it over and over beacause some bugs, unexpected behaviour or died

**Comment by hhyyrylainen** [comment]
This can be done once saving is reimplemented. That's why this is an "easy" issue.

There should also be configuration options for the interval.

**Comment by hhyyrylainen** [comment]
I've basically already added the points that would trigger autosave, but the actual logic is not implemented.
