### ISSUE TITLE
Please implement modes like easy, normal and hard

### ISSUE THREAD

**Issue by AndreLZGava** [Revolutionary-Games/Thrive#575]
There are many enviroments when playing the game, it seems that many of them are harder to survive. It's too hard, sometimes resources like oxygen, amonian and glicogene aren't find soo quikly, and they are spent very fast.

**Comment by crodnu** [comment]
Hi Andre!
We appreciate your suggestions, however this is not the place to submit them.
This place is used to divide work on our team on already thougth out features for the next release.
If you want to make suggestions, please join our [community forum](https://community.revolutionarygamesstudio.com) and open a new thread about it.

**Comment by hhyyrylainen** [comment]
I'm willing to accept technical issues etc. here as github issues. But @crodnu is right that any suggestions etc. should be brought up somewhere else.

**Comment by hhyyrylainen** [comment]
I'll open this because it has been discussed before that there should be difficulty options in the game. But I won't put this into any milestone yet. This also depends on a future issue for specifying the options for a new game.

**Comment by AndreLZGava** [comment]
Ok, I created a account in the site and add it as a topic of game in the future. I hope you implements it in the game, would be great :)
