### ISSUE TITLE
Leviathon: can't compile pong server

### ISSUE THREAD

**Issue by CrackerHax** [Revolutionary-Games/Thrive#577]
Leviathon can't find cef or ffmpeg files (which are definitely there)
Ubuntu 16

compile log:
https://pastebin.com/Dq6ngUAf

**Comment by hhyyrylainen** [comment]
How are you compiling it?
To me it looks like that libEngine.so fails to link against: ffmpeg, cef and cAudio and that causes everything to fail to compile.

**Comment by CrackerHax** [comment]
./SetupThrive.rb

**Comment by hhyyrylainen** [comment]
And is there an error before the one you posted? I'm pretty sure that some dependencies failed to compile resulting in this error. (I have tested on a virtual machine and Ubuntu 18 and it worked fine).

**Comment by CrackerHax** [comment]
all the files compiled fine. They are sitting in Thrive/ThirdParty/Leviathan/build/ThirdParty/lib

**Comment by hhyyrylainen** [comment]
Including the missing files (libavcodec.so.57, libavformat.so.57, libavutil.so.55, libswresample.so.2, libswscale.so.4, libcAudio.so.2, libcef.so)?

**Comment by CrackerHax** [comment]
Yes
https://pasteboard.co/Ho5en2w.png

**Comment by hhyyrylainen** [comment]
Alright so they all installed there. But for the actual linking they are copied to Leviathan/build/bin/lib so I think that's the place where they are missing from and that's why you get those linker errors.

**Comment by CrackerHax** [comment]
Nope I see them in there too.

https://pasteboard.co/Ho5ziMn.png

**Comment by CrackerHax** [comment]
Yes, but I just tried copying them there manually and it is still not finding them.

**Comment by CrackerHax** [comment]
I just tried it from scratch again and it did copy all the files to Leviathon/build/bin/lib, but still fails at the same place with the same errors(s)

**Comment by hhyyrylainen** [comment]
I'll close this because there wasn't a follow up to my comment.
