### ISSUE TITLE
Screenshot button needs to be made again

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#578]
In the new version print scrn button should save a screenshot like in the current release.

Also someplace that would tell players about it would be good.

**Comment by hhyyrylainen** [comment]
Basically only the Engine::SaveScreenShot method needs to be called from a key callback

**Comment by Untrustedlife** [comment]
Ah okay I hadnt looked, ill want to make some edits to it though, apparently it saves them all as "screenshot" and overwrites it each time, so we should probably fix that too.

**Comment by hhyyrylainen** [comment]
That's Leviathan screenshot save code. And I just verified that it calls `    GetOgreWindow()->writeContentsToTimestampedFile(filename, "_window1.png");` So it should already not overwrite old ones. https://www.ogre3d.org/docs/api/1.9/class_ogre_1_1_render_target.html#a2c3046ce0995cc3058e2919b985e80f6 (that's 1.9 documentation but it is probably still the same in 2.1)

**Comment by Untrustedlife** [comment]
Well look at that, should be very easy to add then!

**Comment by Untrustedlife** [comment]
What method needs to be called? I figure i could knock this one out. Should we also create an issue for the suicide button?

**Comment by Untrustedlife** [comment]
Okay, it is resolved in this commit:
https://github.com/Revolutionary-Games/Thrive/commit/1731b10c391e61803b1c6f23459902ffce747564
