### ISSUE TITLE
Thrive crashing on startup

### ISSUE THREAD

**Issue by TorFourr** [Revolutionary-Games/Thrive#579]
Once I open the game, I see a black screen and then the application crashes.

Info:
**Thrive Launcher 32-64x
Thrive 0.3.4
Windows 8.1
AMD CPU**

Crash Log:
_Process Started
Loaded new AlphaHit texture: ThriveGeneric.png (2701x1001)
ERROR: 
 This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information.
ERROR: terminate called after throwing an instance of 'OIS::Exception'
 what(): Win32Mouse::Win32Mouse >> Failed to set format
child process exited with code 3_

**Comment by Untrustedlife** [comment]
Never seen this one.

**Comment by hhyyrylainen** [comment]
Might be a windows 8 specific bug. The new version uses SDL instead of OIS so this might already be fixed. (remind me to tag this "review")
