### ISSUE TITLE
Streamline the ProcessorComponent and CompoundBag situation

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#581]
Right now the ProcessSystem only runs on entities that has both ProcessorComponent and CompoundBag even though the CompoundBag includes a pointer to the ProcessorComponent (which is a bit unsafe but should be mostly fine if Species entities aren't deleted before all their members are extinct and this allows the species to have processes tweaked as a whole).

So the ProcesSystem should run on each entity that has a CompoundBag and just skip ones that have the processor as nullptr.

Also needs to remove the temporary ProcessorComponent adding.

**Comment by hhyyrylainen** [comment]
Here's the commit that adds the extra process component: https://github.com/Revolutionary-Games/Thrive/commit/cc4b1b6

**Comment by hhyyrylainen** [comment]
This has the potential to solve: https://github.com/Revolutionary-Games/Thrive/issues/615

**Comment by hhyyrylainen** [comment]
This is now a high priority

**Comment by Untrustedlife** [comment]
this is now fixed
