### ISSUE TITLE
Better modding experience

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#584]
Not a huge priority but in the future the modding experience (i.e. no more "just unzip these files on top of the game" installations) needs to be improved.

Currently potential approaches:
- https://mod.io (they have their own content policy and terms of service that I partly dislike)
- roll our own (we'd need a website to handle uploading and downloading mod files and then the game or the launcher needs the ability to download them)

**Comment by ATP-Kraken** [comment]
As a modder myself, I think it would serve us well to be able to load assets without overriding the vanilla files.
A file structure like this should be implemented:
![image](https://user-images.githubusercontent.com/34113921/42173204-4bdfdad2-7dec-11e8-9ff3-620133099abf.png)

**Comment by hhyyrylainen** [comment]
Unfortunately it is not possible to automatically use different files for Ogre resources (last I checked, it might be that Ogre 2.1 now has a custom file loader support). So only the json and script files could be loaded like that.
So instead the format I've been thinking of is that you have one folder per mod in bin/Data/Addons and you have a levgm file (like the microbe stage scripts has one) specifying the script files it has and then I'll add some syntax for specifying overwrite graphics resources also there. This also solves the problem of multiple mods wanting to change the same thing

So unfortunately making proper mods that can be easily installed and uninstalled won't be as easy as just throwing files in a folder with the names you want to replace.

**Comment by hhyyrylainen** [comment]
We'll need to rethink how we want modding to work with Godot.
Any input from people who have made mods for Godot games or made Godot games that are moddable is very welcome.

**Comment by hhyyrylainen** [comment]
There's now an example mods repo: https://github.com/Revolutionary-Games/ThriveMods
