### ISSUE TITLE
Get reproduction working again, right now it crashes.

### ISSUE THREAD

**Issue by Untrustedlife** [Revolutionary-Games/Thrive#585]
So the reproduction code needs to be refactored, the organelles grow and such, however they don't duplicate, and when the cell hits max growth the game crashes. So this needs to be fixed before release.

**Comment by Untrustedlife** [comment]
Only problem with reproduction now is that specieas:applytemplate crashes (probably due to physics)

**Comment by Untrustedlife** [comment]
Once that is fixed this can be closed

**Comment by Untrustedlife** [comment]
When an AI species reproduces does it reset now? If so we can close this.

**Comment by hhyyrylainen** [comment]
I think it should. But can you test if it actually does? We might have to fix the clouds before this can properly happen.

**Comment by Untrustedlife** [comment]
I have confirmed it works, i saw an AI cell do it
