### ISSUE TITLE
Reimplement saving

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#587]
(Apparently this wasn't an issue yet)

**Comment by Untrustedlife** [comment]
What annoys me is the weird disconnect weve always had between the player species and the AI species

**Comment by hhyyrylainen** [comment]
Once this is done a few issues need to be reviewed to be fixed:
https://github.com/Revolutionary-Games/Thrive/issues/593, https://github.com/Revolutionary-Games/Thrive/issues/594, https://github.com/Revolutionary-Games/Thrive/issues/401

**Comment by Untrustedlife** [comment]
We ar emoving this and the oassociated isues to 0.4.1 right?

**Comment by hhyyrylainen** [comment]
I think that was the plan. I'll move the issues now.

**Comment by hhyyrylainen** [comment]
Once this is done these issues can be done: https://github.com/Revolutionary-Games/Thrive/issues/573

**Comment by hhyyrylainen** [comment]
This is not critical for 0.4.1

**Comment by Untrustedlife** [comment]
This should be easy now that all cell layouts (including the players) are now just strings.

**Comment by hhyyrylainen** [comment]
I suppose that's true if we are fine with the old type of saving. But I would really like the saving to save everything: alive cells, compounds etc. so that save scumming would not be as effective. As before you could just save and reload if a big cell was about to kill you in order to get rid of it.

**Comment by hhyyrylainen** [comment]
I'm going to work on this soon(tm).
