### ISSUE TITLE
error loading libraries

### ISSUE THREAD

**Issue by Yottaqubyter** [Revolutionary-Games/Thrive#588]
ERROR: /home/yottaqubyter/Escritorio/Thrive Launcher-linux-x64/installed/LINUX_Thrive.0.3.4/Thrive-0.3.4/bin/Thrive: error while loading shared libraries: libilbc.so.0: cannot open shared object file: No such file or directory
child process exited with code 127

**Comment by Yottaqubyter** [comment]
P.D.: I'm on ubuntu

**Comment by hhyyrylainen** [comment]
This is a duplicate of https://github.com/Revolutionary-Games/Thrive/issues/513
