### ISSUE TITLE
Fix flagella rotation and move to membrane edge

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#589]
in movement_organelle.as the organelle rotation is applied again because apparently it is not correctly assigned by the organelle creation method. And this should be fixed.
```
        // BUG: This is already applied for the player but not generated species
        auto@ renderNode = organelle.world.GetComponent_RenderNode(organelle.organelleEntity);
        renderNode.Node.setPosition(organellePos);
        renderNode.Node.setOrientation(Ogre::Quaternion(Ogre::Degree(angle),
                Ogre::Vector3(0, 0, 1)));
```

**Comment by OBPSG** [comment]
I would be willing to give this small problem a try. Do we want to have the logic that handles rotation of organelles for ai microbes in procedural_microbes.as, or do we want to have that logic for all microbes in one place?

**Comment by hhyyrylainen** [comment]
I think there is some pretty huge underlying issue with this.

At least because the flagella is meant to be moved to the membrane outer edge that is also part of this issue as the flagella should be positioned to the membrane edge and THEN rotated properly there.

**Comment by Untrustedlife** [comment]
This is now on the edge, all thats left is to get the angle correct

**Comment by Untrustedlife** [comment]
Rotation is now fixed, closing this.
