### ISSUE TITLE
Loading previous save error

### ISSUE THREAD

**Issue by MkazemAkhgary** [Revolutionary-Games/Thrive#593]
Playing Thrive 0.3.4
Thrive is running. Log output:
Process Started
Loaded new AlphaHit texture: ThriveGeneric.png (2701x1001)
LuaEngine init started
 
 Available Playback Devices: 
 0): Generic Software on Speakers (Realtek High Definition Audio) [DEFAULT] 
 1): Generic Software on Realtek Digital Output (Realtek High Definition Audio) 
 
 Attempting default device: Generic Software on Speakers (Realtek High Definition Audio)
Thrive version 0.3.4 with Lua 5.1 from LuaJIT 2.0.4 ready to go. 
 FPS: 56.2130 avg frame duration: 3.52356 ms
 FPS: 57.3123 avg frame duration: 2.03238 ms
 Game loaded
 Lua error detected! ../scripts\microbe_stage\microbe.lua:212: Can't create microbe from this entity, it's missing sceneNode:
 [C]:-1 (global assert)
 ../scripts\microbe_stage\microbe.lua:212 (upvalue create)
 ../scripts\class.lua:30 (global Microbe)
 ../scripts\microbe_stage\microbe.lua:1306 (method update)
 ../scripts\lua_engine\game_state.lua:186 (method update)
 ../scripts\lua_engine\lua_engine.lua:145 (method update)
 ../scripts\game.lua:39
 
ERROR: [wmv3 @ 0e55aba0] Extra data: 8 bits left, value: 0
 [wmv3 @ 37c67f60] Extra data: 8 bits left, value: 0
child process exited with code 0
Thrive has exited normally.

**Comment by hhyyrylainen** [comment]
The next release will have a completely different saving system. In the meantime you can start a new game and then load the save to see if that helps.

**Comment by MkazemAkhgary** [comment]
@hhyyrylainen thanks. starting the game then loading from save seems to work sometimes.
