### ISSUE TITLE
Implement menu button

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#596]
With the new GUI the "main menu" button in the pause menu doesn't work.

It needs to return the player to the main menu when pressed and they need to be able to then start a new game.

**Comment by 1n48yg** [comment]
I'd like to tackle this problem.

**Comment by hhyyrylainen** [comment]
The way I suggest it would report to the C++ side about quitting to menu is that you have a look at `thrive/src/thrive_v8_extension.js` and how that is implemented on the C++ side `thrive/src/thrive_js_interface.cpp` (the function `bool
    ThriveJSHandler::Execute(const CefString& name,
        CefRefPtr<CefV8Value> object,
        const CefV8ValueList& arguments,
        CefRefPtr<CefV8Value>& retval,
        CefString& exception)` handles the calls coming from JavaScript).
That function is ran in the GUI process and the messages are actually received in the main process by `ThriveJSMessageHandler::OnProcessMessageReceived` where it is then possible to call the ThriveGame methods (there needs to be a new method there for returning to the menu).

**Comment by Untrustedlife** [comment]
Whats the status on this?

**Comment by hhyyrylainen** [comment]
I think the menu button works, @1n48yg but starting the game again from the menu crashes. And there is some cleanup I think that needs to be done on the returning to menu logic.

**Comment by 1n48yg** [comment]
Returning to the menu works as of right now. But going back into the game is a completely new challenge as the startNewGame function is not built to be able to send the player back into the game more than once. I think this issue should be raised to intermediate in difficulty (or at least have the good first issue tag removed) and have someone more experienced assigned.

**Comment by Untrustedlife** [comment]
It doesnta actually pause the game, and there is cleanup, and pressing escape does not open it up, ill see what i can do here.

**Comment by Untrustedlife** [comment]
https://github.com/Revolutionary-Games/Thrive/commit/a46f663ebd7612806a14588157db7c7d3baa8bc8

**Comment by Untrustedlife** [comment]
It works now
