### ISSUE TITLE
Combine C++ and AngelScript side Species classes

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#599]
Right now the situation is a bit confusing with a separate Species class in AngelScript and C++. The AngelScript version should be merged into the C++ side and the species system needs to be switched to using it.

**Comment by turoni** [comment]
Can someone add a bit more specification ons this issue about what AngelScript files need to be merged with what existing C++ files?
Mostly the AngelScript files so no logic is forgotten to import.

**Comment by hhyyrylainen** [comment]
The class `Species` in `species_system.as` needs to be merged with the C++ class named `thrive::Species` in `species.h`.

**Comment by OBPSG** [comment]
I feel like this issue ought to be a prerequisite for #703 because of the amount the species system manages processor components as well.

**Comment by hhyyrylainen** [comment]
I don't have time to look through the code but I don't think changing where the process data is stored has any effect on the overall logic of the species handling.

**Comment by OBPSG** [comment]
Not directly, no. But the species namespace (which the script-side species class references) has some methods that manipulate processor components, so refactoring that would affect my current work on issue #703.
