### ISSUE TITLE
Death needs to be fixed

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#601]
Right now dying has some issues in the new version.
- [x] fix crashing on linux when dying
- [x] make sure respawning works properly
- [ ] add the dying animation back in (this needs to be redone in blender)

**Comment by hhyyrylainen** [comment]
I'd like to keep the lower priority issues in the 0.4.0 milestone until the major issues are fixed and we can consider then what we want to get done before release.

**Comment by Untrustedlife** [comment]
Maybe the death animation is doable now?

**Comment by Untrustedlife** [comment]
I personally think the way we "fix this" would be changing death to not be explosive in general, basically a creature would die, break into bits and those bits would release compounds and eventually dissapear, much like that video of the dying paremecium i posted awhile ago, they don't explode, they rupture and spill compounds out. and it would be based on what was in the microbe that died, this way we have more interesting death, and the ability to add decomposers and scavengers as a viable playstyle, while also being more realistic.

**Comment by hhyyrylainen** [comment]
Not needed as the cells will be made to break into chunks on death.
