### ISSUE TITLE
Reduce the amount of component look ups

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#611]
Right now a ton of functions in MicrobeOperations take a `ObjectID microbeEntity` and look up the components. This is probably pretty slow. So each function should have a variant that directly takes the components (for example `MicrobeComponent@ microbeEntity`) and code that has the components already should call those variants to make things more efficient.

**Comment by OBPSG** [comment]
Is it correct for me to say that, what we basically want to do is save a reference directly to that entity's instance of the component, rather than searching the list of entries for entities matched by that component every time some of these functions are called?

**Comment by hhyyrylainen** [comment]
Saving component references between ticks is bad because then you won't know if the component has become invalid. Instead what I suggest that each function in MicrobeOperations would have two variants: one that accepts the components it needs as parameters so functions that have already retrieved them can use it and then the second version that would look up the needed components and then call the first variant.

**Comment by hhyyrylainen** [comment]
I think this is at least partly done now.

**Comment by hhyyrylainen** [comment]
I'll just consider this done. Further cleanup can be made on further releases.
