### ISSUE TITLE
Make the camera more dynamic

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#613]
https://forum.revolutionarygamesstudio.com/t/making-the-camera-more-fluid/511?u=hhyyrylainen

The camera could be made to feel more fluid by not making it instantly snap to the player position. Instead it could trail a bit behind the camera to give more sense of movement.

- [x] basic implementation done
- [ ] it is tweaked to be good

**Comment by TjWhale** [comment]
Here's a talk about some possible ideas

https://www.youtube.com/watch?v=tu-Qe66AvtY&t=1271s

**Comment by Untrustedlife** [comment]
First half of this is done, and i also personally think that the current default feels good aswell, so we could just close the issue.

**Comment by hhyyrylainen** [comment]
I think we should wait a bit to get @TjWhale and others to playtest the new settings.

**Comment by hhyyrylainen** [comment]
I think we should wait a bit to get @TjWhale and others to playtest the new settings.
