### ISSUE TITLE
Find all TODOs in code

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#614]
There are quite a few TODOs in the code (comments that indicate things that could / should be improved on) for tracking them all of them should be found and converted into github issues (the issue number should be added to the TODO to mark it as found).

These should be addressed for 0.4.1 release to make it the most clean release in Thrive history in order to attract new developers and impress the players.

**Comment by Untrustedlife** [comment]
OBPSG did this, so can we close this? We have the table we just haven't made them into actual issues yet.

**Comment by hhyyrylainen** [comment]
They are not issues on github yet, thus this is the only issue on github keeping track of that.
