### ISSUE TITLE
Inevitable Crash

### ISSUE THREAD

**Issue by TheBestAbracadabra** [Revolutionary-Games/Thrive#616]
Not sure why, but my game will often crash after 2-3 minutes, or after I start to move around. I hope that you can look into further detail.

**Comment by hhyyrylainen** [comment]
We are well aware of many crashes in the last release. The next release will probably have totally different bugs.

I'll close this as non-helpful, unless you have found a new crash / info regarding when it happens: https://community.revolutionarygamesstudio.com/c/bug-reports (check here to see all the known issues).
