### ISSUE TITLE
Fix the constant drift with the new movement

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#618]
There is a constant push to the left(? ) and that should be fixed.

I'm quite sure that the issue is in `MicrobeSystem::applyCellMovement` where the drag is applied when it is too low to have been properly calculated resulting in a constant push to the left. Or maybe the issue is something else, but this needs to be fixed.

**Comment by OBPSG** [comment]
I am willing to take a look at this problem.

**Comment by Untrustedlife** [comment]
Awesome 👏

**Comment by Untrustedlife** [comment]
I assigned you it @OBPSG

**Comment by Untrustedlife** [comment]
nver mind it appears i cant assign you it hmm.

**Comment by hhyyrylainen** [comment]
I think you can only assign members of the revolutionary games organization to issues.

**Comment by hhyyrylainen** [comment]
Did you try increasing `CELL_REQUIRED_DRAG_BEFORE_APPLY`? Because I think that is probably related to this issue.

**Comment by Untrustedlife** [comment]
I think its fixed now,

**Comment by Untrustedlife** [comment]
Its properly fixed in this commit: https://github.com/Revolutionary-Games/Thrive/commit/2b985cf62d9f094fa6b065d2c5596e629468e86c

**Comment by Untrustedlife** [comment]
Is it safe to say we can close this now?

**Comment by hhyyrylainen** [comment]
Fine. If there are further tweaks they can be made before the movement rebalancing issue is closed.
