### ISSUE TITLE
Make perlin noise repeat nicer

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#622]
Now with the new clouds the perlin noise is applied to each separate cloud but at the seams of the clouds the uv coordinates jump and I don't think there is any other way to fix this than to change to a tileable perlin noise texture.

There is some talk about generating such a texture here: https://gamedev.stackexchange.com/questions/23625/how-do-you-generate-tileable-perlin-noise

**Comment by Untrustedlife** [comment]
Naro fixed this and i replaced the texture.
