### ISSUE TITLE
Make bacteria collision shape match their organelles

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#624]
Right now the bacteria is made smaller visually by scaling it by 50%. Physics engines don't like scaling so what apparently is currently done is that they are a single sphere with a fixed size. 
And because of that their visual size doesn't match up with their actual physical size. This should be fixed.

**Comment by NicholasDM** [comment]
What would be the issue, if any, for removing the scaling to fix both this issue and #717?

I imagine rebalancing in size for the hex grid would end up necessary to keep at least somewhat realistic prokaryote and eukaryote ratios.

**Comment by hhyyrylainen** [comment]
The size difference couldn't really work that way as well. Cytoplasm would also need to be changed and all the organelles would have to have multiple times as many hexes and that may cause a host of other problems (missing zooming out in the editor so size would be very limited for prokaryotes, each hex is its individual collision and that might push the physics performance down).

**Comment by hhyyrylainen** [comment]
I'd like to add that I haven't read about scaling with Bullet so it might actually just work if it is scaled.
Our previous physics engine explicitly forbade scaling (and didn't have any support functions for doing it). Bullet might support it and even have specialty functions for dealing with it.

**Comment by NicholasDM** [comment]
Appreciate the insight. I'll take a look later today.

**Comment by Untrustedlife** [comment]
This is in aswell now right?

**Comment by hhyyrylainen** [comment]
Fixed by: https://github.com/Revolutionary-Games/Thrive/pull/754
