### ISSUE TITLE
Make volume scale by distance.

### ISSUE THREAD

**Issue by Untrustedlife** [Revolutionary-Games/Thrive#629]
Make volume of sound effects scale by distance to player cell. In an effiicient/clean way.

**Comment by Untrustedlife** [comment]
The other issue gave a 404 error when clicked on for some reason, so i just closed it via the main issue list and opened this one.

**Comment by hhyyrylainen** [comment]
For sound effects it may be needed to add a volume parameter for playing them (in the engine). For longer sounds it is probably worth it to switch to having 3d positional sound sources.

**Comment by Untrustedlife** [comment]
Okay this is implemented with this:
https://github.com/Revolutionary-Games/Thrive/commit/6159367cd6f4fa7a43d0244fa8b7442971045f08
https://github.com/Revolutionary-Games/Thrive/commit/874913555885c6e8f4d172e715a323daba3b8762

**Comment by Untrustedlife** [comment]
Not sure if we should close this.

**Comment by hhyyrylainen** [comment]
For now I think this is done, I opened this issue: https://github.com/Revolutionary-Games/Thrive/issues/648
