### ISSUE TITLE
Add a popup for when Auto-evo is happening.

### ISSUE THREAD

**Issue by Untrustedlife** [Revolutionary-Games/Thrive#630]
Sometimes when an auto-evo step happens and it has to generate new species, and it generates a new "Epic Cell" or just when crazy evolution stuff is happening in auto-evo this freezes the game for a couple seconds, add a pop up so people know that when this is happening the game is in fact not crashing. Or disable creating new epic cell species when auto-evo is happening..
(I would prefer the former of course)

**Comment by Untrustedlife** [comment]
When it happened to me, i definitely thought it was crashing sinc eit was taking awhile. SO this is probably important.

**Comment by hhyyrylainen** [comment]
In my opinion the initial generation shouldn't create huge cells. And in the future we will only have auto evo happening when the editor is entered. So this is not needed.

**Comment by hhyyrylainen** [comment]
Also as auto-evo right now is ran on the main thread the GUI can't be updated before the function call to the auto-evo ends. So it isn't actually possible to make this right now.

**Comment by Untrustedlife** [comment]
Ahh okay
