### ISSUE TITLE
getMouseHex is offset weirdly

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#631]
And as a result the place where the hex you are about to place in the editor is wrong.
Something is wrong with the cartesian to axial conversion.

**Comment by Untrustedlife** [comment]
https://github.com/Revolutionary-Games/Thrive/commit/801f18bb1582020612fde3b8d9b0a8fe8133edad

**Comment by Untrustedlife** [comment]
I feel like this does a good job fixing the offset

**Comment by Untrustedlife** [comment]
Im not gonna close it yet because i just want thsoe who can to check it out and tell me what they think :)

**Comment by hhyyrylainen** [comment]
I feel like this is just a bandaid and the actual problem is somewhere in the cartesianToAxial and back conversion functions. But if it is good enough (I haven't tested yet as I'm rendering with blender so I don't want to try to use my GPU at the same time for running thrive) I think we can move this issue to 0.4.1 and look at this again later.

**Comment by hhyyrylainen** [comment]
Just tested it and it is now a bit better, but I still think that the actual underlying math is wrong and this is just a bandaid.

**Comment by crodnu** [comment]
Fixed in my last PR, hopefully it didn't break anything else using cube coordinates already...

**Comment by hhyyrylainen** [comment]
I'm pretty sure only the editor used them.
It's now merged: https://github.com/Revolutionary-Games/Thrive/pull/734
