### ISSUE TITLE
Rusticyanin model and Icon, Nitrogen Fixing protiens model and Icon, ocean floor biome and pilus art.

### ISSUE THREAD

**Issue by Untrustedlife** [Revolutionary-Games/Thrive#632]
We need some art for 0.4.1
- [x] New Flagella with working animation
- [x] New chloroplast  Model And Texture 
- [x] New vacuole texture 
- [x] Chromatophores
- [x] New Chemoplast Texture and Model
- [x] Nitrogen fixing plastid
- [x] Metabolosome
- [x] Chemo-synthesizing Proteins
- [x] Nitrogen fixing Proteins
- [x] Floating Iron/not floating rocks in the environment
- [x] Rusticyanin model
2d art:
- [x] Maybe Estuary  Biome?
- [x] Maybe Ocean Floor Biome?
- [x]  Nitrogen fixing Proteins Icon
- [x] New Pilus model and texture
- [x]  Chemo-synthesizing Proteins Icon
- [x] Rusticyanin Icon

**Comment by hhyyrylainen** [comment]
Do we have the new models somewhere?

**Comment by Untrustedlife** [comment]
I think we do. Probabbly need to search for them on discord though.

**Comment by Untrustedlife** [comment]
Sporefox is the one that  made them i believe.

**Comment by hhyyrylainen** [comment]
So it turns out that the models don't actually exist?

**Comment by Untrustedlife** [comment]
The models we need are: Chemoplast, Niitrogen Fixing Plastid, The various proteins

**Comment by Untrustedlife** [comment]
Okay chemoplast and nutrogen fixing plastid are all in
Im going to add to this issue now:

- [ ] Chemoplast
- [ ] Nitrogen fixing plastid
- [ ] Aerobic Proteins
- [ ] Chemo-synthesizing Proteins
- [ ] Nitrogen fixing Proteins
- [ ] PhotosynthesizingProteins
- [ ] New Flagella with working animation

The new pipeline is-> Build model ->join all the bits -> name joined bit properly -> do a smart uv map (go to edit mode press a->press u-> choose smart), then add a texture image edit that until it looks good on the model->export image as png ->send a programmer the blend file so they can export it and the texture -> it gets in game

**Comment by Untrustedlife** [comment]
For 2d Art:
-Maybe Estuary  Biome?
-Maybe Ocean Floor Biome?

**Comment by Untrustedlife** [comment]
Only two of these left.

**Comment by Untrustedlife** [comment]
We have all the assets here, so closing this, and we can create a new issue as needed.
