### ISSUE TITLE
Organelles have their components randomly deleted

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#636]
@Untrustedlife found the error again that some organelle after playing a while is missing the RenderNode component and causes a lot of errors.

I think there might be a case where the component is erroneously deleted from some other place.

**Comment by Untrustedlife** [comment]
Found another instance of this happening in movement_organelle.as, i added a nullcheck, but that means its definetly happening to flagella sometimes aswell.

This time it was also the rendernode.

https://github.com/Revolutionary-Games/Thrive/commit/6b3fca7b14bed6095b6b64afccddedb2db2e64b3

**Comment by hhyyrylainen** [comment]
I think this should be fixed by: https://github.com/hhyyrylainen/Leviathan/commit/636a56cb2542c31e4535bf2820c76737f48ac9a1
