### ISSUE TITLE
Make a 32-bit version

### ISSUE THREAD

**Issue by zenieldanaku** [Revolutionary-Games/Thrive#656]
I've just looked into the new release 0.4.0 for windows and realize that it says '64-bit', which led to a tremendous letdown because I only have a 32-bit windows machine. Is it possible to release a version for 32-bit? Or am I asking too much?

**Comment by hhyyrylainen** [comment]
The whole build system is setup to make only 64 bit binaries. It takes quite a bit of work to work through all the dependencies in setting up the build scripts to make 32 bit versions (and it is possible that if the binary names are the same there needs to be a lot of work done to separate out 32 bit and 64 bit builds to their own subfolders).

**Comment by zenieldanaku** [comment]
I guess that it disfficult, but I won't be able to play Thive in any time soon if there is no build for my type of computer. It would be just another one of those games that I just can't play.

**Comment by hhyyrylainen** [comment]
That is unfortunate. One thing you could check out is building the game on Linux as that *should* automatically build a 32 bit version on a 32 bit OS.

**Comment by zenieldanaku** [comment]
@hhyyrylainen may I ask why you removed this issue from the 0.4.1 milestone?

**Comment by hhyyrylainen** [comment]
There is no one to work on this issue, so as to when this is done can't be really predicted. And as such it was removed from 0.4.1 milestone.

Basically this is on hold until someone makes a pull request for this or someone on the team considers this a good use of their time.

**Comment by zenieldanaku** [comment]
I see. Thanks for the quick reply.

**Comment by hhyyrylainen** [comment]
Why was this closed? This is not done yet.

**Comment by zenieldanaku** [comment]
I closed because I installed Window 7 64-bit in my computer and was able to try the 64-bit version of the game as is. therefore, I don't need a 32-bit version anymore (maybe some other people do, but I never saw anyone else complaing abut this issue).
