### ISSUE TITLE
The process system sometimes has invalid process numbers

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#669]
Causing the log to be spammed with:
`[ERROR] ProcessSystem: Run: entity: 4139 has invalid process: 4640, process count is: 8`

The process number `4640` here is obviously wrong as we have less than 20 processes.

This lags the game majorly.

**Comment by Untrustedlife** [comment]
Ill be looking into this one.

**Comment by Untrustedlife** [comment]
I think i may have fixed this in my last few commits relating to process code, so if someone can play a bit and see if it still happens that would be useful
https://github.com/Revolutionary-Games/Thrive/commit/ea74654687fcebb56e0a25e8d4c8dae3aa0ce34b
https://github.com/Revolutionary-Games/Thrive/commit/66fc5de1bf64a1c57edd22a4c0db30a7adb644c8

**Comment by hhyyrylainen** [comment]
I'm failing to see how that https://github.com/Revolutionary-Games/Thrive/commit/ea74654687fcebb56e0a25e8d4c8dae3aa0ce34b commit would actually affect this as the datatypes were big enough to hold the process numbers and not overflow to begin with.

This needs many hours worth of testing so probably need to recruit many developers to test.

**Comment by Untrustedlife** [comment]
I looked for a long time, there is absolutely no problem with the bioprocess registry code, no typos, it loops through the list itself so it would make 0 sense for it to get some unknown process in there, and everything was matching everywhere except here. Compound registry code looked fine, There may have also been an issue with the old species processor code as well which i just replaced with the players.

**Comment by Untrustedlife** [comment]
The json files also look fine, etc

**Comment by hhyyrylainen** [comment]
I think this is another case of some really strange other place randomly messing with the stuff.
So now if the code related to process system is reviewed the bug hunting needs to go elsewhere. Perhaps in the form of a bunch of debugging code (that shouldn't be committed) reading the properties of the process components to find if it is an initialization problem or if something goes and messes with them.

**Comment by Untrustedlife** [comment]
Well i mean i did also make them use the players code to do processes, there may have been an issue with the AI version of it

**Comment by Untrustedlife** [comment]
Its unlikely but maybe.

**Comment by Untrustedlife** [comment]
Okay, i'm not going to close this and the other issue until we can confirm that these issues areno longer there. so i'll add the review tag

**Comment by hhyyrylainen** [comment]
Should be fixed as: https://github.com/Revolutionary-Games/Thrive/issues/699 is now fixed which probably was the underlying cause.
