### ISSUE TITLE
Make engulfing work if touching a cell before enabling

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#671]
Right now the player has to hit the engulf key a bit before they hit a cell in order to be able to move into it.

A way needs to be figured out for the physics collision to be disabled when the overlap begin callback isn't called again as the cells were already touching.

**Comment by Dak2896** [comment]
The enable engulfing  should be replace by a trigger that when the cell touch another the engulfing  is automatic enabled, and disabled when you move out of the other one cell, or you kill him.  

If i'm right, now the engulfing works like this:

void toggleEngulfMode(CellStageWorld@ world, ObjectID microbeEntity)
{
    MicrobeComponent@ microbeComponent = getMicrobeComponent(world, microbeEntity);
    toggleEngulfMode(microbeComponent);
}

// Disables or enables engulfmode for a microbe, allowing or
// disallowing it to absorb other microbes
void toggleEngulfMode(MicrobeComponent@ microbeComponent)
{
    // auto soundSourceComponent = world.GetComponent_SoundSourceComponent(microbeEntity);
    if(microbeComponent.engulfMode && !microbeComponent.isBeingEngulfed){
        microbeComponent.movementFactor = 1.0f;
        // soundSourceComponent.stopSound("microbe-engulfment"); // Possibly comment out.
    }
    else  if (microbeComponent.isBeingEngulfed)
    {
        microbeComponent.movementFactor = microbeComponent.movementFactor /
            ENGULFED_MOVEMENT_DIVISION;
    }
    else
    {
        microbeComponent.movementFactor = microbeComponent.movementFactor /
            ENGULFING_MOVEMENT_DIVISION;
    }

    microbeComponent.engulfMode = !microbeComponent.engulfMode;
}


but should be implemented in way like is done with compunds 

 // Allowing the microbe to absorb all the compounds.
    setupAbsorberForAllCompounds(compoundAbsorberComponent);

Am i right?

**Comment by hhyyrylainen** [comment]
The problem is when 2 cells collide and neither has engulf mode enabled the collision callback tells the physics engine that the collision is allowed. Now if one of the cells turns on engulf mode the physics collision callback isn't called again (I'm not sure how that could be caused). But the contact callbacks are, so at least the damaging works.

So things go like this (when everything is fine): cell enables engulf -> collision callback (return false) -> collision is called again (apply damage)
(Now that I think about that I'm not sure if it does actually go like that @Untrustedlife wrote the new version of engulfing)

And when it goes wrong:  collision callback (return true) -> contact callback (do nothing) -> cell enables engulf -> contact callback (apply damage)

So the collision callback is not called again.

**Comment by Untrustedlife** [comment]
Regarding that I kinda like the player skill element this adds. Even if it doesn’t make much sense.

**Comment by Dak2896** [comment]
Couldn't be a solution to use the key just for disable engulfingMode  and enter in the mode just by touching another cell?

**Comment by Untrustedlife** [comment]
@Dak2896 no, sometimes you dont want to consume every cell you touch

**Comment by Dak2896** [comment]
@Untrustedlife That's right, could be too much boring for player be careful to do not touch bigger cells, or cell with toxins

**Comment by hhyyrylainen** [comment]
> The "should these collide" callback happens only once. It is not retriggered if either cell that is currently touching enters engulf mode. There needs to be some added feature to the engine to retrigger the collision check between two physics bodies. I haven't found any directly usable API in bullet so it might be a bit tricky to figure out how to do it

**Comment by hhyyrylainen** [comment]
I think I made the logic in the Godot version to allow this, so closing.
