### ISSUE TITLE
Add floating iron particles

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#675]
This isn't fully thought out yet, but I opened this issue to link it to the reworked death issue.

So depending on what the particles are made out of they should either constantly release a cloud or they should grant stuff when the cell engulfs / touches the particle. For the decaying cells the releasing compounds mode is needed.

**Comment by Untrustedlife** [comment]
Have we decided on the specific variant we wanted to go with of the ones listed in @TjWhale 's dev forum post?

**Comment by TjWhale** [comment]
I get the sense most people favour collectible iron chunks, which is fine with me. I think if we're going to do that we should do an experiment to test if it's un-fun. Basically have something (like a random nucleus or something) floating around and when you pick it up it slows you down for 15s and slowly gives you ATP. I'd be really interested to know how this feels as I'm worried it might feel lame to be slowed down, depending on the amount of slowing and ATP and digestion time. 

If it feels ok then we could work on getting models + organelles done etc. If it feels tedious it might be better to go with rocks you can hover near.

**Comment by Untrustedlife** [comment]
Fixed here: https://github.com/Revolutionary-Games/Thrive/pull/735

**Comment by Untrustedlife** [comment]
Fixed in #675
