### ISSUE TITLE
Modify starting cell to be a single hex of cytoplasm

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#677]
I think this is pretty self explanatory

**Comment by Dak2896** [comment]
I modify config file, i saw that there was two cytoplasma in the template, i delete one, it works it seems, or you meant that starting cell should be smaller with one cyto only?

If so i modify organelle_table and reducing nucleus number of Hex, it works but golgi and nucleus are bigger than the Hex.

**Comment by hhyyrylainen** [comment]
The starting cell should have only one cytoplasm organelle and nothing else.
