### ISSUE TITLE
Make editor able to place nucleus

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#678]
Right now the nucleus action is the "new cell" action. That should be split so that it is possible to place *one* nucleus in a cell (if it doesn't have one).

And a new button is needed (and an icon) for the nucleus placing.

**Comment by Dak2896** [comment]
I add in gui_editor possibility to add nucleus, it cost 90 but we can think about balancing later, of course there is no image and good description but at least it works.

**Comment by Untrustedlife** [comment]
I think it should cost 100, also it needs to lock the ability to place other organelles that arent prokaryotic in the editor, also it needs to actually make you look like a bacteria when you dont have it, also we are working on a hot-fix release not 0.4.1 right now.

**Comment by hhyyrylainen** [comment]
Locking the things is a separate issue: https://github.com/Revolutionary-Games/Thrive/issues/679

**Comment by TjWhale** [comment]
@Dak2896 thanks for getting into this issue! I agree with @Untrustedlife I think it should cost 100MP as it's a big moment in evolutionary history. It's cool you're already getting familiar with the code base.

**Comment by Dak2896** [comment]
Ok now the only one problem is to figure out a way to lock possibility to put another nucleus, i try with some flag variable but of course if function is called again it's reset again, what about to class member variable?

But species dictionary is update every mutation right? so it should be possibile to read acutal organelles and so avoid duplication of nucleus

**Comment by Dak2896** [comment]
It seems working now, it cost 100, i make nucleus big 9 instad of 10 because at begin cell now is 1 hex.
and you can create just one nucleus, i think next step is make first evolution little bit harder then others, now getting a nucleus is quite easy

**Comment by hhyyrylainen** [comment]
https://github.com/Revolutionary-Games/Thrive/pull/709
