### ISSUE TITLE
Add separate patches

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#683]
Each species should have a per patch population and they need to try to move surrounding patches at some intervals.
The patches should have different properties like compound densities, light levels, and background image etc.
 
It's fine to be fixed at first: https://github.com/Revolutionary-Games/Thrive/issues/682

**Comment by hhyyrylainen** [comment]
Per the balance comment: some patches should be harder to play in than others.

I assume this also means that this depends on: https://github.com/Revolutionary-Games/Thrive/issues/684

**Comment by Untrustedlife** [comment]
Light and Heat can be done as environmental compounds for now i think (like how we do dissolved oxygen and c02)

**Comment by Untrustedlife** [comment]
Maybe we can get a thermoplast in for this release

**Comment by crodnu** [comment]
thermoplast arent just chloroplast but with heat, they only work by moving through a heat gradient (either from hot to cold or the other way around idk)

**Comment by Untrustedlife** [comment]
Yeah thats a good point. It would have to only run when teh cell is moving i guess? Hmm

**Comment by Untrustedlife** [comment]
I will tackle this finally

**Comment by hhyyrylainen** [comment]
https://github.com/Revolutionary-Games/Thrive/commit/eaf97fde72720bb1cd76752deb438196d3730a58
