### ISSUE TITLE
Balance different builds

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#687]
This hasn't been thought out yet but "gluttonous" builds and builds with low number of organelles should be made infeasible with balancing tweaks.

**Comment by 1n48yg** [comment]
I would like to try and tackle this issue a bit.

**Comment by TjWhale** [comment]
It might be a bit tricky to do stuff before we've seperated the patches, though it is a nice thing to work on, what sort of thing were you thinking?

**Comment by 1n48yg** [comment]
I agree tweaking the individual values of organelles might be a bit too early at this point. I was thinking about some more general changes such as linking some compound cloud spawn rates to the current generation to represent the decrease of resources over time or making it so larger cells have a harder time balancing energy production and consumption.

**Comment by hhyyrylainen** [comment]
I'll just make this the general balance stuff issue.

**Comment by yowshi** [comment]
are gluttonous builds actually that big a problem? considering the time investment required in a game to make one is an additional cost necessary?

**Comment by buckly90** [comment]
I am going to investigate this and try baking gluttonous cells in-game, and rebalance where ever necessary. With luck I wont need to change anything but I suspect I will need to make parts like oxytoxy more expensive. We'll just have to see!

**Comment by hhyyrylainen** [comment]
I'll close this because a bunch of balance changes were done, but it seems that balancing work never really ends. I'm sure we'll remember to balance the game without this issue being open, right?
