### ISSUE TITLE
Rebalance time to reproduce

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#690]
The time it takes to get to the editor needs to be tweaked.
Some tweaks to be done: change phosphate and ammonia availability, balancing Nitrogen Fixing Plastid.
Concrete numbers aren't clear so this needs a lot of testing.

**Comment by Untrustedlife** [comment]
Maybe the nucleus should also cost more ammonia and phosphate?

**Comment by Dak2896** [comment]
Nucleus need some maintenance, so yes i think should cost something, by the way it unlock a lot of organelles some disadvantages are needed.

**Comment by TjWhale** [comment]
I'd like to kind of go the other way with this. I think pretty much all cells should take a similar amount of resources to reach the editor. Especially as big cells may well be slower which means they will have a harder time finding the resources.

I think maybe the amount of ammonia and phosphate you require should be constant. Or maybe something like a constant + small amount per organelle, something like that.

I think it should take 2 minutes to reach the editor each time or something like that.

**Comment by Dak2896** [comment]
So are we are with this issue?
because it touch different things: compounds availability, 

- [ ] compounds availability

- [ ] Nitrogen fixing Plastid balancing

- [ ] time to reproduce?

- [ ] Nucleus osmoregulation ( @Untrustedlife i think already made it)

**Comment by Untrustedlife** [comment]
two parts of this issue left

**Comment by hhyyrylainen** [comment]
I'll just close this as we did some rebalancing regarding this in 0.4.2.
