### ISSUE TITLE
Process system sometimes has invalid ProcessorComponent

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#699]
This is probably the cause behind this issue: https://github.com/Revolutionary-Games/Thrive/issues/669

So far we have received 5 crash reports all of which crash here:
```
Crash reason:  EXCEPTION_ACCESS_VIOLATION_READ
Crash address: 0xffffffffffffffff
Process uptime: 315 seconds

Thread 0 (crashed)
 0  Thrive.exe!thrive::ProcessSystem::Run(Leviathan::GameWorld &) [process_system.cpp : 197 + 0x0]
    rax = 0x0000098f01ca0001   rdx = 0x000000000000000f
    rcx = 0x000000ffffffffff   rbx = 0x0000000000000000
    rsi = 0x8000008300000082   rdi = 0x0000000000000083
    rbp = 0x000000000023f220   rsp = 0x000000000023f120
     r8 = 0x000000000ba87cb0    r9 = 0x0000000000000000
    r10 = 0x0000000000000000   r11 = 0x0000098f01ca0001
    r12 = 0x000000000baa8b30   r13 = 0x000000001b855270
    r14 = 0x000000001be26ed0   r15 = 0x000000001b695070
    rip = 0x000000013f848501
    Found by: given as instruction pointer in context
 1  Thrive.exe!thrive::CellStageWorld::_RunTickSystems() [cell_stage_world.cpp : 686 + 0xf]
```

The address seems to be pretty random.

And the source code for around that line is 
```c++
        for(const auto& process : processor->process_capacities) {
            const BioProcessId processId = process.first; // This is line 197
            const double processCapacity = process.second;
```

So what probably is happening is that the CompoundBag which has a pointer to the ProcessorComponent keeps the pointer even after the ProcessorComponent is released. So we just need to sort it out so that CompoundBags don't use deleted processor components, which already is an issue:
https://github.com/Revolutionary-Games/Thrive/issues/581

```
(which is a bit unsafe but should be mostly fine if Species entities aren't deleted before all their members are extinct and this allows the species to have processes tweaked as a whole)
```
famous last words

**Comment by Untrustedlife** [comment]
I have an idea as to how to fix this and the other issue now, the processor component being set was on the species level, and they were directly using the species processor component, i need to make it so that cells  copy the capcities of the species processor component into their local component,

**Comment by Untrustedlife** [comment]
Added review tag, we need to confirm this crash is gone now.

**Comment by hhyyrylainen** [comment]
Should be now fine as confirmed by a few early testers of 0.4.0.2
