### ISSUE TITLE
Code should specify svn version

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#711]
Right now the setup script just grabs the latest svn revision but that is not optimal when working with multiple git branches and if we want historical builds to work.

So we need to have like a new file in the root folder specifying the svn version and then the setup script (and quick recompile) should checkout that revision instead of the latest one. That way it is possible to control what svn stuff is included. Later we may have to also switch to using svn branches but for now it is unnecessary.

**Comment by crodnu** [comment]
Also we should move materials and shaders to github

**Comment by hhyyrylainen** [comment]
Git lfs seems like a solution. I'm currently exploring that.
