### ISSUE TITLE
Rebalance MP costs and reorganise organelle menu

### ISSUE THREAD

**Issue by TjWhale** [Revolutionary-Games/Thrive#714]
MP costs should be rebalanced, we can always iterate on this once we see how it feels.

Nucleus: 100
Flagella: >35
Toxin: 60
Cytoplasm: 35
Everything else: Between 35 and 50.

The menu should have the nucleus and it's organelles grouped together.

**Comment by Dak2896** [comment]
I'm making different kind of balancing, right now i'm focusing on make flagella useful not only when you are big cell but also when you are small prokaryotic and you would like to eat faster, or be fast predator.

**Comment by Untrustedlife** [comment]
The first half of this is now completed.

**Comment by NicholasDM** [comment]
Second half is completed by pull request #736

**Comment by hhyyrylainen** [comment]
Merged: https://github.com/Revolutionary-Games/Thrive/pull/736
