### ISSUE TITLE
Suggestion: A way to control download location

### ISSUE THREAD

**Issue by CTH999** [Revolutionary-Games/Thrive#715]
I don't know If I just can't find it, but I don't think it downloaded where I wanted it

I want it to download in a specific folder, but as far as I can tell, while I got the launcher to download there just fine, I can't see how to control where it downloads the main game files.

The file location I want it to use is on the desktop...

Just thought I would give you the idea of controlling the download location, but ultimately, it's your choice. (Since it's your game...)

**Comment by hhyyrylainen** [comment]
This is actually an issue for the launcher.
I created an issue there: https://github.com/Revolutionary-Games/Thrive-Launcher/issues/22
