### ISSUE TITLE
Make player be the same size as other prokaryotes, when prokaryotic.

### ISSUE THREAD

**Issue by Untrustedlife** [Revolutionary-Games/Thrive#717]
We now have playable prokaryotes, but they dont actually look like the AI prokaryotes because those are scaled down 50%, the player needs to be scaled down when prokaryotic aswell.

**Comment by hhyyrylainen** [comment]
If someone takes a look at this they should consider also fixing: https://github.com/Revolutionary-Games/Thrive/issues/624
Because otherwise the collisions are a bit wonky as the collision shapes don't quite match the bacteria visual sizes.

**Comment by NicholasDM** [comment]
What would be the issue with removing the scaling for prokaryotes being smaller, which would fix this issue and #624?

**Comment by Dak2896** [comment]
I made some test and the only thing i get was changing it at beginning by change isBacteria in config template to true.

The problem appear when nucleus was added, i handle to change the render to the right one but physics one was just a sphere instead off the real size of cell.

@Untrustedlife  Am i right?

**Comment by hhyyrylainen** [comment]
Fixed in: https://github.com/Revolutionary-Games/Thrive/pull/754
