### ISSUE TITLE
When reproducing (leaving editor) cells should be spaced further apart.

### ISSUE THREAD

**Issue by TjWhale** [Revolutionary-Games/Thrive#718]
When leaving the editor two copies of the player's cell are created. However if the players cell is very big then these are created on top of each other and get tangled. The distance they are separated by should increase with the size of the cell.

**Comment by Dak2896** [comment]
I will work on this if no one has already taked it

**Comment by hhyyrylainen** [comment]
I don't think anyone's working on this. I assigned you to this issue.

**Comment by Dak2896** [comment]
#739
