### ISSUE TITLE
When low on ATP the cell should be damaged.

### ISSUE THREAD

**Issue by TjWhale** [Revolutionary-Games/Thrive#720]
There are situations where a cell has a lot of flagella and not enough mitochondria and so it runs out of ATP. However if the cell is large enough the ATP can get stuck at a small value (for example 5) and not go low enough to cause ATP damage. 

The desired behaviour is when the cell runs out of ATP it should take some damage and be slowed, which is what is implemented and usually works.

See this discussion https://community.revolutionarygamesstudio.com/t/community-challenge-can-you-reproduce-this-bug/1451

You can see this happening in this video https://youtu.be/oRYLqqiDdZ4?t=976

**Comment by Dak2896** [comment]
Sorry i don't understand exactly what you mean, if cell remain at 5 atp should become slower?

**Comment by TjWhale** [comment]
When a cell runs out of ATP it should take damage and become slowed. The issue is that if you make a really large cell with lots of flagella and hold down forwards the ATP can become stuck on some value, such as 5, and you don't take damage even though you are using more than you are producing. 

If you are out of ATP and holding a key to move your flagella should still keep trying to take ATP.

**Comment by hhyyrylainen** [comment]
I just had an idea what might be going wrong: the organelles are probably ran, and then the process system is ran so even though the flagella on each tick consume all of the ATP the process system then makes some more and then when it comes time to apply damage to cells with no ATP the player has the ATP they just generated. So the flagella can drain all ATP but as long as the player has ATP generation they won't die.

I didn't actually check from the code if that's the case, but that might help whoever decides to look into this.

To me this still feels like instead the player should be told that their flagella is not working effectively.

**Comment by TjWhale** [comment]
The behaviour I'd like is when press a movement key the flagella try to draw power. If that makes you run out of power you get hurt.
I think if we have a system where the flagella automatically turn off some people won't understand why they are slow. I'd rather make it a bit harsher so the player really understands about ATP and how important it is.

**Comment by Untrustedlife** [comment]
I think i may have fixed this.
Flagella DID turn off automagiclaly if you couldnt support them in one step. Now they dont do that

**Comment by Untrustedlife** [comment]
https://github.com/Revolutionary-Games/Thrive/pull/779

**Comment by Untrustedlife** [comment]
Okay, it seems to still be happening, its better by a bit because now you actually do take some damage though when it gets stuck down there. Its because of the order the systems run in, im sure of it.

**Comment by Untrustedlife** [comment]
actually this is probabbly fixed

**Comment by Untrustedlife** [comment]
and we merged that pull request so
