### ISSUE TITLE
Move finished scripts to C++

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#724]
As per the discussion here: https://forum.revolutionarygamesstudio.com/t/modding-support-and-moving-scripts-to-c/559?u=hhyyrylainen

It is better in the long run to start moving finalized (or mostly done) scripts from AngelScript to C++ and maybe do a bit of refactoring and cleanup at the same time.

Some of the first things I think should be moved:
- [ ] microbe system
- [x] OrganelleComponent
- [ ] PlacedOrganelle

and then starting on the organelle placing etc. logic, that is a bit of a mess right now

**Comment by Kasterisk** [comment]
Should the `MicrobeComponent ` need to be moved also, or should it just stay in the script?

**Comment by hhyyrylainen** [comment]
For the microbe system to be moved it needs MicrobeComponent to be moved. And for MicrobeComponent to be moved it needs PlacedOrganelle. So a lot of stuff needs to be moved at once for the microbe stuff to be moved.

**Comment by Kasterisk** [comment]
Ah okay, that makes sense.
