### ISSUE TITLE
If you create a cell with a nucleus and go back to the main menu, the editor isn't reset, this needs to be fixed

### ISSUE THREAD

**Issue by Untrustedlife** [Revolutionary-Games/Thrive#726]
Fix the bug where if you create a cell with a nucleus and go back to the main menu, the editor isnt reset so you cannot place a new nucleus.

**Comment by hhyyrylainen** [comment]
Fixed by: https://github.com/Revolutionary-Games/Thrive/commit/1c3363e93f64d0b4fdf678005535cf062955881a
