### ISSUE TITLE
Make engulfing work based on visual size

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#729]
Right now it is calculated based on the number of organelles each of the cells have. It should instead be calculated by the number of hexes and applying the bacteria (50%) scaling so that visual size would match what you can engulf.

**Comment by turoni** [comment]
Hi, I want to take this on as a first issue.
Not exactly sure how github works but I think I don't have the neccesary right to assign this to myself.
So can anyone assign this to me or grant me the rights to do so?

I added my introduction here: https://forum.revolutionarygamesstudio.com/t/hi-new-developper-here/578

**Comment by hhyyrylainen** [comment]
Assigning only works for members of the https://github.com/Revolutionary-Games organization. I've only invited people after their first pull request. But your comment is enough (or you can say so on discord) that you are working on this. We are really bad at keeping the issue assignees updated, anyway.

**Comment by turoni** [comment]
Okay, good to know

**Comment by turoni** [comment]
I have made a fix locally with the limited knowledge I have gathered from studying the angel scripts.
I do not know enough about the mechanics yet to effectively test this out but feedback might teach me on what I should have used instead.

What is the recommended flow? Creating a branch on which I commit my fix and that can be reviewed?

**Comment by hhyyrylainen** [comment]
Once you are ready you'll need to fork (as you don't have write access to the main repo yet), create a new branch in your fork and make a pull request from it.

**Comment by hhyyrylainen** [comment]
Fixed by: https://github.com/Revolutionary-Games/Thrive/pull/745

**Comment by hhyyrylainen** [comment]
This still needs a check for bacteria to have their hex size reduced by 50% when checking.

**Comment by turoni** [comment]
Can you elaborate on where the reduced needs to happen?
Is it just while the comparison is happening that one of the two needs to have their totalHexCache * 0.5 ?

**Comment by hhyyrylainen** [comment]
I would add the reduction after this bit:
```
        int firstMicrobeComponentHexCount = firstMicrobeComponent.totalHexCountCache;
        int secondMicrobeComponentHexCount = secondMicrobeComponent.totalHexCountCache;
```
Something like:
```
if(first microbe is bacteria)
    firstMicrobeComponentHexCount /= 2;
```
(this isn't actual code)

and then the same thing for the second. (I wouldn't use float division or multiplication as it's I think fine if something with 1 hex has 0 engulfing size)

**Comment by turoni** [comment]
Okay, thanks. That tells me enough to investigate further.

**Comment by turoni** [comment]
I created a new branch from the master https://github.com/Revolutionary-Games/Thrive/commit/d5b85c75a02c7e79aa80c5c5a4e038e8c67b807d
Does this contain everything you mean?

**Comment by turoni** [comment]
Due to problems I had in my branch I created a second branch which had everything I need, hopefully I get better at git in the future but it solved my issues this time.
https://github.com/Revolutionary-Games/Thrive/commit/7e057af7a04f29c6936cb6ab8c6ef16f6a50693f
This branch contains the check on bacteria an reduction by 50%

**Comment by turoni** [comment]
https://github.com/Revolutionary-Games/Thrive/commit/4ad3a617994a07099d14964909dc8d38c13cc219 adds the caching and removes the expensive calls.

**Comment by hhyyrylainen** [comment]
Only thing missing is updating the isBacteria flag for when the editor is exited.

**Comment by turoni** [comment]
Like this: 913b45568ad9e2018111e3854666085aa5665d09 ?

**Comment by turoni** [comment]
I added the update to restoreOrganelleLayout
All locations I could find that this is called seemed like a good place to update isBacteria

**Comment by hhyyrylainen** [comment]
I think that does work. But the species is updated when leaving the editor (check the editor exiting code).
It's not optimal to have similar things in different places. But I suppose it's fine.
You should open a pull request so that people notice your changes need testing.
