### ISSUE TITLE
[Windows] symbolic link: Error missing file or accessing cache location

### ISSUE THREAD

**Issue by xuefer** [Revolutionary-Games/Thrive#730]
windows 10
c:\disks\app is a mounted disk
c:\app\games is symbolic link to c:\disks\app\games
Thrive-0.4.0.2-WINDOWS-64bit.7z is unpacked into C:\app\Games\SIM\Thrive

Error missing file or accessing cache location: boost::filesystem::create_directories: The filename, directory name, or volume label syntax is incorrect: "c:/disks\?\Volume{931e6638-1b3d-11e7-8497-bc5ff4acdc0f}\
Args are (1)

**Comment by hhyyrylainen** [comment]
So the problem is that Thrive does not work properly with the weird "symbolic" links on Windows, that expand to some really crazy paths?

**Comment by xuefer** [comment]
yes, works after moving it out of the symlinked/mounted
