### ISSUE TITLE
Suggestion: Improved Organell Selection, Removal, & Preview

### ISSUE THREAD

**Issue by CTH999** [Revolutionary-Games/Thrive#732]
So, right now you look at the organelles, see the one you want to place, place it down, and it forms a... brown hex? So, I think that anything you put down should be the same design as the organelle you selected, but, maybe to separate it, there could be a brown border around it (10 pixels for instance?)

Also, there should be an ability to remove organelles, for a cost. That way, to remove a single flagella you don't have to start the cell completely over.

There should also be a preview showing you what the cell will look like.

**Comment by Untrustedlife** [comment]
You can already remove organelles with a right click.

**Comment by Untrustedlife** [comment]
Also displaying orgranelles in the editor is already planned, we just weren't able to get it done in time for 0.4.0. Also they are already teh same design as the organelle. your mitochondria are two hexes each for example.

**Comment by Untrustedlife** [comment]
The displaying is covered by this issue:
https://github.com/Revolutionary-Games/Thrive/issues/543

**Comment by CTH999** [comment]
Ok, thanks.

What I meant by the same desing was that in the editor, the coloring was the same, and I am glad you'll have other plans. They where just ideas. However, you might want to figure out a way to make the deleting feature easier to find. A removal tool perhaps?
