### ISSUE TITLE
Bacteria should have smaller compound grab radius

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#755]
Right now bacteria has unscaled compound grab radius so they can grab as much compounds as eukaryotes. It should be fixed that the bacteria scale is taken into account also in compound gathering.

**Comment by Untrustedlife** [comment]
sorry dak
i fixed this here:
https://github.com/Revolutionary-Games/Thrive/commit/0493181c20710804bd68d86c072f729757565ebd

**Comment by Untrustedlife** [comment]
Heres the new better one:
https://github.com/Revolutionary-Games/Thrive/commit/380221a24a231be246b89f7d33212915dfb09331

**Comment by Untrustedlife** [comment]
(I needed something for todays dev build and i couldnt get chunks varying by biome in today)

**Comment by Untrustedlife** [comment]
(I also forgot you were working on this lol)
