### ISSUE TITLE
The player should be the only initial species

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#761]
- [x] player is the only initial species
- [x] doesn't apply to freebuild
- [x] species need to sometimes split off also from the player

**Comment by crodnu** [comment]
Currently the player isn't affected by auto evo, so that would need to be changed first i think (unless we have another species with only one hex of cytoplasm for the ai but then the ai would only branch off from the player at the start and they would risk extinction).

**Comment by hhyyrylainen** [comment]
Good point. Added one more subtask.

**Comment by TjWhale** [comment]
I was imagining that the player would choose to split their own species and then choose which of the "child" species they would play. The other would be ai controlled. 
So for the first few editor sessions there is only the player's species and no ai species and then as soon as a split occurs an ai species is created. Would that solve this issue?

**Comment by hhyyrylainen** [comment]
Why would the player choose to split their species? I think the splitting needs to happen automatically and not be something the player can just avoid.

**Comment by Untrustedlife** [comment]
Maybe any time you reproduce it automatically splits your species since you are adding stuff in the editor this would mean you are competing with evolving ancestors and it means your competitors would be at least as competitive as you

**Comment by Untrustedlife** [comment]
And we will need to change the mutation code.

**Comment by Untrustedlife** [comment]
We dont have freebuild which is the middle part of this issue
