### ISSUE TITLE
Make all new species split from existing ones

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#762]
Instead of being randomly generated.

**Comment by TjWhale** [comment]
[Here](https://forum.revolutionarygamesstudio.com/t/population-system-species-splitting/494?u=tjwhale) is the discussion on species splitting. I think we can't please everyone so doing something basic to start with would be good.

**Comment by Untrustedlife** [comment]
This nessessesitates adding the ability for species to evolve new types of membranes if we want to have the current variety(they cannot right now) Which likely means starting the player off with a cell wall and allowing them to add it in a very basic iteration of the appearance editor I think.

**Comment by TjWhale** [comment]
If the ai can evolve different membranes then they'll still come into the world right? I don't think we need to player appearance editor other than for if the player wants to add one to their species.

**Comment by Untrustedlife** [comment]
Am starting on this.
