### ISSUE TITLE
Species should respond to the patch they are in

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#766]
Instead of having randomly their population altered the species should instead calculate their population gain / loss based on how well adapted they are to the conditions of the patch they are in.

This should be done at the same time as the proper CPA system is started. And this should definitely be ran in the background to reduce current lag spikes.

**Comment by TjWhale** [comment]
[Here](https://forum.revolutionarygamesstudio.com/t/new-cpa-system-with-auto-evo/498/15?u=tjwhale) is an algorithm for having population numbers respond to patch conditions. Feel free to ask about it if you have any questions.

**Comment by hhyyrylainen** [comment]
The basic auto-evo framework is now done, and should allow making a proper population calculation that takes patch conditions into account.

**Comment by hhyyrylainen** [comment]
We probably need this for species splitting or at least removing really inept species from the game.

**Comment by hhyyrylainen** [comment]
Seeing as @NickTheNick's auto-evo algorithm is probably going to take still some time, maybe we need some simple algorithm designed to handle calculating how well a species does given some environmental constraints?

**Comment by Dak2896** [comment]
Could be the case that by resolving #788 to calculate the dynamic tooltips and atp bar in the GUI we will able to calculate for each species the atp production/consumption?

**Comment by hhyyrylainen** [comment]
Maybe. Knowing the ATP balance could certainly be used to penalize species that don't have a positive ATP balance.

**Comment by hhyyrylainen** [comment]
As no simple algorithm to implement showed up, and I don't feel like making something temporary from scratch, I'm going to throw this issue out of the next release.

**Comment by hhyyrylainen** [comment]
This is impeded by the auto evo algorithm not being done: https://forum.revolutionarygamesstudio.com/t/nicks-auto-evo-algorithm-episode-1/629

**Comment by hhyyrylainen** [comment]
Basic prototype was added.
