### ISSUE TITLE
Reduce the amount of lag after playing a while

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#767]
Right now a lot of lag is probably caused by the microbe and AI systems. 

- [ ] They should be made more efficient or run at longer intervals.

- [ ] Multithreading could help here, but as these are quite tightly coupled to the GameWorld logic this needs to be done *very* carefully

**Comment by Untrustedlife** [comment]
I will definetly at least be able to tackle the first half, i havent done too much multithreading in c++ though.

**Comment by MkazemAkhgary** [comment]
I got to about 1-2fps but the game is only using 15% of processor power and 10% of iGPU on 6700k, seems like it could utilize more power via multi threading.

**Comment by Untrustedlife** [comment]
I have improved efficiency a bit, im sure theres plenty more ways to improve effieiency.

**Comment by Untrustedlife** [comment]
(In my branch, https://github.com/Revolutionary-Games/Thrive/tree/768_and_737)

**Comment by hhyyrylainen** [comment]
The new auto-evo I wrote doesn't have a cap on species.
Also having a cap on the number of alive cells could help. With that we'd need to make sure that all the species got a certain fraction of that cap in proportion to their populations.

**Comment by hhyyrylainen** [comment]
Maybe even moving some of the major time using systems to C++ would help.

**Comment by TjWhale** [comment]
Do we have any kind of profiling for the game which shows which functions are taking a long time? It might be interesting.

**Comment by hhyyrylainen** [comment]
There's no profiling other than F3 showing if rendering or logic is taking longer. I've used a normal profiler to get a some kind of picture (which was if I remember correctly) that scripts take longer than all the C++ systems. BSF has some kind of profiler which might be usable. But it would be really hard to write a new simple included profiler either.

**Comment by hhyyrylainen** [comment]
Finding what is causing the lag depends on: https://github.com/Revolutionary-Games/Thrive/issues/890

**Comment by hhyyrylainen** [comment]
I'm going to take a guess that the Godot version may not accumulate lag the same way, so I'm closing this.
