### ISSUE TITLE
Generate the process list again whenever the organelles of a cell change (At least for the player)

### ISSUE THREAD

**Issue by Untrustedlife** [Revolutionary-Games/Thrive#768]
In order to resolve the issue where your duplicated organelles dont do processes we need to generate the process list again whenever the organelles of a cell change.

**Comment by hhyyrylainen** [comment]
Based on the report here: https://community.revolutionarygamesstudio.com/t/0-4-1-release-candidate-testing/1599/39?u=hhyyrylainen

This will also resolve: https://github.com/Revolutionary-Games/Thrive/issues/703

**Comment by OBPSG** [comment]
I may as well ask this question because someone has to: What kind of impact will this change have on performance?

**Comment by hhyyrylainen** [comment]
Probably some. But I don't see a way around it. Unless we up memory consumption by a huge amount and cache a process list for every single cell state to only have to generate each list once.
