### ISSUE TITLE
Drag force shouldn't affect ATP use

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#769]
I've seen multiple reports about consuming ATP while getting pushed. I now looked at the code and from a quick look it looks like that the way the drag is applied to moving cells that is counted as movement force that costs ATP. So it should be applied separately without adding to the ATP cost.

Hopefully this is not a duplicate issue.

**Comment by Gilbrilthor** [comment]
I'm going to see if I can tackle this for a first bug. I'll have to set up my build environment first, but I think I can swap the order and fix this.

**Comment by Untrustedlife** [comment]
@Gilbrilthor  any news?

**Comment by Gilbrilthor** [comment]
I've been struggling to get it to compile on my end due to it complaining about boost.

I took a look at the code and have a good idea what to change, but I haven't gotten that far.

Although, if it's in the angel script, could I change that from the release build installed by the launcher?

**Comment by Untrustedlife** [comment]
I have fixed this in my branch

**Comment by hhyyrylainen** [comment]
I looked at the code some time ago, and (if I remember correctly) there's one more thing to do:
it now checks if the cell is attempting to move and then deducts ATP, so I think if you get pushed you will use more ATP. So the check should be split so that only the basic movement contributes to ATP usage (and not the resulting force).
