### ISSUE TITLE
Compound amounts can exceed storage

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#770]
https://community.revolutionarygamesstudio.com/t/compound-bug/1666

So basically sometimes the player has more of glucose than their max storage capacity.

**Comment by Untrustedlife** [comment]
Am fixing this in my branch now

**Comment by Untrustedlife** [comment]
Its fixed, ill push my changes, basically the game didnt think about the case where you have too many compounds. Now it does. (To be more accurate, i didnt think about that case when i reimplemented the purgecompound code)

**Comment by Untrustedlife** [comment]
https://github.com/Revolutionary-Games/Thrive/tree/768_and_737

**Comment by Untrustedlife** [comment]
should i close this? Since its  fixed in my branch?

**Comment by hhyyrylainen** [comment]
I suppose you can. It's just that I think issues should be closed once they are surely included. There's likely only a tiny chance that your branch doesn't end up being merged.
