### ISSUE TITLE
Minor Changes to Interface Wording

### ISSUE THREAD

**Issue by NickTheNick** [Revolutionary-Games/Thrive#774]
Iron Ions rewritten as Iron, Phosphates rewritten as Phosphate, subscripts added for O2 and CO2.

As discussed here: https://forum.revolutionarygamesstudio.com/t/personal-feedback-on-0-4-1/599

**Comment by Untrustedlife** [comment]
Fixed here:
https://github.com/Revolutionary-Games/Thrive/commit/79496dc517532667b85ee0ca7513cd70cfbb309f
![image](https://user-images.githubusercontent.com/4032123/56336487-3f6a4b80-6166-11e9-86a1-004bcc454764.png)
