### ISSUE TITLE
Fix nitrogenase offset in editor

### ISSUE THREAD

**Issue by NickTheNick** [Revolutionary-Games/Thrive#775]
As discussed in this thread:

https://forum.revolutionarygamesstudio.com/t/tooltips-update-for-0-4-2/605

Nein99 is working on updating the GUI at the moment and I can help out with the tooltips to learn more about how the UI works.

**Comment by NickTheNick** [comment]
Progress updates on this are on the linked thread as well as suggestions for future improvements/features. 

Some of the main bugs that should probably be resolved (pictures on the forum link): 
-There is a very weird bug with the Nitrogen Fixing Plastid, and I have no idea why
-Nitrogenase Protein icon in the organelle menu is offset by a few pixels for some reason
-Fix text overflow bug

**Comment by Untrustedlife** [comment]
Fixed the bug with the plastid and the text overflow bug aswell on my branch

**Comment by Untrustedlife** [comment]
https://github.com/Revolutionary-Games/Thrive/tree/thrive_chunk_improvements

**Comment by Untrustedlife** [comment]
nitrogenase protein is still offset

**Comment by Untrustedlife** [comment]
This is now fixed.
https://github.com/Revolutionary-Games/Thrive/pull/782
