### ISSUE TITLE
The process list update needs cleanup

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#781]
There's now a few issues after https://github.com/Revolutionary-Games/Thrive/pull/780 left to resolve:
- [x] When the player dies the process list isn't reset, also when a cell finishes splitting it isn't done. So the recreation of the process list should be added to the resetOrganelleLayout function.
- [x] There are two copies of the process list generation code. They should be merged

**Comment by Untrustedlife** [comment]
Ill work on this and making all cells descend from player species now

**Comment by Untrustedlife** [comment]
Got the first half done in my branch so far

**Comment by Untrustedlife** [comment]
Okay this is now fixed in my branch
