### ISSUE TITLE
Remake lost models

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#787]
Some models we only have the Ogre .mesh files for. For the graphics engine change these need to be redone.

- [x] ER
- [x] golgi
- [x] vacuole
- [x] mitochondrion
- [x] nucleus
- [ ] icecrystal (done but MIA) there is now one ice crystal model

**Comment by Uniow** [comment]
Here are all the redone models, they might not be final if something looks off.
https://drive.google.com/file/d/1MaMw9E_dJeRKI0B9YhZ-gZh2OQQbGkiD/view?usp=sharing

**Comment by hhyyrylainen** [comment]
I think all of the models might be fine now. There's a few still that don't match with the organelle names. But I'll close this for now.
