### ISSUE TITLE
When undoing an organelle placing it doesn't restore cytoplasm

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#789]
**Describe the bug**

**To Reproduce**
1. Place an organelle on top of cytoplasm in the editor
2. Click the undo button
3. Observe that the organelle is removed but cytoplasm doesn't come back

**Expected behavior**
Cytoplasm should be replaced when undoing. There is already a TODO comment in the code

**Additional context**
https://community.revolutionarygamesstudio.com/t/the-new-miscellaneous-talk-that-doesnt-deserve-a-new-thread-thread-thread/41/2241?u=hhyyrylainen

**Comment by Dak2896** [comment]
Ok i understand how should work, my bad english didn't help me to understand, I try fix it correctly now.

**Comment by Dak2896** [comment]
I'm working fix it on branch undo-cytoplasm and this happen:
1 - Place cyto
2 - Place something other (cyto is deleted)
3 - Uno, organelle is removed (cyto is palced)
4 - From this point redo replace organelle on cyto but make undo cause crash:

![image](https://user-images.githubusercontent.com/28767492/65877759-b732d800-e38c-11e9-8de1-1f7b3bc0bde8.png)


What it could be? i'm making something with handle i guess but i cannot understand what.

**Comment by hhyyrylainen** [comment]
I get a segmentation fault doing that. It doesn't trigger immediately, but rather the next time AS does garbage collection. I was able to verify that the object type that is incorrectly deleted before the garbage collector reads its properties is PlacedOrganelle.

**Comment by hhyyrylainen** [comment]
Looking at the code, this is suspicious:
`action.data["replacedCyto"] = organelleHere;`
to me it looks like you are doing an assignment operation here instead of a handle copy which would be:
`@action.data["replacedCyto"] = organelleHere;`
This is actually a problem I've reported to the AS developer that I'd like to get some AS compiler error here, but so far that hasn't happened (or I haven't updated AS).
