### ISSUE TITLE
Intel graphics crashes need fixing

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#804]
It seems that some intel hd graphics versions don't work with bsf, directx11 api. But some even old intel hd graphics versions do work (albeit being very slow, hopefully I get a response here: https://discourse.bsframework.io/t/improving-rendering-performance/498). So investigating and reporting these crashes to bsf should be done. Hopefully they can guarantee that newer than certain threshold intel graphics could be made to work.

**Comment by hhyyrylainen** [comment]
There is now this thread: https://discourse.bsframework.io/t/bsf-fatal-error-when-running-a-program-on-windows/510
So basically we need to wait / motivate the bsf developer to fix it.

**Comment by hhyyrylainen** [comment]
A test build should be made that could use the forward rendering path in bsf to see if that works or not: https://discourse.bsframework.io/t/bsf-fatal-error-when-running-a-program-on-windows/510/10?u=hhyyrylainen

**Comment by hhyyrylainen** [comment]
We got about 40 reports on the first day after 0.4.2 release, about crashing with intel graphics. And that's with about 300 total downloads. So quite a large fraction of potential players have this issue.

**Comment by hhyyrylainen** [comment]
The main report for this issue is: https://dev.revolutionarygamesstudio.com/report/30
and there are 174 duplicates.

**Comment by Dominatat** [comment]
hhyyrylainen I found the issue how can I contact you? I have a stopgap fix I can give to you.

**Comment by hhyyrylainen** [comment]
It's a bit late to have a fix for this issue: https://forum.revolutionarygamesstudio.com/t/switching-to-godot/663

I've left all issues open for now until the Godot version gets merged into master.

**Comment by Dominatat** [comment]
Alright
