### ISSUE TITLE
Make music use streaming audio

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#808]
Right now there is maybe a slight lag spike when a new track starts playing as it is entirely (maybe) loaded into memory on the main thread.
Would be nice to add a streaming audio version to the engine and use that for the music.

**Comment by izhuravlev** [comment]
Hi @hhyyrylainen,
I can take a look at this one. Can you provide me with more information on how to start contributing to your project and how can I start on this bug?

**Comment by hhyyrylainen** [comment]
You can find the setup instructions in the doc folder: https://github.com/Revolutionary-Games/Thrive/blob/master/doc/setup_instructions.md

This issue is tagged 'engine' because I think this needs changes to https://github.com/hhyyrylainen/Leviathan/tree/develop
The sound playing system needs a new method to start an audio stream with the Alure stream decoder (instead of the entire stream at once). Which then needs to be used by the music playing methods in the Thrive scripts.

We have a pretty normal, I think, fork workflow: https://gist.github.com/Chaser324/ce0505fbed06b947d962
Other than that when making a pull request make sure that all the formatting is fine, we have CI setup to enforce that. We also have a RunCodeFormatting.rb script which can be used to locally do the formatting (with the right tools installed).
