### ISSUE TITLE
Organelle rotation in the editor is now weird

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#816]
Related to: https://github.com/Revolutionary-Games/Thrive/issues/813
rotating organelles is a bit weird now in the editor, probably another issue with the rotation code, likely similar to what causes the flagella to be weird.

**Comment by Untrustedlife** [comment]
Ill grab this as my first pr after awhile

**Comment by hhyyrylainen** [comment]
The latest branch is https://github.com/Revolutionary-Games/Thrive/tree/patches

**Comment by Untrustedlife** [comment]
Not master?

**Comment by hhyyrylainen** [comment]
Actually, I think the organelle rotation changes are there too... yeah, please ignore.

**Comment by Untrustedlife** [comment]
I fixed the rotations, the offset is still a little bit wrong but I improved it significantly

**Comment by Untrustedlife** [comment]
https://github.com/Revolutionary-Games/Thrive/pull/818

**Comment by hhyyrylainen** [comment]
This was improved by: https://github.com/Revolutionary-Games/Thrive/pull/818 but they are still rotated a bit weird. For example many of the organelles at their default rotation are positioned very differently than once rotated 360 degrees, which is strange.

**Comment by hhyyrylainen** [comment]
@Untrustedlife will you work more on this or can I clear you being assigned?
