### ISSUE TITLE
Deleting organelles in the editor with right click is broken

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#819]
When trying to delete organelles the MP cost is deducted but the organelle doesn't visually disappear. But it might be possible to place new stuff then over it?

**Comment by untrustedlifeswanleap** [comment]
Interesting, i think this is a visual bug becaus eit was working before

**Comment by Dak2896** [comment]
I think to solve it it works just call _updateAlreadyPlacedVisuals() at the end of removeOrganelleAt().
From my test seems works.

**Comment by hhyyrylainen** [comment]
Does that work with undo and redo? I think that the update call needs to be placed within the actions themselves.

**Comment by Dak2896** [comment]
Not yet, i was opening new issue about that, because if:
1 - put two organelles 
2 - make undo
3 - delete one with right click
4 - go undo until 100 MP
5 make redo until finish

The situation is we have -10 MP and only the organelle that we didn't right click on

**Comment by hhyyrylainen** [comment]
The model now visually disappears correctly, but there is one further issue with the editor not handling redo undo steps correctly.
