### ISSUE TITLE
Rename the JSON files

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#821]
The thrive naming convention is snake_case so it would be nice to have the simulation parameters json files also follow that.

For example `thrive/scripts/SimulationParameters/MicrobeStage/BioProcesses.json` -> `thrive/scripts/simulation_parameters/microbe_stage/bio_processes.json`

Other than renaming files the code that loads the json files need changes to use the new names.

**Comment by sowmiyamuthuraman** [comment]
Can I work on this?

**Comment by hhyyrylainen** [comment]
Yes, you are free to help with this.
