### ISSUE TITLE
Player taking damage sound doesn't play

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#837]
The player taking damage sound does not play (or it plays so low volume that it's not audible).
Would be nice to alert the player with it.

**Comment by ShimmyShaman** [comment]
```
if(damageType == "toxin"){
            // Play the toxin sound
            playSoundWithDistance(world, "Data/Sound/soundeffects/microbe-toxin-damage.ogg", microbeEntity);
        }
```

I can hear that when it happens. There's no sound played for any other cause of damage (ATP starvation - don't hear any sound for that, there's no '_atp-lack-damage.ogg_'). There is a sound played when the player gets engulfed, thats done elsewhere.

So should this be a request for a sound file for when the player is _starving_?

**Comment by hhyyrylainen** [comment]
Perhaps it is, then. There does not seem to be a separate damage sound from the toxin sound effect.
