### ISSUE TITLE
The current patch in the patch map should be highlighted

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#839]
Right now it looks the same as the other patches. The border colour should be changed to indicate it is the current patch.

**Comment by izhuravlev** [comment]
Hi @hhyyrylainen,
I can try to solve this bug. 
It will be great if you can provide me with more information on this bug.

**Comment by hhyyrylainen** [comment]
This is basically already fixed in: https://github.com/Revolutionary-Games/Thrive/pull/858
That just needs one small tweak before merging.
