### ISSUE TITLE
More patch details should be shown on the map

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#849]
Right now only the species in a patch and the patch name is shown. The environmental conditions should be also shown.

- [x] environmental compounds
- [ ] other compound amounts (important for species that do chemosynthesis which is not available everywhere)
- [ ] chunk details (if there is iron or not)

**Comment by Dak2896** [comment]
I'm going to handle this with the GUI tested some times ago
