### ISSUE TITLE
Rendering issues on AMD (again)

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#851]
One user has commented that they have an AMD graphics card and cannot see the organelles in the editor. Presumably everything else works.

I'm pretty out of ideas here as the organelles being rendered in the editor vs in stage shouldn't be all that different.

**Comment by ShimmyShaman** [comment]
Have AMD graphics card. Can't replicate it. All editor components/organelles show up in editor and in game.

**Comment by hhyyrylainen** [comment]
Then perhaps the user accidentally played that last release and didn't try the RC. I'll leave this open for now but I'll close this later if no one else reports the same issue once 0.4.2 is released tomorrow.

**Comment by hhyyrylainen** [comment]
I have not heard any new reports about this. So I'll consider that this was an incorrect report.
