### ISSUE TITLE
Make escaping from engulfing population effect more accurate

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#861]
It's possible that a species gets the population buff from not actually escaping something that could kill it. The escaping from engulfing effect should be made only apply when a cell escapes something that could actually kill it.
https://community.revolutionarygamesstudio.com/t/0-4-2-feedback-thread/2143?u=hhyyrylainen

I'm also marking this issue as review as I didn't personally verify this.

**Comment by Savalige** [comment]
I have been trying to replicate the issue, but haven't found it to add population unless it takes damage. The problem with some species growing really fast, is most likely due to them going in and out of being engulfed rapidly as there are no timer (atleast what I am aware of) to prevent this.

**Comment by hhyyrylainen** [comment]
Adding a timer for every cell that prevents rapidly adding population effects, would then solve this.
