### ISSUE TITLE
Make editor tooltips dynamic

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#866]
The tooltips should calculate their effectiveness based on the current patch.
I think that we may have to have it so that the GUI loads bioprocesses.json, and organelles.json (depends on: https://github.com/Revolutionary-Games/Thrive/issues/788) and from the received patch map data computes the effectiveness with the currently selected patch (this can't be calculated in C++ because the editor can change the patch and that isn't applied immediately only after the player confirms the choice by exiting the editor).
Also it should have big red letters if the organelle is useless in the current patch (for example thykaloid in the vents).

**Comment by TjWhale** [comment]
I'm not sure if this is crazy but is it possible to compute the organelle effectiveness for all patches as part of updating the patches (like the time we multiply glucose by 0.8) and then storing that info as part of the patch object. That way we could keep the computations on the c++ side. Maybe it's a bad idea to do so much computation and to send it all as Json.

**Comment by hhyyrylainen** [comment]
I suppose it is possible. Doing it while showing the auto-evo loading screen would give quite a bit of time. Probably at least hundreds of milliseconds before the player notices anything. Though, I would guess that this is quite a bit of data. I don't think it is fully possible to say at this point which will be better.
I'll accept either approach if they perform well enough / don't cause problems..

**Comment by Dak2896** [comment]
If we know the selected patch and we load bioprocess.json can we compute an organelle effectiveness just by two things??

**Comment by hhyyrylainen** [comment]
The GUI wouldn't know which processes an organelle does. That's why this depends on: https://github.com/Revolutionary-Games/Thrive/issues/788

**Comment by GatoCreador887** [comment]
Is it not possible to send the processes to the gui from AS?

**Comment by hhyyrylainen** [comment]
There are currently no json bindings for AngelScript in the engine. If there were the process data could be sent.
