### ISSUE TITLE
Being engulfed should debuff movement

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#871]
When a cell is being engulfed it should get a debuff to its movement speed.

**Comment by Dak2896** [comment]
If i understand we want that engulfed make cell slower than the engulfing one right?

**Comment by hhyyrylainen** [comment]
Not sure if that makes sense. I thought that the cell should have a debuff like only being able to move at 50% of their original speed.
@TjWhale could you clarify how this should work?

**Comment by TjWhale** [comment]
The idea is that if you're a big slow cell and you manage to get a small fast cell into your membrane then it should be close to impossible for the small one to escape.

On the branch ai_changes I managed to use the isBeingEngulfed toggle to make some progress with this I think. So try that branch first to see what you think, the cells run away pretty effectively but stop moving if they are caught.

**Comment by hhyyrylainen** [comment]
This doesn't look like it'll get done for next release.

**Comment by GatoCreador887** [comment]
I am pretty sure this already happens.
https://github.com/Revolutionary-Games/Thrive/blob/91b98bd736858c0c5f3165db02cb338891fda166/scripts/microbe_stage/microbe.as#L378
https://github.com/Revolutionary-Games/Thrive/blob/91b98bd736858c0c5f3165db02cb338891fda166/scripts/microbe_stage/microbe.as#L379

**Comment by hhyyrylainen** [comment]
I think that is the code that *used* to work but doesn't anymore due to physics engine differences. At least I think that is the case.

I remember the movement debuff being very significant and there is like none ATM.

**Comment by GatoCreador887** [comment]
This does in fact work. `ENGULFED_MOVEMENT_DIVISION` is just too low right now to be noticeable. I raised it to `50` and engulfed cells almost completely stopped moving.

**Comment by hhyyrylainen** [comment]
Okay, so this can be solved by a PR just tweaking the `ENGULFED_MOVEMENT_DIVISION` constant.

**Comment by Kasterisk** [comment]
I'm just gonna create the PR for this.
