### ISSUE TITLE
GLIBC is missing

### ISSUE THREAD

**Issue by CStafford-14** [Revolutionary-Games/Thrive#882]
I'm running the latest version of Thrive on Ubuntu 18.04.03 on GNOME 3.28. I have a Dell Inspiron R17 N7110 with an Intel Core i5 and NVIDIA GeForce 525M.

When running Thrive for the first time, I get this error.

> ERROR: /home/--USER--/.config/Revolutionary-Games/Launcher/Installed/Thrive-0.4.2.0-LINUX-generic/Thrive-0.4.2.0-LINUX-generic/bin/Thrive: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/--USER--/.config/Revolutionary-Games/Launcher/Installed/Thrive-0.4.2.0-LINUX-generic/Thrive-0.4.2.0-LINUX-generic/bin/lib/libavutil.so.55)
child process exited with code 1

I can't find GLIBC on my device, nor can I find an installable version (Via the terminal). I'm pretty sure this issue has been reported before, but I've found no answers or outdated posts. So I'll ask it again in 2019: What's going wrong with GLIBC?

**Comment by hhyyrylainen** [comment]
Glibc is tightly coupled with the program loader (ld) on Linux. I've read quite a bit about this and from what I understand it is not possible to easily have multiple versions of glibc installed. It is theoretically possible to have multiple glibc versions (or for us to bundle the required glibc version), but it is very difficult: https://unix.stackexchange.com/questions/62940/how-to-run-new-software-without-updating-glibc

The ubuntu version you are using has glibc version `2.27` And as the versions are not forward compatible the program can't run (without a lot of tweaking, see the link above).
It is possible to recompile the game with an older glibc version, but you'll need at least GCC 8.3 (which is also not provided by ubuntu 18 by default).

I've been hoping to make a flatpak version, that can easily use bundled dependencies, at some point, but haven't gotten around to it. Hopefully the freedesktop base image has new enough GCC for our use...

I'm closing this issue as the release notes mention that glibc 2.28 is required for running the precompiled releases.
