### ISSUE TITLE
Right-click freezes the game

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#883]
For some reason right click in the GUI (probably not in the editor) freezes the game on windows.
On Linux it spams logs with:
```
[1020/202743.917484:WARNING:x11_util.cc(1422)] X error received: serial 275, error_code 3 (BadWindow), request_code 4, minor_code 0 (Unknown)
[1020/202744.433515:WARNING:x11_util.cc(1422)] X error received: serial 402, error_code 3 (BadWindow), request_code 4, minor_code 0 (Unknown)

```

It's probably some CEF related thing trying to open a non-existing context menu.

**Comment by Kasterisk** [comment]
I think the simplest solution is adding `oncontextmenu="return false;"` to the gui html body tag, it seems to disable the context menu for me when I test it. Would this somehow be a proper fix?

**Comment by hhyyrylainen** [comment]
I suppose it would at least make the issue not able to be triggered. I think that CEF has some default handler callback that should be used to block the context menu, properly. But I've been looking at changing away from CEF due to various issues, so I'd accept a PR just adding that (as long as it doesn't break the remove organelle in editor, which is bound to right click).

**Comment by Kasterisk** [comment]
Interesting, but in the meantime this could be a temporary fix. About the removing organelle, it should probably not affect that, as there is no GUI over the cell viewer screen.

**Comment by hhyyrylainen** [comment]
You should test if the fix doesn't break anything and then open a PR.

**Comment by Kasterisk** [comment]
Ok, I've found no problems so far. I will open a PR.
