### ISSUE TITLE
Tweak timings for variable update rate

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#888]
With the new variable rate updates some systems are now running at slightly different speeds than before. These should be rebalanced

**Comment by TjWhale** [comment]
Some things included in this:
- [ ] cell movement (needs to be not too fast for small prokaryotes and not too slow for large Eukaryotes)

- [ ] The amount the membrane wiggles (though this might change after changing the movement, also a lot of wiggling is quite nice)

- [ ] The rate the cell turns, it is close to instant now and should be slower, more fluid. This should remain constant for all cells.

- [ ] The rate glucose is used is a bit high so maybe that will need rebalancing too, though that is hard.

**Comment by hhyyrylainen** [comment]
The membrane wiggle isn't coupled to the new update rate. The default membrane has some always happening wiggling, but **also** it has the membrane world position added to it, so moving through the world increases the wiggle amount. The wiggle amount per world unit travelled can be changed, but movement speed will always have an effect on it.


Making the process system run slower will reduce glucose usage rate.

**Comment by hhyyrylainen** [comment]
Once there's https://github.com/Revolutionary-Games/Thrive/issues/866 it will be much easier to just tweak the numbers a bit to make wanted kind of cells viable.

**Comment by hhyyrylainen** [comment]
I'll just close this, the generic rebalance issue can also serve the purpose for keeping track of this.
