### ISSUE TITLE
Pilus should block toxins and floating chunks

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#893]
Right now hitting a pilus with a toxin counts as hitting the cell, instead it should deflect the toxins.
Also the floating chunks that do damage shouldn't count hitting a pilus.

**Comment by Dak2896** [comment]
Are all Pilus issues closed?

**Comment by hhyyrylainen** [comment]
At least this should be closed. I think there is one more about needing to make engulfing cells that have a pilus harder.
