### ISSUE TITLE
Remove keypress logs

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#900]
They aren't very useful for anything and cause log spam.
The cheat key pressed can be kept (but if whoever fixes this wants to go above an beyond this could be changed to print the cloud cheats once, but editor cheat should always print to log).

**Comment by UltimaBGD** [comment]
I can take a look at this if you want.

**Comment by hhyyrylainen** [comment]
If you could work on this, that would be really helpful.

**Comment by GatoCreador887** [comment]
The ones for cheat keys are in `PlayerMicrobeControl::ReceiveInput` and for toxins and engulfing look at `PlayerMicrobeControlSystem::Run`.

**Comment by UltimaBGD** [comment]
Just to make sure, the editor cheat that should always print to log is this one?

https://github.com/UltimaBGD/Thrive/blob/6ad9bb42b3923a8da68e151a2da368ac9d48001d/src/microbe_stage/player_microbe_control.cpp#L70-L74

**Comment by UltimaBGD** [comment]
I have seen a few additional keypress logs across the files, like the screenshot key in global_keypresses.cpp, which I think makes sense, There is also right and left in microbe_editor_key_handler.cpp that I see. Do any of those fall under this issue?

**Comment by hhyyrylainen** [comment]
I think that rotating in the editor, does fall under this issue. Screenshot does not.
