### ISSUE TITLE
Report report 174 to bsf

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#903]
These reports are about some directx API failing: https://dev.revolutionarygamesstudio.com/report/174
we can't do anything else than report this to bsf.

**Comment by GatoCreador887** [comment]
Should this be left open, even though bsf is put on the backburner and we are trying to move to diligent?

**Comment by hhyyrylainen** [comment]
I'll close this, as well as the crash reports related to bsf once we have some kind of new graphics engine working and (maybe) merged to master.
