### ISSUE TITLE
Game does not start; libGL error: failed to load driver: nouveau

### ISSUE THREAD

**Issue by DetonDev** [Revolutionary-Games/Thrive#907]
A bug that occurred when I tried to play Thrive after downloading the launcher. Instead of starting the game, the launcher displayed an error log.

1. Go to Thrive launcher
2. Click on 'Play 0.4.2 (Current) Linux x64'
3. See error

I ran Thrive on Xubuntu 19.04
Graphics card used: NVIDIA GeForce GTX 1050 Ti
The Thrive version I ran was 0.4.2

Log:
https://pastebin.com/jcn9kR8T

**Comment by hhyyrylainen** [comment]
I'm seeing a lot of `libGL error: failed to load driver: nouveau` in there, so this might actually be graphics driver related issue. I personally use the nvidia proprietary drivers and they work fine with thrive.
Did the game generate a crash dump file? I'd be interested in that.
https://dev.revolutionarygamesstudio.com/crashdump-tool

**Comment by DetonDev** [comment]
> Did the game generate a crash dump file? I'd be interested in that.
> https://dev.revolutionarygamesstudio.com/crashdump-tool

No, not that I can see.

**Comment by GatoCreador887** [comment]
I also use nvidia drivers and I don't have trouble.

**Comment by hhyyrylainen** [comment]
I'm heavily leaning towards this being a problem with CEF not starting (those libgl load error messages), and not anything to do with the last line printed in the logs. If the game segfaulted inside the engine code or thrive code, it *should* in all cases generate a crash dump. So I very much doubt the last printed log message has anything to do with the game not starting.

**Comment by DetonDev** [comment]
Alright, so I fiddled about with my driver software to see if I could get the error to go away, and it got a little further before throwing up a new error. This time, it did generate a .dmp

I used the Thrive crashdump tool to get this text: [https://pastebin.com/6a1PP4aQ](url)

**Comment by hhyyrylainen** [comment]
So the start of the callstack is: `Thrive!google_breakpad::ExceptionHandler::SimulateSignalDelivery(int)`
which indicates that the graphics engine ran into a fatal condition. That condition should be printed to the log file.
But I'd guess that the problem is that some opengl operation failed, so there's likely still some driver problems.

**Comment by hhyyrylainen** [comment]
I don't think this is a problem we can fix as this seems like a driver issue.
