### ISSUE TITLE
Add unlock conditions for organelles

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#910]
It's pretty overwhelming to have a ton of organelles unlocked from the start, we should implement conditions for unlocking organelles, like needing to be in a light biome to get thykaloids, getting engulfed or engulfing another cell to get a pilus, that sort of thing.

**Comment by TheRexYo** [comment]
Well, the easiest way to implement that would be to have it detect what the current patch map is, right? Afterwards, it could probably unlock the organelle with a global-style variable of some kind, so that all scripts can detect if it's enabled.

**Comment by hhyyrylainen** [comment]
The `PlayerData` class already contains a `LockedMap& lockedMap();` that has the functionality for having unlocks, it was used before for unlocking the chloroplast but that was removed.

As to where the unlock would be triggered, I think somewhere like `PatchManager::applyPatchSettings()` would be good
