### ISSUE TITLE
Smooth out the jitter in player movement

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#911]
I just noticed when playing thrive for a bit that when zooming in there is noticeable jitter in the player cell movement while moving, but everything else seems smooth. Some possible things that are a problem:
- the applied drag causes the jitter (and it needs a bigger cutoff value)
- some interpolation in the camera movement and the cell movement result in the jitter

**Comment by Kasterisk** [comment]
It seems to be the camera interpolation, dividing elapsed time with `CAMERA_FLOW` in this line https://github.com/Revolutionary-Games/Thrive/blob/1b3556a917b757d22d19485c060b6fb2c83a93a6/src/microbe_stage/microbe_camera_system.cpp#L60
reduces most of the noticeable jitter, but there are still some small twitchiness happening.
