### ISSUE TITLE
Pilus should block being engulfed more often

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#918]
One more thing to fix about the pilus that I noticed: if you enter engulf mode you can quite easily start engulfing an AI cell with a pilus, and once you start engulfing the collision with the pilus is ignored, so the cell being engulfed can no longer use it to defend itself.

One possible fix is to modify the AI to take advantage of the pilus by pointing it towards potential attackers, right now the AI has no clue if it has a pilus or not.

**Comment by 84634E1A607A** [comment]
Seems https://github.com/Revolutionary-Games/Thrive/pull/3106 makes this more serious.

**Comment by hhyyrylainen** [comment]
With the new physics and ECS this should get a new look.

**Comment by hhyyrylainen** [comment]
Based on my recent gameplay testing experiences, I'd say this is pretty much fixed as I've not seen any cells get engulfed through a pilus when no other cell parts are touching.
