### ISSUE TITLE
Segment the ATP balance bar

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#921]
The actual data sent to the GUI includes a breakdown of which organelle types use how much ATP. The bars should be changed to have these separate parts, as well as tooltips saying what the parts are.

**Comment by DonGororo** [comment]
We have these concepts for the bars. The bar sections should be hideable so the player can understand better how each process affects ATP consuption.
![bars](https://user-images.githubusercontent.com/59174955/71366715-23476580-25a3-11ea-84ee-361d5bce9504.png)

**Comment by hhyyrylainen** [comment]
There was some confusion on what it means that a section is hideable. This is what I think it means:
> I think it means that clicking one of the bar sections should make it inactive so that you can see what the atp balance would be without that particular cost or production

**Comment by hhyyrylainen** [comment]
Comment from discord:
```
all a basic implementation needs is: loop all the entries in the production and consumption maps, make bars out of them showing either an icon or the group name, select colours somehow, and then make that the ATP balance bars. The hardest parts are picking the colours and making sure the icon / name is hidden when the bar is short
```

adding tooltips and making the individual bars toggleable can be a separate issue
