### ISSUE TITLE
Membrane types should have effects

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#922]
The different membrane types should have different effects.
The different effects have not been designed yet. I'm opening this issue to keep track of this.

**Comment by buckly90** [comment]
Single Membrane:
++Mobility
++Osmoregulation Cost

Double Membrane:
+Mobility
+Osmoregulation Cost
+Health

Celluose Wall:
-Mobility
-Osmoregulation Cost
+Health
+Physical Resistance

Chitin Wall:
-Mobility
-Osmoregulation Cost
+Health
+Toxin Resistance

Calcium Carbonate (This stuff is actually really complex jeez, so have a fusion):
--Mobility
-Osmoregulation Cost
++Health
+Physical Resistance
+Toxin Resistance

Fluidity/Rigidity Slider:
Increments will be smaller than base membrane stats.
Left Side:
+Mobility
-Health
Right Side:
-Mobiltity
+Health

Numeric changes will need to be tested, so put whatever feels right to you and we will see how it goes from there.

**Comment by GatoCreador887** [comment]
I'm assigning myself to this. Some things may be above my skill level to implement, but I will do my best.
Anyone who wants to collaborate on implementing this is free to assign themselves as well.
