### ISSUE TITLE
Report shows negative population when species goes extinct in a patch

### ISSUE THREAD

**Issue by GatoCreador887** [Revolutionary-Games/Thrive#938]
![Primum Myeppiun  |  has a mutation  |  population in patches:  |  Pangonian Tidepool population: -141 previous: 58  |  Pangonian Tidepool population: 13 previous: 150](https://user-images.githubusercontent.com/36546666/73024195-16649e80-3dfb-11ea-9e7d-b41decf6fea6.png)
The population of a species in each patch should never be negative.

**Comment by hhyyrylainen** [comment]
One thing to consider, is that I see two possible fixes:
- the auto-evo (or some extra post process step is added) is changed so that the populations can't go under 0
- the user readable report generation is changed to force < 0 numbers to 0, or replace with the text "extinct".

**Comment by GatoCreador887** [comment]
Reopening because it does not actually seem to be fixed.
![image](https://user-images.githubusercontent.com/36546666/73127805-2368c580-3f94-11ea-8bbb-d645f81a0718.png)
This screenshot was taken after the PR was merged, on a branch including the commit.
