### ISSUE TITLE
Selected organelle is still showing when hovering the cursor on the editor gui

### ISSUE THREAD

**Issue by Kasterisk** [Revolutionary-Games/Thrive#939]
Organelle is still showing on the hex grid, shouldn't it be hidden? looks kinda bit weird to me so I opened a new issue to confirm if this is a real bug.

**Comment by hhyyrylainen** [comment]
Can you share a sceenshot of what you mean? Just to confirm if I interpreted this correctly.

**Comment by Kasterisk** [comment]
Sure, from the image below the cytoplasm is still visible behind the gui.
![Untitled](https://user-images.githubusercontent.com/54026083/73081640-9160ae80-3efa-11ea-9af7-270a827f6df3.png)
It just looks a bit off to me for it to be visible while you were choosing an organelle from the gui panel.

**Comment by hhyyrylainen** [comment]
That's really minor stuff. And it would take a bunch (or at least a bit) of work for the GUI to tell the editor that it should hide the hover hex while over the organelle menu. But I'll let this be open for now.
