### ISSUE TITLE
Outdated win text

### ISSUE THREAD

**Issue by Kasterisk** [Revolutionary-Games/Thrive#945]
It says the 0.4.2 dev build as the current thrive version, the text could be reworded a little and maybe also add some short music or sound effect once you have won? To make it a little more rewarding experience.

> ![wintext](https://user-images.githubusercontent.com/54026083/73166359-49bf6a00-4128-11ea-95a5-5942cc636e3d.png)

**Comment by hhyyrylainen** [comment]
I don't think we should put much effort into changing the current win screen which will be removed at some point.
I do agree that the win text should be rewritten to not make any references to which version of thrive it is.

**Comment by Kasterisk** [comment]
Alright, just editing the text won't be a hassle.

**Comment by mahakbansal2019** [comment]
Hi! @Kasterisk 
I want to work on this?
Can I take this issue?
If yes then from where should I start to solve this issue?

**Comment by hhyyrylainen** [comment]
The win text is here: https://github.com/Revolutionary-Games/Thrive/blob/master/scripts/gui/thrive_gui.html#L218

**Comment by Kasterisk** [comment]
Yes! you are free to work on this issue, it should be in the link given by hhryylainen.

**Comment by mahakbansal2019** [comment]
I just want to make sure that I only need to reword the win text  and remove the version ? @Kasterisk

**Comment by Kasterisk** [comment]
Yes, that will be good enough.

**Comment by hhyyrylainen** [comment]
https://github.com/Revolutionary-Games/Thrive/pull/950
