### ISSUE TITLE
Metabolosome tooltip is incorrect

### ISSUE THREAD

**Issue by fgdfgfthgr-fox** [Revolutionary-Games/Thrive#948]
![TIM图片20200130191437](https://user-images.githubusercontent.com/60460773/73425010-3d8c1480-4395-11ea-9fbd-bbc71a21c234.png)
![TIM图片20200130191443](https://user-images.githubusercontent.com/60460773/73425014-3ebd4180-4395-11ea-857d-c7e7ef50b70a.png)
As we can see, Metabolosomes is suppose to be more efficient than Cytoplasm in terms of energy conversion, but in actual game Cytoplasm seems to give more energy per glucose.

**Comment by hhyyrylainen** [comment]
The reason this was done is that metabolosomes are made to be faster so while they use more glucose per ATP they support much higher ATP demanding cells. With the latest balancing the amount of ATP made by second by metabolosomes are multiple times higher than cytoplasm gives.

**Comment by fgdfgfthgr-fox** [comment]
> The reason this was done is that metabolosomes are made to be faster so while they use more glucose per ATP they support much higher ATP demanding cells. With the latest balancing the amount of ATP made by second by metabolosomes are multiple times higher than cytoplasm gives.

If metabolosomes is having high yield with lower efficiency, why is its say "at much higher efficiency"?

**Comment by hhyyrylainen** [comment]
Okay, the tooltip should be updated, then.

**Comment by Shupsta** [comment]
Attempted fix https://github.com/Revolutionary-Games/Thrive/pull/952#issue-375101771
