### ISSUE TITLE
Remake oxytoxy model

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#971]
For some reason the X shaped toxin model has been lost. It needs to be remade.

**Comment by TheGreaterGameCreator** [comment]
Weren't you working on particle toxin implementation?

**Comment by hhyyrylainen** [comment]
That's a feature that has been stuck in planning phase for very long time. We need something that works for the next release.

**Comment by DonGororo** [comment]
Would this effect work as a substitute?
![Screenshot_3](https://user-images.githubusercontent.com/59174955/79972295-05790700-8496-11ea-9138-cdd30732b469.png)

**Comment by hhyyrylainen** [comment]
I suppose that could replace the model Node in the projectile scene. But there is still a need for the organelle model to be used in the cell for oxytoxy proteins.
