### ISSUE TITLE
Update to Godot 3.2.1

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#972]
We are no longer on the latest version. From a quick test I did, there doesn't seem to be anything that broke.

**Comment by skyace65** [comment]
I just compared the game in 3.2 and 3.2.1 and everything is still working. And it looks like using a newer point release doesn't change any files so a PR doesn't need to be made for this.

**Comment by hhyyrylainen** [comment]
A bunch of documentation as well as the CI builds reference the godot version. Those need updating.
