### ISSUE TITLE
Enable Godot GUI scaling

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#981]
Now the GUI doesn't look very nice when stretched to 4K. It seems that this godot code could fix all the issues without making anything blurry or stuff like that:
```c#
GetTree().SetScreenStretch(SceneTree.StretchMode.Mode2d, SceneTree.StretchAspect.Expand, OS.WindowSize);
```

**Comment by skyace65** [comment]
GUI scaling shouldn't be done through code. There's a way to do it in project settings, I'll make a PR quickly
