### ISSUE TITLE
Remove scale on Microbe physics

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#987]
remove the scale on the collision parent. documentation says to never scale: https://docs.godotengine.org/en/latest/tutorials/physics/physics_introduction.html

Instead there should be an intermediate node that has all the graphics nodes on it that has the scale, and the physics building part will need to have the direct scale applying parts uncommented.

**Comment by crodnu** [comment]
Same with floating chunks

**Comment by hhyyrylainen** [comment]
https://github.com/Revolutionary-Games/Thrive/issues/1057
